; generated by MIR2 Z80 codegen

; fun main() ; clobbers: A
main:
    LD A, 72
    CALL ConOut
    LD A, 101
    CALL ConOut
    LD A, 108
    CALL ConOut
    LD A, 108
    CALL ConOut
    LD A, 111
    CALL ConOut
    LD A, 32
    CALL ConOut
    LD A, 102
    CALL ConOut
    LD A, 114
    CALL ConOut
    LD A, 111
    CALL ConOut
    LD A, 109
    CALL ConOut
    LD A, 32
    CALL ConOut
    LD A, 80
    CALL ConOut
    LD A, 97
    CALL ConOut
    LD A, 115
    CALL ConOut
    LD A, 99
    CALL ConOut
    LD A, 97
    CALL ConOut
    LD A, 108
    CALL ConOut
    LD A, 32
    CALL ConOut
    LD A, 111
    CALL ConOut
    LD A, 110
    CALL ConOut
    LD A, 32
    CALL ConOut
    LD A, 90
    CALL ConOut
    LD A, 56
    CALL ConOut
    LD A, 48
    CALL ConOut
    LD A, 33
    CALL ConOut
    JP WriteCrLf

