version: 2
updates:
  # Disable automatic PRs for npm (keep security alerts only)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0

  # Disable automatic PRs for Go modules (keep security alerts only)
  - package-ecosystem: "gomod"
    directory: "/minzc"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0

  # Disable automatic PRs for GitHub Actions (keep security alerts only)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0