// vir-oracle — run the SMT-based allocator offline and compare it to the
// production backend.
//
// VIR is no longer a code generator (see docs/adr/0043-vir-demoted-to-offline-oracle.md).
// It exists to answer one question the production path cannot answer about
// itself: given this function, what would an optimal allocation look like?
//
// That matters because the precomputed regalloc tables are generated by
// exhaustive search under a hand-written cost function. "Optimal" is currently
// validated against the very model that produced it. An independent SMT
// formulation reaching the same answer is evidence; agreement between a search
// and its own cost function is not.
//
// IMPORTANT: this compares allocation *size*, not correctness. The oracle can
// report a tighter answer for a function it also miscompiles — gcd is exactly
// such a case (17 instructions vs production's 19, and it returns 0 instead of
// 4). A smaller wrong answer is still wrong. Treat a negative delta as "worth
// investigating", never as "production is leaving value on the table".
//
// Requires a `z3` binary on PATH. That is a research-tool dependency; the
// compiler itself has none.
//
// Usage:
//
//	vir-oracle prog.nanz            # human-readable comparison
//	vir-oracle --json prog.c        # one JSON record per function
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/minz/minzc/pkg/c89"
	"github.com/minz/minzc/pkg/hir"
	"github.com/minz/minzc/pkg/nanz"
	"github.com/minz/minzc/pkg/pipeline"
	"github.com/minz/minzc/pkg/vir"
)

// Record is the oracle's product: one row per function, machine-readable so a
// corpus run can be diffed over time. Reporting agreement is the whole point,
// so disagreements must be countable, not just visible.
type Record struct {
	Func       string `json:"func"`
	Solved     bool   `json:"solved"`
	Error      string `json:"error,omitempty"`
	SolveMS    int64  `json:"solve_ms"`
	OracleInst int    `json:"oracle_insts"`
	ProdInst   int    `json:"prod_insts"`
	Delta      int    `json:"delta"` // oracle - production; negative means the oracle is tighter
}

func main() {
	asJSON := false
	args := os.Args[1:]
	var files []string
	for _, a := range args {
		switch a {
		case "--json":
			asJSON = true
		case "-h", "--help":
			usage()
			return
		default:
			files = append(files, a)
		}
	}
	if len(files) != 1 {
		usage()
		os.Exit(2)
	}

	if _, err := exec.LookPath("z3"); err != nil {
		fmt.Fprintln(os.Stderr, "vir-oracle: no z3 binary on PATH — the oracle needs an SMT solver")
		os.Exit(1)
	}

	recs, err := run(files[0])
	if err != nil {
		fmt.Fprintf(os.Stderr, "vir-oracle: %v\n", err)
		os.Exit(1)
	}

	if asJSON {
		enc := json.NewEncoder(os.Stdout)
		for _, r := range recs {
			_ = enc.Encode(r)
		}
		return
	}
	report(recs)
}

func run(path string) ([]Record, error) {
	src, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	hm, err := parse(path, string(src))
	if err != nil {
		return nil, err
	}

	// Production path first — it is the baseline we are comparing against.
	steps, err := pipeline.CompileHIRSteps(hm, pipeline.DefaultOptions())
	if err != nil {
		return nil, fmt.Errorf("production pipeline: %w", err)
	}
	if steps.MIR2Module == nil {
		return nil, fmt.Errorf("production pipeline produced no MIR2 module")
	}

	start := time.Now()
	oracleASM, results := vir.CodegenModule(steps.MIR2Module, vir.SolverOptions{})
	elapsed := time.Since(start).Milliseconds()

	prod := countPerFunc(steps.Assembly)
	oracle := countPerFunc(oracleASM)

	recs := make([]Record, 0, len(results))
	for _, r := range results {
		rec := Record{
			Func:   r.Name,
			Solved: r.OK,
			Error:  r.Error,
			// CodegenModule solves the whole module in one call, so this is the
			// module total divided evenly — an average, not this function's cost.
			// Per-function timing needs a per-function entry point.
			SolveMS: elapsed / int64(max(1, len(results))),
		}
		if r.OK {
			rec.OracleInst = oracle[r.Name]
			rec.ProdInst = prod[r.Name]
			rec.Delta = rec.OracleInst - rec.ProdInst
		}
		recs = append(recs, rec)
	}
	return recs, nil
}

func parse(path, src string) (*hir.Module, error) {
	base := filepath.Base(path)
	switch filepath.Ext(path) {
	case ".nanz", ".minz":
		dir := filepath.Dir(path)
		return nanz.ParseWithOpts(src, path, nanz.ParseOpts{BaseDir: dir})
	case ".c", ".m":
		abs, _ := filepath.Abs(path)
		return c89.CompileWithOpts(src, base, c89.CompileOpts{
			BaseDir:      filepath.Dir(abs),
			IncludePaths: []string{filepath.Dir(abs)},
		})
	default:
		return nil, fmt.Errorf("unsupported extension %q (want .nanz or .c)", filepath.Ext(path))
	}
}

// countPerFunc counts emitted instructions between a `label:` and the next one.
// Deliberately crude: instruction count is a proxy, not the metric we would
// publish. Bytes and T-states are the real ones — see report 116 on why
// instruction counts flatter us.
func countPerFunc(asm string) map[string]int {
	out := map[string]int{}
	cur := ""
	for _, line := range strings.Split(asm, "\n") {
		t := strings.TrimSpace(line)
		if t == "" || strings.HasPrefix(t, ";") {
			continue
		}
		if strings.HasSuffix(t, ":") && !strings.HasPrefix(t, ".") {
			cur = strings.TrimSuffix(t, ":")
			continue
		}
		if cur != "" {
			out[cur]++
		}
	}
	return out
}

func report(recs []Record) {
	solved, failed, tighter, same, looser := 0, 0, 0, 0, 0
	for _, r := range recs {
		if !r.Solved {
			failed++
			continue
		}
		solved++
		switch {
		case r.Delta < 0:
			tighter++
		case r.Delta == 0:
			same++
		default:
			looser++
		}
	}
	fmt.Printf("%-28s %8s %8s %7s\n", "function", "oracle", "prod", "delta")
	for _, r := range recs {
		if !r.Solved {
			fmt.Printf("%-28s %8s %8s %7s  %s\n", r.Func, "-", "-", "-", r.Error)
			continue
		}
		fmt.Printf("%-28s %8d %8d %+7d\n", r.Func, r.OracleInst, r.ProdInst, r.Delta)
	}
	fmt.Printf("\n%d solved, %d unsolved — oracle tighter on %d, equal on %d, looser on %d\n",
		solved, failed, tighter, same, looser)
	if looser > 0 {
		fmt.Println("note: 'looser' means the SMT model disagrees with production. Investigate " +
			"before trusting either — the cost models may simply differ.")
	}
	fmt.Println("note: this compares size, not correctness. The oracle can be tighter on a " +
		"function it miscompiles (gcd is such a case).")
}

func usage() {
	fmt.Fprintln(os.Stderr, `vir-oracle — offline SMT allocator, for comparison against the production backend

  vir-oracle [--json] <file.nanz|file.c>

Requires a z3 binary on PATH. Not part of the compiler; see
docs/adr/0043-vir-demoted-to-offline-oracle.md.`)
}

func max(a, b int) int {
	if a > b {
		return a
	}
	return b
}
