// Package mir2abap translates MIR2 modules to ABAP source text.
//
// Enables running Nanz programs natively on SAP systems.
// MIR2 SSA registers → ABAP local variables (lv_rN).
// Memory → XSTRING byte buffer with helper FORMs for load/store.
// Block params → mutable locals, branches → GOTO labels.
//
// Output: a single REPORT with FORMs (one per MIR2 function).
// Can be executed via GENERATE SUBROUTINE POOL or deployed as include.
package mir2abap

import (
	"fmt"
	"strings"

	"github.com/minz/minzc/pkg/mir2"
)

// abapSym sanitizes a MIR2 symbol name for ABAP.
func abapSym(name string) string {
	s := strings.ReplaceAll(name, "@", "_")
	s = strings.ReplaceAll(s, ".", "_")
	s = strings.ReplaceAll(s, "$", "_")
	if len(s) > 30 { // ABAP identifier limit
		s = s[:30]
	}
	return strings.ToLower(s)
}

// Compile translates a MIR2 module to an ABAP REPORT.
func Compile(m *mir2.Module) (string, error) {
	g := &gen{sb: &strings.Builder{}, mod: m}
	g.emitModule()
	return g.sb.String(), nil
}

type gen struct {
	sb       *strings.Builder
	mod      *mir2.Module
	ptrRegs  map[mir2.Reg]bool
	slotVars map[mir2.Reg]string
}

func (g *gen) line(s string) { g.sb.WriteString(s); g.sb.WriteByte('\n') }
func (g *gen) printf(format string, args ...interface{}) {
	fmt.Fprintf(g.sb, format, args...)
}

// ── module ──────────────────────────────────────────────────────────────────

func (g *gen) emitModule() {
	g.line("* Generated by mir2abap — do not edit.")
	g.line("REPORT zmir2_out.")
	g.line("")

	// Memory buffer (flat heap, like MIR2 VM)
	g.line("DATA gv_mem TYPE xstring.")
	g.line("DATA gv_mem_size TYPE i VALUE 65536.")
	g.line("")

	// String pool
	if g.mod.Strings.Len() > 0 {
		g.line("* ── string pool ──")
		for i := 0; i < g.mod.Strings.Len(); i++ {
			s := g.mod.Strings.At(i)
			sym := abapSym(g.mod.Strings.Symbol(i))
			g.printf("DATA %s TYPE i VALUE %d.\n", sym, 0) // offset filled at INIT
			_ = s
		}
		g.line("")
	}

	// Globals
	if len(g.mod.Globals) > 0 {
		g.line("* ── globals ──")
		for _, gl := range g.mod.Globals {
			g.printf("DATA %s TYPE i VALUE 0. \" %s\n", abapSym(gl.Name), gl.Ty)
		}
		g.line("")
	}

	// Memory helpers
	g.emitMemoryHelpers()

	// Print helper
	g.emitPrintHelpers()

	// Forward declare all functions as FORMs
	g.line("* ── functions ──")
	for _, f := range g.mod.Funcs {
		if !f.Attrs.IsExtern {
			g.emitFunc(f)
			g.line("")
		}
	}

	// Initialization + main entry
	g.line("* ── init + main ──")
	g.line("INITIALIZATION.")
	g.printf("  gv_mem = ||.\n")
	g.printf("  DATA lv_chunk TYPE x LENGTH 256.\n")
	g.printf("  DO 256 TIMES. CONCATENATE gv_mem lv_chunk INTO gv_mem IN BYTE MODE. ENDDO.\n")
	g.line("")

	// Init string pool: copy string bytes into memory
	if g.mod.Strings.Len() > 0 {
		offset := 0
		for i := 0; i < g.mod.Strings.Len(); i++ {
			s := g.mod.Strings.At(i)
			sym := abapSym(g.mod.Strings.Symbol(i))
			g.printf("  %s = %d.\n", sym, offset)
			// Write string bytes to memory
			for _, b := range []byte(s) {
				g.printf("  PERFORM mem_st8 USING %d %d.\n", offset, int(b))
				offset++
			}
			g.printf("  PERFORM mem_st8 USING %d 0. \" NUL\n", offset)
			offset++
		}
		g.line("")
	}

	// Init globals with Init data
	g.line("START-OF-SELECTION.")
	g.line("  PERFORM main.")
}

// ── memory helpers ──────────────────────────────────────────────────────────

func (g *gen) emitMemoryHelpers() {
	g.line("* ── memory helpers ──")

	// Load u8
	g.line("FORM mem_ld8 USING iv_addr TYPE i CHANGING rv TYPE i.")
	g.line("  DATA lv_b TYPE x LENGTH 1.")
	g.line("  lv_b = gv_mem+iv_addr(1).")
	g.line("  rv = lv_b.")
	g.line("ENDFORM.")
	g.line("")

	// Store u8
	g.line("FORM mem_st8 USING iv_addr TYPE i iv_val TYPE i.")
	g.line("  DATA lv_b TYPE x LENGTH 1.")
	g.line("  lv_b = iv_val.")
	g.line("  gv_mem+iv_addr(1) = lv_b.")
	g.line("ENDFORM.")
	g.line("")

	// Load u16 (little-endian)
	g.line("FORM mem_ld16 USING iv_addr TYPE i CHANGING rv TYPE i.")
	g.line("  DATA lv_lo TYPE i. DATA lv_hi TYPE i.")
	g.line("  PERFORM mem_ld8 USING iv_addr CHANGING lv_lo.")
	g.line("  PERFORM mem_ld8 USING iv_addr + 1 CHANGING lv_hi.")
	g.line("  rv = lv_hi * 256 + lv_lo.")
	g.line("ENDFORM.")
	g.line("")

	// Store u16 (little-endian)
	g.line("FORM mem_st16 USING iv_addr TYPE i iv_val TYPE i.")
	g.line("  PERFORM mem_st8 USING iv_addr ( iv_val MOD 256 ).")
	g.line("  PERFORM mem_st8 USING iv_addr + 1 ( iv_val / 256 MOD 256 ).")
	g.line("ENDFORM.")
	g.line("")
}

func (g *gen) emitPrintHelpers() {
	g.line("* ── print helpers (host function stubs) ──")
	g.line("FORM mir_io_print_str USING iv_ptr TYPE i.")
	g.line("  DATA lv_ch TYPE i. DATA lv_off TYPE i. lv_off = iv_ptr.")
	g.line("  DO.")
	g.line("    PERFORM mem_ld8 USING lv_off CHANGING lv_ch.")
	g.line("    IF lv_ch = 0. EXIT. ENDIF.")
	g.line("    DATA lv_c TYPE c LENGTH 1. lv_c = cl_abap_conv_in_ce=>uccpi( lv_ch ).")
	g.line("    WRITE lv_c NO-GAP.")
	g.line("    lv_off = lv_off + 1.")
	g.line("  ENDDO.")
	g.line("ENDFORM.")
	g.line("")

	g.line("FORM mir_io_print_u8 USING iv_val TYPE i.")
	g.line("  WRITE iv_val.")
	g.line("ENDFORM.")
	g.line("")

	g.line("FORM mir_io_print_nl.")
	g.line("  NEW-LINE.")
	g.line("ENDFORM.")
	g.line("")
}

// ── function ────────────────────────────────────────────────────────────────

func (g *gen) emitFunc(f *mir2.Func) {
	g.ptrRegs = make(map[mir2.Reg]bool)
	g.slotVars = make(map[mir2.Reg]string)

	name := abapSym(f.Name)

	// Build FORM signature
	params := f.Contract.Params
	results := f.Contract.Returns

	var using []string
	for i, p := range params {
		using = append(using, fmt.Sprintf("iv_p%d TYPE i \" %s", i, p.Ty))
	}
	var changing []string
	for i := range results {
		changing = append(changing, fmt.Sprintf("rv_r%d TYPE i", i))
	}

	sig := fmt.Sprintf("FORM %s", name)
	if len(using) > 0 {
		sig += " USING " + strings.Join(using, " ")
	}
	if len(changing) > 0 {
		sig += " CHANGING " + strings.Join(changing, " ")
	}
	g.printf("%s.\n", sig)

	// Declare all registers as local variables
	allRegs := make(map[mir2.Reg]bool)
	for _, b := range f.Blocks {
		for _, p := range b.Params {
			allRegs[p.Dst] = true
		}
		for _, inst := range b.Insts {
			if inst.Dst != mir2.NoReg {
				allRegs[inst.Dst] = true
			}
		}
	}
	for r := range allRegs {
		g.printf("  DATA lv_r%d TYPE i.\n", r)
	}
	g.line("")

	// Bind function parameters to their registers
	if len(params) > 0 {
		for i, p := range params {
			g.printf("  lv_r%d = iv_p%d. \" param %s\n", p.Reg, i, p.Ty)
		}
		g.line("")
	}

	// Emit blocks
	for i, b := range f.Blocks {
		if i > 0 {
			g.printf("  %s.\n", blockLabel(b.Label)) // label
		}

		// Block params (for branches)
		// Already declared above, assigned at branch site

		for _, inst := range b.Insts {
			g.emitInst(f, inst)
		}
		g.emitTerm(f, b)
	}

	g.line("ENDFORM.")
}

func blockLabel(label string) string {
	return "lbl_" + strings.ReplaceAll(strings.ReplaceAll(label, ".", "_"), "@", "_")
}

// ── instructions ────────────────────────────────────────────────────────────

func (g *gen) emitInst(f *mir2.Func, inst *mir2.Inst) {
	dst := inst.Dst
	a, b := inst.Src[0], inst.Src[1]
	ra := func(r mir2.Reg) string { return fmt.Sprintf("lv_r%d", r) }

	def := func(expr string) {
		g.printf("  lv_r%d = %s.\n", dst, expr)
	}

	mask := func(ty mir2.Ty) string {
		w := mir2.ByteWidth(ty)
		if w == 1 {
			return " MOD 256"
		}
		if w == 2 {
			return " MOD 65536"
		}
		return ""
	}

	switch inst.Op {
	// Binary arithmetic
	case mir2.OpAdd:
		def(fmt.Sprintf("( %s + %s )%s", ra(a), ra(b), mask(inst.Ty)))
	case mir2.OpSub:
		def(fmt.Sprintf("( %s - %s )%s", ra(a), ra(b), mask(inst.Ty)))
	case mir2.OpMul:
		def(fmt.Sprintf("( %s * %s )%s", ra(a), ra(b), mask(inst.Ty)))
	case mir2.OpDiv:
		g.printf("  IF %s <> 0. lv_r%d = %s / %s. ELSE. lv_r%d = 0. ENDIF.\n", ra(b), dst, ra(a), ra(b), dst)
	case mir2.OpMod:
		g.printf("  IF %s <> 0. lv_r%d = %s MOD %s. ELSE. lv_r%d = 0. ENDIF.\n", ra(b), dst, ra(a), ra(b), dst)

	// Bitwise — ABAP doesn't have &|^ operators, use BIT functions
	case mir2.OpAnd:
		def(fmt.Sprintf("cl_abap_math=>bit_and( iv_x = %s iv_y = %s )", ra(a), ra(b)))
	case mir2.OpOr:
		def(fmt.Sprintf("cl_abap_math=>bit_or( iv_x = %s iv_y = %s )", ra(a), ra(b)))
	case mir2.OpXor:
		def(fmt.Sprintf("cl_abap_math=>bit_xor( iv_x = %s iv_y = %s )", ra(a), ra(b)))
	case mir2.OpShl:
		def(fmt.Sprintf("( %s * 2 ** %s )%s", ra(a), ra(b), mask(inst.Ty)))
	case mir2.OpShr:
		def(fmt.Sprintf("( %s / 2 ** %s )", ra(a), ra(b)))

	// Unary
	case mir2.OpNeg:
		def(fmt.Sprintf("( 0 - %s )%s", ra(a), mask(inst.Ty)))
	case mir2.OpNot:
		w := mir2.ByteWidth(inst.Ty)
		if w == 1 {
			def(fmt.Sprintf("( 255 - %s )", ra(a)))
		} else {
			def(fmt.Sprintf("( 65535 - %s )", ra(a)))
		}

	// Conversions
	case mir2.OpExt, mir2.OpSext, mir2.OpTrunc, mir2.OpMove:
		def(fmt.Sprintf("%s%s", ra(a), mask(inst.Ty)))

	// Comparison
	case mir2.OpCmp:
		g.emitCmp(inst)

	// Const
	case mir2.OpConst:
		g.printf("  lv_r%d = %d.\n", dst, inst.Imm)

	// Memory
	case mir2.OpLoad:
		w := mir2.ByteWidth(inst.Ty)
		if w <= 1 {
			g.printf("  PERFORM mem_ld8 USING %s CHANGING lv_r%d.\n", ra(a), dst)
		} else {
			g.printf("  PERFORM mem_ld16 USING %s CHANGING lv_r%d.\n", ra(a), dst)
		}
	case mir2.OpStore:
		ptr, val := inst.Src[0], inst.Src[1]
		w := mir2.ByteWidth(inst.Ty)
		if w <= 1 {
			g.printf("  PERFORM mem_st8 USING %s %s.\n", ra(ptr), ra(val))
		} else {
			g.printf("  PERFORM mem_st16 USING %s %s.\n", ra(ptr), ra(val))
		}

	case mir2.OpAddrOf:
		g.printf("  lv_r%d = %s. \" addr-of %s\n", dst, abapSym(inst.Sym), inst.Sym)

	case mir2.OpField, mir2.OpPtrBump:
		g.printf("  lv_r%d = %s + %d.\n", dst, ra(a), inst.Imm)

	case mir2.OpPtrAdd:
		g.printf("  lv_r%d = %s + %s.\n", dst, ra(a), ra(b))

	case mir2.OpAlloca:
		// Allocate from top of memory
		g.printf("  lv_r%d = gv_mem_size. \" alloca %d bytes\n", dst, inst.Imm)
		g.printf("  gv_mem_size = gv_mem_size + %d.\n", inst.Imm)

	// Calls
	case mir2.OpCall:
		g.emitCall(inst)

	// SMC → mutable static
	case mir2.OpPatchSlot:
		name := fmt.Sprintf("gv_slot_r%d", dst)
		g.slotVars[dst] = name
		g.printf("  %s = %d. lv_r%d = %s.\n", name, inst.Imm, dst, name)
	case mir2.OpLoadPatched:
		name := g.slotVars[a]
		if name == "" {
			name = fmt.Sprintf("gv_slot_r%d", a)
		}
		g.printf("  lv_r%d = %s.\n", dst, name)
	case mir2.OpPatch:
		name := g.slotVars[a]
		if name == "" {
			name = fmt.Sprintf("gv_slot_r%d", a)
		}
		g.printf("  %s = %s.\n", name, ra(b))

	default:
		g.printf("  \" TODO: %s (r%d)\n", inst.Op, dst)
	}
}

// ── comparison ──────────────────────────────────────────────────────────────

func (g *gen) emitCmp(inst *mir2.Inst) {
	a, b := inst.Src[0], inst.Src[1]
	ra := func(r mir2.Reg) string { return fmt.Sprintf("lv_r%d", r) }

	var op string
	switch inst.Cond {
	case mir2.CmpEq:
		op = "="
	case mir2.CmpNe:
		op = "<>"
	case mir2.CmpLt, mir2.CmpUlt, mir2.CmpSubCarry:
		op = "<"
	case mir2.CmpLe, mir2.CmpUle:
		op = "<="
	case mir2.CmpGt, mir2.CmpUgt, mir2.CmpSubCarryNot:
		op = ">"
	case mir2.CmpGe, mir2.CmpUge:
		op = ">="
	default:
		op = "="
	}

	g.printf("  IF %s %s %s. lv_r%d = 1. ELSE. lv_r%d = 0. ENDIF.\n",
		ra(a), op, ra(b), inst.Dst, inst.Dst)
}

// ── calls ───────────────────────────────────────────────────────────────────

func (g *gen) emitCall(inst *mir2.Inst) {
	name := abapSym(inst.Sym)

	// Map intrinsic calls
	switch inst.Sym {
	case "@mir.io.print.str":
		g.printf("  PERFORM mir_io_print_str USING lv_r%d.\n", inst.Args[0])
		return
	case "@mir.io.print.u8", "@mir.io.print.u16":
		g.printf("  PERFORM mir_io_print_u8 USING lv_r%d.\n", inst.Args[0])
		return
	case "@mir.io.print.nl":
		g.line("  PERFORM mir_io_print_nl.")
		return
	case "@mir.io.print.char":
		g.printf("  DATA lv_ch TYPE c LENGTH 1. lv_ch = cl_abap_conv_in_ce=>uccpi( lv_r%d ). WRITE lv_ch NO-GAP.\n", inst.Args[0])
		return
	}

	// Regular call
	var using []string
	for _, arg := range inst.Args {
		using = append(using, fmt.Sprintf("lv_r%d", arg))
	}
	if inst.Dst != mir2.NoReg {
		g.printf("  PERFORM %s USING %s CHANGING lv_r%d.\n", name, strings.Join(using, " "), inst.Dst)
	} else {
		if len(using) > 0 {
			g.printf("  PERFORM %s USING %s.\n", name, strings.Join(using, " "))
		} else {
			g.printf("  PERFORM %s.\n", name)
		}
	}
}

// ── terminators ─────────────────────────────────────────────────────────────

func (g *gen) emitTerm(f *mir2.Func, b *mir2.Block) {
	switch t := b.Term.(type) {
	case *mir2.TermRet:
		if len(t.Vals) > 0 {
			g.printf("  rv_r0 = lv_r%d.\n", t.Vals[0])
		}
		if b != f.Blocks[len(f.Blocks)-1] {
			g.line("  RETURN.")
		}

	case *mir2.TermJmp:
		target := f.BlockByLabel(t.Target)
		if target != nil {
			for i, p := range target.Params {
				if i < len(t.Args) {
					g.printf("  lv_r%d = lv_r%d.\n", p.Dst, t.Args[i])
				}
			}
		}
		g.printf("  GOTO %s.\n", blockLabel(t.Target))

	case *mir2.TermBrIf:
		g.printf("  IF lv_r%d <> 0.\n", t.Cond)
		thenBlock := f.BlockByLabel(t.Then)
		if thenBlock != nil {
			for i, p := range thenBlock.Params {
				if i < len(t.ThenArgs) {
					g.printf("    lv_r%d = lv_r%d.\n", p.Dst, t.ThenArgs[i])
				}
			}
		}
		g.printf("    GOTO %s.\n", blockLabel(t.Then))
		g.line("  ENDIF.")

		elseBlock := f.BlockByLabel(t.Else)
		if elseBlock != nil {
			for i, p := range elseBlock.Params {
				if i < len(t.ElseArgs) {
					g.printf("  lv_r%d = lv_r%d.\n", p.Dst, t.ElseArgs[i])
				}
			}
		}
		g.printf("  GOTO %s.\n", blockLabel(t.Else))
	}
}
