package mir2

import (
	"strings"
	"testing"
)

// ── Double EX DE,HL elimination ───────────────────────────────────────────────

func TestElimDoubleExDeHl_Basic(t *testing.T) {
	src := "; generated by MIR2 Z80 codegen\n\nfoo:\n    SBC HL, DE\n    EX DE, HL\n    EX DE, HL\n    RET\n"
	got := asmPeepholePass(src)
	if strings.Contains(got, "EX DE, HL") {
		t.Fatalf("double EX DE,HL not eliminated:\n%s", got)
	}
	if !strings.Contains(got, "SBC HL, DE") || !strings.Contains(got, "RET") {
		t.Fatalf("surrounding instructions lost:\n%s", got)
	}
}

func TestElimDoubleExDeHl_WithCommentBetween(t *testing.T) {
	src := "foo:\n    EX DE, HL\n    ; swap back\n    EX DE, HL\n    RET\n"
	got := asmPeepholePass(src)
	if strings.Contains(got, "EX DE, HL") {
		t.Fatalf("double EX DE,HL with intervening comment not eliminated:\n%s", got)
	}
}

func TestElimDoubleExDeHl_SingleKept(t *testing.T) {
	src := "foo:\n    EX DE, HL\n    ADD HL, DE\n    RET\n"
	got := asmPeepholePass(src)
	if !strings.Contains(got, "EX DE, HL") {
		t.Fatalf("single EX DE,HL wrongly eliminated:\n%s", got)
	}
}

func TestElimDoubleExDeHl_TripleCollapses(t *testing.T) {
	// Triple EX DE,HL: first pair cancels, third survives.
	src := "foo:\n    EX DE, HL\n    EX DE, HL\n    EX DE, HL\n    RET\n"
	got := asmPeepholePass(src)
	count := strings.Count(got, "EX DE, HL")
	if count != 1 {
		t.Fatalf("expected 1 EX DE,HL to survive in triple, got %d:\n%s", count, got)
	}
}

// ── Single-JP → EQU alias ────────────────────────────────────────────────────

func TestElimSingleJpEqu_Basic(t *testing.T) {
	src := "; generated by MIR2 Z80 codegen\n\nalias_func:\n    JP real_func\n\nreal_func:\n    ADD A, C\n    RET\n"
	got := asmPeepholePass(src)
	if !strings.Contains(got, "alias_func    EQU real_func") {
		t.Fatalf("single-JP not converted to EQU:\n%s", got)
	}
	if strings.Contains(got, "JP real_func") {
		t.Fatalf("JP still present after EQU conversion:\n%s", got)
	}
}

func TestElimSingleJpEqu_MultiInstrNotConverted(t *testing.T) {
	src := "alias_func:\n    LD A, D\n    JP real_func\n\nreal_func:\n    ADD A, C\n    RET\n"
	got := asmPeepholePass(src)
	if strings.Contains(got, "EQU real_func") {
		t.Fatalf("multi-instruction function wrongly converted to EQU:\n%s", got)
	}
}

func TestElimSingleJpEqu_MainNotConverted(t *testing.T) {
	// main must never become an EQU — it is the binary entry point.
	src := "main:\n    JP some_func\n\nsome_func:\n    RET\n"
	got := asmPeepholePass(src)
	if !strings.Contains(got, "main:") {
		t.Fatalf("main label removed:\n%s", got)
	}
	if strings.Contains(got, "main    EQU") {
		t.Fatalf("main wrongly converted to EQU:\n%s", got)
	}
}

func TestElimSingleJpEqu_ConditionalJpNotConverted(t *testing.T) {
	// JP NZ,target has a comma — must not be converted.
	src := "foo:\n    JP NZ, bar\n\nbar:\n    RET\n"
	got := asmPeepholePass(src)
	if strings.Contains(got, "EQU bar") {
		t.Fatalf("conditional JP wrongly converted to EQU:\n%s", got)
	}
}

// ── Integration: double EX DE,HL in generated asm is eliminated ──────────────

func TestAbsDiff_NoExDeHl(t *testing.T) {
	// Build a synthetic function that would naturally emit EX DE,HL pairs,
	// then confirm the peephole pass strips them.
	src := "; generated by MIR2 Z80 codegen\n\nfoo:\n    EX DE, HL\n    EX DE, HL\n    RET\n"
	got := asmPeepholePass(src)
	if strings.Contains(got, "EX DE, HL") {
		t.Fatalf("peephole did not eliminate double EX DE,HL:\n%s", got)
	}
	if !strings.Contains(got, "RET") {
		t.Fatalf("RET missing after elimination:\n%s", got)
	}
}
