package mir2

import (
	"fmt"
	"strings"
)

// M6502Codegen translates a MIR2 module (with register allocation done)
// into 6502 assembly text suitable for 64tass or ca65.
//
// This is a skeleton implementation — Phase 1 covers:
//   - Function prologue/epilogue (label + RTS)
//   - OpConst (LDA #imm, LDX #imm, LDY #imm)
//   - OpMove (TAX, TAY, TXA, TYA, LDA zp, STA zp)
//   - OpAdd / OpSub (CLC;ADC / SEC;SBC — 8-bit only)
//   - OpCall (JSR)
//   - Terminators: TermRet (RTS), TermJmp (JMP), TermBrIf (Bcc), TermBrIf2
//   - Comments with register annotations
//
// Phase 2 will add: 16-bit ops, memory access, TermDJNZ equivalent.

// M6502CodegenOptions configures the 6502 code generator.
type M6502CodegenOptions struct {
	Origin uint16 // code origin address (default 0x0200 for bare metal)
}

// M6502Codegen generates 6502 assembly from an allocated MIR2 module.
func M6502Codegen(mod *Module, ar *AllocResult, opts ...M6502CodegenOptions) string {
	cg := &m6502cg{
		mod: mod,
		ar:  ar,
	}
	if len(opts) > 0 {
		cg.origin = opts[0].Origin
	}
	if cg.origin == 0 {
		cg.origin = 0x0200
	}
	return cg.generate()
}

type m6502cg struct {
	mod      *Module
	ar       *AllocResult
	origin   uint16
	sb       strings.Builder
	labelSeq int
}

func (cg *m6502cg) uniqueLabel(prefix string) string {
	cg.labelSeq++
	return fmt.Sprintf("%s_%d", prefix, cg.labelSeq)
}

func (cg *m6502cg) emit(format string, args ...any) {
	fmt.Fprintf(&cg.sb, format+"\n", args...)
}

func (cg *m6502cg) comment(format string, args ...any) {
	fmt.Fprintf(&cg.sb, "; "+format+"\n", args...)
}

func (cg *m6502cg) generate() string {
	cg.comment("generated by MIR2 6502 codegen")
	cg.comment("")
	cg.emit("    .cpu \"6502\"")
	cg.emit("    * = $%04X", cg.origin)
	cg.emit("")

	for _, f := range cg.mod.Funcs {
		cg.genFunc(f)
	}

	return cg.sb.String()
}

func (cg *m6502cg) genFunc(f *Func) {
	// Function header comment
	cg.comment("fun %s(%s) -> %s", f.Name, cg.fmtParams(f), cg.fmtReturn(f))

	// Extern functions — just emit the label
	if f.Attrs.IsExtern {
		cg.emit("%s:", sanitizeIdent6502(f.Name))
		cg.emit("")
		return
	}

	// Label
	cg.emit("%s:", sanitizeIdent6502(f.Name))

	// Generate each block
	for i, b := range f.Blocks {
		if i > 0 {
			cg.emit(".%s:", sanitizeIdent6502(b.Label))
		}
		cg.genBlock(b)
	}

	cg.emit("")
}

func (cg *m6502cg) genBlock(b *Block) {
	for _, inst := range b.Insts {
		cg.genInst(inst)
	}

	// Block terminator
	switch t := b.Term.(type) {
	case *TermRet:
		// Ensure return value is in A (6502 calling convention).
		if len(t.Vals) > 0 {
			retLoc := cg.loc(t.Vals[0])
			if retLoc != "A" {
				cg.genMoveToA(retLoc)
			}
		}
		cg.emit("    RTS")
	case *TermJmp:
		cg.emit("    JMP .%s", sanitizeIdent6502(t.Target))
	case *TermBrIf:
		cg.genCondBranch(t)
	case *TermBrIf2:
		cg.genThreeWayBranch(t)
	case *TermUnreachable:
		cg.comment("unreachable")
	}
}

func (cg *m6502cg) genInst(inst *Inst) {
	dst := cg.loc(inst.Dst)

	switch inst.Op {
	case OpConst:
		cg.genConst(dst, int(inst.Imm))

	case OpMove:
		cg.genMove(dst, cg.loc(inst.Src[0]))

	case OpAdd:
		cg.genAdd(dst, cg.loc(inst.Src[0]), cg.loc(inst.Src[1]))

	case OpSub:
		cg.genSub(dst, cg.loc(inst.Src[0]), cg.loc(inst.Src[1]))

	case OpCall:
		cg.emit("    JSR %s", sanitizeIdent6502(inst.Sym))

	case OpNeg:
		src := cg.loc(inst.Src[0])
		if src != "A" {
			cg.genMoveToA(src)
		}
		cg.emit("    EOR #$FF")
		cg.emit("    CLC")
		cg.emit("    ADC #1")
		if dst != "A" {
			cg.genMoveFromA(dst)
		}

	case OpAnd:
		cg.genBitwise("AND", dst, cg.loc(inst.Src[0]), cg.loc(inst.Src[1]))

	case OpOr:
		cg.genBitwise("ORA", dst, cg.loc(inst.Src[0]), cg.loc(inst.Src[1]))

	case OpXor:
		cg.genBitwise("EOR", dst, cg.loc(inst.Src[0]), cg.loc(inst.Src[1]))

	case OpCmp:
		lhs := cg.loc(inst.Src[0])
		rhs := cg.loc(inst.Src[1])
		cmpOp := cg.prepareCompare(lhs, rhs)
		cg.emit("    CMP %s", cmpOp)
		cg.genCmpBool(dst, inst.Cond)

	default:
		cg.comment("TODO: %s (op=%d)", inst.Op, inst.Op)
	}
}

// ── Instruction generators ──────────────────────────────────────────────────

func (cg *m6502cg) genConst(dst string, val int) {
	val8 := val & 0xFF
	switch dst {
	case "A":
		cg.emit("    LDA #$%02X", val8)
	case "X":
		cg.emit("    LDX #$%02X", val8)
	case "Y":
		cg.emit("    LDY #$%02X", val8)
	default:
		cg.emit("    LDA #$%02X", val8)
		cg.emit("    STA %s", dst)
	}
}

func (cg *m6502cg) genMove(dst, src string) {
	if dst == src {
		return
	}
	switch {
	case src == "A" && dst == "X":
		cg.emit("    TAX")
	case src == "A" && dst == "Y":
		cg.emit("    TAY")
	case src == "X" && dst == "A":
		cg.emit("    TXA")
	case src == "Y" && dst == "A":
		cg.emit("    TYA")
	case src == "X" && dst == "Y":
		cg.emit("    TXA")
		cg.emit("    TAY")
	case src == "Y" && dst == "X":
		cg.emit("    TYA")
		cg.emit("    TAX")
	default:
		if dst == "A" {
			cg.emit("    LDA %s", src)
		} else if src == "A" {
			cg.emit("    STA %s", dst)
		} else {
			cg.emit("    LDA %s", src)
			cg.emit("    STA %s", dst)
		}
	}
}

func (cg *m6502cg) genAdd(dst, lhs, rhs string) {
	op := cg.prepareALU(lhs, rhs)
	cg.emit("    CLC")
	cg.emit("    ADC %s", op)
	if dst != "A" {
		cg.genMoveFromA(dst)
	}
}

func (cg *m6502cg) genSub(dst, lhs, rhs string) {
	op := cg.prepareALU(lhs, rhs)
	cg.emit("    SEC")
	cg.emit("    SBC %s", op)
	if dst != "A" {
		cg.genMoveFromA(dst)
	}
}

func (cg *m6502cg) genBitwise(mnem, dst, lhs, rhs string) {
	op := cg.prepareALU(lhs, rhs)
	cg.emit("    %s %s", mnem, op)
	if dst != "A" {
		cg.genMoveFromA(dst)
	}
}

// prepareALU loads lhs into A and returns a safe operand for the rhs.
// Handles the case where loading lhs into A would clobber rhs.
func (cg *m6502cg) prepareALU(lhs, rhs string) string {
	if lhs == "A" {
		return cg.ensureOperand(rhs)
	}
	// lhs not in A — loading it will clobber A.
	// If rhs is in A, spill rhs first.
	if rhs == "A" {
		cg.emit("    STA %s", zpScratch)
		cg.genMoveToA(lhs)
		return zpScratch
	}
	cg.genMoveToA(lhs)
	return cg.ensureOperand(rhs)
}

func (cg *m6502cg) genCondBranch(t *TermBrIf) {
	// TermBrIf: Cond != 0 → Then, Cond == 0 → Else.
	// Test the condition without clobbering other registers.
	cond := cg.loc(t.Cond)
	switch cond {
	case "A":
		cg.emit("    CMP #$00")
	case "X":
		cg.emit("    CPX #$00")
	case "Y":
		cg.emit("    CPY #$00")
	default:
		// ZP location — use LDX or LDY to test without clobbering A.
		cg.emit("    LDX %s", cond)
	}
	cg.emit("    BNE .%s", sanitizeIdent6502(t.Then))
	if t.Else != "" {
		cg.emit("    JMP .%s", sanitizeIdent6502(t.Else))
	}
}

func (cg *m6502cg) genThreeWayBranch(t *TermBrIf2) {
	// TermBrIf2: load Lhs into A, CMP Rhs, then branch on flags.
	// After CMP: Z=1 → equal, C=0 → less-than, C=1∧Z=0 → greater-than.
	lhs := cg.loc(t.Lhs)
	rhs := cg.loc(t.Rhs)
	cmpOp := cg.prepareCompare(lhs, rhs)
	cg.emit("    CMP %s", cmpOp)
	cg.emit("    BEQ .%s", sanitizeIdent6502(t.Eq))
	cg.emit("    BCC .%s", sanitizeIdent6502(t.Lt))
	cg.emit("    JMP .%s", sanitizeIdent6502(t.Gt))
}

// ── Comparison helpers ───────────────────────────────────────────────────────

// prepareCompare loads lhs into A and returns an operand string for CMP.
// Handles the tricky case where loading lhs into A would clobber rhs.
func (cg *m6502cg) prepareCompare(lhs, rhs string) string {
	if lhs == "A" {
		return cg.ensureOperand(rhs)
	}
	// lhs is not in A — we need to load it.  But if rhs IS in A,
	// loading lhs would clobber rhs, so spill rhs first.
	if rhs == "A" {
		cg.emit("    STA %s", zpScratch)
		cg.genMoveToA(lhs)
		return zpScratch
	}
	cg.genMoveToA(lhs)
	return cg.ensureOperand(rhs)
}

// genCmpBool materializes a boolean (0/1) into dst based on 6502 flags
// set by the immediately preceding CMP instruction.
//
// IMPORTANT: On 6502, LDA/LDX/LDY clobber Z and N flags.  We must branch
// BEFORE loading any value, so that the branch decisions use CMP's flags.
// We also load directly into the target register (LDX/LDY when possible)
// to avoid clobbering A, which may still hold a live value.
//
// 6502 CMP flag semantics (unsigned):
//
//	A == operand → Z=1, C=1
//	A >  operand → Z=0, C=1
//	A <  operand → Z=0, C=0
func (cg *m6502cg) genCmpBool(dst string, cond CmpCond) {
	// Pick load instruction that targets dst directly (avoids clobbering A).
	ldImm := "LDA"
	switch dst {
	case "X":
		ldImm = "LDX"
	case "Y":
		ldImm = "LDY"
	}

	setTrue := cg.uniqueLabel("ct")
	done := cg.uniqueLabel("cd")

	// Emit branch-first pattern: branch on CMP flags, then load constant.
	switch cond {
	case CmpEq:
		cg.emit("    BEQ .%s", setTrue)
	case CmpNe:
		cg.emit("    BNE .%s", setTrue)
	case CmpLt, CmpUlt:
		cg.emit("    BCC .%s", setTrue)
	case CmpGe, CmpUge:
		cg.emit("    BCS .%s", setTrue)
	case CmpGt, CmpUgt:
		// C=1 AND Z=0 → true.  Two branches needed.
		falseL := cg.uniqueLabel("cf")
		cg.emit("    BEQ .%s", falseL) // equal → false
		cg.emit("    BCS .%s", setTrue) // carry set → greater → true
		cg.emit(".%s:", falseL)
		cg.emit("    %s #$00", ldImm)
		cg.emit("    JMP .%s", done)
		cg.emit(".%s:", setTrue)
		cg.emit("    %s #$01", ldImm)
		cg.emit(".%s:", done)
		cg.genCmpBoolStore(dst, ldImm)
		return
	case CmpLe, CmpUle:
		// Z=1 OR C=0 → true.
		cg.emit("    BEQ .%s", setTrue)
		cg.emit("    BCC .%s", setTrue)
		cg.emit("    %s #$00", ldImm)
		cg.emit("    JMP .%s", done)
		cg.emit(".%s:", setTrue)
		cg.emit("    %s #$01", ldImm)
		cg.emit(".%s:", done)
		cg.genCmpBoolStore(dst, ldImm)
		return
	default:
		cg.comment("TODO: CmpCond %d", cond)
		cg.emit("    %s #$00", ldImm)
		cg.genCmpBoolStore(dst, ldImm)
		return
	}
	// Common case: single branch condition
	cg.emit("    %s #$00", ldImm) // false
	cg.emit("    JMP .%s", done)
	cg.emit(".%s:", setTrue)
	cg.emit("    %s #$01", ldImm) // true
	cg.emit(".%s:", done)
	cg.genCmpBoolStore(dst, ldImm)
}

// genCmpBoolStore handles ZP destinations: if dst is not A/X/Y, the boolean
// was loaded into A and must be stored to the ZP location.
func (cg *m6502cg) genCmpBoolStore(dst, ldImm string) {
	if ldImm == "LDA" && dst != "A" {
		// ZP destination — store from A
		cg.emit("    STA %s", dst)
	}
}

// ── Helpers ──────────────────────────────────────────────────────────────────

func (cg *m6502cg) genMoveToA(src string) {
	switch src {
	case "A":
	case "X":
		cg.emit("    TXA")
	case "Y":
		cg.emit("    TYA")
	default:
		cg.emit("    LDA %s", src)
	}
}

func (cg *m6502cg) genMoveFromA(dst string) {
	switch dst {
	case "A":
	case "X":
		cg.emit("    TAX")
	case "Y":
		cg.emit("    TAY")
	default:
		cg.emit("    STA %s", dst)
	}
}

// zpScratch is a reserved zero-page address used as a temporary when a
// register value must be used as an ALU operand.  On NMOS 6502, ADC/SBC/AND/
// ORA/EOR/CMP cannot take a register name — only #imm, zp, abs, or indexed
// modes.  We spill to this scratch byte before the ALU instruction.
const zpScratch = "$00" // ZP $00 — safe because we don't use it for allocation

// ensureOperand makes sure `loc` is usable as an ALU operand (the second
// arg to ADC/SBC/AND/ORA/EOR/CMP).  On NMOS 6502, these instructions accept
// #imm, zp, abs, or indexed modes — NOT a register name.
//
// If loc is A, X, or Y we spill to zpScratch first.  Note: when the caller
// has already loaded lhs into A and rhs is also A (e.g. "a + a"), we must
// still spill because "ADC A" is not a valid instruction.
func (cg *m6502cg) ensureOperand(loc string) string {
	switch loc {
	case "A":
		cg.emit("    STA %s", zpScratch)
		return zpScratch
	case "X":
		cg.emit("    STX %s", zpScratch)
		return zpScratch
	case "Y":
		cg.emit("    STY %s", zpScratch)
		return zpScratch
	default:
		return loc
	}
}

// loc maps a virtual register to its allocated physical location name.
func (cg *m6502cg) loc(r Reg) string {
	if r == NoReg {
		return ""
	}
	if loc, ok := cg.ar.Locs[r]; ok {
		return loc.Name
	}
	return fmt.Sprintf("v%d", r)
}

func (cg *m6502cg) fmtParams(f *Func) string {
	var parts []string
	for _, p := range f.Contract.Params {
		loc := cg.loc(p.Reg)
		parts = append(parts, fmt.Sprintf("%s: %s = %s", p.Name, p.Ty, loc))
	}
	return strings.Join(parts, ", ")
}

func (cg *m6502cg) fmtReturn(f *Func) string {
	if len(f.Contract.Returns) == 0 {
		return "void"
	}
	var parts []string
	for _, r := range f.Contract.Returns {
		parts = append(parts, r.Ty.String())
	}
	return strings.Join(parts, ", ")
}

// sanitizeIdent6502 converts a Nanz identifier to a valid 6502 asm label.
func sanitizeIdent6502(s string) string {
	var b strings.Builder
	for _, ch := range s {
		if (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') ||
			(ch >= '0' && ch <= '9') || ch == '_' {
			b.WriteRune(ch)
		} else {
			b.WriteRune('_')
		}
	}
	return b.String()
}
