package mir2

import (
	"fmt"
	"strings"
)

// Z80Codegen lowers allocated MIR2 to Z80 assembly text (.a80 format).
//
// Prerequisites:
//   - AllocResult covering every virtual register in the module
//   - Verified MIR2 module (Verify passed)
//
// Output: a string of Z80 assembly ready for MZA.
// Label format: @funcname_blockname (underscore-joined, no special chars).
//
// Supported opcodes (first pass):
//
//	OpConst        → LD r, n  /  LD rr, nn
//	OpMove         → LD r, r  /  EX DE,HL  /  PUSH+POP
//	OpAdd          → ADD A,r  /  ADD HL,rr
//	OpSub          → SUB r    /  SBC HL,rr
//	OpAnd/Or/Xor   → AND/OR/XOR r
//	OpNeg          → NEG
//	OpNot          → CPL
//	OpExt          → LD H,0 / LD L,r  (zero-extend u8→u16 via HL)
//	OpCmp          → CP r  (result stays in F; ClassFlag)
//	OpLoad         → LD A,(HL)  /  LD r,(HL)
//	OpStore        → LD (HL),A  /  LD (HL),r
//	OpCall         → CALL label
//	OpPatchSlot    → LD r, 0   (initial value; literal byte patchable)
//	OpLoadPatched  → LD r, r   (SMC: already patched in stream)
//	OpPatch        → (comment: SMC patch — no emission in pure assembler)
//	TermJmp        → JP label
//	TermBrIf       → JP Z/NZ/C/NC label  (flag-class cond)
//	TermRet        → RET

// ── Public entry point ────────────────────────────────────────────────────────

// Z80Codegen generates Z80 assembly for the entire module.
func Z80Codegen(m *Module, ar *AllocResult) string {
	var sb strings.Builder
	cg := &z80cg{ar: ar, sb: &sb, mod: m}

	sb.WriteString("; generated by MIR2 Z80 codegen\n\n")

	for _, f := range m.Funcs {
		cg.genFunc(f)
		sb.WriteByte('\n')
	}

	// Emit global variable data sections.
	if len(m.Globals) > 0 {
		sb.WriteString("; globals\n")
		for _, g := range m.Globals {
			w := ByteWidth(g.Ty)
			if w == 0 {
				continue
			}
			// Page-aligned globals (e.g. LUT tables): emit ALIGN directive first.
			if at, ok := g.Ty.(*ArrayTy); ok && at.Align > 0 {
				fmt.Fprintf(&sb, "    ALIGN %d\n", at.Align)
			}
			sb.WriteString(sanitizeIdent(g.Name) + ":\n")
			// Emit as DB sequence for all types — always readable,
			// correct for struct fields, and unambiguous byte order.
			sb.WriteString("    DB ")
			for i := 0; i < w; i++ {
				if i > 0 {
					sb.WriteString(", ")
				}
				b := byte(0)
				if i < len(g.Init) {
					b = g.Init[i]
				}
				fmt.Fprintf(&sb, "%d", b)
			}
			sb.WriteByte('\n')
		}
	}

	// Emit string pool — NUL-terminated byte sequences.
	// Symbol names: @mir2.str.N → mir2_str_N (sanitized for assembler).
	if m.Strings.Len() > 0 {
		sb.WriteString("; strings\n")
		for i := 0; i < m.Strings.Len(); i++ {
			sym := sanitizeIdent(m.Strings.Symbol(i))
			s := m.Strings.At(i)
			sb.WriteString(sym + ":\n")
			sb.WriteString("    DB ")
			for j, c := range []byte(s) {
				if j > 0 {
					sb.WriteString(", ")
				}
				fmt.Fprintf(&sb, "%d", c)
			}
			sb.WriteString(", 0\n") // NUL terminator
		}
	}

	return sb.String()
}

// ── Internal codegen state ────────────────────────────────────────────────────

type z80cg struct {
	ar         *AllocResult
	sb         *strings.Builder
	mod        *Module // parent module (for callee contract lookup at call sites)
	fn         *Func   // current function
	blockIdx   int     // index of current block in fn.Blocks (for fall-through)
	cmpSwapped  map[Reg]bool    // dst reg → operands were swapped in genCmp
	cmpAndZero  map[Reg]bool    // dst reg → comparison used AND A (rhs=0), use NZ/Z not NC/C
	cmpNeedsTwo map[Reg]bool    // dst reg → CmpGt/CmpLe with lhs in A, needs two-JP in BrIf
	callFlags   map[Reg]CmpCond // dst reg of OpCall → FlagCond when callee returns ClassFlag
	constVals  map[Reg]int64 // virtual reg → compile-time constant value (for peepholes)
	deadConsts map[Reg]bool  // OpConst dsts whose LD is suppressed by DSE

	// holdsPhys is a bidirectional alias map for local copy-propagation within a
	// basic block.  holdsPhys[r] = s means physical register r currently holds the
	// same value as s (and holdsPhys[s] = r by symmetry).  Used to eliminate
	// redundant LD instructions: if A ≡ D, we skip "LD A, D" before an ALU op.
	// The map is cleared at every block boundary and at any CALL.
	holdsPhys map[string]string

	// physOverride tracks dynamic relocation of virtual registers that happened
	// as a side-effect of call-argument setup (emitCallArgs parallel copies).
	// physOverride[r] = "B" means virtual register r is now in physical "B",
	// overriding the static allocator assignment g.ar.Loc(r).Name.
	// Cleared at every CALL (the call clobbers volatile state).
	physOverride map[Reg]string

	// trampolines: small glue blocks emitted after main function body that
	// perform block-argument parallel copies then jump to the real target.
	// Needed for BrIf edges where the non-fall-through path requires copies.
	trampolines []trampolineBlock
	trampIdx    int

	// Page-aligned LUT optimisation (21T vs 39T).
	// Pre-scanned per block; cleared at each new block.
	//
	// lutLoadPat: Load dst → pattern descriptor for page-aligned table accesses.
	//   When set, emit LD HL,sym + LD L,src8 + LD A,(HL) instead of the
	//   general Ext+PtrAdd+Load sequence.
	// lutSkip: virtual regs whose emit is merged into the Load instruction above.
	//   Affected: Ext(idx16), AddrOf(base), PtrAdd(ptr).
	lutLoadPat map[Reg]lutLoadPat
	lutSkip    map[Reg]bool
}

// lutLoadPat describes a page-aligned LUT access merged at codegen time.
type lutLoadPat struct {
	sym     string // page-aligned global symbol
	src8Reg Reg    // virtual reg holding the 8-bit index (after lo-subtract if any)
}

// trampolineBlock is emitted after all regular blocks of a function.
// It resolves block-argument copies for one outgoing BrIf edge.
type trampolineBlock struct {
	label  string        // local label for this trampoline
	copies []parallelCopy
	target string        // real destination label (already formatted)
}

// parallelCopy is a single register-to-register move in a parallel copy sequence.
type parallelCopy struct {
	srcName string
	dstName string
	ty      Ty
}

func (g *z80cg) emit(s string) { g.sb.WriteString(s); g.sb.WriteByte('\n') }
func (g *z80cg) emitf(f string, args ...any) { g.emit(fmt.Sprintf(f, args...)) }
func (g *z80cg) comment(s string)            { g.emitf("    ; %s", s) }

// isSimpleReg reports whether s names a plain physical register (no parens,
// no digits) — safe to use as an alias key in holdsPhys.
func isSimpleReg(s string) bool {
	if len(s) == 0 {
		return false
	}
	for _, c := range s {
		if !((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z')) {
			return false
		}
	}
	return true
}

// ── Register topology ─────────────────────────────────────────────────────────
//
// Writing to a 16-bit pair register (e.g. HL) implicitly changes its bytes
// (H, L), and vice versa: writing to H invalidates HL.  These tables encode
// that topology so invalidate() can clear all affected aliases at once.

// regBytes maps a 16-bit register to its 8-bit byte components.
var regBytes = map[string][]string{
	"BC": {"B", "C"},
	"DE": {"D", "E"},
	"HL": {"H", "L"},
	"IX": {"IXH", "IXL"},
	"IY": {"IYH", "IYL"},
}

// regParent maps an 8-bit component to its 16-bit parent register.
var regParent = map[string]string{
	"B": "BC", "C": "BC",
	"D": "DE", "E": "DE",
	"H": "HL", "L": "HL",
	"IXH": "IX", "IXL": "IX",
	"IYH": "IY", "IYL": "IY",
}

// killOne removes a single register and its bidirectional partner from holdsPhys.
func (g *z80cg) killOne(r string) {
	if partner, ok := g.holdsPhys[r]; ok {
		delete(g.holdsPhys, partner)
		delete(g.holdsPhys, r)
	}
}

// invalidate removes all tracking for r: kills r itself, its byte components
// (if r is a 16-bit pair), and its parent pair (if r is an 8-bit component).
func (g *z80cg) invalidate(r string) {
	g.killOne(r)
	if bytes, ok := regBytes[r]; ok {
		for _, b := range bytes {
			g.killOne(b)
		}
	}
	if parent, ok := regParent[r]; ok {
		g.killOne(parent)
	}
}

// setCopy records that dst was loaded from src (they now hold the same value).
// Invalidates dst's old aliases and clears src's previous bidirectional link
// before establishing the new one, preventing stale reverse entries.
func (g *z80cg) setCopy(dst, src string) {
	g.invalidate(dst)
	g.killOne(src) // break src's old reverse-link (could be left by a prior setCopy)
	if isSimpleReg(dst) && isSimpleReg(src) {
		g.holdsPhys[dst] = src
		g.holdsPhys[src] = dst
	}
}

// holdsValue reports whether physical register a currently holds the same
// value as b (either they are the same register, or a copy alias exists).
func (g *z80cg) holdsValue(a, b string) bool {
	return a == b || g.holdsPhys[a] == b
}

// emitLDA emits "LD A, src" and records the copy alias A ≡ src.
func (g *z80cg) emitLDA(src string) {
	g.emitf("    LD A, %s", src)
	g.setCopy("A", src)
}

// loc returns the physical location name for virtual register r.
func (g *z80cg) loc(r Reg) string {
	if r == NoReg {
		return "?"
	}
	if phys, ok := g.physOverride[r]; ok {
		return phys
	}
	return g.ar.Loc(r).Name
}

// ── Function ──────────────────────────────────────────────────────────────────

// computeDeadConsts returns the set of OpConst dsts whose LD can be suppressed
// because every use of the constant is already handled by a codegen peephole:
//
//   - OpCmp with Src[1] being the const → CP imm8 fires (no register needed).
//   - OpAdd/OpSub with Src[1]==const, value==1, and lhs/dst at the same physical
//     location → INC/DEC fires (no register needed).
//
// Constants with zero uses are also suppressed.
func computeDeadConsts(f *Func, ar *AllocResult) map[Reg]bool {
	// Collect all OpConst dsts and their immediate values.
	constVal := make(map[Reg]int64)
	for _, b := range f.Blocks {
		for _, inst := range b.Insts {
			if inst.Op == OpConst {
				constVal[inst.Dst] = inst.Imm
			}
		}
	}
	if len(constVal) == 0 {
		return nil
	}

	physName := func(r Reg) string {
		if loc, ok := ar.Locs[r]; ok {
			return loc.Name
		}
		return ""
	}

	totalUses  := make(map[Reg]int)
	foldedUses := make(map[Reg]int)

	for _, b := range f.Blocks {
		for _, inst := range b.Insts {
			// Call/CallIndirect args live in inst.Args, not inst.Src — count them
			// as non-peephole uses so their LD is not suppressed.
			for _, src := range inst.Args {
				if _, isConst := constVal[src]; isConst {
					totalUses[src]++
					// call args are never peephole-foldable
				}
			}
			for _, src := range inst.Src {
				cv, isConst := constVal[src]
				if !isConst {
					continue
				}
				totalUses[src]++
				switch inst.Op {
				case OpCmp:
					// CP imm8: fires when rhs (Src[1]) has a known constant.
					if src == inst.Src[1] {
						foldedUses[src]++
					}
				case OpAdd, OpSub:
					// INC/DEC: fires when rhs==1 and the op is in-place (lhs phys == dst phys).
					if src == inst.Src[1] && cv == 1 &&
						physName(inst.Src[0]) == physName(inst.Dst) {
						foldedUses[src]++
					}
				case OpAnd, OpOr, OpXor:
					// AND/OR/XOR immediate peephole: always emits "AND n" etc., no register needed.
					if src == inst.Src[1] {
						foldedUses[src]++
					}
				case OpMul:
					// genMul folds constant Src[1] into shift sequences.
					if src == inst.Src[1] {
						foldedUses[src]++
					}
					case OpShl, OpShr, OpSar:
					// genShift always shifts by 1 and completely ignores Src[1].
					// Any constant passed as the shift count is effectively dead.
					if src == inst.Src[1] {
						foldedUses[src]++
					}
				}
			}
		}
		// Block args in terminators (TermJmp.Args, TermBrIf.*Args, TermRet.Vals)
		// are general uses — they cannot be peephole-folded.
		if b.Term != nil {
			for _, src := range b.Term.termUses() {
				if _, isConst := constVal[src]; isConst {
					totalUses[src]++
					// no foldedUses increment — terminators are never peephole-dead
				}
			}
		}
	}

	dead := make(map[Reg]bool)
	for r := range constVal {
		total := totalUses[r]
		if total == 0 || total == foldedUses[r] {
			dead[r] = true
		}
	}
	return dead
}

func (g *z80cg) genFunc(f *Func) {
	g.fn = f
	g.cmpSwapped = make(map[Reg]bool)
	g.cmpAndZero = make(map[Reg]bool)
	g.cmpNeedsTwo = make(map[Reg]bool)
	g.callFlags = make(map[Reg]CmpCond)
	g.constVals = make(map[Reg]int64)
	g.deadConsts = computeDeadConsts(f, g.ar)
	g.holdsPhys = make(map[string]string)
	g.physOverride = make(map[Reg]string)
	g.trampolines = g.trampolines[:0]
	g.trampIdx = 0
	g.lutLoadPat = make(map[Reg]lutLoadPat)
	g.lutSkip = make(map[Reg]bool)

	label := sanitizeIdent(f.Name)
	g.emitf("%s:", label)

	for i, b := range f.Blocks {
		g.blockIdx = i
		g.genBlock(f, b)
	}

	// Emit trampoline blocks: small copy+JP stubs for BrIf edges with block args.
	for _, tramp := range g.trampolines {
		g.emitf("%s:", tramp.label)
		g.emitParallelCopy(tramp.copies)
		g.emitf("    JP %s", tramp.target)
	}
}

// ── Page-aligned LUT pre-scan ──────────────────────────────────────────────────

// scanLUTPatterns detects the pattern emitted by LUTGen for page-aligned tables:
//
//	idx16 = Ext(src8, u8→u16, ClassIndex)
//	base  = AddrOf("sym")                      ← sym has Align==256
//	ptr   = PtrAdd(base, idx16)
//	dst   = Load(ptr, u8, ClassAcc)
//
// When found:
//   - g.lutLoadPat[dst] = {sym, src8Reg}
//   - g.lutSkip[idx16, base, ptr] = true
//
// The pattern is cleared (g.lutLoadPat, g.lutSkip rebuilt) at each new block.
// This is safe because LUTGen only ever creates single-use intermediate regs.
func (g *z80cg) scanLUTPatterns(b *Block) {
	// Reset per-block maps (keep same map objects; just clear them).
	clear(g.lutLoadPat)
	clear(g.lutSkip)

	// Build: reg → defining instruction (within this block only).
	defInst := make(map[Reg]*Inst, len(b.Insts))
	for _, inst := range b.Insts {
		if inst.Dst != NoReg {
			defInst[inst.Dst] = inst
		}
	}

	for _, inst := range b.Insts {
		// Looking for: dst = Load(ptr, u8)
		if inst.Op != OpLoad || inst.Ty.Width() != 8 || inst.Dst == NoReg {
			continue
		}
		ptrReg := inst.Src[0]

		// ptr = PtrAdd(base, idx16)
		ptrInst, ok := defInst[ptrReg]
		if !ok || ptrInst.Op != OpPtrAdd {
			continue
		}
		baseReg := ptrInst.Src[0]
		idx16Reg := ptrInst.Src[1]

		// base = AddrOf(sym) where sym is page-aligned
		baseInst, ok := defInst[baseReg]
		if !ok || baseInst.Op != OpAddrOf {
			continue
		}
		sym := baseInst.Sym
		if !g.isGlobalPageAligned(sym) {
			continue
		}

		// idx16 = Ext(src8, u8→u16)
		extInst, ok := defInst[idx16Reg]
		if !ok || extInst.Op != OpExt {
			continue
		}
		if extInst.SrcTy == nil || extInst.SrcTy.Width() != 8 || extInst.Ty.Width() != 16 {
			continue
		}
		src8Reg := extInst.Src[0]

		// Pattern matched: record and mark intermediates for skipping.
		g.lutLoadPat[inst.Dst] = lutLoadPat{sym: sym, src8Reg: src8Reg}
		g.lutSkip[idx16Reg] = true
		g.lutSkip[baseReg] = true
		g.lutSkip[ptrReg] = true
	}
}

// isGlobalPageAligned reports whether the named global in the current module
// has Align == 256 (i.e. is a page-aligned LUT candidate).
func (g *z80cg) isGlobalPageAligned(sym string) bool {
	for _, gl := range g.mod.Globals {
		if gl.Name == sym {
			if at, ok := gl.Ty.(*ArrayTy); ok {
				return at.Align == 256
			}
		}
	}
	return false
}

// ── Block ─────────────────────────────────────────────────────────────────────

func (g *z80cg) genBlock(f *Func, b *Block) {
	if b.Label != "entry" {
		g.emitf(".%s_%s:", sanitizeIdent(f.Name), sanitizeIdent(b.Label))
	}
	clear(g.holdsPhys) // all register aliases unknown at block entry

	// Pre-scan: identify page-aligned LUT access patterns so we can merge
	// Ext + AddrOf + PtrAdd + Load into: LD HL,sym; LD L,src8; LD A,(HL).
	g.scanLUTPatterns(b)

	// Detect DJNZ peephole: DEC B + JP loop_head → DJNZ loop_body.
	peep := g.detectDJNZPeephole(f, b)

	limit := len(b.Insts)
	if peep.skipLast {
		limit-- // skip final DEC B; DJNZ handles it
	}
	for _, inst := range b.Insts[:limit] {
		g.genInst(inst)
	}

	if peep.bodyLbl != "" {
		g.emitf("    DJNZ %s", peep.bodyLbl)
		// Exit path after DJNZ falls through (B=0).
		// Use the check block's Else edge copies.
		exitCopies := g.buildBlockCopies(f, peep.checkBrif.Else, peep.checkBrif.ElseArgs)
		g.emitParallelCopy(exitCopies)
		if !g.isFallThrough(f, peep.checkBrif.Else) || len(exitCopies) != 0 {
			g.emitf("    JP %s", blockLabel(f.Name, peep.checkBrif.Else))
		}
	} else {
		g.genTerm(f, b.Term)
	}
}

// ── Instructions ──────────────────────────────────────────────────────────────

func (g *z80cg) genInst(inst *Inst) {
	// Instructions merged into a page-aligned LUT load are skipped here;
	// their code is emitted by the Load case below.
	if g.lutSkip[inst.Dst] {
		return
	}

	dst := g.loc(inst.Dst)

	switch inst.Op {
	case OpConst:
		g.constVals[inst.Dst] = inst.Imm
		if dst == "F" {
			// Bool constant into flag register: SCF (true) or AND A (false, clears C+sets Z).
			if inst.Imm != 0 {
				g.emit("    SCF")
			} else {
				g.emit("    AND A") // A=A (no change), clears C, sets Z based on A
			}
			return
		}
		if !g.deadConsts[inst.Dst] {
			g.emitf("    LD %s, %d", dst, inst.Imm)
		}

	case OpMove:
		src := g.loc(inst.Src[0])
		if dst == src {
			return // no-op
		}
		g.emitMov(dst, src, inst.Ty.Width())

	case OpAdd:
		g.genBinOp("ADD", inst)

	case OpSub:
		g.genBinOp("SUB", inst)

	case OpMul:
		g.genMul(inst)

	case OpAnd:
		g.genBinOp("AND", inst)

	case OpOr:
		g.genBinOp("OR", inst)

	case OpXor:
		g.genBinOp("XOR", inst)

	case OpNeg:
		g.emit("    NEG")
		g.invalidate("A")

	case OpNot:
		g.emit("    CPL")
		g.invalidate("A")

	case OpShl:
		g.genShift("SLA", inst)

	case OpShr:
		g.genShift("SRL", inst)

	case OpSar:
		g.genShift("SRA", inst)

	case OpExt:
		// Zero-extend srcTy → Ty.  Primary case: u8 → u16 into HL.
		g.genExt(inst)

	case OpSext:
		g.genSext(inst)

	case OpTrunc:
		src := g.loc(inst.Src[0])
		// Truncate 16-bit → 8-bit: take low byte.
		// If dst is L and src is HL, or dst is E and src is DE — no-op.
		if dst != src {
			g.emitf("    LD %s, %s", dst, lowByte(src))
		}

	case OpCmp:
		g.genCmp(inst)

	case OpLoad:
		// Page-aligned LUT fast path:
		//   LD HL, sym   ; 10T (L=0 guaranteed by ALIGN 256)
		//   LD L, idx8   ;  4T
		//   LD A, (HL)   ;  7T  → 21T total vs 39T general
		if pat, ok := g.lutLoadPat[inst.Dst]; ok {
			src8 := g.loc(pat.src8Reg)
			g.emitf("    LD HL, %s", sanitizeIdent(pat.sym))
			g.invalidate("HL")
			g.emitf("    LD L, %s", src8)
			g.invalidate("L")
			if dst != "A" {
				g.emitf("    LD A, (HL)")
				g.invalidate("A")
				g.emitMov(dst, "A", 8)
			} else {
				g.emitf("    LD A, (HL)")
				g.invalidate("A")
			}
			break
		}
		ptr := g.loc(inst.Src[0])
		w := inst.Ty.Width()
		if w <= 8 {
			g.emitf("    LD %s, (%s)", dst, ptr)
		} else {
			// 16-bit load: LD L,(ptr) / INC ptr / LD H,(ptr) — little-endian
			g.emitf("    LD %s, (%s)     ; lo", lowByte(dst), ptr)
			g.emitf("    INC %s", ptr)
			g.emitf("    LD %s, (%s)     ; hi", highByte(dst), ptr)
			g.emitf("    DEC %s", ptr)
		}

	case OpStore:
		ptr := g.loc(inst.Src[0])
		val := g.loc(inst.Src[1])
		w := inst.Ty.Width()
		if w <= 8 {
			g.emitf("    LD (%s), %s", ptr, val)
		} else {
			g.emitf("    LD (%s), %s     ; lo", ptr, lowByte(val))
			g.emitf("    INC %s", ptr)
			g.emitf("    LD (%s), %s     ; hi", ptr, highByte(val))
			g.emitf("    DEC %s", ptr)
		}

	case OpCall, OpCallIndirect:
		g.genCall(inst)

	case OpAddrOf:
		g.emitf("    LD %s, %s", dst, inst.Sym)

	case OpPtrAdd:
		// Runtime pointer advance: dst = base_ptr + offset_u16.
		// Z80: needs both operands in 16-bit register pairs.
		// Optimal: base in HL (dst), offset in DE → ADD HL, DE (11T, no A clobber).
		base := g.loc(inst.Src[0])
		off := g.loc(inst.Src[1])
		if dst != base {
			g.emitMov(dst, base, 16)
		}
		// Ensure offset is in a 16-bit pair different from dst.
		offPair := off
		if len(off) == 1 { // 8-bit reg (A, B, C, D, E, H, L) — zero-extend to pair
			offPair = "DE"
			if dst == "DE" {
				offPair = "BC"
			}
			g.emitf("    LD %s, 0", offPair)
			g.emitf("    LD %s, %s", lowByte(offPair), off)
		} else if off == dst {
			// Same pair: ADD HL, HL doubles the pointer — that's wrong.
			// Move offset to temp pair first.
			offPair = "DE"
			if dst == "DE" {
				offPair = "BC"
			}
			g.emitMov(offPair, off, 16)
		}
		g.emitf("    ADD %s, %s", dst, offPair)
		g.invalidate(dst)

	case OpField, OpPtrBump:
		// Advance pointer by compile-time byte offset.
		// OpField: struct field access; OpPtrBump: iterator advance.
		// SoA256 special strides: -1 → INC L (element advance), 256 → INC H (field switch).
		src := g.loc(inst.Src[0])
		offset := inst.Imm
		if dst != src {
			g.emitMov(dst, src, 16) // copy base ptr
		}
		switch {
		case offset == 0:
			// nothing — dst already at target
		case offset == -1:
			// SoA256: INC L — advance element index (H=column, L=index)
			g.emitf("    INC %s", lowByte(dst))
		case offset == 256:
			// SoA256: INC H — switch to next field column (H=column, L=index)
			g.emitf("    INC %s", highByte(dst))
		case offset <= 3:
			for range offset {
				g.emitf("    INC %s", dst)
			}
		default:
			// LD BC, offset; ADD HL, BC  (or equivalent pair for dst)
			tmp := "BC"
			if dst == "BC" {
				tmp = "DE"
			}
			g.emitf("    LD %s, %d", tmp, offset)
			g.emitf("    ADD %s, %s", dst, tmp)
		}
		g.invalidate(dst)

	case OpAlloca:
		// Reserve bytes on stack; dst = current SP.
		n := inst.Imm
		for range n {
			g.emit("    DEC SP")
		}
		g.emitf("    LD %s, SP", dst)

	case OpPatchSlot:
		// Mutable immediate: emit initial value; the byte after LD is patchable.
		w := inst.Ty.Width()
		if w <= 8 {
			g.emitf("    LD %s, %d          ; [patch_slot init=%d]", dst, inst.Imm, inst.Imm)
		} else {
			g.emitf("    LD %s, %d          ; [patch_slot init=%d]", dst, inst.Imm, inst.Imm)
		}

	case OpLoadPatched:
		// After patching, the slot register already holds the new value.
		// Emit a move; the codegen may elide this if dst == slot.
		slot := g.loc(inst.Src[0])
		if dst != slot {
			g.emitMov(dst, slot, inst.Ty.Width())
		}

	case OpPatch:
		// SMC patch: at runtime the code rewrites the immediate in OpPatchSlot.
		// In the pure-assembler path we emit a self-modifying write sequence.
		// slot = inst.Src[0], newVal = inst.Src[1]
		slotReg := g.loc(inst.Src[0])
		newVal := g.loc(inst.Src[1])
		g.comment(fmt.Sprintf("patch %s ← %s  (SMC: rewrite immediate in stream)", slotReg, newVal))
		// The patch_slot instruction is always LD r, n (2 bytes).
		// At runtime: caller computes address of the immediate byte and writes newVal.
		// We emit a placeholder comment; actual SMC requires knowing the patch address.
		// The Z80 backend will resolve this in a second pass.
		g.emitf("    ; TODO: LD (patch_addr_%s), %s", slotReg, newVal)

	case OpPush:
		src := g.loc(inst.Src[0])
		// PUSH requires a 16-bit pair; pad single registers to their pair.
		pair := toPair(src)
		g.emitf("    PUSH %s", pair)
		g.invalidate(src)

	case OpPop:
		pair := toPair(dst)
		g.emitf("    POP %s", pair)
		g.invalidate(pair)

	case OpAsm:
		if inst.Asm != nil {
			g.emitf("    %s", inst.Asm.Template)
		}

	default:
		g.comment(fmt.Sprintf("TODO: %s", inst.Op))
	}
}

// ── Binary operations ─────────────────────────────────────────────────────────

func (g *z80cg) genBinOp(mnem string, inst *Inst) {
	dst := g.loc(inst.Dst)
	lhs := g.loc(inst.Src[0])
	rhs := g.loc(inst.Src[1])
	w := inst.Ty.Width()

	if w <= 8 {
		// Peephole: ADD/SUB dst, N where dst == lhs and N ≤ 3 → INC/DEC dst × N.
		// N=1: 1B/4T vs 4B/15T; N=2: 2B/8T vs 4B/15T; N=3: 3B/12T vs 4B/15T.
		// N=4 would be 16T vs 15T — worse in T-states, skip and fall through to ALU.
		if mnem == "ADD" && lhs == dst {
			if cv, ok := g.constVals[inst.Src[1]]; ok && cv >= 1 && cv <= 3 {
				for range cv {
					g.emitf("    INC %s", dst)
				}
				g.invalidate(dst)
				return
			}
		}
		if mnem == "SUB" && lhs == dst {
			if cv, ok := g.constVals[inst.Src[1]]; ok && cv >= 1 && cv <= 3 {
				for range cv {
					g.emitf("    DEC %s", dst)
				}
				g.invalidate(dst)
				return
			}
		}
		// 8-bit: accumulator must hold lhs.  Emit LD A,lhs if needed.
		//
		// Special case: rhs is already A and lhs is elsewhere.
		// Loading lhs into A would destroy the rhs value.
		//   ADD: commutative → just ADD A, lhs.
		//   SUB: A = lhs - A → NEG first (A = -A), then ADD A, lhs.
		if rhs == "A" && lhs != "A" {
			g.invalidate("A") // A about to hold a new result
			switch mnem {
			case "ADD":
				g.emitf("    ADD A, %s", lhs)
			case "SUB":
				g.emit("    NEG")
				g.emitf("    ADD A, %s", lhs)
			default:
				g.comment(fmt.Sprintf("TODO: 8-bit %s %s, A → %s with A as rhs", mnem, lhs, dst))
				g.emitf("    LD A, %s", lhs)
				g.emit8ALU(mnem, rhs)
			}
			if dst != "A" {
				g.emitf("    LD %s, A", dst)
				g.setCopy(dst, "A")
			}
			return
		}
		// Coalescing: if A already holds lhs or (commutative) rhs, skip LD A, reg.
		isCommutative := mnem == "ADD" || mnem == "AND" || mnem == "OR" || mnem == "XOR"
		if g.holdsValue("A", lhs) {
			// A == lhs already — skip LD A, lhs.
			g.invalidate("A")
			g.emit8ALU(mnem, rhs)
			if dst != "A" {
				g.emitf("    LD %s, A", dst)
				g.setCopy(dst, "A")
			}
			return
		}
		if isCommutative && g.holdsValue("A", rhs) {
			// A == rhs, commutative swap: emit OP A, lhs instead.
			g.invalidate("A")
			g.emit8ALU(mnem, lhs)
			if dst != "A" {
				g.emitf("    LD %s, A", dst)
				g.setCopy(dst, "A")
			}
			return
		}

		// Immediate peephole: AND/OR/XOR/ADD/SUB n — no register needed for rhs.
		if cv, ok := g.constVals[inst.Src[1]]; ok {
			if lhs != "A" {
				g.emitLDA(lhs)
			}
			switch mnem {
			case "AND", "OR", "XOR", "SUB":
				g.emitf("    %s %d", mnem, cv)
			case "ADD":
				g.emitf("    ADD A, %d", cv)
			default:
				g.emit8ALU(mnem, rhs)
			}
			g.invalidate("A") // ALU result is a new value — break old lhs alias
			if dst != "A" {
				g.emitf("    LD %s, A", dst)
				g.setCopy(dst, "A")
			}
			return
		}
		if lhs != "A" {
			g.emitLDA(lhs)
		}
		g.emit8ALU(mnem, rhs)
		g.invalidate("A") // ALU result is a new value — break old lhs alias
		if dst != "A" {
			g.emitf("    LD %s, A", dst)
			g.setCopy(dst, "A")
		}
	} else {
		// 16-bit peephole: INC/DEC rr when adding/subtracting 1 in-place.
		if lhs == dst {
			if cv, ok := g.constVals[inst.Src[1]]; ok {
				if mnem == "ADD" && cv == 1 {
					g.emitf("    INC %s", dst)
					g.invalidate(dst) // pair + its bytes all change
					return
				}
				if mnem == "SUB" && cv == 1 {
					g.emitf("    DEC %s", dst)
					g.invalidate(dst)
					return
				}
			}
		}
		// 16-bit ADD: ADD HL,rr  (Z80 only has ADD HL,rr natively)
		// SUB/AND/OR/XOR on 16-bit require workarounds; emit comment for now.
		switch mnem {
		case "ADD":
			// Ensure lhs is in dst (HL usually).
			if lhs != dst {
				g.emitMov(dst, lhs, w)
			}
			g.emitf("    ADD %s, %s", dst, rhs)
			g.invalidate(dst)
		case "SUB":
			// SBC HL,rr (but clobbers carry; assume carry=0 before).
			if lhs != dst {
				g.emitMov(dst, lhs, w)
			}
			g.emit("    SCF")
			g.emit("    CCF") // clear carry
			g.emitf("    SBC %s, %s", dst, rhs)
			g.invalidate(dst)
		default:
			g.comment(fmt.Sprintf("TODO: 16-bit %s %s, %s → %s", mnem, lhs, rhs, dst))
		}
	}
}

// emit8ALU emits an 8-bit ALU instruction with A as the implicit destination.
// MZA requires "ADD A, src" (two operands) but "SUB/AND/OR/XOR src" (one operand).
func (g *z80cg) emit8ALU(mnem, src string) {
	switch mnem {
	case "ADD", "ADC":
		g.emitf("    %s A, %s", mnem, src)
	default:
		g.emitf("    %s %s", mnem, src)
	}
}

// ── Shifts ────────────────────────────────────────────────────────────────────

func (g *z80cg) genShift(mnem string, inst *Inst) {
	dst := g.loc(inst.Dst)
	src := g.loc(inst.Src[0])
	if dst != src {
		g.emitf("    LD %s, %s", dst, src)
		g.setCopy(dst, src)
	}
	// Shift count in Src[1] — Z80 shifts are always by 1 per instruction.
	// For constant counts, emit N copies.  Variable shifts → TODO.
	count := int64(1)
	if cv, ok := g.constVals[inst.Src[1]]; ok && cv > 0 {
		count = cv
	}
	for i := int64(0); i < count; i++ {
		g.emitf("    %s %s", mnem, dst)
	}
	g.invalidate(dst) // shift modifies dst
}

// ── Multiply ──────────────────────────────────────────────────────────────────

// genMul emits 8-bit unsigned multiply via shift-and-add.
// Power-of-2 constants use N×(ADD A,A); small constants use LD tmp,A + adds.
// Variable or large constants fall back to a software-loop comment (TODO).
func (g *z80cg) genMul(inst *Inst) {
	dst := g.loc(inst.Dst)
	lhs := g.loc(inst.Src[0])

	if inst.Ty.Width() > 8 {
		g.comment(fmt.Sprintf("TODO: 16-bit mul → %s", dst))
		return
	}

	cv, isConst := g.constVals[inst.Src[1]]

	if isConst {
		switch cv {
		case 0:
			g.emit("    XOR A")
			g.invalidate("A")
			if dst != "A" {
				g.emitf("    LD %s, A", dst)
				g.setCopy(dst, "A")
			}
			return
		case 1:
			if dst != lhs {
				g.emitMov(dst, lhs, 8)
			}
			return
		}
		// Power-of-2: log2(cv) × (ADD A,A).
		if cv > 0 && cv&(cv-1) == 0 {
			shifts := 0
			for n := cv; n > 1; n >>= 1 {
				shifts++
			}
			if !g.holdsValue("A", lhs) {
				g.emitLDA(lhs)
			}
			for i := 0; i < shifts; i++ {
				g.emit("    ADD A, A")
			}
			g.invalidate("A")
			if dst != "A" {
				g.emitf("    LD %s, A", dst)
				g.setCopy(dst, "A")
			}
			return
		}
		// x*3 = x + x*2: LD tmp,A; ADD A,A; ADD A,tmp
		// x*5 = x + x*4: LD tmp,A; ADD A,A; ADD A,A; ADD A,tmp
		// x*6 = x*2 + x*4: LD tmp,A; ADD A,A (tmp=x*2 in tmp); ADD A,A (A=x*4); ADD A,tmp
		// x*9 = x + x*8:   LD tmp,A; 3×ADD A,A; ADD A,tmp
		if cv == 3 || cv == 5 || cv == 6 || cv == 9 {
			if !g.holdsValue("A", lhs) {
				g.emitLDA(lhs)
			}
			// Pick a temp register that isn't A or dst.
			tmp := "C"
			if dst == "C" {
				tmp = "D"
			}
			switch cv {
			case 3: // x + x*2
				g.emitf("    LD %s, A", tmp) // tmp = x
				g.emit("    ADD A, A")        // A  = x*2
				g.emitf("    ADD A, %s", tmp) // A  = x*3
			case 5: // x + x*4
				g.emitf("    LD %s, A", tmp)
				g.emit("    ADD A, A")
				g.emit("    ADD A, A")         // A  = x*4
				g.emitf("    ADD A, %s", tmp) // A  = x*5
			case 6: // x*2 + x*4
				g.emit("    ADD A, A")         // A  = x*2
				g.emitf("    LD %s, A", tmp)  // tmp= x*2
				g.emit("    ADD A, A")         // A  = x*4
				g.emitf("    ADD A, %s", tmp) // A  = x*6
			case 9: // x + x*8
				g.emitf("    LD %s, A", tmp)
				g.emit("    ADD A, A")
				g.emit("    ADD A, A")
				g.emit("    ADD A, A")         // A  = x*8
				g.emitf("    ADD A, %s", tmp) // A  = x*9
			}
			g.invalidate("A")
			if dst != "A" {
				g.emitf("    LD %s, A", dst)
				g.setCopy(dst, "A")
			}
			return
		}
	}

	// Variable or unsupported constant: emit software-loop comment.
	rhs := g.loc(inst.Src[1])
	g.comment(fmt.Sprintf("TODO: general mul %s * %s → %s", lhs, rhs, dst))
}

// ── Type conversions ──────────────────────────────────────────────────────────

func (g *z80cg) genExt(inst *Inst) {
	dst := g.loc(inst.Dst)
	src := g.loc(inst.Src[0])
	srcW := inst.SrcTy.Width()
	dstW := inst.Ty.Width()

	if srcW == 8 && dstW == 16 {
		// Zero-extend u8 → u16.
		// dst should be a 16-bit reg (HL/DE/BC/IX/IY).
		// Most natural: put source in low byte, zero high byte.
		lo := lowByte(dst)
		hi := highByte(dst)
		if src != lo {
			g.emitf("    LD %s, %s", lo, src)
		}
		g.emitf("    LD %s, 0", hi)
		return
	}
	// Fallback.
	g.comment(fmt.Sprintf("TODO: ext %s→%s %s→%s", inst.SrcTy, inst.Ty, src, dst))
}

func (g *z80cg) genSext(inst *Inst) {
	dst := g.loc(inst.Dst)
	src := g.loc(inst.Src[0])
	srcW := inst.SrcTy.Width()
	dstW := inst.Ty.Width()

	if srcW == 8 && dstW == 16 {
		// Sign-extend u8 → u16 via A.
		lo := lowByte(dst)
		hi := highByte(dst)
		if src != "A" {
			g.emitf("    LD A, %s", src)
		}
		if lo != "A" {
			g.emitf("    LD %s, A", lo)
		}
		// Propagate sign bit into high byte: RLCA; SBC A,A gives 0x00 or 0xFF.
		g.emit("    RLCA")
		g.emit("    SBC A, A")
		if hi != "A" {
			g.emitf("    LD %s, A", hi)
		}
		return
	}
	g.comment(fmt.Sprintf("TODO: sext %s→%s %s→%s", inst.SrcTy, inst.Ty, src, dst))
}

// ── Compare ───────────────────────────────────────────────────────────────────

func (g *z80cg) genCmp(inst *Inst) {
	lhs := g.loc(inst.Src[0])
	rhs := g.loc(inst.Src[1])

	// 16-bit comparison: one or both operands are register pairs (HL/DE/BC/…).
	// Z80 only supports SBC HL, rr for 16-bit flag-setting subtraction.
	if isPairReg(lhs) || isPairReg(rhs) {
		g.genCmp16(inst)
		return
	}

	// CmpGt / CmpUgt and CmpLe / CmpUle are not directly expressible as a
	// single Z80 flag after a normal CP (which would need NC+NZ or C+Z).
	// Fix: force-swap the operands.
	//   CmpGt(a,b): a>b ↔ b<a → put b in A, CP a → C flag single-condition ✓
	//   CmpLe(a,b): a≤b ↔ b≥a → put b in A, CP a → NC flag single-condition ✓
	// Exception: rhs==0 is handled by the AND A path below (cmpAndZero mechanism
	// already returns NZ for Gt and Z for Le in condCode, so no swap needed).
	isGtOrLe := inst.Cond == CmpGt || inst.Cond == CmpUgt ||
		inst.Cond == CmpLe || inst.Cond == CmpUle
	if isGtOrLe {
		rhsIsZero := false
		if cv, ok := g.constVals[inst.Src[1]]; ok && cv == 0 {
			rhsIsZero = true
		}
		if !rhsIsZero {
			if lhs != "A" {
				// Force-swap: put rhs in A, emit CP lhs → single condition.
				//   CmpGt(a,b) → b<a → C flag ✓
				//   CmpLe(a,b) → b≥a → NC flag ✓
				if cv, ok := g.constVals[inst.Src[1]]; ok {
					g.emitf("    LD A, %d", cv)
					g.invalidate("A")
				} else if !g.holdsValue("A", rhs) {
					g.emitLDA(rhs)
				}
				g.emitf("    CP %s", lhs)
				g.cmpSwapped[inst.Dst] = true
				return
			}
			// lhs IS "A": force-swap would clobber the live value in A.
			// Emit normally (A=lhs already, CP rhs); TermBrIf will use two JPs.
			g.cmpNeedsTwo[inst.Dst] = true
			// Fall through to normal CP code (which will find A=lhs and emit CP rhs).
		}
		// rhsIsZero: fall through to AND A path (cmpAndZero handles NZ/Z).
	}

	// Z80 CP instruction: computes A − operand and sets flags.
	// We need A = lhs, then CP rhs.
	//
	// Peephole: if rhs is a known constant, use CP imm8 directly.
	// This avoids an extra register load (e.g. LD C,0 / LD A,B / CP C
	// → LD A,B / CP 0), and the constant no longer needs to be
	// materialised into a register (eliminating a dead store).
	if cv, ok := g.constVals[inst.Src[1]]; ok {
		if !g.holdsValue("A", lhs) {
			g.emitLDA(lhs)
		}
		if cv == 0 {
			g.emit("    AND A") // AND A ≡ CP 0 for all flags; 1B/4T vs 2B/7T
			g.cmpAndZero[inst.Dst] = true
		} else {
			g.emitf("    CP %d", cv)
		}
		// CP/AND A does not modify A; aliases remain valid.
		return
	}

	// Two-address conflict: if rhs is already in A and lhs is elsewhere,
	// loading lhs into A would destroy rhs.
	// Fix: swap operands (emit CP lhs with A=rhs) and mark as swapped.
	// condCode() will invert the CmpCond to compensate.
	if rhs == "A" && lhs != "A" {
		// A already holds rhs. CP lhs computes A−lhs = rhs−lhs.
		// This is the swapped comparison; condCode will invert it.
		g.emitf("    CP %s", lhs)
		g.cmpSwapped[inst.Dst] = true
		// CP does not modify A; aliases remain valid.
		return
	}

	// Coalescing: A already holds lhs — skip LD A, lhs.
	if !g.holdsValue("A", lhs) {
		g.emitLDA(lhs)
	}
	g.emitf("    CP %s", rhs)
	// CP does not modify A; aliases remain valid.
}

// ── Calls ─────────────────────────────────────────────────────────────────────

func (g *z80cg) genCall(inst *Inst) {
	clear(g.holdsPhys) // calls clobber all volatile registers
	if inst.Op == OpCallIndirect {
		ptr := g.loc(inst.Src[0])
		g.emitf("    CALL (%s)          ; indirect", ptr)
		return
	}

	// ── Built-in intrinsics (inlined, no CALL emitted) ────────────────────────
	switch inst.Sym {
	case "@mir.io.print.str":
		// Emit inline NUL-terminated string output loop via OUT (0x01), A.
		// The string pointer must be in HL (ClassPointer).
		// HL is advanced in-place; A and F are clobbered.
		idx := g.trampIdx
		g.trampIdx++
		g.emitf(".print_str_%d:", idx)
		g.emit("    LD A, (HL)")
		g.emit("    AND A")
		g.emitf("    JR Z, .print_str_done_%d", idx)
		g.emit("    OUT (0x01), A")
		g.emit("    INC HL")
		g.emitf("    JR .print_str_%d", idx)
		g.emitf(".print_str_done_%d:", idx)
		// A, F, HL clobbered — invalidate holdsPhys entries for these.
		g.invalidate("A")
		g.invalidate("HL")
		return

	case "@mir.io.print.u8":
		// Emit single OUT (0x01), A.  The value must already be in A.
		g.emit("    OUT (0x01), A")
		g.invalidate("A")
		return

	case "@mir.io.print.nl":
		// Emit newline (\n = 0x0A) via OUT (0x01), A.
		g.emit("    LD A, 0x0A")
		g.emit("    OUT (0x01), A")
		g.invalidate("A")
		return
	}

	sym := sanitizeIdent(inst.Sym)

	// Emit argument setup (parallel copy) when we have explicit Args and the
	// callee's contract is known.  This covers cases where the current physical
	// locations of the argument registers differ from the callee's expected
	// parameter locations (e.g. phi in C must move to A for the second CALL).
	var callee *Func
	if g.mod != nil {
		callee = g.mod.FuncByName(inst.Sym)
	}
	if len(inst.Args) > 0 && callee != nil && len(callee.Contract.Params) > 0 {
		g.emitCallArgs(inst.Args, callee.Contract.Params)
	}

	g.emitf("    CALL %s", sym)

	// The CALL clobbers A and F (volatile registers on Z80).  Remove physOverride
	// entries for any virtual register that was relocated into A or F by
	// emitCallArgs — those locations are no longer valid after the call.
	// Non-volatile relocations (B/C/D/E/H/L) remain valid.
	for r, phys := range g.physOverride {
		if phys == "A" || phys == "F" {
			delete(g.physOverride, r)
		}
	}

	// Flag-return ABI: if the callee returns ClassFlag, the result is in the CPU
	// flag register (not A).  Record which condition means "true" so that a
	// subsequent TermBrIf on inst.Dst can emit JP <cond> directly without
	// AND A / CP 0.
	if inst.Dst != NoReg && callee != nil {
		if len(callee.Contract.Returns) > 0 {
			ret := callee.Contract.Returns[0]
			if ret.Class == ClassFlag {
				g.callFlags[inst.Dst] = ret.FlagCond
			}
		}
	}
}

// emitCallArgs emits the parallel-copy argument setup for a CALL instruction.
// It maps the current physical locations of the call arguments to the physical
// locations expected by the callee's parameter contract and uses emitParallelCopy
// to resolve any cycles (e.g. A→B, C→A).
//
// As a side effect it updates physOverride so that loc(r) returns the new
// physical location for any virtual register that was moved by the copy.
// physOverride is cleared after the CALL by genCall.
func (g *z80cg) emitCallArgs(args []Reg, params []Param) {
	var copies []parallelCopy
	for i, arg := range args {
		if i >= len(params) {
			break
		}
		srcPhys := g.loc(arg)
		dstPhys := canonicalReturnLoc(params[i].Class, params[i].Ty)
		if srcPhys != dstPhys {
			copies = append(copies, parallelCopy{srcName: srcPhys, dstName: dstPhys, ty: params[i].Ty})
		}
	}
	if len(copies) == 0 {
		return
	}
	g.emitParallelCopy(copies)

	// Update physOverride for each argument that was relocated.
	// After any parallel copy sequence, each source arg ends up at its declared
	// destination physical location — regardless of chain/cycle resolution order.
	for i, arg := range args {
		if i >= len(params) {
			break
		}
		srcPhys := g.ar.Loc(arg).Name
		if p, ok := g.physOverride[arg]; ok {
			srcPhys = p
		}
		dstPhys := canonicalReturnLoc(params[i].Class, params[i].Ty)
		if srcPhys != dstPhys {
			g.physOverride[arg] = dstPhys
		}
	}
}

// ── Move helper ───────────────────────────────────────────────────────────────

func (g *z80cg) emitMov(dst, src string, widthBits int) {
	if dst == src {
		return
	}

	// ── Flag-register special cases ───────────────────────────────────────────

	if dst == "F" {
		// Materialise a register value into the flag register.
		// Convention: Z=1 (zero) means false, NZ means true — i.e. AND A / OR A.
		// Callers using CmpNe (NZ) as the flag condition get this for free.
		if src == "A" {
			g.emit("    AND A") // sets Z/NZ and clears C based on A's value
		} else {
			// Load into A first, then set flags.
			g.emitf("    LD A, %s", src)
			g.emit("    AND A")
		}
		g.invalidate("A")
		return
	}

	if src == "F" {
		// Materialise a flag result into a register.
		// Uses the SBC A,A trick for C-flag convention: A = 0xFF (carry set = true)
		// or 0x00 (carry clear = false).  Works for CmpLt/CmpUlt/CmpGe/CmpUge.
		//
		// For Z-flag convention (CmpEq/CmpNe), the sequence is:
		//   JR NZ, $+3 / SCF / then SBC A,A — converts Z to C, then materialise.
		// We use the simpler carry path by default; HIR lowers bool-returning
		// functions to carry-based comparisons where possible.
		if dst == "A" {
			g.emit("    SBC A, A") // A=0xFF if C=1 (true), A=0x00 if C=0 (false)
		} else {
			g.emit("    SBC A, A")
			g.emitf("    LD %s, A", dst)
		}
		g.invalidate("A")
		return
	}

	// ── Normal register moves ─────────────────────────────────────────────────

	if widthBits <= 8 {
		g.emitf("    LD %s, %s", dst, src)
		if isSimpleReg(dst) && isSimpleReg(src) {
			g.setCopy(dst, src)
		}
		return
	}
	// 16-bit register move.
	switch {
	case dst == "HL" && src == "DE":
		g.emit("    EX DE, HL")
	case dst == "DE" && src == "HL":
		g.emit("    EX DE, HL")
	default:
		// General 16-bit move via PUSH/POP.
		g.emitf("    PUSH %s", src)
		g.emitf("    POP %s", dst)
	}
}

// ── Terminators ───────────────────────────────────────────────────────────────

func (g *z80cg) genTerm(f *Func, t Term) {
	switch t := t.(type) {
	case *TermRet:
		// Move each return value to its calling-convention physical register.
		// Skip the move if the destination already holds the same value (copy alias).
		for i, rv := range t.Vals {
			if i >= len(g.fn.Contract.Returns) {
				break
			}
			ret := g.fn.Contract.Returns[i]
			retLoc := canonicalReturnLoc(ret.Class, ret.Ty)
			src := g.loc(rv)
			if src != retLoc && !g.holdsValue(retLoc, src) {
				g.emitMov(retLoc, src, ret.Ty.Width())
			}
		}
		g.emit("    RET")

	case *TermJmp:
		// Resolve block-argument parallel copies before the jump.
		copies := g.buildBlockCopies(f, t.Target, t.Args)
		g.emitParallelCopy(copies)
		// Fall-through elimination: if the target is the very next physical block,
		// the JP is redundant — execution falls through naturally.
		if !g.isFallThrough(f, t.Target) {
			g.emitf("    JP %s", blockLabel(f.Name, t.Target))
		}

	case *TermBrIf:
		cc := g.condCode(f, t.Cond)

		// Build block-arg copies for each edge.
		thenCopies := g.buildBlockCopies(f, t.Then, t.ThenArgs)
		elseCopies := g.buildBlockCopies(f, t.Else, t.ElseArgs)

		// If a branch has non-trivial copies, it cannot be a fall-through:
		// redirect it through a trampoline that performs the copies then JP.
		thenLbl := g.branchLabel(f, t.Then, thenCopies)
		elseLbl := g.branchLabel(f, t.Else, elseCopies)

		// Fall-through is only possible when there are no copies for that edge.
		thenFT := g.isFallThrough(f, t.Then) && len(thenCopies) == 0
		elseFT := g.isFallThrough(f, t.Else) && len(elseCopies) == 0

		// Two-condition sentinels: CmpGt/CmpLe with lhs in A (no operand swap).
		// CGT = NC && NZ (a > b); CLE = C || Z (a ≤ b).
		if cc == "CLE" {
			// a ≤ b: branch to then if C (a<b) or Z (a==b).
			g.emitf("    JP C, %s", thenLbl)
			g.emitf("    JP Z, %s", thenLbl)
			if !elseFT {
				g.emitf("    JP %s", elseLbl)
			}
		} else if cc == "CGT" {
			// a > b: branch to else if Z (a==b) or C (a<b), else fall/JP to then.
			g.emitf("    JP Z, %s", elseLbl)
			g.emitf("    JP C, %s", elseLbl)
			if !thenFT {
				g.emitf("    JP %s", thenLbl)
			}
		} else if elseFT {
			g.emitf("    JP %s, %s", cc, thenLbl)
			// else falls through naturally
		} else if thenFT {
			g.emitf("    JP %s, %s", invertCC(cc), elseLbl)
			// then falls through naturally
		} else {
			g.emitf("    JP %s, %s", cc, thenLbl)
			g.emitf("    JP %s", elseLbl)
		}

	case *TermBrIf2:
		// Three-way unsigned comparison: one CP, three outcomes (==, <, >).
		// Emit: CP rhs (with A=lhs), then JP Z eq, JP C lt, fall-through/JP gt.
		lhs := g.loc(t.Lhs)
		rhs := g.loc(t.Rhs)

		// Emit the CP (same logic as genCmp).
		if cv, ok := g.constVals[t.Rhs]; ok {
			if !g.holdsValue("A", lhs) {
				g.emitLDA(lhs)
			}
			g.emitf("    CP %d", cv)
		} else if rhs == "A" && lhs != "A" {
			// A already holds rhs; swap: CP lhs computes rhs-lhs.
			// Eq is still Z (rhs-lhs==0 ↔ rhs==lhs), but C now means rhs<lhs.
			// So we swap Lt↔Gt below.
			g.emitf("    CP %s", lhs)
			// Build copies for eq, swapped lt/gt.
			eqCopies := g.buildBlockCopies(f, t.Eq, t.EqArgs)
			ltCopies := g.buildBlockCopies(f, t.Gt, t.GtArgs) // swapped: C→gt
			gtCopies := g.buildBlockCopies(f, t.Lt, t.LtArgs) // swapped: NC,NZ→lt
			eqLbl := g.branchLabel(f, t.Eq, eqCopies)
			ltLbl := g.branchLabel(f, t.Gt, ltCopies)
			gtLbl := g.branchLabel(f, t.Lt, gtCopies)
			g.emitf("    JP Z, %s", eqLbl)
			g.emitf("    JP C, %s", ltLbl)
			if !g.isFallThrough(f, t.Lt) || len(gtCopies) != 0 {
				g.emitf("    JP %s", gtLbl)
			}
			return
		} else {
			if !g.holdsValue("A", lhs) {
				g.emitLDA(lhs)
			}
			g.emitf("    CP %s", rhs)
		}

		// Build copies for each of the three edges.
		eqCopies := g.buildBlockCopies(f, t.Eq, t.EqArgs)
		ltCopies := g.buildBlockCopies(f, t.Lt, t.LtArgs)
		gtCopies := g.buildBlockCopies(f, t.Gt, t.GtArgs)
		eqLbl := g.branchLabel(f, t.Eq, eqCopies)
		ltLbl := g.branchLabel(f, t.Lt, ltCopies)
		gtLbl := g.branchLabel(f, t.Gt, gtCopies)

		g.emitf("    JP Z, %s", eqLbl)
		g.emitf("    JP C, %s", ltLbl)
		if !g.isFallThrough(f, t.Gt) || len(gtCopies) != 0 {
			g.emitf("    JP %s", gtLbl)
		}

	case *TermDJNZ:
		// Emit body-edge copies for non-counter args.
		// The counter (B) is handled implicitly by DJNZ.
		// body.Params[0] = counter (gets decremented B); BodyArgs = params[1:].
		bodyBlock := f.BlockByLabel(t.Body)
		var bodyCopies []parallelCopy
		if bodyBlock != nil {
			for i, arg := range t.BodyArgs {
				if i+1 >= len(bodyBlock.Params) {
					break
				}
				param := bodyBlock.Params[i+1] // skip counter param[0]
				src := g.loc(arg)
				dst := g.ar.Loc(param.Dst).Name
				if src != dst {
					bodyCopies = append(bodyCopies, parallelCopy{srcName: src, dstName: dst, ty: param.Ty})
				}
			}
		}
		g.emitParallelCopy(bodyCopies)
		g.emitf("    DJNZ %s", blockLabel(f.Name, t.Body))
		// Exit path.
		exitCopies := g.buildBlockCopies(f, t.Exit, t.ExitArgs)
		g.emitParallelCopy(exitCopies)
		if !g.isFallThrough(f, t.Exit) || len(exitCopies) != 0 {
			g.emitf("    JP %s", blockLabel(f.Name, t.Exit))
		}

	case *TermUnreachable:
		g.comment("unreachable")
	}
}

// branchLabel returns the label to jump to for a BrIf edge.
// If the edge has parallel copies, a trampoline block is registered and its
// label is returned instead of the real target label.
func (g *z80cg) branchLabel(f *Func, target string, copies []parallelCopy) string {
	realLbl := blockLabel(f.Name, target)
	if len(copies) == 0 {
		return realLbl
	}
	tramLbl := fmt.Sprintf(".%s_trmp%d", sanitizeIdent(f.Name), g.trampIdx)
	g.trampIdx++
	g.trampolines = append(g.trampolines, trampolineBlock{
		label:  tramLbl,
		copies: copies,
		target: realLbl,
	})
	return tramLbl
}

// buildBlockCopies computes the parallel copies needed to pass args to a
// target block's formal parameters.  Returns only moves where src ≠ dst.
func (g *z80cg) buildBlockCopies(f *Func, targetName string, args []Reg) []parallelCopy {
	if len(args) == 0 {
		return nil
	}
	var target *Block
	for _, b := range f.Blocks {
		if b.Label == targetName {
			target = b
			break
		}
	}
	if target == nil {
		return nil
	}
	var copies []parallelCopy
	for i, arg := range args {
		if i >= len(target.Params) {
			break
		}
		src := g.ar.Loc(arg).Name
		dst := g.ar.Loc(target.Params[i].Dst).Name
		if src != dst {
			copies = append(copies, parallelCopy{srcName: src, dstName: dst, ty: target.Params[i].Ty})
		}
	}
	return copies
}

// emitParallelCopy resolves and emits a set of parallel register moves,
// correctly handling cycles (e.g. HL↔DE → EX DE,HL).
func (g *z80cg) emitParallelCopy(copies []parallelCopy) {
	if len(copies) == 0 {
		return
	}

	type move struct {
		src, dst string
		ty       Ty
		done     bool
	}
	moves := make([]move, len(copies))
	for i, c := range copies {
		moves[i] = move{src: c.srcName, dst: c.dstName, ty: c.ty}
	}

	for {
		// Emit any move whose dst is not a source of another pending move.
		progress := false
		for i := range moves {
			if moves[i].done {
				continue
			}
			dstNeeded := false
			for j := range moves {
				if j != i && !moves[j].done && moves[j].src == moves[i].dst {
					dstNeeded = true
					break
				}
			}
			if !dstNeeded {
				g.emitSingleCopy(moves[i].src, moves[i].dst, moves[i].ty)
				moves[i].done = true
				progress = true
				break
			}
		}
		if progress {
			continue
		}

		// All remaining moves form cycles.  Find first undone.
		first := -1
		undone := 0
		for i := range moves {
			if !moves[i].done {
				undone++
				if first == -1 {
					first = i
				}
			}
		}
		if first == -1 {
			break
		}

		// Special case: HL↔DE two-node cycle → EX DE, HL.
		if undone == 2 {
			a, b := -1, -1
			for i := range moves {
				if !moves[i].done {
					if a == -1 {
						a = i
					} else {
						b = i
					}
				}
			}
			as, ad := moves[a].src, moves[a].dst
			bs, bd := moves[b].src, moves[b].dst
			if (as == "HL" && ad == "DE" && bs == "DE" && bd == "HL") ||
				(as == "DE" && ad == "HL" && bs == "HL" && bd == "DE") {
				g.emit("    EX DE, HL")
				moves[a].done = true
				moves[b].done = true
				continue
			}
		}

		// General cycle: break with a temporary.
		m := &moves[first]
		if m.ty.Width() <= 8 {
			// u8 cycle: use A as scratch.
			//
			// Walk BACKWARD through the cycle so we always read old values.
			// Example 3-cycle D→C, C→E, E→D:
			//   Save A = D  (free the D slot)
			//   LD D, E     (backward: who writes TO D? E→D. Do it now while E is clean.)
			//   LD E, C     (backward: who writes TO E? C→E.)
			//   LD C, A     (put D_old into C, the first.dst)
			firstDst := m.dst
			if m.src != "A" {
				g.emitf("    LD A, %s", m.src)
			}
			m.done = true
			cur := m.src // start at the freed slot (m.src moved to A)
			for {
				found := false
				for i := range moves {
					if !moves[i].done && moves[i].dst == cur {
						g.emitf("    LD %s, %s", moves[i].dst, moves[i].src)
						cur = moves[i].src // the source is the new freed slot
						moves[i].done = true
						found = true
						break
					}
				}
				if !found {
					break
				}
			}
			if firstDst != "A" {
				g.emitf("    LD %s, A", firstDst)
			}
		} else {
			// u16 cycle: use stack.
			g.emitf("    PUSH %s", m.src)
			m.done = true
			cur := m.dst
			for {
				found := false
				for i := range moves {
					if !moves[i].done && moves[i].src == cur {
						g.emitSingleCopy(moves[i].src, moves[i].dst, moves[i].ty)
						cur = moves[i].dst
						moves[i].done = true
						found = true
						break
					}
				}
				if !found {
					break
				}
			}
			g.emitf("    POP %s", cur)
		}
	}
}

// emitSingleCopy emits a non-destructive register copy (src → dst).
// For 16-bit, this emits two LD instructions (not EX DE,HL which is a swap).
func (g *z80cg) emitSingleCopy(src, dst string, ty Ty) {
	if src == dst {
		return
	}
	if ty.Width() <= 8 {
		g.emitf("    LD %s, %s", dst, src)
	} else {
		// 16-bit non-destructive copy: two 8-bit LDs.
		g.emitf("    LD %s, %s", highByte(dst), highByte(src))
		g.emitf("    LD %s, %s", lowByte(dst), lowByte(src))
	}
}

// condCode returns the Z80 condition code for the virtual register holding
// the comparison result.  If genCmp swapped the operands, the condition
// is automatically inverted via CmpCond.Swap().
//
// For ClassFlag returns from CALL instructions, callFlags[cond] holds the
// agreed FlagCond directly — no AND A / CP 0 is needed at the call site.
func (g *z80cg) condCode(f *Func, cond Reg) string {
	// Fast path: call result with ClassFlag return — condition already in F.
	if fc, ok := g.callFlags[cond]; ok {
		return cmpCondCode(fc)
	}

	for _, b := range f.Blocks {
		for _, inst := range b.Insts {
			if inst.Dst == cond && inst.Op == OpCmp {
				c := inst.Cond
				if g.cmpSwapped[cond] {
					c = c.Swap() // operands were swapped → invert condition
				}
				// When genCmp emitted AND A (rhs=0), carry is always 0.
				// Replace NC/C-based conditions with NZ/Z-based ones:
				//   CmpGt(n, 0) → n != 0 → NZ
				//   CmpGe(n, 0) → n >= 0 → always true → handled as NC (fine)
				//   CmpLt(n, 0) → never for unsigned → C (never fires)
				//   CmpLe(n, 0) → n == 0 → Z
				if g.cmpAndZero[cond] {
					switch c {
					case CmpGt, CmpUgt:
						return "NZ"
					case CmpLe, CmpUle:
						return "Z"
					}
				}
				if g.cmpNeedsTwo[cond] {
					switch c {
					case CmpGt, CmpUgt:
						return "CGT" // NC && NZ: JP Z,else; JP NC,then
					case CmpLe, CmpUle:
						return "CLE" // C || Z: JP C,then; JP Z,then
					}
				}
				return cmpCondCode(c)
			}
		}
	}
	return "NZ" // fallback
}

// isFallThrough reports whether targetLabel is the next physical block after
// the current one (g.blockIdx), making a JP redundant.
func (g *z80cg) isFallThrough(f *Func, targetLabel string) bool {
	next := g.blockIdx + 1
	if next >= len(f.Blocks) {
		return false
	}
	return f.Blocks[next].Label == targetLabel
}

// invertCC returns the Z80 condition code that is the logical negation of cc.
func invertCC(cc string) string {
	switch cc {
	case "Z":
		return "NZ"
	case "NZ":
		return "Z"
	case "C":
		return "NC"
	case "NC":
		return "C"
	case "PE":
		return "PO"
	case "PO":
		return "PE"
	case "M":
		return "P"
	case "P":
		return "M"
	}
	return cc
}

// cmpCondCode maps CmpCond → Z80 condition string.
func cmpCondCode(c CmpCond) string {
	switch c {
	case CmpEq:
		return "Z"
	case CmpNe:
		return "NZ"
	case CmpLt, CmpUlt:
		return "C"
	case CmpGe, CmpUge:
		return "NC"
	case CmpLe, CmpUle:
		// LE: JP Z / JP C — requires two jumps; emit Z for now (backend TODO).
		return "Z"
	case CmpGt, CmpUgt:
		return "NC"
	}
	return "NZ"
}

// canonicalReturnLoc returns the physical register name where a return value of
// the given class and type must reside on function exit (calling convention).
func canonicalReturnLoc(cls RegClass, ty Ty) string {
	w := ty.Width()
	switch cls {
	case ClassFlag:
		// Flag-return ABI: result lives in the CPU flag register (F), not in A.
		// Callers test with JP <FlagCond> directly after the CALL instruction.
		// "F" is the sentinel name for LocFlag in Z80PhysLocs.
		return "F"
	case ClassAcc:
		if w <= 8 {
			return "A"
		}
		return "HL" // u16 [acc] → HL
	case ClassPointer, ClassPair:
		return "HL"
	case ClassIndex:
		return "DE"
	case ClassCounter:
		return "B"
	default:
		if w <= 8 {
			return "A"
		}
		return "HL"
	}
}

// ── Label helpers ─────────────────────────────────────────────────────────────

func blockLabel(funcName, blockLabel string) string {
	if blockLabel == "entry" {
		return sanitizeIdent(funcName)
	}
	return fmt.Sprintf(".%s_%s", sanitizeIdent(funcName), sanitizeIdent(blockLabel))
}

func sanitizeIdent(s string) string {
	var b strings.Builder
	for _, c := range s {
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
			(c >= '0' && c <= '9') || c == '_' {
			b.WriteRune(c)
		} else {
			b.WriteByte('_')
		}
	}
	return b.String()
}

// ── 16-bit register half helpers ──────────────────────────────────────────────

// lowByte returns the low-byte name of a 16-bit register.
func lowByte(rr string) string {
	switch rr {
	case "HL":
		return "L"
	case "DE":
		return "E"
	case "BC":
		return "C"
	case "IX":
		return "IXL"
	case "IY":
		return "IYL"
	}
	return rr // already 8-bit
}

// highByte returns the high-byte name of a 16-bit register.
func highByte(rr string) string {
	switch rr {
	case "HL":
		return "H"
	case "DE":
		return "D"
	case "BC":
		return "B"
	case "IX":
		return "IXH"
	case "IY":
		return "IYH"
	}
	return rr
}

// isPairReg reports whether r is a 16-bit register pair name.
func isPairReg(r string) bool {
	switch r {
	case "HL", "DE", "BC", "IX", "IY":
		return true
	}
	return false
}

// genCmp16 emits a 16-bit comparison using SBC HL, rr.
//
// Z80 only provides SBC HL, rr for 16-bit arithmetic that sets flags.
// The sequence is:
//
//	OR A           ; clear carry (preserves A; sets S/Z/H/PV from A)
//	SBC HL, rr     ; HL = lhs − rhs − 0; sets C (borrow) and Z (equal)
//
// SBC is destructive (clobbers HL).  We save/restore HL with PUSH/POP so
// that lhs remains available for subsequent uses (e.g. the "return a" branch
// of min16).
//
// Conditions after SBC HL, rr (unsigned):
//
//	C flag set   → lhs < rhs (CmpUlt / CmpUge after negation)
//	Z flag set   → lhs == rhs
//
// Signed comparisons (CmpLt/CmpGt on i16) require S⊕V which needs two
// conditional jumps — marked as TODO.
func (g *z80cg) genCmp16(inst *Inst) {
	lhs := g.loc(inst.Src[0])
	rhs := g.loc(inst.Src[1])

	// Handle CmpGt/CmpLe by swapping operands:
	//   CmpUgt(a,b): a>b ↔ b<a → swap → SBC HL(=b), rr(=a) → C means b<a ✓
	//   CmpUle(a,b): a≤b ↔ b≥a → swap → SBC HL(=b), rr(=a) → NC means b≥a ✓
	isGtOrLe := inst.Cond == CmpGt || inst.Cond == CmpUgt ||
		inst.Cond == CmpLe || inst.Cond == CmpUle
	if isGtOrLe {
		lhs, rhs = rhs, lhs
		g.cmpSwapped[inst.Dst] = true
	}

	// SBC HL, rr requires lhs in HL.  If lhs is already HL we proceed.
	// If rhs is HL and lhs is DE, EX DE,HL is the cheapest fix.
	// Otherwise move lhs byte-by-byte into HL.
	if lhs != "HL" {
		if lhs == "DE" && rhs == "HL" {
			// Swap via EX DE,HL: after EX, HL=old_DE=lhs, DE=old_HL=rhs.
			g.emit("    EX DE, HL")
			g.invalidate("HL")
			g.invalidate("DE")
			lhs, rhs = "HL", "DE"
		} else if rhs == "HL" {
			// rhs is HL, lhs is BC or IX/IY.  Byte-copy lhs into a temp.
			// Swap via move: save HL in rhs pair, load lhs to HL.
			// NOTE: this clobbers any live value in DE — use only when DE is free.
			g.emitf("    LD D, %s", highByte(rhs)) // save rhs high into D
			g.emitf("    LD E, %s", lowByte(rhs))  // save rhs low  into E
			g.emitf("    LD H, %s", highByte(lhs))
			g.emitf("    LD L, %s", lowByte(lhs))
			g.invalidate("HL")
			g.invalidate("DE")
			lhs, rhs = "HL", "DE"
		} else {
			// Neither operand is HL; move lhs into HL byte-by-byte.
			g.emitf("    LD H, %s", highByte(lhs))
			g.emitf("    LD L, %s", lowByte(lhs))
			g.invalidate("HL")
			lhs = "HL"
		}
	}

	// lhs is now in HL.  SBC HL, rr clobbers HL; save and restore so the
	// original lhs value survives for use in taken/not-taken branches.
	// TODO: elide PUSH/POP when liveness shows HL is dead after this compare.
	g.emit("    PUSH HL") // save lhs
	g.emit("    OR A")    // clear carry; idempotent for A
	g.emitf("    SBC HL, %s", rhs)
	g.emit("    POP HL")  // restore lhs
	g.invalidate("HL")
}

// ── PUSH/POP pair helpers ─────────────────────────────────────────────────────

// toPair returns the 16-bit register pair containing the given register.
func toPair(r string) string {
	switch r {
	case "A", "F", "AF":
		return "AF"
	case "B", "C", "BC":
		return "BC"
	case "D", "E", "DE":
		return "DE"
	case "H", "L", "HL":
		return "HL"
	}
	return r // IX, IY already pairs
}

// ── DJNZ peephole ─────────────────────────────────────────────────────────────

// findConstInFunc finds the Imm value of an OpConst instruction defining r.
func findConstInFunc(f *Func, r Reg) (int64, bool) {
	for _, b := range f.Blocks {
		for _, inst := range b.Insts {
			if inst.Op == OpConst && inst.Dst == r {
				return inst.Imm, true
			}
		}
	}
	return 0, false
}

// djnzPeepholeResult holds the result of DJNZ peephole detection.
type djnzPeepholeResult struct {
	skipLast  bool      // skip the last OpSub instruction (DJNZ handles DEC B)
	bodyLbl   string    // DJNZ target: the loop body label (brif.Then)
	checkBrif *TermBrIf // the check block's brif (for exit-edge copies)
}

// detectDJNZPeephole checks if block b ends with the DJNZ-optimizable pattern:
//
//	last_inst: OpSub(counter→B, 1)
//	term:      TermJmp to check_block
//	check_block: [OpCmp(CmpNe, B, 0)] + TermBrIf(Then=body, Else=exit)
//	all args trivially in-place (no non-trivial copies needed)
func (g *z80cg) detectDJNZPeephole(f *Func, b *Block) djnzPeepholeResult {
	if len(b.Insts) == 0 {
		return djnzPeepholeResult{}
	}
	jmp, ok := b.Term.(*TermJmp)
	if !ok {
		return djnzPeepholeResult{}
	}
	// Last instruction must be OpSub(counter, 1) with counter→B.
	last := b.Insts[len(b.Insts)-1]
	if last.Op != OpSub {
		return djnzPeepholeResult{}
	}
	if g.ar.Loc(last.Src[0]).Name != "B" || g.ar.Loc(last.Dst).Name != "B" {
		return djnzPeepholeResult{}
	}
	// RHS must be constant 1.
	rhs, found := findConstInFunc(f, last.Src[1])
	if !found || rhs != 1 {
		return djnzPeepholeResult{}
	}
	// Target must be the check block: only CmpNe(B, 0) + optional Const(0) + TermBrIf.
	check := f.BlockByLabel(jmp.Target)
	if check == nil || len(check.Insts) == 0 || len(check.Insts) > 2 {
		return djnzPeepholeResult{}
	}
	// Find the OpCmp instruction (last if there are two).
	var cmp *Inst
	for i := len(check.Insts) - 1; i >= 0; i-- {
		if check.Insts[i].Op == OpCmp {
			cmp = check.Insts[i]
			break
		}
	}
	if cmp == nil || cmp.Cond != CmpNe {
		return djnzPeepholeResult{}
	}
	if g.ar.Loc(cmp.Src[0]).Name != "B" {
		return djnzPeepholeResult{}
	}
	zero, found2 := findConstInFunc(f, cmp.Src[1])
	if !found2 || zero != 0 {
		return djnzPeepholeResult{}
	}
	// Verify all instructions in check block are CmpNe + optional Const(0) only.
	for _, inst := range check.Insts {
		if inst.Op != OpCmp && inst.Op != OpConst {
			return djnzPeepholeResult{}
		}
	}
	brif, ok2 := check.Term.(*TermBrIf)
	if !ok2 || brif.Cond != cmp.Dst {
		return djnzPeepholeResult{}
	}
	// Verify all TermJmp args are trivially in-place (excluding counter B→B).
	for i, arg := range jmp.Args {
		if i >= len(check.Params) {
			break
		}
		srcLoc := g.ar.Loc(arg).Name
		dstLoc := g.ar.Loc(check.Params[i].Dst).Name
		if srcLoc == "B" && dstLoc == "B" {
			continue // counter handled by DJNZ
		}
		if srcLoc != dstLoc {
			return djnzPeepholeResult{} // non-trivial copy, fall back
		}
	}
	// Verify exit-edge copies are trivial.
	exitBlock := f.BlockByLabel(brif.Else)
	if exitBlock != nil {
		for i, arg := range brif.ElseArgs {
			if i >= len(exitBlock.Params) {
				break
			}
			if g.ar.Loc(arg).Name != g.ar.Loc(exitBlock.Params[i].Dst).Name {
				return djnzPeepholeResult{} // non-trivial exit copy, fall back
			}
		}
	}
	return djnzPeepholeResult{
		skipLast:  true,
		bodyLbl:   blockLabel(f.Name, brif.Then),
		checkBrif: brif,
	}
}
