package mir2

import (
	"fmt"
	"strings"
)

// Z80Codegen lowers allocated MIR2 to Z80 assembly text (.a80 format).
//
// Prerequisites:
//   - AllocResult covering every virtual register in the module
//   - Verified MIR2 module (Verify passed)
//
// Output: a string of Z80 assembly ready for MZA.
// Label format: @funcname_blockname (underscore-joined, no special chars).
//
// Supported opcodes (first pass):
//
//	OpConst        → LD r, n  /  LD rr, nn
//	OpMove         → LD r, r  /  EX DE,HL  /  PUSH+POP
//	OpAdd          → ADD A,r  /  ADD HL,rr
//	OpSub          → SUB r    /  SBC HL,rr
//	OpAnd/Or/Xor   → AND/OR/XOR r
//	OpNeg          → NEG
//	OpNot          → CPL
//	OpExt          → LD H,0 / LD L,r  (zero-extend u8→u16 via HL)
//	OpCmp          → CP r  (result stays in F; ClassFlag)
//	OpLoad         → LD A,(HL)  /  LD r,(HL)
//	OpStore        → LD (HL),A  /  LD (HL),r
//	OpCall         → CALL label
//	OpPatchSlot    → LD r, 0   (initial value; literal byte patchable)
//	OpLoadPatched  → LD r, r   (SMC: already patched in stream)
//	OpPatch        → (comment: SMC patch — no emission in pure assembler)
//	TermJmp        → JP label
//	TermBrIf       → JP Z/NZ/C/NC label  (flag-class cond)
//	TermRet        → RET

// ── Public entry point ────────────────────────────────────────────────────────

// Z80Codegen generates Z80 assembly for the entire module.
func Z80Codegen(m *Module, ar *AllocResult) string {
	var sb strings.Builder
	cg := &z80cg{ar: ar, sb: &sb}

	sb.WriteString("; generated by MIR2 Z80 codegen\n\n")

	for _, f := range m.Funcs {
		cg.genFunc(f)
		sb.WriteByte('\n')
	}
	return sb.String()
}

// ── Internal codegen state ────────────────────────────────────────────────────

type z80cg struct {
	ar         *AllocResult
	sb         *strings.Builder
	fn         *Func   // current function
	blockIdx   int     // index of current block in fn.Blocks (for fall-through)
	cmpSwapped map[Reg]bool  // dst reg → operands were swapped in genCmp
	constVals  map[Reg]int64 // virtual reg → compile-time constant value (for peepholes)
	deadConsts map[Reg]bool  // OpConst dsts whose LD is suppressed by DSE

	// trampolines: small glue blocks emitted after main function body that
	// perform block-argument parallel copies then jump to the real target.
	// Needed for BrIf edges where the non-fall-through path requires copies.
	trampolines []trampolineBlock
	trampIdx    int
}

// trampolineBlock is emitted after all regular blocks of a function.
// It resolves block-argument copies for one outgoing BrIf edge.
type trampolineBlock struct {
	label  string        // local label for this trampoline
	copies []parallelCopy
	target string        // real destination label (already formatted)
}

// parallelCopy is a single register-to-register move in a parallel copy sequence.
type parallelCopy struct {
	srcName string
	dstName string
	ty      Ty
}

func (g *z80cg) emit(s string) { g.sb.WriteString(s); g.sb.WriteByte('\n') }
func (g *z80cg) emitf(f string, args ...any) { g.emit(fmt.Sprintf(f, args...)) }
func (g *z80cg) comment(s string)            { g.emitf("    ; %s", s) }

// loc returns the physical location name for virtual register r.
func (g *z80cg) loc(r Reg) string {
	if r == NoReg {
		return "?"
	}
	return g.ar.Loc(r).Name
}

// ── Function ──────────────────────────────────────────────────────────────────

// computeDeadConsts returns the set of OpConst dsts whose LD can be suppressed
// because every use of the constant is already handled by a codegen peephole:
//
//   - OpCmp with Src[1] being the const → CP imm8 fires (no register needed).
//   - OpAdd/OpSub with Src[1]==const, value==1, and lhs/dst at the same physical
//     location → INC/DEC fires (no register needed).
//
// Constants with zero uses are also suppressed.
func computeDeadConsts(f *Func, ar *AllocResult) map[Reg]bool {
	// Collect all OpConst dsts and their immediate values.
	constVal := make(map[Reg]int64)
	for _, b := range f.Blocks {
		for _, inst := range b.Insts {
			if inst.Op == OpConst {
				constVal[inst.Dst] = inst.Imm
			}
		}
	}
	if len(constVal) == 0 {
		return nil
	}

	physName := func(r Reg) string {
		if loc, ok := ar.Locs[r]; ok {
			return loc.Name
		}
		return ""
	}

	totalUses  := make(map[Reg]int)
	foldedUses := make(map[Reg]int)

	for _, b := range f.Blocks {
		for _, inst := range b.Insts {
			for _, src := range inst.Src {
				cv, isConst := constVal[src]
				if !isConst {
					continue
				}
				totalUses[src]++
				switch inst.Op {
				case OpCmp:
					// CP imm8: fires when rhs (Src[1]) has a known constant.
					if src == inst.Src[1] {
						foldedUses[src]++
					}
				case OpAdd, OpSub:
					// INC/DEC: fires when rhs==1 and the op is in-place (lhs phys == dst phys).
					if src == inst.Src[1] && cv == 1 &&
						physName(inst.Src[0]) == physName(inst.Dst) {
						foldedUses[src]++
					}
				case OpAnd, OpOr, OpXor:
					// AND/OR/XOR immediate peephole: always emits "AND n" etc., no register needed.
					if src == inst.Src[1] {
						foldedUses[src]++
					}
				case OpShl, OpShr, OpSar:
					// genShift always shifts by 1 and completely ignores Src[1].
					// Any constant passed as the shift count is effectively dead.
					if src == inst.Src[1] {
						foldedUses[src]++
					}
				}
			}
		}
		// Block args in terminators (TermJmp.Args, TermBrIf.*Args, TermRet.Vals)
		// are general uses — they cannot be peephole-folded.
		if b.Term != nil {
			for _, src := range b.Term.termUses() {
				if _, isConst := constVal[src]; isConst {
					totalUses[src]++
					// no foldedUses increment — terminators are never peephole-dead
				}
			}
		}
	}

	dead := make(map[Reg]bool)
	for r := range constVal {
		total := totalUses[r]
		if total == 0 || total == foldedUses[r] {
			dead[r] = true
		}
	}
	return dead
}

func (g *z80cg) genFunc(f *Func) {
	g.fn = f
	g.cmpSwapped = make(map[Reg]bool)
	g.constVals = make(map[Reg]int64)
	g.deadConsts = computeDeadConsts(f, g.ar)
	g.trampolines = g.trampolines[:0]
	g.trampIdx = 0

	label := sanitizeIdent(f.Name)
	g.emitf("%s:", label)

	for i, b := range f.Blocks {
		g.blockIdx = i
		g.genBlock(f, b)
	}

	// Emit trampoline blocks: small copy+JP stubs for BrIf edges with block args.
	for _, tramp := range g.trampolines {
		g.emitf("%s:", tramp.label)
		g.emitParallelCopy(tramp.copies)
		g.emitf("    JP %s", tramp.target)
	}
}

// ── Block ─────────────────────────────────────────────────────────────────────

func (g *z80cg) genBlock(f *Func, b *Block) {
	if b.Label != "entry" {
		g.emitf(".%s_%s:", sanitizeIdent(f.Name), sanitizeIdent(b.Label))
	}

	for _, inst := range b.Insts {
		g.genInst(inst)
	}
	g.genTerm(f, b.Term)
}

// ── Instructions ──────────────────────────────────────────────────────────────

func (g *z80cg) genInst(inst *Inst) {
	dst := g.loc(inst.Dst)

	switch inst.Op {
	case OpConst:
		g.constVals[inst.Dst] = inst.Imm
		if !g.deadConsts[inst.Dst] {
			g.emitf("    LD %s, %d", dst, inst.Imm)
		}

	case OpMove:
		src := g.loc(inst.Src[0])
		if dst == src {
			return // no-op
		}
		g.emitMov(dst, src, inst.Ty.Width())

	case OpAdd:
		g.genBinOp("ADD", inst)

	case OpSub:
		g.genBinOp("SUB", inst)

	case OpAnd:
		g.genBinOp("AND", inst)

	case OpOr:
		g.genBinOp("OR", inst)

	case OpXor:
		g.genBinOp("XOR", inst)

	case OpNeg:
		g.emit("    NEG")

	case OpNot:
		g.emit("    CPL")

	case OpShl:
		g.genShift("SLA", inst)

	case OpShr:
		g.genShift("SRL", inst)

	case OpSar:
		g.genShift("SRA", inst)

	case OpExt:
		// Zero-extend srcTy → Ty.  Primary case: u8 → u16 into HL.
		g.genExt(inst)

	case OpSext:
		g.genSext(inst)

	case OpTrunc:
		src := g.loc(inst.Src[0])
		// Truncate 16-bit → 8-bit: take low byte.
		// If dst is L and src is HL, or dst is E and src is DE — no-op.
		if dst != src {
			g.emitf("    LD %s, %s", dst, lowByte(src))
		}

	case OpCmp:
		g.genCmp(inst)

	case OpLoad:
		ptr := g.loc(inst.Src[0])
		w := inst.Ty.Width()
		if w <= 8 {
			g.emitf("    LD %s, (%s)", dst, ptr)
		} else {
			// 16-bit load: LD L,(ptr) / INC ptr / LD H,(ptr) — little-endian
			g.emitf("    LD %s, (%s)     ; lo", lowByte(dst), ptr)
			g.emitf("    INC %s", ptr)
			g.emitf("    LD %s, (%s)     ; hi", highByte(dst), ptr)
			g.emitf("    DEC %s", ptr)
		}

	case OpStore:
		ptr := g.loc(inst.Src[0])
		val := g.loc(inst.Src[1])
		w := inst.Ty.Width()
		if w <= 8 {
			g.emitf("    LD (%s), %s", ptr, val)
		} else {
			g.emitf("    LD (%s), %s     ; lo", ptr, lowByte(val))
			g.emitf("    INC %s", ptr)
			g.emitf("    LD (%s), %s     ; hi", ptr, highByte(val))
			g.emitf("    DEC %s", ptr)
		}

	case OpCall, OpCallIndirect:
		g.genCall(inst)

	case OpAddrOf:
		g.emitf("    LD %s, %s", dst, inst.Sym)

	case OpAlloca:
		// Reserve bytes on stack; dst = current SP.
		n := inst.Imm
		for range n {
			g.emit("    DEC SP")
		}
		g.emitf("    LD %s, SP", dst)

	case OpPatchSlot:
		// Mutable immediate: emit initial value; the byte after LD is patchable.
		w := inst.Ty.Width()
		if w <= 8 {
			g.emitf("    LD %s, %d          ; [patch_slot init=%d]", dst, inst.Imm, inst.Imm)
		} else {
			g.emitf("    LD %s, %d          ; [patch_slot init=%d]", dst, inst.Imm, inst.Imm)
		}

	case OpLoadPatched:
		// After patching, the slot register already holds the new value.
		// Emit a move; the codegen may elide this if dst == slot.
		slot := g.loc(inst.Src[0])
		if dst != slot {
			g.emitMov(dst, slot, inst.Ty.Width())
		}

	case OpPatch:
		// SMC patch: at runtime the code rewrites the immediate in OpPatchSlot.
		// In the pure-assembler path we emit a self-modifying write sequence.
		// slot = inst.Src[0], newVal = inst.Src[1]
		slotReg := g.loc(inst.Src[0])
		newVal := g.loc(inst.Src[1])
		g.comment(fmt.Sprintf("patch %s ← %s  (SMC: rewrite immediate in stream)", slotReg, newVal))
		// The patch_slot instruction is always LD r, n (2 bytes).
		// At runtime: caller computes address of the immediate byte and writes newVal.
		// We emit a placeholder comment; actual SMC requires knowing the patch address.
		// The Z80 backend will resolve this in a second pass.
		g.emitf("    ; TODO: LD (patch_addr_%s), %s", slotReg, newVal)

	case OpAsm:
		if inst.Asm != nil {
			g.emitf("    %s", inst.Asm.Template)
		}

	default:
		g.comment(fmt.Sprintf("TODO: %s", inst.Op))
	}
}

// ── Binary operations ─────────────────────────────────────────────────────────

func (g *z80cg) genBinOp(mnem string, inst *Inst) {
	dst := g.loc(inst.Dst)
	lhs := g.loc(inst.Src[0])
	rhs := g.loc(inst.Src[1])
	w := inst.Ty.Width()

	if w <= 8 {
		// Peephole: ADD/SUB dst, 1 where dst == lhs → INC/DEC dst (avoids clobbering A).
		if mnem == "ADD" && lhs == dst {
			if cv, ok := g.constVals[inst.Src[1]]; ok && cv == 1 {
				g.emitf("    INC %s", dst)
				return
			}
		}
		if mnem == "SUB" && lhs == dst {
			if cv, ok := g.constVals[inst.Src[1]]; ok && cv == 1 {
				g.emitf("    DEC %s", dst)
				return
			}
		}
		// 8-bit: accumulator must hold lhs.  Emit LD A,lhs if needed.
		//
		// Special case: rhs is already A and lhs is elsewhere.
		// Loading lhs into A would destroy the rhs value.
		//   ADD: commutative → just ADD A, lhs.
		//   SUB: A = lhs - A → NEG first (A = -A), then ADD A, lhs.
		if rhs == "A" && lhs != "A" {
			switch mnem {
			case "ADD":
				g.emitf("    ADD A, %s", lhs)
			case "SUB":
				g.emit("    NEG")
				g.emitf("    ADD A, %s", lhs)
			default:
				g.comment(fmt.Sprintf("TODO: 8-bit %s %s, A → %s with A as rhs", mnem, lhs, dst))
				g.emitf("    LD A, %s", lhs)
				g.emit8ALU(mnem, rhs)
			}
			if dst != "A" {
				g.emitf("    LD %s, A", dst)
			}
			return
		}
		// Immediate peephole: AND/OR/XOR/ADD/SUB n — no register needed for rhs.
		if cv, ok := g.constVals[inst.Src[1]]; ok {
			if lhs != "A" {
				g.emitf("    LD A, %s", lhs)
			}
			switch mnem {
			case "AND", "OR", "XOR", "SUB":
				g.emitf("    %s %d", mnem, cv)
			case "ADD":
				g.emitf("    ADD A, %d", cv)
			default:
				g.emit8ALU(mnem, rhs)
			}
			if dst != "A" {
				g.emitf("    LD %s, A", dst)
			}
			return
		}
		if lhs != "A" {
			g.emitf("    LD A, %s", lhs)
		}
		g.emit8ALU(mnem, rhs)
		if dst != "A" {
			g.emitf("    LD %s, A", dst)
		}
	} else {
		// 16-bit peephole: INC/DEC rr when adding/subtracting 1 in-place.
		if lhs == dst {
			if cv, ok := g.constVals[inst.Src[1]]; ok {
				if mnem == "ADD" && cv == 1 {
					g.emitf("    INC %s", dst)
					return
				}
				if mnem == "SUB" && cv == 1 {
					g.emitf("    DEC %s", dst)
					return
				}
			}
		}
		// 16-bit ADD: ADD HL,rr  (Z80 only has ADD HL,rr natively)
		// SUB/AND/OR/XOR on 16-bit require workarounds; emit comment for now.
		switch mnem {
		case "ADD":
			// Ensure lhs is in dst (HL usually).
			if lhs != dst {
				g.emitMov(dst, lhs, w)
			}
			g.emitf("    ADD %s, %s", dst, rhs)
		case "SUB":
			// SBC HL,rr (but clobbers carry; assume carry=0 before).
			if lhs != dst {
				g.emitMov(dst, lhs, w)
			}
			g.emit("    SCF")
			g.emit("    CCF") // clear carry
			g.emitf("    SBC %s, %s", dst, rhs)
		default:
			g.comment(fmt.Sprintf("TODO: 16-bit %s %s, %s → %s", mnem, lhs, rhs, dst))
		}
	}
}

// emit8ALU emits an 8-bit ALU instruction with A as the implicit destination.
// MZA requires "ADD A, src" (two operands) but "SUB/AND/OR/XOR src" (one operand).
func (g *z80cg) emit8ALU(mnem, src string) {
	switch mnem {
	case "ADD", "ADC":
		g.emitf("    %s A, %s", mnem, src)
	default:
		g.emitf("    %s %s", mnem, src)
	}
}

// ── Shifts ────────────────────────────────────────────────────────────────────

func (g *z80cg) genShift(mnem string, inst *Inst) {
	dst := g.loc(inst.Dst)
	src := g.loc(inst.Src[0])
	if dst != src {
		g.emitf("    LD %s, %s", dst, src)
	}
	// Shift count in Src[1] — on Z80 shifts are always by 1.
	// For constant counts, emit N rotates; variable shifts → TODO.
	g.emitf("    %s %s", mnem, dst)
}

// ── Type conversions ──────────────────────────────────────────────────────────

func (g *z80cg) genExt(inst *Inst) {
	dst := g.loc(inst.Dst)
	src := g.loc(inst.Src[0])
	srcW := inst.SrcTy.Width()
	dstW := inst.Ty.Width()

	if srcW == 8 && dstW == 16 {
		// Zero-extend u8 → u16.
		// dst should be a 16-bit reg (HL/DE/BC/IX/IY).
		// Most natural: put source in low byte, zero high byte.
		lo := lowByte(dst)
		hi := highByte(dst)
		if src != lo {
			g.emitf("    LD %s, %s", lo, src)
		}
		g.emitf("    LD %s, 0", hi)
		return
	}
	// Fallback.
	g.comment(fmt.Sprintf("TODO: ext %s→%s %s→%s", inst.SrcTy, inst.Ty, src, dst))
}

func (g *z80cg) genSext(inst *Inst) {
	dst := g.loc(inst.Dst)
	src := g.loc(inst.Src[0])
	srcW := inst.SrcTy.Width()
	dstW := inst.Ty.Width()

	if srcW == 8 && dstW == 16 {
		// Sign-extend u8 → u16 via A.
		lo := lowByte(dst)
		hi := highByte(dst)
		if src != "A" {
			g.emitf("    LD A, %s", src)
		}
		if lo != "A" {
			g.emitf("    LD %s, A", lo)
		}
		// Propagate sign bit into high byte: RLCA; SBC A,A gives 0x00 or 0xFF.
		g.emit("    RLCA")
		g.emit("    SBC A, A")
		if hi != "A" {
			g.emitf("    LD %s, A", hi)
		}
		return
	}
	g.comment(fmt.Sprintf("TODO: sext %s→%s %s→%s", inst.SrcTy, inst.Ty, src, dst))
}

// ── Compare ───────────────────────────────────────────────────────────────────

func (g *z80cg) genCmp(inst *Inst) {
	lhs := g.loc(inst.Src[0])
	rhs := g.loc(inst.Src[1])

	// Z80 CP instruction: computes A − operand and sets flags.
	// We need A = lhs, then CP rhs.
	//
	// Peephole: if rhs is a known constant, use CP imm8 directly.
	// This avoids an extra register load (e.g. LD C,0 / LD A,B / CP C
	// → LD A,B / CP 0), and the constant no longer needs to be
	// materialised into a register (eliminating a dead store).
	if cv, ok := g.constVals[inst.Src[1]]; ok {
		if lhs != "A" {
			g.emitf("    LD A, %s", lhs)
		}
		g.emitf("    CP %d", cv)
		return
	}

	// Two-address conflict: if rhs is already in A and lhs is elsewhere,
	// loading lhs into A would destroy rhs.
	// Fix: swap operands (emit CP lhs with A=rhs) and mark as swapped.
	// condCode() will invert the CmpCond to compensate.
	if rhs == "A" && lhs != "A" {
		// A already holds rhs. CP lhs computes A−lhs = rhs−lhs.
		// This is the swapped comparison; condCode will invert it.
		g.emitf("    CP %s", lhs)
		g.cmpSwapped[inst.Dst] = true
		return
	}

	if lhs != "A" {
		g.emitf("    LD A, %s", lhs)
	}
	g.emitf("    CP %s", rhs)
}

// ── Calls ─────────────────────────────────────────────────────────────────────

func (g *z80cg) genCall(inst *Inst) {
	if inst.Op == OpCallIndirect {
		ptr := g.loc(inst.Src[0])
		g.emitf("    CALL (%s)          ; indirect", ptr)
		return
	}
	sym := sanitizeIdent(inst.Sym)
	g.emitf("    CALL %s", sym)
}

// ── Move helper ───────────────────────────────────────────────────────────────

func (g *z80cg) emitMov(dst, src string, widthBits int) {
	if dst == src {
		return
	}
	if widthBits <= 8 {
		g.emitf("    LD %s, %s", dst, src)
		return
	}
	// 16-bit register move.
	switch {
	case dst == "HL" && src == "DE":
		g.emit("    EX DE, HL")
	case dst == "DE" && src == "HL":
		g.emit("    EX DE, HL")
	default:
		// General 16-bit move via PUSH/POP.
		g.emitf("    PUSH %s", src)
		g.emitf("    POP %s", dst)
	}
}

// ── Terminators ───────────────────────────────────────────────────────────────

func (g *z80cg) genTerm(f *Func, t Term) {
	switch t := t.(type) {
	case *TermRet:
		// Move each return value to its calling-convention physical register.
		for i, rv := range t.Vals {
			if i >= len(g.fn.Contract.Returns) {
				break
			}
			ret := g.fn.Contract.Returns[i]
			retLoc := canonicalReturnLoc(ret.Class, ret.Ty)
			src := g.loc(rv)
			if src != retLoc {
				g.emitMov(retLoc, src, ret.Ty.Width())
			}
		}
		g.emit("    RET")

	case *TermJmp:
		// Resolve block-argument parallel copies before the jump.
		copies := g.buildBlockCopies(f, t.Target, t.Args)
		g.emitParallelCopy(copies)
		// Fall-through elimination: if the target is the very next physical block,
		// the JP is redundant — execution falls through naturally.
		if !g.isFallThrough(f, t.Target) {
			g.emitf("    JP %s", blockLabel(f.Name, t.Target))
		}

	case *TermBrIf:
		cc := g.condCode(f, t.Cond)

		// Build block-arg copies for each edge.
		thenCopies := g.buildBlockCopies(f, t.Then, t.ThenArgs)
		elseCopies := g.buildBlockCopies(f, t.Else, t.ElseArgs)

		// If a branch has non-trivial copies, it cannot be a fall-through:
		// redirect it through a trampoline that performs the copies then JP.
		thenLbl := g.branchLabel(f, t.Then, thenCopies)
		elseLbl := g.branchLabel(f, t.Else, elseCopies)

		// Fall-through is only possible when there are no copies for that edge.
		thenFT := g.isFallThrough(f, t.Then) && len(thenCopies) == 0
		elseFT := g.isFallThrough(f, t.Else) && len(elseCopies) == 0

		if elseFT {
			g.emitf("    JP %s, %s", cc, thenLbl)
			// else falls through naturally
		} else if thenFT {
			g.emitf("    JP %s, %s", invertCC(cc), elseLbl)
			// then falls through naturally
		} else {
			g.emitf("    JP %s, %s", cc, thenLbl)
			g.emitf("    JP %s", elseLbl)
		}

	case *TermUnreachable:
		g.comment("unreachable")
	}
}

// branchLabel returns the label to jump to for a BrIf edge.
// If the edge has parallel copies, a trampoline block is registered and its
// label is returned instead of the real target label.
func (g *z80cg) branchLabel(f *Func, target string, copies []parallelCopy) string {
	realLbl := blockLabel(f.Name, target)
	if len(copies) == 0 {
		return realLbl
	}
	tramLbl := fmt.Sprintf(".%s_trmp%d", sanitizeIdent(f.Name), g.trampIdx)
	g.trampIdx++
	g.trampolines = append(g.trampolines, trampolineBlock{
		label:  tramLbl,
		copies: copies,
		target: realLbl,
	})
	return tramLbl
}

// buildBlockCopies computes the parallel copies needed to pass args to a
// target block's formal parameters.  Returns only moves where src ≠ dst.
func (g *z80cg) buildBlockCopies(f *Func, targetName string, args []Reg) []parallelCopy {
	if len(args) == 0 {
		return nil
	}
	var target *Block
	for _, b := range f.Blocks {
		if b.Label == targetName {
			target = b
			break
		}
	}
	if target == nil {
		return nil
	}
	var copies []parallelCopy
	for i, arg := range args {
		if i >= len(target.Params) {
			break
		}
		src := g.ar.Loc(arg).Name
		dst := g.ar.Loc(target.Params[i].Dst).Name
		if src != dst {
			copies = append(copies, parallelCopy{srcName: src, dstName: dst, ty: target.Params[i].Ty})
		}
	}
	return copies
}

// emitParallelCopy resolves and emits a set of parallel register moves,
// correctly handling cycles (e.g. HL↔DE → EX DE,HL).
func (g *z80cg) emitParallelCopy(copies []parallelCopy) {
	if len(copies) == 0 {
		return
	}

	type move struct {
		src, dst string
		ty       Ty
		done     bool
	}
	moves := make([]move, len(copies))
	for i, c := range copies {
		moves[i] = move{src: c.srcName, dst: c.dstName, ty: c.ty}
	}

	for {
		// Emit any move whose dst is not a source of another pending move.
		progress := false
		for i := range moves {
			if moves[i].done {
				continue
			}
			dstNeeded := false
			for j := range moves {
				if j != i && !moves[j].done && moves[j].src == moves[i].dst {
					dstNeeded = true
					break
				}
			}
			if !dstNeeded {
				g.emitSingleCopy(moves[i].src, moves[i].dst, moves[i].ty)
				moves[i].done = true
				progress = true
				break
			}
		}
		if progress {
			continue
		}

		// All remaining moves form cycles.  Find first undone.
		first := -1
		undone := 0
		for i := range moves {
			if !moves[i].done {
				undone++
				if first == -1 {
					first = i
				}
			}
		}
		if first == -1 {
			break
		}

		// Special case: HL↔DE two-node cycle → EX DE, HL.
		if undone == 2 {
			a, b := -1, -1
			for i := range moves {
				if !moves[i].done {
					if a == -1 {
						a = i
					} else {
						b = i
					}
				}
			}
			as, ad := moves[a].src, moves[a].dst
			bs, bd := moves[b].src, moves[b].dst
			if (as == "HL" && ad == "DE" && bs == "DE" && bd == "HL") ||
				(as == "DE" && ad == "HL" && bs == "HL" && bd == "DE") {
				g.emit("    EX DE, HL")
				moves[a].done = true
				moves[b].done = true
				continue
			}
		}

		// General cycle: break with a temporary.
		m := &moves[first]
		if m.ty.Width() <= 8 {
			// u8 cycle: use A as scratch.
			if m.src != "A" {
				g.emitf("    LD A, %s", m.src)
			}
			m.done = true
			cur := m.dst
			for {
				found := false
				for i := range moves {
					if !moves[i].done && moves[i].src == cur {
						g.emitf("    LD %s, %s", moves[i].dst, moves[i].src)
						cur = moves[i].dst
						moves[i].done = true
						found = true
						break
					}
				}
				if !found {
					break
				}
			}
			if cur != "A" {
				g.emitf("    LD %s, A", cur)
			}
		} else {
			// u16 cycle: use stack.
			g.emitf("    PUSH %s", m.src)
			m.done = true
			cur := m.dst
			for {
				found := false
				for i := range moves {
					if !moves[i].done && moves[i].src == cur {
						g.emitSingleCopy(moves[i].src, moves[i].dst, moves[i].ty)
						cur = moves[i].dst
						moves[i].done = true
						found = true
						break
					}
				}
				if !found {
					break
				}
			}
			g.emitf("    POP %s", cur)
		}
	}
}

// emitSingleCopy emits a non-destructive register copy (src → dst).
// For 16-bit, this emits two LD instructions (not EX DE,HL which is a swap).
func (g *z80cg) emitSingleCopy(src, dst string, ty Ty) {
	if src == dst {
		return
	}
	if ty.Width() <= 8 {
		g.emitf("    LD %s, %s", dst, src)
	} else {
		// 16-bit non-destructive copy: two 8-bit LDs.
		g.emitf("    LD %s, %s", highByte(dst), highByte(src))
		g.emitf("    LD %s, %s", lowByte(dst), lowByte(src))
	}
}

// condCode returns the Z80 condition code for the virtual register holding
// the comparison result.  If genCmp swapped the operands, the condition
// is automatically inverted via CmpCond.Swap().
func (g *z80cg) condCode(f *Func, cond Reg) string {
	for _, b := range f.Blocks {
		for _, inst := range b.Insts {
			if inst.Dst == cond && inst.Op == OpCmp {
				c := inst.Cond
				if g.cmpSwapped[cond] {
					c = c.Swap() // operands were swapped → invert condition
				}
				return cmpCondCode(c)
			}
		}
	}
	return "NZ" // fallback
}

// isFallThrough reports whether targetLabel is the next physical block after
// the current one (g.blockIdx), making a JP redundant.
func (g *z80cg) isFallThrough(f *Func, targetLabel string) bool {
	next := g.blockIdx + 1
	if next >= len(f.Blocks) {
		return false
	}
	return f.Blocks[next].Label == targetLabel
}

// invertCC returns the Z80 condition code that is the logical negation of cc.
func invertCC(cc string) string {
	switch cc {
	case "Z":
		return "NZ"
	case "NZ":
		return "Z"
	case "C":
		return "NC"
	case "NC":
		return "C"
	case "PE":
		return "PO"
	case "PO":
		return "PE"
	case "M":
		return "P"
	case "P":
		return "M"
	}
	return cc
}

// cmpCondCode maps CmpCond → Z80 condition string.
func cmpCondCode(c CmpCond) string {
	switch c {
	case CmpEq:
		return "Z"
	case CmpNe:
		return "NZ"
	case CmpLt, CmpUlt:
		return "C"
	case CmpGe, CmpUge:
		return "NC"
	case CmpLe, CmpUle:
		// LE: JP Z / JP C — requires two jumps; emit Z for now (backend TODO).
		return "Z"
	case CmpGt, CmpUgt:
		return "NC"
	}
	return "NZ"
}

// canonicalReturnLoc returns the physical register name where a return value of
// the given class and type must reside on function exit (calling convention).
func canonicalReturnLoc(cls RegClass, ty Ty) string {
	w := ty.Width()
	switch cls {
	case ClassAcc:
		if w <= 8 {
			return "A"
		}
		return "HL" // u16 [acc] → HL
	case ClassPointer, ClassPair:
		return "HL"
	case ClassIndex:
		return "DE"
	case ClassCounter:
		return "B"
	default:
		if w <= 8 {
			return "A"
		}
		return "HL"
	}
}

// ── Label helpers ─────────────────────────────────────────────────────────────

func blockLabel(funcName, blockLabel string) string {
	if blockLabel == "entry" {
		return sanitizeIdent(funcName)
	}
	return fmt.Sprintf(".%s_%s", sanitizeIdent(funcName), sanitizeIdent(blockLabel))
}

func sanitizeIdent(s string) string {
	var b strings.Builder
	for _, c := range s {
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
			(c >= '0' && c <= '9') || c == '_' {
			b.WriteRune(c)
		} else {
			b.WriteByte('_')
		}
	}
	return b.String()
}

// ── 16-bit register half helpers ──────────────────────────────────────────────

// lowByte returns the low-byte name of a 16-bit register.
func lowByte(rr string) string {
	switch rr {
	case "HL":
		return "L"
	case "DE":
		return "E"
	case "BC":
		return "C"
	case "IX":
		return "IXL"
	case "IY":
		return "IYL"
	}
	return rr // already 8-bit
}

// highByte returns the high-byte name of a 16-bit register.
func highByte(rr string) string {
	switch rr {
	case "HL":
		return "H"
	case "DE":
		return "D"
	case "BC":
		return "B"
	case "IX":
		return "IXH"
	case "IY":
		return "IYH"
	}
	return rr
}
