package mir2

import (
	"fmt"
	"strings"
)

// Z80Codegen lowers allocated MIR2 to Z80 assembly text (.a80 format).
//
// Prerequisites:
//   - AllocResult covering every virtual register in the module
//   - Verified MIR2 module (Verify passed)
//
// Output: a string of Z80 assembly ready for MZA.
// Label format: @funcname_blockname (underscore-joined, no special chars).
//
// Supported opcodes (first pass):
//
//	OpConst        → LD r, n  /  LD rr, nn
//	OpMove         → LD r, r  /  EX DE,HL  /  PUSH+POP
//	OpAdd          → ADD A,r  /  ADD HL,rr
//	OpSub          → SUB r    /  SBC HL,rr
//	OpAnd/Or/Xor   → AND/OR/XOR r
//	OpNeg          → NEG
//	OpNot          → CPL
//	OpExt          → LD H,0 / LD L,r  (zero-extend u8→u16 via HL)
//	OpCmp          → CP r  (result stays in F; ClassFlag)
//	OpLoad         → LD A,(HL)  /  LD r,(HL)
//	OpStore        → LD (HL),A  /  LD (HL),r
//	OpCall         → CALL label
//	OpPatchSlot    → LD r, 0   (initial value; literal byte patchable)
//	OpLoadPatched  → LD r, r   (SMC: already patched in stream)
//	OpPatch        → (comment: SMC patch — no emission in pure assembler)
//	TermJmp        → JP label
//	TermBrIf       → JP Z/NZ/C/NC label  (flag-class cond)
//	TermRet        → RET

// ── Public entry point ────────────────────────────────────────────────────────

// Z80Codegen generates Z80 assembly for the entire module.
func Z80Codegen(m *Module, ar *AllocResult) string {
	var sb strings.Builder
	cg := &z80cg{ar: ar, sb: &sb}

	sb.WriteString("; generated by MIR2 Z80 codegen\n\n")

	for _, f := range m.Funcs {
		cg.genFunc(f)
		sb.WriteByte('\n')
	}

	// Emit global variable data sections.
	if len(m.Globals) > 0 {
		sb.WriteString("; globals\n")
		for _, g := range m.Globals {
			w := ByteWidth(g.Ty)
			if w == 0 {
				continue
			}
			sb.WriteString(sanitizeIdent(g.Name) + ":\n")
			// Emit as DB sequence for all types — always readable,
			// correct for struct fields, and unambiguous byte order.
			sb.WriteString("    DB ")
			for i := 0; i < w; i++ {
				if i > 0 {
					sb.WriteString(", ")
				}
				b := byte(0)
				if i < len(g.Init) {
					b = g.Init[i]
				}
				fmt.Fprintf(&sb, "%d", b)
			}
			sb.WriteByte('\n')
		}
	}

	// Emit string pool — NUL-terminated byte sequences.
	// Symbol names: @mir2.str.N → mir2_str_N (sanitized for assembler).
	if m.Strings.Len() > 0 {
		sb.WriteString("; strings\n")
		for i := 0; i < m.Strings.Len(); i++ {
			sym := sanitizeIdent(m.Strings.Symbol(i))
			s := m.Strings.At(i)
			sb.WriteString(sym + ":\n")
			sb.WriteString("    DB ")
			for j, c := range []byte(s) {
				if j > 0 {
					sb.WriteString(", ")
				}
				fmt.Fprintf(&sb, "%d", c)
			}
			sb.WriteString(", 0\n") // NUL terminator
		}
	}

	return sb.String()
}

// ── Internal codegen state ────────────────────────────────────────────────────

type z80cg struct {
	ar         *AllocResult
	sb         *strings.Builder
	fn         *Func   // current function
	blockIdx   int     // index of current block in fn.Blocks (for fall-through)
	cmpSwapped  map[Reg]bool // dst reg → operands were swapped in genCmp
	cmpAndZero  map[Reg]bool // dst reg → comparison used AND A (rhs=0), use NZ/Z not NC/C
	constVals  map[Reg]int64 // virtual reg → compile-time constant value (for peepholes)
	deadConsts map[Reg]bool  // OpConst dsts whose LD is suppressed by DSE

	// holdsPhys is a bidirectional alias map for local copy-propagation within a
	// basic block.  holdsPhys[r] = s means physical register r currently holds the
	// same value as s (and holdsPhys[s] = r by symmetry).  Used to eliminate
	// redundant LD instructions: if A ≡ D, we skip "LD A, D" before an ALU op.
	// The map is cleared at every block boundary and at any CALL.
	holdsPhys map[string]string

	// trampolines: small glue blocks emitted after main function body that
	// perform block-argument parallel copies then jump to the real target.
	// Needed for BrIf edges where the non-fall-through path requires copies.
	trampolines []trampolineBlock
	trampIdx    int
}

// trampolineBlock is emitted after all regular blocks of a function.
// It resolves block-argument copies for one outgoing BrIf edge.
type trampolineBlock struct {
	label  string        // local label for this trampoline
	copies []parallelCopy
	target string        // real destination label (already formatted)
}

// parallelCopy is a single register-to-register move in a parallel copy sequence.
type parallelCopy struct {
	srcName string
	dstName string
	ty      Ty
}

func (g *z80cg) emit(s string) { g.sb.WriteString(s); g.sb.WriteByte('\n') }
func (g *z80cg) emitf(f string, args ...any) { g.emit(fmt.Sprintf(f, args...)) }
func (g *z80cg) comment(s string)            { g.emitf("    ; %s", s) }

// isSimpleReg reports whether s names a plain physical register (no parens,
// no digits) — safe to use as an alias key in holdsPhys.
func isSimpleReg(s string) bool {
	if len(s) == 0 {
		return false
	}
	for _, c := range s {
		if !((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z')) {
			return false
		}
	}
	return true
}

// ── Register topology ─────────────────────────────────────────────────────────
//
// Writing to a 16-bit pair register (e.g. HL) implicitly changes its bytes
// (H, L), and vice versa: writing to H invalidates HL.  These tables encode
// that topology so invalidate() can clear all affected aliases at once.

// regBytes maps a 16-bit register to its 8-bit byte components.
var regBytes = map[string][]string{
	"BC": {"B", "C"},
	"DE": {"D", "E"},
	"HL": {"H", "L"},
	"IX": {"IXH", "IXL"},
	"IY": {"IYH", "IYL"},
}

// regParent maps an 8-bit component to its 16-bit parent register.
var regParent = map[string]string{
	"B": "BC", "C": "BC",
	"D": "DE", "E": "DE",
	"H": "HL", "L": "HL",
	"IXH": "IX", "IXL": "IX",
	"IYH": "IY", "IYL": "IY",
}

// killOne removes a single register and its bidirectional partner from holdsPhys.
func (g *z80cg) killOne(r string) {
	if partner, ok := g.holdsPhys[r]; ok {
		delete(g.holdsPhys, partner)
		delete(g.holdsPhys, r)
	}
}

// invalidate removes all tracking for r: kills r itself, its byte components
// (if r is a 16-bit pair), and its parent pair (if r is an 8-bit component).
func (g *z80cg) invalidate(r string) {
	g.killOne(r)
	if bytes, ok := regBytes[r]; ok {
		for _, b := range bytes {
			g.killOne(b)
		}
	}
	if parent, ok := regParent[r]; ok {
		g.killOne(parent)
	}
}

// setCopy records that dst was loaded from src (they now hold the same value).
// Invalidates dst's old aliases and clears src's previous bidirectional link
// before establishing the new one, preventing stale reverse entries.
func (g *z80cg) setCopy(dst, src string) {
	g.invalidate(dst)
	g.killOne(src) // break src's old reverse-link (could be left by a prior setCopy)
	if isSimpleReg(dst) && isSimpleReg(src) {
		g.holdsPhys[dst] = src
		g.holdsPhys[src] = dst
	}
}

// holdsValue reports whether physical register a currently holds the same
// value as b (either they are the same register, or a copy alias exists).
func (g *z80cg) holdsValue(a, b string) bool {
	return a == b || g.holdsPhys[a] == b
}

// emitLDA emits "LD A, src" and records the copy alias A ≡ src.
func (g *z80cg) emitLDA(src string) {
	g.emitf("    LD A, %s", src)
	g.setCopy("A", src)
}

// loc returns the physical location name for virtual register r.
func (g *z80cg) loc(r Reg) string {
	if r == NoReg {
		return "?"
	}
	return g.ar.Loc(r).Name
}

// ── Function ──────────────────────────────────────────────────────────────────

// computeDeadConsts returns the set of OpConst dsts whose LD can be suppressed
// because every use of the constant is already handled by a codegen peephole:
//
//   - OpCmp with Src[1] being the const → CP imm8 fires (no register needed).
//   - OpAdd/OpSub with Src[1]==const, value==1, and lhs/dst at the same physical
//     location → INC/DEC fires (no register needed).
//
// Constants with zero uses are also suppressed.
func computeDeadConsts(f *Func, ar *AllocResult) map[Reg]bool {
	// Collect all OpConst dsts and their immediate values.
	constVal := make(map[Reg]int64)
	for _, b := range f.Blocks {
		for _, inst := range b.Insts {
			if inst.Op == OpConst {
				constVal[inst.Dst] = inst.Imm
			}
		}
	}
	if len(constVal) == 0 {
		return nil
	}

	physName := func(r Reg) string {
		if loc, ok := ar.Locs[r]; ok {
			return loc.Name
		}
		return ""
	}

	totalUses  := make(map[Reg]int)
	foldedUses := make(map[Reg]int)

	for _, b := range f.Blocks {
		for _, inst := range b.Insts {
			// Call/CallIndirect args live in inst.Args, not inst.Src — count them
			// as non-peephole uses so their LD is not suppressed.
			for _, src := range inst.Args {
				if _, isConst := constVal[src]; isConst {
					totalUses[src]++
					// call args are never peephole-foldable
				}
			}
			for _, src := range inst.Src {
				cv, isConst := constVal[src]
				if !isConst {
					continue
				}
				totalUses[src]++
				switch inst.Op {
				case OpCmp:
					// CP imm8: fires when rhs (Src[1]) has a known constant.
					if src == inst.Src[1] {
						foldedUses[src]++
					}
				case OpAdd, OpSub:
					// INC/DEC: fires when rhs==1 and the op is in-place (lhs phys == dst phys).
					if src == inst.Src[1] && cv == 1 &&
						physName(inst.Src[0]) == physName(inst.Dst) {
						foldedUses[src]++
					}
				case OpAnd, OpOr, OpXor:
					// AND/OR/XOR immediate peephole: always emits "AND n" etc., no register needed.
					if src == inst.Src[1] {
						foldedUses[src]++
					}
				case OpShl, OpShr, OpSar:
					// genShift always shifts by 1 and completely ignores Src[1].
					// Any constant passed as the shift count is effectively dead.
					if src == inst.Src[1] {
						foldedUses[src]++
					}
				}
			}
		}
		// Block args in terminators (TermJmp.Args, TermBrIf.*Args, TermRet.Vals)
		// are general uses — they cannot be peephole-folded.
		if b.Term != nil {
			for _, src := range b.Term.termUses() {
				if _, isConst := constVal[src]; isConst {
					totalUses[src]++
					// no foldedUses increment — terminators are never peephole-dead
				}
			}
		}
	}

	dead := make(map[Reg]bool)
	for r := range constVal {
		total := totalUses[r]
		if total == 0 || total == foldedUses[r] {
			dead[r] = true
		}
	}
	return dead
}

func (g *z80cg) genFunc(f *Func) {
	g.fn = f
	g.cmpSwapped = make(map[Reg]bool)
	g.cmpAndZero = make(map[Reg]bool)
	g.constVals = make(map[Reg]int64)
	g.deadConsts = computeDeadConsts(f, g.ar)
	g.holdsPhys = make(map[string]string)
	g.trampolines = g.trampolines[:0]
	g.trampIdx = 0

	label := sanitizeIdent(f.Name)
	g.emitf("%s:", label)

	for i, b := range f.Blocks {
		g.blockIdx = i
		g.genBlock(f, b)
	}

	// Emit trampoline blocks: small copy+JP stubs for BrIf edges with block args.
	for _, tramp := range g.trampolines {
		g.emitf("%s:", tramp.label)
		g.emitParallelCopy(tramp.copies)
		g.emitf("    JP %s", tramp.target)
	}
}

// ── Block ─────────────────────────────────────────────────────────────────────

func (g *z80cg) genBlock(f *Func, b *Block) {
	if b.Label != "entry" {
		g.emitf(".%s_%s:", sanitizeIdent(f.Name), sanitizeIdent(b.Label))
	}
	clear(g.holdsPhys) // all register aliases unknown at block entry

	for _, inst := range b.Insts {
		g.genInst(inst)
	}
	g.genTerm(f, b.Term)
}

// ── Instructions ──────────────────────────────────────────────────────────────

func (g *z80cg) genInst(inst *Inst) {
	dst := g.loc(inst.Dst)

	switch inst.Op {
	case OpConst:
		g.constVals[inst.Dst] = inst.Imm
		if !g.deadConsts[inst.Dst] {
			g.emitf("    LD %s, %d", dst, inst.Imm)
		}

	case OpMove:
		src := g.loc(inst.Src[0])
		if dst == src {
			return // no-op
		}
		g.emitMov(dst, src, inst.Ty.Width())

	case OpAdd:
		g.genBinOp("ADD", inst)

	case OpSub:
		g.genBinOp("SUB", inst)

	case OpAnd:
		g.genBinOp("AND", inst)

	case OpOr:
		g.genBinOp("OR", inst)

	case OpXor:
		g.genBinOp("XOR", inst)

	case OpNeg:
		g.emit("    NEG")
		g.invalidate("A")

	case OpNot:
		g.emit("    CPL")
		g.invalidate("A")

	case OpShl:
		g.genShift("SLA", inst)

	case OpShr:
		g.genShift("SRL", inst)

	case OpSar:
		g.genShift("SRA", inst)

	case OpExt:
		// Zero-extend srcTy → Ty.  Primary case: u8 → u16 into HL.
		g.genExt(inst)

	case OpSext:
		g.genSext(inst)

	case OpTrunc:
		src := g.loc(inst.Src[0])
		// Truncate 16-bit → 8-bit: take low byte.
		// If dst is L and src is HL, or dst is E and src is DE — no-op.
		if dst != src {
			g.emitf("    LD %s, %s", dst, lowByte(src))
		}

	case OpCmp:
		g.genCmp(inst)

	case OpLoad:
		ptr := g.loc(inst.Src[0])
		w := inst.Ty.Width()
		if w <= 8 {
			g.emitf("    LD %s, (%s)", dst, ptr)
		} else {
			// 16-bit load: LD L,(ptr) / INC ptr / LD H,(ptr) — little-endian
			g.emitf("    LD %s, (%s)     ; lo", lowByte(dst), ptr)
			g.emitf("    INC %s", ptr)
			g.emitf("    LD %s, (%s)     ; hi", highByte(dst), ptr)
			g.emitf("    DEC %s", ptr)
		}

	case OpStore:
		ptr := g.loc(inst.Src[0])
		val := g.loc(inst.Src[1])
		w := inst.Ty.Width()
		if w <= 8 {
			g.emitf("    LD (%s), %s", ptr, val)
		} else {
			g.emitf("    LD (%s), %s     ; lo", ptr, lowByte(val))
			g.emitf("    INC %s", ptr)
			g.emitf("    LD (%s), %s     ; hi", ptr, highByte(val))
			g.emitf("    DEC %s", ptr)
		}

	case OpCall, OpCallIndirect:
		g.genCall(inst)

	case OpAddrOf:
		g.emitf("    LD %s, %s", dst, inst.Sym)

	case OpPtrAdd:
		// Runtime pointer advance: dst = base_ptr + offset_u16.
		// Z80: needs both operands in 16-bit register pairs.
		// Optimal: base in HL (dst), offset in DE → ADD HL, DE (11T, no A clobber).
		base := g.loc(inst.Src[0])
		off := g.loc(inst.Src[1])
		if dst != base {
			g.emitMov(dst, base, 16)
		}
		// Ensure offset is in a 16-bit pair different from dst.
		offPair := off
		if len(off) == 1 { // 8-bit reg (A, B, C, D, E, H, L) — zero-extend to pair
			offPair = "DE"
			if dst == "DE" {
				offPair = "BC"
			}
			g.emitf("    LD %s, 0", offPair)
			g.emitf("    LD %s, %s", lowByte(offPair), off)
		} else if off == dst {
			// Same pair: ADD HL, HL doubles the pointer — that's wrong.
			// Move offset to temp pair first.
			offPair = "DE"
			if dst == "DE" {
				offPair = "BC"
			}
			g.emitMov(offPair, off, 16)
		}
		g.emitf("    ADD %s, %s", dst, offPair)
		g.invalidate(dst)

	case OpField, OpPtrBump:
		// Advance pointer by compile-time byte offset.
		// OpField: struct field access; OpPtrBump: iterator advance.
		// Same Z80 codegen for AoS layout (Phase 3). SoA256 INC L lowering: Phase 3c.
		src := g.loc(inst.Src[0])
		offset := inst.Imm
		if dst != src {
			g.emitMov(dst, src, 16) // copy base ptr
		}
		switch {
		case offset == 0:
			// nothing — dst already at target
		case offset <= 3:
			for range offset {
				g.emitf("    INC %s", dst)
			}
		default:
			// LD BC, offset; ADD HL, BC  (or equivalent pair for dst)
			tmp := "BC"
			if dst == "BC" {
				tmp = "DE"
			}
			g.emitf("    LD %s, %d", tmp, offset)
			g.emitf("    ADD %s, %s", dst, tmp)
		}
		g.invalidate(dst)

	case OpAlloca:
		// Reserve bytes on stack; dst = current SP.
		n := inst.Imm
		for range n {
			g.emit("    DEC SP")
		}
		g.emitf("    LD %s, SP", dst)

	case OpPatchSlot:
		// Mutable immediate: emit initial value; the byte after LD is patchable.
		w := inst.Ty.Width()
		if w <= 8 {
			g.emitf("    LD %s, %d          ; [patch_slot init=%d]", dst, inst.Imm, inst.Imm)
		} else {
			g.emitf("    LD %s, %d          ; [patch_slot init=%d]", dst, inst.Imm, inst.Imm)
		}

	case OpLoadPatched:
		// After patching, the slot register already holds the new value.
		// Emit a move; the codegen may elide this if dst == slot.
		slot := g.loc(inst.Src[0])
		if dst != slot {
			g.emitMov(dst, slot, inst.Ty.Width())
		}

	case OpPatch:
		// SMC patch: at runtime the code rewrites the immediate in OpPatchSlot.
		// In the pure-assembler path we emit a self-modifying write sequence.
		// slot = inst.Src[0], newVal = inst.Src[1]
		slotReg := g.loc(inst.Src[0])
		newVal := g.loc(inst.Src[1])
		g.comment(fmt.Sprintf("patch %s ← %s  (SMC: rewrite immediate in stream)", slotReg, newVal))
		// The patch_slot instruction is always LD r, n (2 bytes).
		// At runtime: caller computes address of the immediate byte and writes newVal.
		// We emit a placeholder comment; actual SMC requires knowing the patch address.
		// The Z80 backend will resolve this in a second pass.
		g.emitf("    ; TODO: LD (patch_addr_%s), %s", slotReg, newVal)

	case OpAsm:
		if inst.Asm != nil {
			g.emitf("    %s", inst.Asm.Template)
		}

	default:
		g.comment(fmt.Sprintf("TODO: %s", inst.Op))
	}
}

// ── Binary operations ─────────────────────────────────────────────────────────

func (g *z80cg) genBinOp(mnem string, inst *Inst) {
	dst := g.loc(inst.Dst)
	lhs := g.loc(inst.Src[0])
	rhs := g.loc(inst.Src[1])
	w := inst.Ty.Width()

	if w <= 8 {
		// Peephole: ADD/SUB dst, N where dst == lhs and N ≤ 3 → INC/DEC dst × N.
		// N=1: 1B/4T vs 4B/15T; N=2: 2B/8T vs 4B/15T; N=3: 3B/12T vs 4B/15T.
		// N=4 would be 16T vs 15T — worse in T-states, skip and fall through to ALU.
		if mnem == "ADD" && lhs == dst {
			if cv, ok := g.constVals[inst.Src[1]]; ok && cv >= 1 && cv <= 3 {
				for range cv {
					g.emitf("    INC %s", dst)
				}
				g.invalidate(dst)
				return
			}
		}
		if mnem == "SUB" && lhs == dst {
			if cv, ok := g.constVals[inst.Src[1]]; ok && cv >= 1 && cv <= 3 {
				for range cv {
					g.emitf("    DEC %s", dst)
				}
				g.invalidate(dst)
				return
			}
		}
		// 8-bit: accumulator must hold lhs.  Emit LD A,lhs if needed.
		//
		// Special case: rhs is already A and lhs is elsewhere.
		// Loading lhs into A would destroy the rhs value.
		//   ADD: commutative → just ADD A, lhs.
		//   SUB: A = lhs - A → NEG first (A = -A), then ADD A, lhs.
		if rhs == "A" && lhs != "A" {
			g.invalidate("A") // A about to hold a new result
			switch mnem {
			case "ADD":
				g.emitf("    ADD A, %s", lhs)
			case "SUB":
				g.emit("    NEG")
				g.emitf("    ADD A, %s", lhs)
			default:
				g.comment(fmt.Sprintf("TODO: 8-bit %s %s, A → %s with A as rhs", mnem, lhs, dst))
				g.emitf("    LD A, %s", lhs)
				g.emit8ALU(mnem, rhs)
			}
			if dst != "A" {
				g.emitf("    LD %s, A", dst)
				g.setCopy(dst, "A")
			}
			return
		}
		// Coalescing: if A already holds lhs or (commutative) rhs, skip LD A, reg.
		isCommutative := mnem == "ADD" || mnem == "AND" || mnem == "OR" || mnem == "XOR"
		if g.holdsValue("A", lhs) {
			// A == lhs already — skip LD A, lhs.
			g.invalidate("A")
			g.emit8ALU(mnem, rhs)
			if dst != "A" {
				g.emitf("    LD %s, A", dst)
				g.setCopy(dst, "A")
			}
			return
		}
		if isCommutative && g.holdsValue("A", rhs) {
			// A == rhs, commutative swap: emit OP A, lhs instead.
			g.invalidate("A")
			g.emit8ALU(mnem, lhs)
			if dst != "A" {
				g.emitf("    LD %s, A", dst)
				g.setCopy(dst, "A")
			}
			return
		}

		// Immediate peephole: AND/OR/XOR/ADD/SUB n — no register needed for rhs.
		if cv, ok := g.constVals[inst.Src[1]]; ok {
			if lhs != "A" {
				g.emitLDA(lhs)
			}
			switch mnem {
			case "AND", "OR", "XOR", "SUB":
				g.emitf("    %s %d", mnem, cv)
			case "ADD":
				g.emitf("    ADD A, %d", cv)
			default:
				g.emit8ALU(mnem, rhs)
			}
			g.invalidate("A") // ALU result is a new value — break old lhs alias
			if dst != "A" {
				g.emitf("    LD %s, A", dst)
				g.setCopy(dst, "A")
			}
			return
		}
		if lhs != "A" {
			g.emitLDA(lhs)
		}
		g.emit8ALU(mnem, rhs)
		g.invalidate("A") // ALU result is a new value — break old lhs alias
		if dst != "A" {
			g.emitf("    LD %s, A", dst)
			g.setCopy(dst, "A")
		}
	} else {
		// 16-bit peephole: INC/DEC rr when adding/subtracting 1 in-place.
		if lhs == dst {
			if cv, ok := g.constVals[inst.Src[1]]; ok {
				if mnem == "ADD" && cv == 1 {
					g.emitf("    INC %s", dst)
					g.invalidate(dst) // pair + its bytes all change
					return
				}
				if mnem == "SUB" && cv == 1 {
					g.emitf("    DEC %s", dst)
					g.invalidate(dst)
					return
				}
			}
		}
		// 16-bit ADD: ADD HL,rr  (Z80 only has ADD HL,rr natively)
		// SUB/AND/OR/XOR on 16-bit require workarounds; emit comment for now.
		switch mnem {
		case "ADD":
			// Ensure lhs is in dst (HL usually).
			if lhs != dst {
				g.emitMov(dst, lhs, w)
			}
			g.emitf("    ADD %s, %s", dst, rhs)
			g.invalidate(dst)
		case "SUB":
			// SBC HL,rr (but clobbers carry; assume carry=0 before).
			if lhs != dst {
				g.emitMov(dst, lhs, w)
			}
			g.emit("    SCF")
			g.emit("    CCF") // clear carry
			g.emitf("    SBC %s, %s", dst, rhs)
			g.invalidate(dst)
		default:
			g.comment(fmt.Sprintf("TODO: 16-bit %s %s, %s → %s", mnem, lhs, rhs, dst))
		}
	}
}

// emit8ALU emits an 8-bit ALU instruction with A as the implicit destination.
// MZA requires "ADD A, src" (two operands) but "SUB/AND/OR/XOR src" (one operand).
func (g *z80cg) emit8ALU(mnem, src string) {
	switch mnem {
	case "ADD", "ADC":
		g.emitf("    %s A, %s", mnem, src)
	default:
		g.emitf("    %s %s", mnem, src)
	}
}

// ── Shifts ────────────────────────────────────────────────────────────────────

func (g *z80cg) genShift(mnem string, inst *Inst) {
	dst := g.loc(inst.Dst)
	src := g.loc(inst.Src[0])
	if dst != src {
		g.emitf("    LD %s, %s", dst, src)
		g.setCopy(dst, src)
	}
	// Shift count in Src[1] — Z80 shifts are always by 1 per instruction.
	// For constant counts, emit N copies.  Variable shifts → TODO.
	count := int64(1)
	if cv, ok := g.constVals[inst.Src[1]]; ok && cv > 0 {
		count = cv
	}
	for i := int64(0); i < count; i++ {
		g.emitf("    %s %s", mnem, dst)
	}
	g.invalidate(dst) // shift modifies dst
}

// ── Type conversions ──────────────────────────────────────────────────────────

func (g *z80cg) genExt(inst *Inst) {
	dst := g.loc(inst.Dst)
	src := g.loc(inst.Src[0])
	srcW := inst.SrcTy.Width()
	dstW := inst.Ty.Width()

	if srcW == 8 && dstW == 16 {
		// Zero-extend u8 → u16.
		// dst should be a 16-bit reg (HL/DE/BC/IX/IY).
		// Most natural: put source in low byte, zero high byte.
		lo := lowByte(dst)
		hi := highByte(dst)
		if src != lo {
			g.emitf("    LD %s, %s", lo, src)
		}
		g.emitf("    LD %s, 0", hi)
		return
	}
	// Fallback.
	g.comment(fmt.Sprintf("TODO: ext %s→%s %s→%s", inst.SrcTy, inst.Ty, src, dst))
}

func (g *z80cg) genSext(inst *Inst) {
	dst := g.loc(inst.Dst)
	src := g.loc(inst.Src[0])
	srcW := inst.SrcTy.Width()
	dstW := inst.Ty.Width()

	if srcW == 8 && dstW == 16 {
		// Sign-extend u8 → u16 via A.
		lo := lowByte(dst)
		hi := highByte(dst)
		if src != "A" {
			g.emitf("    LD A, %s", src)
		}
		if lo != "A" {
			g.emitf("    LD %s, A", lo)
		}
		// Propagate sign bit into high byte: RLCA; SBC A,A gives 0x00 or 0xFF.
		g.emit("    RLCA")
		g.emit("    SBC A, A")
		if hi != "A" {
			g.emitf("    LD %s, A", hi)
		}
		return
	}
	g.comment(fmt.Sprintf("TODO: sext %s→%s %s→%s", inst.SrcTy, inst.Ty, src, dst))
}

// ── Compare ───────────────────────────────────────────────────────────────────

func (g *z80cg) genCmp(inst *Inst) {
	lhs := g.loc(inst.Src[0])
	rhs := g.loc(inst.Src[1])

	// Z80 CP instruction: computes A − operand and sets flags.
	// We need A = lhs, then CP rhs.
	//
	// Peephole: if rhs is a known constant, use CP imm8 directly.
	// This avoids an extra register load (e.g. LD C,0 / LD A,B / CP C
	// → LD A,B / CP 0), and the constant no longer needs to be
	// materialised into a register (eliminating a dead store).
	if cv, ok := g.constVals[inst.Src[1]]; ok {
		if !g.holdsValue("A", lhs) {
			g.emitLDA(lhs)
		}
		if cv == 0 {
			g.emit("    AND A") // AND A ≡ CP 0 for all flags; 1B/4T vs 2B/7T
			g.cmpAndZero[inst.Dst] = true
		} else {
			g.emitf("    CP %d", cv)
		}
		// CP/AND A does not modify A; aliases remain valid.
		return
	}

	// Two-address conflict: if rhs is already in A and lhs is elsewhere,
	// loading lhs into A would destroy rhs.
	// Fix: swap operands (emit CP lhs with A=rhs) and mark as swapped.
	// condCode() will invert the CmpCond to compensate.
	if rhs == "A" && lhs != "A" {
		// A already holds rhs. CP lhs computes A−lhs = rhs−lhs.
		// This is the swapped comparison; condCode will invert it.
		g.emitf("    CP %s", lhs)
		g.cmpSwapped[inst.Dst] = true
		// CP does not modify A; aliases remain valid.
		return
	}

	// Coalescing: A already holds lhs — skip LD A, lhs.
	if !g.holdsValue("A", lhs) {
		g.emitLDA(lhs)
	}
	g.emitf("    CP %s", rhs)
	// CP does not modify A; aliases remain valid.
}

// ── Calls ─────────────────────────────────────────────────────────────────────

func (g *z80cg) genCall(inst *Inst) {
	clear(g.holdsPhys) // calls clobber all volatile registers
	if inst.Op == OpCallIndirect {
		ptr := g.loc(inst.Src[0])
		g.emitf("    CALL (%s)          ; indirect", ptr)
		return
	}
	sym := sanitizeIdent(inst.Sym)
	g.emitf("    CALL %s", sym)
}

// ── Move helper ───────────────────────────────────────────────────────────────

func (g *z80cg) emitMov(dst, src string, widthBits int) {
	if dst == src {
		return
	}
	if widthBits <= 8 {
		g.emitf("    LD %s, %s", dst, src)
		if isSimpleReg(dst) && isSimpleReg(src) {
			g.setCopy(dst, src)
		}
		return
	}
	// 16-bit register move.
	switch {
	case dst == "HL" && src == "DE":
		g.emit("    EX DE, HL")
	case dst == "DE" && src == "HL":
		g.emit("    EX DE, HL")
	default:
		// General 16-bit move via PUSH/POP.
		g.emitf("    PUSH %s", src)
		g.emitf("    POP %s", dst)
	}
}

// ── Terminators ───────────────────────────────────────────────────────────────

func (g *z80cg) genTerm(f *Func, t Term) {
	switch t := t.(type) {
	case *TermRet:
		// Move each return value to its calling-convention physical register.
		// Skip the move if the destination already holds the same value (copy alias).
		for i, rv := range t.Vals {
			if i >= len(g.fn.Contract.Returns) {
				break
			}
			ret := g.fn.Contract.Returns[i]
			retLoc := canonicalReturnLoc(ret.Class, ret.Ty)
			src := g.loc(rv)
			if src != retLoc && !g.holdsValue(retLoc, src) {
				g.emitMov(retLoc, src, ret.Ty.Width())
			}
		}
		g.emit("    RET")

	case *TermJmp:
		// Resolve block-argument parallel copies before the jump.
		copies := g.buildBlockCopies(f, t.Target, t.Args)
		g.emitParallelCopy(copies)
		// Fall-through elimination: if the target is the very next physical block,
		// the JP is redundant — execution falls through naturally.
		if !g.isFallThrough(f, t.Target) {
			g.emitf("    JP %s", blockLabel(f.Name, t.Target))
		}

	case *TermBrIf:
		cc := g.condCode(f, t.Cond)

		// Build block-arg copies for each edge.
		thenCopies := g.buildBlockCopies(f, t.Then, t.ThenArgs)
		elseCopies := g.buildBlockCopies(f, t.Else, t.ElseArgs)

		// If a branch has non-trivial copies, it cannot be a fall-through:
		// redirect it through a trampoline that performs the copies then JP.
		thenLbl := g.branchLabel(f, t.Then, thenCopies)
		elseLbl := g.branchLabel(f, t.Else, elseCopies)

		// Fall-through is only possible when there are no copies for that edge.
		thenFT := g.isFallThrough(f, t.Then) && len(thenCopies) == 0
		elseFT := g.isFallThrough(f, t.Else) && len(elseCopies) == 0

		if elseFT {
			g.emitf("    JP %s, %s", cc, thenLbl)
			// else falls through naturally
		} else if thenFT {
			g.emitf("    JP %s, %s", invertCC(cc), elseLbl)
			// then falls through naturally
		} else {
			g.emitf("    JP %s, %s", cc, thenLbl)
			g.emitf("    JP %s", elseLbl)
		}

	case *TermBrIf2:
		// Three-way unsigned comparison: one CP, three outcomes (==, <, >).
		// Emit: CP rhs (with A=lhs), then JP Z eq, JP C lt, fall-through/JP gt.
		lhs := g.loc(t.Lhs)
		rhs := g.loc(t.Rhs)

		// Emit the CP (same logic as genCmp).
		if cv, ok := g.constVals[t.Rhs]; ok {
			if !g.holdsValue("A", lhs) {
				g.emitLDA(lhs)
			}
			g.emitf("    CP %d", cv)
		} else if rhs == "A" && lhs != "A" {
			// A already holds rhs; swap: CP lhs computes rhs-lhs.
			// Eq is still Z (rhs-lhs==0 ↔ rhs==lhs), but C now means rhs<lhs.
			// So we swap Lt↔Gt below.
			g.emitf("    CP %s", lhs)
			// Build copies for eq, swapped lt/gt.
			eqCopies := g.buildBlockCopies(f, t.Eq, t.EqArgs)
			ltCopies := g.buildBlockCopies(f, t.Gt, t.GtArgs) // swapped: C→gt
			gtCopies := g.buildBlockCopies(f, t.Lt, t.LtArgs) // swapped: NC,NZ→lt
			eqLbl := g.branchLabel(f, t.Eq, eqCopies)
			ltLbl := g.branchLabel(f, t.Gt, ltCopies)
			gtLbl := g.branchLabel(f, t.Lt, gtCopies)
			g.emitf("    JP Z, %s", eqLbl)
			g.emitf("    JP C, %s", ltLbl)
			if !g.isFallThrough(f, t.Lt) || len(gtCopies) != 0 {
				g.emitf("    JP %s", gtLbl)
			}
			return
		} else {
			if !g.holdsValue("A", lhs) {
				g.emitLDA(lhs)
			}
			g.emitf("    CP %s", rhs)
		}

		// Build copies for each of the three edges.
		eqCopies := g.buildBlockCopies(f, t.Eq, t.EqArgs)
		ltCopies := g.buildBlockCopies(f, t.Lt, t.LtArgs)
		gtCopies := g.buildBlockCopies(f, t.Gt, t.GtArgs)
		eqLbl := g.branchLabel(f, t.Eq, eqCopies)
		ltLbl := g.branchLabel(f, t.Lt, ltCopies)
		gtLbl := g.branchLabel(f, t.Gt, gtCopies)

		g.emitf("    JP Z, %s", eqLbl)
		g.emitf("    JP C, %s", ltLbl)
		if !g.isFallThrough(f, t.Gt) || len(gtCopies) != 0 {
			g.emitf("    JP %s", gtLbl)
		}

	case *TermUnreachable:
		g.comment("unreachable")
	}
}

// branchLabel returns the label to jump to for a BrIf edge.
// If the edge has parallel copies, a trampoline block is registered and its
// label is returned instead of the real target label.
func (g *z80cg) branchLabel(f *Func, target string, copies []parallelCopy) string {
	realLbl := blockLabel(f.Name, target)
	if len(copies) == 0 {
		return realLbl
	}
	tramLbl := fmt.Sprintf(".%s_trmp%d", sanitizeIdent(f.Name), g.trampIdx)
	g.trampIdx++
	g.trampolines = append(g.trampolines, trampolineBlock{
		label:  tramLbl,
		copies: copies,
		target: realLbl,
	})
	return tramLbl
}

// buildBlockCopies computes the parallel copies needed to pass args to a
// target block's formal parameters.  Returns only moves where src ≠ dst.
func (g *z80cg) buildBlockCopies(f *Func, targetName string, args []Reg) []parallelCopy {
	if len(args) == 0 {
		return nil
	}
	var target *Block
	for _, b := range f.Blocks {
		if b.Label == targetName {
			target = b
			break
		}
	}
	if target == nil {
		return nil
	}
	var copies []parallelCopy
	for i, arg := range args {
		if i >= len(target.Params) {
			break
		}
		src := g.ar.Loc(arg).Name
		dst := g.ar.Loc(target.Params[i].Dst).Name
		if src != dst {
			copies = append(copies, parallelCopy{srcName: src, dstName: dst, ty: target.Params[i].Ty})
		}
	}
	return copies
}

// emitParallelCopy resolves and emits a set of parallel register moves,
// correctly handling cycles (e.g. HL↔DE → EX DE,HL).
func (g *z80cg) emitParallelCopy(copies []parallelCopy) {
	if len(copies) == 0 {
		return
	}

	type move struct {
		src, dst string
		ty       Ty
		done     bool
	}
	moves := make([]move, len(copies))
	for i, c := range copies {
		moves[i] = move{src: c.srcName, dst: c.dstName, ty: c.ty}
	}

	for {
		// Emit any move whose dst is not a source of another pending move.
		progress := false
		for i := range moves {
			if moves[i].done {
				continue
			}
			dstNeeded := false
			for j := range moves {
				if j != i && !moves[j].done && moves[j].src == moves[i].dst {
					dstNeeded = true
					break
				}
			}
			if !dstNeeded {
				g.emitSingleCopy(moves[i].src, moves[i].dst, moves[i].ty)
				moves[i].done = true
				progress = true
				break
			}
		}
		if progress {
			continue
		}

		// All remaining moves form cycles.  Find first undone.
		first := -1
		undone := 0
		for i := range moves {
			if !moves[i].done {
				undone++
				if first == -1 {
					first = i
				}
			}
		}
		if first == -1 {
			break
		}

		// Special case: HL↔DE two-node cycle → EX DE, HL.
		if undone == 2 {
			a, b := -1, -1
			for i := range moves {
				if !moves[i].done {
					if a == -1 {
						a = i
					} else {
						b = i
					}
				}
			}
			as, ad := moves[a].src, moves[a].dst
			bs, bd := moves[b].src, moves[b].dst
			if (as == "HL" && ad == "DE" && bs == "DE" && bd == "HL") ||
				(as == "DE" && ad == "HL" && bs == "HL" && bd == "DE") {
				g.emit("    EX DE, HL")
				moves[a].done = true
				moves[b].done = true
				continue
			}
		}

		// General cycle: break with a temporary.
		m := &moves[first]
		if m.ty.Width() <= 8 {
			// u8 cycle: use A as scratch.
			//
			// Walk BACKWARD through the cycle so we always read old values.
			// Example 3-cycle D→C, C→E, E→D:
			//   Save A = D  (free the D slot)
			//   LD D, E     (backward: who writes TO D? E→D. Do it now while E is clean.)
			//   LD E, C     (backward: who writes TO E? C→E.)
			//   LD C, A     (put D_old into C, the first.dst)
			firstDst := m.dst
			if m.src != "A" {
				g.emitf("    LD A, %s", m.src)
			}
			m.done = true
			cur := m.src // start at the freed slot (m.src moved to A)
			for {
				found := false
				for i := range moves {
					if !moves[i].done && moves[i].dst == cur {
						g.emitf("    LD %s, %s", moves[i].dst, moves[i].src)
						cur = moves[i].src // the source is the new freed slot
						moves[i].done = true
						found = true
						break
					}
				}
				if !found {
					break
				}
			}
			if firstDst != "A" {
				g.emitf("    LD %s, A", firstDst)
			}
		} else {
			// u16 cycle: use stack.
			g.emitf("    PUSH %s", m.src)
			m.done = true
			cur := m.dst
			for {
				found := false
				for i := range moves {
					if !moves[i].done && moves[i].src == cur {
						g.emitSingleCopy(moves[i].src, moves[i].dst, moves[i].ty)
						cur = moves[i].dst
						moves[i].done = true
						found = true
						break
					}
				}
				if !found {
					break
				}
			}
			g.emitf("    POP %s", cur)
		}
	}
}

// emitSingleCopy emits a non-destructive register copy (src → dst).
// For 16-bit, this emits two LD instructions (not EX DE,HL which is a swap).
func (g *z80cg) emitSingleCopy(src, dst string, ty Ty) {
	if src == dst {
		return
	}
	if ty.Width() <= 8 {
		g.emitf("    LD %s, %s", dst, src)
	} else {
		// 16-bit non-destructive copy: two 8-bit LDs.
		g.emitf("    LD %s, %s", highByte(dst), highByte(src))
		g.emitf("    LD %s, %s", lowByte(dst), lowByte(src))
	}
}

// condCode returns the Z80 condition code for the virtual register holding
// the comparison result.  If genCmp swapped the operands, the condition
// is automatically inverted via CmpCond.Swap().
func (g *z80cg) condCode(f *Func, cond Reg) string {
	for _, b := range f.Blocks {
		for _, inst := range b.Insts {
			if inst.Dst == cond && inst.Op == OpCmp {
				c := inst.Cond
				if g.cmpSwapped[cond] {
					c = c.Swap() // operands were swapped → invert condition
				}
				// When genCmp emitted AND A (rhs=0), carry is always 0.
				// Replace NC/C-based conditions with NZ/Z-based ones:
				//   CmpGt(n, 0) → n != 0 → NZ
				//   CmpGe(n, 0) → n >= 0 → always true → handled as NC (fine)
				//   CmpLt(n, 0) → never for unsigned → C (never fires)
				//   CmpLe(n, 0) → n == 0 → Z
				if g.cmpAndZero[cond] {
					switch c {
					case CmpGt, CmpUgt:
						return "NZ"
					case CmpLe, CmpUle:
						return "Z"
					}
				}
				return cmpCondCode(c)
			}
		}
	}
	return "NZ" // fallback
}

// isFallThrough reports whether targetLabel is the next physical block after
// the current one (g.blockIdx), making a JP redundant.
func (g *z80cg) isFallThrough(f *Func, targetLabel string) bool {
	next := g.blockIdx + 1
	if next >= len(f.Blocks) {
		return false
	}
	return f.Blocks[next].Label == targetLabel
}

// invertCC returns the Z80 condition code that is the logical negation of cc.
func invertCC(cc string) string {
	switch cc {
	case "Z":
		return "NZ"
	case "NZ":
		return "Z"
	case "C":
		return "NC"
	case "NC":
		return "C"
	case "PE":
		return "PO"
	case "PO":
		return "PE"
	case "M":
		return "P"
	case "P":
		return "M"
	}
	return cc
}

// cmpCondCode maps CmpCond → Z80 condition string.
func cmpCondCode(c CmpCond) string {
	switch c {
	case CmpEq:
		return "Z"
	case CmpNe:
		return "NZ"
	case CmpLt, CmpUlt:
		return "C"
	case CmpGe, CmpUge:
		return "NC"
	case CmpLe, CmpUle:
		// LE: JP Z / JP C — requires two jumps; emit Z for now (backend TODO).
		return "Z"
	case CmpGt, CmpUgt:
		return "NC"
	}
	return "NZ"
}

// canonicalReturnLoc returns the physical register name where a return value of
// the given class and type must reside on function exit (calling convention).
func canonicalReturnLoc(cls RegClass, ty Ty) string {
	w := ty.Width()
	switch cls {
	case ClassAcc:
		if w <= 8 {
			return "A"
		}
		return "HL" // u16 [acc] → HL
	case ClassPointer, ClassPair:
		return "HL"
	case ClassIndex:
		return "DE"
	case ClassCounter:
		return "B"
	default:
		if w <= 8 {
			return "A"
		}
		return "HL"
	}
}

// ── Label helpers ─────────────────────────────────────────────────────────────

func blockLabel(funcName, blockLabel string) string {
	if blockLabel == "entry" {
		return sanitizeIdent(funcName)
	}
	return fmt.Sprintf(".%s_%s", sanitizeIdent(funcName), sanitizeIdent(blockLabel))
}

func sanitizeIdent(s string) string {
	var b strings.Builder
	for _, c := range s {
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
			(c >= '0' && c <= '9') || c == '_' {
			b.WriteRune(c)
		} else {
			b.WriteByte('_')
		}
	}
	return b.String()
}

// ── 16-bit register half helpers ──────────────────────────────────────────────

// lowByte returns the low-byte name of a 16-bit register.
func lowByte(rr string) string {
	switch rr {
	case "HL":
		return "L"
	case "DE":
		return "E"
	case "BC":
		return "C"
	case "IX":
		return "IXL"
	case "IY":
		return "IYL"
	}
	return rr // already 8-bit
}

// highByte returns the high-byte name of a 16-bit register.
func highByte(rr string) string {
	switch rr {
	case "HL":
		return "H"
	case "DE":
		return "D"
	case "BC":
		return "B"
	case "IX":
		return "IXH"
	case "IY":
		return "IYH"
	}
	return rr
}
