; eZ80 ADL mode assembly — generated by MinZ compiler
; Target: Agon Light 2 (eZ80 @ 18.432 MHz)

    .ASSUME ADL=1
    ORG $040045

; fun main()
main:
    LD HL, _mir2.str.0
    CALL mos_puts
    LD HL, _mir2.str.1
    CALL mos_puts
    RET

; fun mos_putchar(ch: u8 = A)
mos_putchar:
    ; TODO: asm
    RET

; fun mos_puts(str: ptr = HL)
mos_puts:
    ; TODO: asm
    RET

; strings
_mir2.str.0:
    DB 72, 101, 108, 108, 111, 32, 102, 114, 111, 109, 32, 77, 105, 110, 90, 32, 111, 110, 32, 65, 103, 111, 110, 32, 76, 105, 103, 104, 116, 32, 50, 33, 13, 10, 0
_mir2.str.1:
    DB 101, 90, 56, 48, 32, 65, 68, 76, 32, 109, 111, 100, 101, 44, 32, 99, 111, 109, 112, 105, 108, 101, 100, 32, 119, 105, 116, 104, 32, 45, 98, 32, 101, 122, 56, 48, 13, 10, 0
