; eZ80 ADL mode assembly — generated by MinZ compiler
; Target: Agon Light 2 (eZ80 @ 18.432 MHz)

    .ASSUME ADL=1
    ORG $040045

; fun main()
main:
    CALL tui_clear
    CALL tui_hide_cursor
    CALL draw_title
    CALL draw_panel
    CALL draw_status_bar
    LD C, 1
    LD D, 0
    JP .main_loop_head1
.main_loop_head1:
    LD D, 0
    LD A, C
    CP 0
    JP NZ, .main_loop_body2
    JP .main_loop_exit3
.main_loop_body2:
    CALL tui_read_key
    LD HL, KEY_UP
    LD D, (HL)
    LD A, ?
    CP D
    JP Z, .main_if_then4
    JP .main_if_join5
.main_if_then4:
    LD HL, cursor
    LD D, (HL)
    LD E, 0
    LD A, D
    CP 0
    JP NZ, .main_if_then6
    JP .main_if_join7
.main_if_then6:
    LD HL, cursor
    LD D, (HL)
    LD HL, cursor
    LD E, (HL)
    LD H, 1
    LD A, E
    SUB 1
    LD HL, cursor
    LD (HL), A
    LD A, D
    CALL draw_file_entry
    LD HL, cursor
    LD D, (HL)
    LD A, D
    CALL draw_file_entry
    JP .main_if_join7
.main_if_join7:
    JP .main_if_join5
.main_if_join5:
    LD HL, KEY_DOWN
    LD D, (HL)
    LD A, ?
    CP D
    JP Z, .main_if_then8
    JP .main_if_join9
.main_if_then8:
    LD HL, cursor
    LD D, (HL)
    LD HL, FILE_COUNT
    LD E, (HL)
    LD H, 1
    LD A, E
    SUB 1
    LD A, D
    CP A
    JP NZ, .main_if_then10
    JP .main_if_join11
.main_if_then10:
    LD HL, cursor
    LD D, (HL)
    LD HL, cursor
    LD E, (HL)
    LD H, 1
    LD A, E
    ADD A, 1
    LD HL, cursor
    LD (HL), A
    LD A, D
    CALL draw_file_entry
    LD HL, cursor
    LD D, (HL)
    LD A, D
    CALL draw_file_entry
    JP .main_if_join11
.main_if_join11:
    JP .main_if_join9
.main_if_join9:
    LD HL, KEY_ESC
    LD D, (HL)
    LD A, ?
    CP D
    JP Z, .main_if_then12
    JP .main_if_join13
.main_if_then12:
    LD C, 0
    JP .main_if_join13
.main_if_join13:
    LD HL, KEY_ENTER
    LD D, (HL)
    LD A, ?
    CP D
    JP Z, .main_if_then14
    JP .main_if_join15
.main_if_then14:
    LD A, 0
    LD D, 22
    CALL tui_goto
    LD HL, COLOR_GREEN
    LD D, (HL)
    LD A, D
    LD HL, COLOR_BLACK
    LD D, (HL)
    LD B, 1
    CALL tui_color
    LD HL, _mir2.str.30
    CALL tui_puts
    LD HL, cursor
    LD D, (HL)
    LD A, D
    CALL file_name
    LD L, 0
    LD H, A
    CALL tui_puts
    LD HL, _mir2.str.31
    CALL tui_puts
    JP .main_if_join15
.main_if_join15:
    LD D, ?
    JP .main_loop_head1
.main_loop_exit3:
    CALL tui_show_cursor
    CALL tui_reset
    CALL tui_clear
    RET

; fun agon$tui_render$_tui_mos_putchar(ch: u8 = A)
agon_tui_render__tui_mos_putchar:
    RST.LIL $10
    RET

; fun agon$tui_render$_tui_esc()
agon_tui_render__tui_esc:
    LD A, $1B
        RST.LIL $10
    RET

; fun agon$tui_render$_tui_mos_puts(str: ptr = HL)
agon_tui_render__tui_mos_puts:
    .loop: LD A, (HL)
    OR A
    RET Z
        RST.LIL $10
        INC HL
        JR .loop
    RET

; fun agon$tui_render$_tui_vdu(byte: u8 = A)
agon_tui_render__tui_vdu:
    RST.LIL $10
    RET

; fun agon$tui_render$_tui_print_dec(val: u8 = A)
agon_tui_render__tui_print_dec:
    ; A = val (0-255)
        LD B, A
        ; Hundreds digit
        LD C, 0
        .hloop: CP 100
    JR C, .hdone
    SUB 100
    INC C
    JR .hloop
        .hdone:
        LD B, A
        LD A, C
    OR A
    JR Z, .skip_h
        ADD A, 48
    RST.LIL $10
        .skip_h:
        ; Tens digit
        LD A, B
    LD C, 0
        .tloop: CP 10
    JR C, .tdone
    SUB 10
    INC C
    JR .tloop
        .tdone:
        LD B, A
        LD A, C
    ADD A, 48
    RST.LIL $10
        ; Units digit
        LD A, B
    ADD A, 48
    RST.LIL $10
    RET

; fun agon$tui_render$tui_goto(x: u8 = B, y: u8 = C)
agon_tui_render_tui_goto:
    CALL agon_tui_render__tui_esc
    LD A, 91
    CALL agon_tui_render__tui_mos_putchar
    LD D, 1
    LD A, C
    ADD A, 1
    CALL agon_tui_render__tui_print_dec
    LD A, 59
    CALL agon_tui_render__tui_mos_putchar
    LD C, 1
    LD A, B
    ADD A, 1
    CALL agon_tui_render__tui_print_dec
    LD A, 72
    CALL agon_tui_render__tui_mos_putchar
    RET

; fun agon$tui_render$tui_color(fg: u8 = D, bg: u8 = E, bright: u8 = C)
agon_tui_render_tui_color:
    LD H, 30
    LD A, H
    ADD A, D
    LD D, 40
    LD A, D
    ADD A, E
    LD B, A
    LD D, 0
    LD A, C
    CP 0
    JP NZ, .agon_tui_render_tui_color_if_then1
    LD D, A
    JP .agon_tui_render_tui_color_if_join2
.agon_tui_render_tui_color_if_then1:
    LD C, 60
    ADD A, 60
    LD C, 60
    LD A, B
    ADD A, 60
    LD B, A
    LD D, A
    JP .agon_tui_render_tui_color_if_join2
.agon_tui_render_tui_color_if_join2:
    CALL agon_tui_render__tui_esc
    LD A, 91
    CALL agon_tui_render__tui_mos_putchar
    LD A, D
    CALL agon_tui_render__tui_print_dec
    LD A, 59
    CALL agon_tui_render__tui_mos_putchar
    LD A, B
    CALL agon_tui_render__tui_print_dec
    LD A, 109
    CALL agon_tui_render__tui_mos_putchar
    RET

; fun agon$tui_render$tui_reset()
agon_tui_render_tui_reset:
    CALL agon_tui_render__tui_esc
    LD A, 91
    CALL agon_tui_render__tui_mos_putchar
    LD A, 48
    CALL agon_tui_render__tui_mos_putchar
    LD A, 109
    CALL agon_tui_render__tui_mos_putchar
    RET

; fun agon$tui_render$tui_clear()
agon_tui_render_tui_clear:
    CALL agon_tui_render__tui_esc
    LD A, 91
    CALL agon_tui_render__tui_mos_putchar
    LD A, 50
    CALL agon_tui_render__tui_mos_putchar
    LD A, 74
    CALL agon_tui_render__tui_mos_putchar
    CALL agon_tui_render__tui_esc
    LD A, 91
    CALL agon_tui_render__tui_mos_putchar
    LD A, 72
    CALL agon_tui_render__tui_mos_putchar
    RET

; fun agon$tui_render$tui_putch(ch: u8 = A)
agon_tui_render_tui_putch:
    JP .agon_tui_render_tui_putch_if_join2
.agon_tui_render_tui_putch_if_join2:
    JP .agon_tui_render_tui_putch_if_join4
.agon_tui_render_tui_putch_if_join4:
    JP .agon_tui_render_tui_putch_if_join6
.agon_tui_render_tui_putch_if_join6:
    JP .agon_tui_render_tui_putch_if_join8
.agon_tui_render_tui_putch_if_join8:
    JP .agon_tui_render_tui_putch_if_join10
.agon_tui_render_tui_putch_if_join10:
    JP .agon_tui_render_tui_putch_if_join12
.agon_tui_render_tui_putch_if_join12:
    LD C, 6
    CP 6
    JP NZ, .agon_tui_render_tui_putch_if_then13
    JP .agon_tui_render_tui_putch_if_join14
.agon_tui_render_tui_putch_if_then13:
    CALL agon_tui_render__tui_mos_putchar
    JP .agon_tui_render_tui_putch_if_join14
.agon_tui_render_tui_putch_if_join14:
    RET

; fun agon$tui_render$tui_puts(str: ptr = HL)
agon_tui_render_tui_puts:
    CALL agon_tui_render__tui_mos_puts
    RET

; fun agon$tui_render$tui_read_key() -> u8 = A
agon_tui_render_tui_read_key:
    LD A, $00     ; MOS_GETKEY
        RST.LIL $08
    RET

; fun agon$tui_render$tui_read_line(buf: ptr = HL, maxlen: u8 = C) -> u8 = A
agon_tui_render_tui_read_line:
    ; HL = buf (from param 0), A = maxlen (from param 1)
        LD B, A        ; B = maxlen
        LD C, 1        ; C = 1 (clear buffer before use)
        LD A, $09      ; MOS_EDITLINE
        RST.LIL $08
        ; On return: A = length of string entered
    RET

; fun agon$tui_render$tui_width() -> u8 = A
agon_tui_render_tui_width:
    LD A, 80
    RET

; fun agon$tui_render$tui_height() -> u8 = A
agon_tui_render_tui_height:
    LD A, 30
    RET

; fun agon$tui_render$tui_set_mode(mode: u8 = B)
agon_tui_render_tui_set_mode:
    LD A, 22
    CALL agon_tui_render__tui_vdu
    LD A, B
    CALL agon_tui_render__tui_vdu
    RET

; fun agon$tui_render$tui_hide_cursor()
agon_tui_render_tui_hide_cursor:
    CALL agon_tui_render__tui_esc
    LD A, 91
    CALL agon_tui_render__tui_mos_putchar
    LD A, 63
    CALL agon_tui_render__tui_mos_putchar
    LD A, 50
    CALL agon_tui_render__tui_mos_putchar
    LD A, 53
    CALL agon_tui_render__tui_mos_putchar
    LD A, 108
    CALL agon_tui_render__tui_mos_putchar
    RET

; fun agon$tui_render$tui_show_cursor()
agon_tui_render_tui_show_cursor:
    CALL agon_tui_render__tui_esc
    LD A, 91
    CALL agon_tui_render__tui_mos_putchar
    LD A, 63
    CALL agon_tui_render__tui_mos_putchar
    LD A, 50
    CALL agon_tui_render__tui_mos_putchar
    LD A, 53
    CALL agon_tui_render__tui_mos_putchar
    LD A, 104
    CALL agon_tui_render__tui_mos_putchar
    RET

; fun agon$tui_render$tui_scroll_region(top: u8 = A, bottom: u8 = C)
agon_tui_render_tui_scroll_region:
    CALL agon_tui_render__tui_esc
    LD B, 91
    LD A, B
    CALL agon_tui_render__tui_mos_putchar
    LD D, 1
    ADD A, 1
    CALL agon_tui_render__tui_print_dec
    LD A, 59
    CALL agon_tui_render__tui_mos_putchar
    LD D, 1
    LD A, C
    ADD A, 1
    CALL agon_tui_render__tui_print_dec
    LD A, 114
    CALL agon_tui_render__tui_mos_putchar
    RET

; fun agon$tui_render$tui_reverse()
agon_tui_render_tui_reverse:
    CALL agon_tui_render__tui_esc
    LD A, 91
    CALL agon_tui_render__tui_mos_putchar
    LD A, 55
    CALL agon_tui_render__tui_mos_putchar
    LD A, 109
    CALL agon_tui_render__tui_mos_putchar
    RET

; fun agon$tui_render$draw_box(x: u8 = A, y: u8 = C, w: u8 = D, h: u8 = E)
agon_tui_render_draw_box:
    LD B, A
    LD A, B
    LD A, C
    CALL agon_tui_render_tui_goto
    LD B, 1
    LD A, B
    CALL agon_tui_render_tui_putch
    LD H, 0
    JP .agon_tui_render_draw_box_loop_head1
.agon_tui_render_draw_box_loop_head1:
    LD L, 2
    LD A, D
    SUB 2
    LD L, A
    LD A, H
    CP L
    JP NZ, .agon_tui_render_draw_box_loop_body2
    JP .agon_tui_render_draw_box_loop_exit3
.agon_tui_render_draw_box_loop_body2:
    LD B, 5
    LD A, B
    CALL agon_tui_render_tui_putch
    LD L, 1
    LD A, H
    ADD A, 1
    LD H, A
    JP .agon_tui_render_draw_box_loop_head1
.agon_tui_render_draw_box_loop_exit3:
    LD B, 2
    LD A, B
    CALL agon_tui_render_tui_putch
    LD H, 1
    LD C, E
    LD E, A
    LD L, C
    JP .agon_tui_render_draw_box_loop_head4
.agon_tui_render_draw_box_loop_head4:
    LD A, 1
    LD A, C
    SUB 1
    LD A, H
    CP A
    JP NZ, .agon_tui_render_draw_box_loop_body5
    JP .agon_tui_render_draw_box_loop_exit6
.agon_tui_render_draw_box_loop_body5:
    LD A, E
    LD A, L
    ADD A, H
    LD B, A
    LD A, B
    CALL agon_tui_render_tui_goto
    LD A, 6
    CALL agon_tui_render_tui_putch
    LD A, E
    ADD A, D
    LD B, 1
    SUB 1
    LD A, L
    ADD A, H
    LD B, A
    LD A, B
    CALL agon_tui_render_tui_goto
    LD A, 6
    CALL agon_tui_render_tui_putch
    LD A, 1
    LD A, H
    ADD A, 1
    LD H, A
    JP .agon_tui_render_draw_box_loop_head4
.agon_tui_render_draw_box_loop_exit6:
    LD A, L
    ADD A, C
    LD B, A
    LD C, 1
    LD A, B
    SUB 1
    LD B, A
    LD A, E
    LD A, B
    CALL agon_tui_render_tui_goto
    LD A, 3
    CALL agon_tui_render_tui_putch
    LD C, 0
    JP .agon_tui_render_draw_box_loop_head7
.agon_tui_render_draw_box_loop_head7:
    LD E, 2
    LD A, D
    SUB 2
    LD A, C
    CP A
    JP NZ, .agon_tui_render_draw_box_loop_body8
    JP .agon_tui_render_draw_box_loop_exit9
.agon_tui_render_draw_box_loop_body8:
    LD A, 5
    CALL agon_tui_render_tui_putch
    LD E, 1
    LD A, C
    ADD A, 1
    LD C, A
    JP .agon_tui_render_draw_box_loop_head7
.agon_tui_render_draw_box_loop_exit9:
    LD A, 4
    CALL agon_tui_render_tui_putch
    RET

; fun agon$tui_render$clear_rect(x: u8 = C, y: u8 = D, w: u8 = E, h: u8 = H)
agon_tui_render_clear_rect:
    LD L, 0
    LD C, H
    LD D, E
    LD E, C
    LD H, D
    JP .agon_tui_render_clear_rect_loop_head1
.agon_tui_render_clear_rect_loop_head1:
    LD A, L
    CP C
    ; TODO: terminator *mir2.TermCondRet
.agon_tui_render_clear_rect_loop_body2:
    LD A, E
    LD A, H
    ADD A, L
    LD B, A
    LD A, B
    CALL agon_tui_render_tui_goto
    LD B, 0
    JP .agon_tui_render_clear_rect_loop_head4
.agon_tui_render_clear_rect_loop_head4:
    LD A, B
    CP D
    JP NZ, .agon_tui_render_clear_rect_loop_body5
    JP .agon_tui_render_clear_rect_loop_exit6
.agon_tui_render_clear_rect_loop_body5:
    LD A, 32
    CALL agon_tui_render_tui_putch
    LD A, 1
    LD A, B
    ADD A, 1
    LD B, A
    JP .agon_tui_render_clear_rect_loop_head4
.agon_tui_render_clear_rect_loop_exit6:
    LD A, 1
    LD A, L
    ADD A, 1
    LD L, A
    JP .agon_tui_render_clear_rect_loop_head1

; fun agon$tui_render$puts_padded(str: ptr = HL, width: u8 = C)
agon_tui_render_puts_padded:
    LD B, 0
    JP .agon_tui_render_puts_padded_loop_head1
.agon_tui_render_puts_padded_loop_head1:
    LD A, B
    CP C
    ; TODO: terminator *mir2.TermCondRet
.agon_tui_render_puts_padded_loop_body2:
    LD D, (HL)
    LD E, 0
    LD A, D
    CP 0
    JP NZ, .agon_tui_render_puts_padded_if_then4
    JP .agon_tui_render_puts_padded_if_else6
.agon_tui_render_puts_padded_if_then4:
    LD D, (HL)
    LD A, D
    CALL agon_tui_render_tui_putch
    LD DE, 1
    ADD HL, DE
    JP .agon_tui_render_puts_padded_if_join5
.agon_tui_render_puts_padded_if_join5:
    LD D, 1
    LD A, B
    ADD A, 1
    LD B, A
    JP .agon_tui_render_puts_padded_loop_head1
.agon_tui_render_puts_padded_if_else6:
    LD A, 32
    CALL agon_tui_render_tui_putch
    JP .agon_tui_render_puts_padded_if_join5

; fun file_name(idx: u8 = A) -> ptr = A
file_name:
    LD C, 0
    CP 0
    JP Z, .file_name_if_then1
    JP .file_name_if_join2
.file_name_if_then1:
    LD HL, _mir2.str.0
    LD A, L
    RET
.file_name_if_join2:
    LD C, 1
    CP 1
    JP Z, .file_name_if_then3
    JP .file_name_if_join4
.file_name_if_then3:
    LD HL, _mir2.str.1
    LD A, L
    RET
.file_name_if_join4:
    LD C, 2
    CP 2
    JP Z, .file_name_if_then5
    JP .file_name_if_join6
.file_name_if_then5:
    LD HL, _mir2.str.2
    LD A, L
    RET
.file_name_if_join6:
    LD C, 3
    CP 3
    JP Z, .file_name_if_then7
    JP .file_name_if_join8
.file_name_if_then7:
    LD HL, _mir2.str.3
    LD A, L
    RET
.file_name_if_join8:
    LD C, 4
    CP 4
    JP Z, .file_name_if_then9
    JP .file_name_if_join10
.file_name_if_then9:
    LD HL, _mir2.str.4
    LD A, L
    RET
.file_name_if_join10:
    LD C, 5
    CP 5
    JP Z, .file_name_if_then11
    JP .file_name_if_join12
.file_name_if_then11:
    LD HL, _mir2.str.5
    LD A, L
    RET
.file_name_if_join12:
    LD C, 6
    CP 6
    JP Z, .file_name_if_then13
    JP .file_name_if_join14
.file_name_if_then13:
    LD HL, _mir2.str.6
    LD A, L
    RET
.file_name_if_join14:
    LD C, 7
    CP 7
    LD HL, _mir2.str.8
    ; TODO: terminator *mir2.TermCondRet
.file_name_if_then15:
    LD HL, _mir2.str.7
    LD A, L
    RET

; fun file_size(idx: u8 = A) -> ptr = A
file_size:
    LD C, 0
    CP 0
    JP Z, .file_size_if_then1
    JP .file_size_if_join2
.file_size_if_then1:
    LD HL, _mir2.str.9
    LD A, L
    RET
.file_size_if_join2:
    LD C, 1
    CP 1
    JP Z, .file_size_if_then3
    JP .file_size_if_join4
.file_size_if_then3:
    LD HL, _mir2.str.10
    LD A, L
    RET
.file_size_if_join4:
    LD C, 2
    CP 2
    JP Z, .file_size_if_then5
    JP .file_size_if_join6
.file_size_if_then5:
    LD HL, _mir2.str.11
    LD A, L
    RET
.file_size_if_join6:
    LD C, 3
    CP 3
    JP Z, .file_size_if_then7
    JP .file_size_if_join8
.file_size_if_then7:
    LD HL, _mir2.str.12
    LD A, L
    RET
.file_size_if_join8:
    LD C, 4
    CP 4
    JP Z, .file_size_if_then9
    JP .file_size_if_join10
.file_size_if_then9:
    LD HL, _mir2.str.13
    LD A, L
    RET
.file_size_if_join10:
    LD C, 5
    CP 5
    JP Z, .file_size_if_then11
    JP .file_size_if_join12
.file_size_if_then11:
    LD HL, _mir2.str.13
    LD A, L
    RET
.file_size_if_join12:
    LD C, 6
    CP 6
    JP Z, .file_size_if_then13
    JP .file_size_if_join14
.file_size_if_then13:
    LD HL, _mir2.str.13
    LD A, L
    RET
.file_size_if_join14:
    LD C, 7
    CP 7
    LD HL, _mir2.str.15
    ; TODO: terminator *mir2.TermCondRet
.file_size_if_then15:
    LD HL, _mir2.str.14
    LD A, L
    RET

; fun draw_panel()
draw_panel:
    LD HL, COLOR_WHITE
    LD C, (HL)
    LD A, C
    LD HL, COLOR_BLUE
    LD C, (HL)
    LD B, 1
    CALL tui_color
    LD HL, PANEL_X
    LD C, (HL)
    LD A, C
    LD HL, PANEL_Y
    LD C, (HL)
    LD HL, PANEL_W
    LD D, (HL)
    LD B, D
    LD HL, PANEL_H
    LD D, (HL)
    CALL draw_box
    LD HL, PANEL_X
    LD D, (HL)
    LD C, 2
    LD A, D
    ADD A, 2
    LD HL, PANEL_Y
    LD C, (HL)
    CALL tui_goto
    LD HL, COLOR_BLACK
    LD C, (HL)
    LD A, C
    LD HL, COLOR_CYAN
    LD C, (HL)
    LD B, 0
    CALL tui_color
    LD HL, _mir2.str.16
    CALL tui_puts
    LD HL, PANEL_X
    LD C, (HL)
    LD D, 2
    LD A, C
    ADD A, 2
    LD HL, PANEL_Y
    LD C, (HL)
    LD D, 1
    LD A, C
    ADD A, 1
    LD B, A
    CALL tui_goto
    LD HL, COLOR_YELLOW
    LD C, (HL)
    LD A, C
    LD HL, COLOR_BLUE
    LD C, (HL)
    LD B, 1
    CALL tui_color
    LD HL, _mir2.str.17
    CALL tui_puts
    LD C, 0
    JP .draw_panel_loop_head1
.draw_panel_loop_head1:
    LD HL, FILE_COUNT
    LD D, (HL)
    LD A, C
    CP D
    ; TODO: terminator *mir2.TermCondRet
.draw_panel_loop_body2:
    LD A, C
    CALL draw_file_entry
    LD D, 1
    LD A, C
    ADD A, 1
    LD C, A
    JP .draw_panel_loop_head1

; fun draw_file_entry(idx: u8 = C)
draw_file_entry:
    LD HL, PANEL_X
    LD D, (HL)
    LD E, 1
    LD A, D
    ADD A, 1
    LD HL, PANEL_Y
    LD D, (HL)
    LD E, 2
    LD A, D
    ADD A, 2
    LD B, A
    LD A, B
    ADD A, C
    LD B, A
    CALL tui_goto
    LD HL, cursor
    LD D, (HL)
    LD A, C
    CP D
    JP Z, .draw_file_entry_if_then1
    JP .draw_file_entry_if_else3
.draw_file_entry_if_then1:
    LD HL, COLOR_BLACK
    LD D, (HL)
    LD A, D
    LD HL, COLOR_CYAN
    LD D, (HL)
    LD B, 0
    CALL tui_color
    JP .draw_file_entry_if_join2
.draw_file_entry_if_join2:
    LD A, 32
    CALL tui_putch
    LD A, C
    CALL file_name
    LD L, 0
    LD H, A
    CALL tui_puts
    LD A, 32
    CALL tui_putch
    LD A, C
    CALL file_size
    LD L, 0
    LD H, A
    CALL tui_puts
    LD C, 0
    JP .draw_file_entry_loop_head4
.draw_file_entry_loop_head4:
    LD D, 12
    LD A, C
    CP 12
    ; TODO: terminator *mir2.TermCondRet
.draw_file_entry_loop_body5:
    LD A, 32
    CALL tui_putch
    LD D, 1
    LD A, C
    ADD A, 1
    LD C, A
    JP .draw_file_entry_loop_head4
.draw_file_entry_if_else3:
    LD HL, COLOR_WHITE
    LD D, (HL)
    LD A, D
    LD HL, COLOR_BLUE
    LD D, (HL)
    LD B, 1
    CALL tui_color
    JP .draw_file_entry_if_join2

; fun draw_status_bar()
draw_status_bar:
    LD A, 0
    LD C, 23
    CALL tui_goto
    LD HL, COLOR_BLACK
    LD C, (HL)
    LD A, C
    LD HL, COLOR_CYAN
    LD C, (HL)
    LD B, 0
    CALL tui_color
    LD HL, _mir2.str.18
    CALL tui_puts
    LD HL, COLOR_WHITE
    LD C, (HL)
    LD A, C
    LD HL, COLOR_BLACK
    LD C, (HL)
    LD B, 0
    CALL tui_color
    LD HL, _mir2.str.19
    CALL tui_puts
    LD HL, COLOR_BLACK
    LD C, (HL)
    LD A, C
    LD HL, COLOR_CYAN
    LD C, (HL)
    LD B, 0
    CALL tui_color
    LD HL, _mir2.str.20
    CALL tui_puts
    LD HL, COLOR_WHITE
    LD C, (HL)
    LD A, C
    LD HL, COLOR_BLACK
    LD C, (HL)
    LD B, 0
    CALL tui_color
    LD HL, _mir2.str.21
    CALL tui_puts
    LD HL, COLOR_BLACK
    LD C, (HL)
    LD A, C
    LD HL, COLOR_CYAN
    LD C, (HL)
    LD B, 0
    CALL tui_color
    LD HL, _mir2.str.22
    CALL tui_puts
    LD HL, COLOR_WHITE
    LD C, (HL)
    LD A, C
    LD HL, COLOR_BLACK
    LD C, (HL)
    LD B, 0
    CALL tui_color
    LD HL, _mir2.str.23
    CALL tui_puts
    LD HL, COLOR_BLACK
    LD C, (HL)
    LD A, C
    LD HL, COLOR_CYAN
    LD C, (HL)
    LD B, 0
    CALL tui_color
    LD HL, _mir2.str.24
    CALL tui_puts
    LD HL, COLOR_WHITE
    LD C, (HL)
    LD A, C
    LD HL, COLOR_BLACK
    LD C, (HL)
    LD B, 0
    CALL tui_color
    LD HL, _mir2.str.25
    CALL tui_puts
    LD HL, COLOR_BLACK
    LD C, (HL)
    LD A, C
    LD HL, COLOR_CYAN
    LD C, (HL)
    LD B, 0
    CALL tui_color
    LD HL, _mir2.str.26
    CALL tui_puts
    LD HL, COLOR_WHITE
    LD C, (HL)
    LD A, C
    LD HL, COLOR_BLACK
    LD C, (HL)
    LD B, 0
    CALL tui_color
    LD HL, _mir2.str.27
    CALL tui_puts
    RET

; fun draw_title()
draw_title:
    LD A, 0
    LD C, 0
    CALL tui_goto
    LD HL, COLOR_BLACK
    LD C, (HL)
    LD A, C
    LD HL, COLOR_CYAN
    LD C, (HL)
    LD B, 0
    CALL tui_color
    LD HL, _mir2.str.28
    CALL tui_puts
    LD HL, _mir2.str.29
    CALL tui_puts
    RET

; globals
KEY_ENTER:
    DB 13
KEY_ESC:
    DB 27
KEY_UP:
    DB 11
KEY_DOWN:
    DB 10
COLOR_WHITE:
    DB 7
COLOR_BLUE:
    DB 4
COLOR_CYAN:
    DB 6
COLOR_YELLOW:
    DB 3
COLOR_BLACK:
    DB 0
COLOR_GREEN:
    DB 2
PANEL_X:
    DB 1
PANEL_Y:
    DB 1
PANEL_W:
    DB 40
PANEL_H:
    DB 20
FILE_COUNT:
    DB 8
cursor:
    DB 0
; strings
_mir2.str.0:
    DB 72, 69, 76, 76, 79, 32, 32, 32, 32, 46, 66, 73, 78, 0
_mir2.str.1:
    DB 78, 67, 95, 65, 71, 79, 78, 32, 32, 46, 66, 73, 78, 0
_mir2.str.2:
    DB 84, 69, 84, 82, 73, 83, 32, 32, 32, 46, 66, 73, 78, 0
_mir2.str.3:
    DB 82, 69, 65, 68, 77, 69, 32, 32, 32, 46, 84, 88, 84, 0
_mir2.str.4:
    DB 83, 84, 68, 76, 73, 66, 32, 32, 32, 46, 32, 32, 32, 0
_mir2.str.5:
    DB 68, 79, 67, 83, 32, 32, 32, 32, 32, 46, 32, 32, 32, 0
_mir2.str.6:
    DB 69, 88, 65, 77, 80, 76, 69, 83, 32, 46, 32, 32, 32, 0
_mir2.str.7:
    DB 80, 76, 65, 83, 77, 65, 32, 32, 32, 46, 66, 73, 78, 0
_mir2.str.8:
    DB 63, 63, 63, 0
_mir2.str.9:
    DB 32, 32, 32, 49, 54, 54, 0
_mir2.str.10:
    DB 32, 32, 49, 48, 50, 52, 0
_mir2.str.11:
    DB 32, 32, 50, 48, 52, 56, 0
_mir2.str.12:
    DB 32, 32, 32, 53, 49, 50, 0
_mir2.str.13:
    DB 32, 32, 60, 68, 73, 82, 62, 0
_mir2.str.14:
    DB 32, 32, 32, 55, 56, 57, 0
_mir2.str.15:
    DB 32, 32, 32, 32, 32, 48, 0
_mir2.str.16:
    DB 32, 47, 115, 100, 99, 97, 114, 100, 32, 0
_mir2.str.17:
    DB 78, 97, 109, 101, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 83, 105, 122, 101, 0
_mir2.str.18:
    DB 32, 70, 49, 0
_mir2.str.19:
    DB 72, 101, 108, 112, 32, 0
_mir2.str.20:
    DB 32, 70, 51, 0
_mir2.str.21:
    DB 86, 105, 101, 119, 32, 0
_mir2.str.22:
    DB 32, 70, 53, 0
_mir2.str.23:
    DB 67, 111, 112, 121, 32, 0
_mir2.str.24:
    DB 32, 70, 56, 0
_mir2.str.25:
    DB 68, 101, 108, 32, 32, 0
_mir2.str.26:
    DB 32, 70, 49, 48, 0
_mir2.str.27:
    DB 81, 117, 105, 116, 0
_mir2.str.28:
    DB 32, 77, 105, 110, 90, 32, 78, 67, 32, 102, 111, 114, 32, 65, 103, 111, 110, 32, 76, 105, 103, 104, 116, 32, 50, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 0
_mir2.str.29:
    DB 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 0
_mir2.str.30:
    DB 83, 101, 108, 101, 99, 116, 101, 100, 58, 32, 0
_mir2.str.31:
    DB 32, 32, 0
