; eZ80 ADL mode assembly — generated by MinZ compiler
; Target: Agon Light 2 (eZ80 @ 18.432 MHz)

    .ASSUME ADL=1
    ORG $040045

; fun main()
main:
    CALL tui_clear
    CALL tui_hide_cursor
    LD A, 0
    LD C, 0
    CALL tui_goto
    LD A, 0
    LD C, 6
    LD B, 0
    CALL tui_color
    LD HL, _mir2.str.0
    CALL tui_puts
    LD A, 7
    LD C, 4
    LD B, 1
    CALL tui_color
    LD A, 2
    LD C, 2
    LD B, 36
    LD D, 12
    CALL draw_box
    LD A, 4
    LD C, 2
    CALL tui_goto
    LD A, 0
    LD C, 6
    LD B, 0
    CALL tui_color
    LD HL, _mir2.str.1
    CALL tui_puts
    LD A, 4
    LD C, 4
    CALL tui_goto
    LD A, 7
    LD C, 4
    LD B, 1
    CALL tui_color
    LD HL, _mir2.str.2
    CALL tui_puts
    LD A, 4
    LD C, 5
    CALL tui_goto
    LD A, 3
    LD C, 4
    LD B, 1
    CALL tui_color
    LD HL, _mir2.str.3
    CALL tui_puts
    LD A, 4
    LD C, 6
    CALL tui_goto
    LD A, 2
    LD C, 4
    LD B, 1
    CALL tui_color
    LD HL, _mir2.str.4
    CALL tui_puts
    LD A, 4
    LD C, 7
    CALL tui_goto
    LD A, 1
    LD C, 4
    LD B, 0
    CALL tui_color
    LD HL, _mir2.str.5
    CALL tui_puts
    LD A, 4
    LD C, 9
    CALL tui_goto
    LD A, 6
    LD C, 4
    LD B, 1
    CALL tui_color
    LD HL, _mir2.str.6
    CALL tui_puts
    LD A, 4
    LD C, 10
    CALL tui_goto
    LD A, 7
    LD C, 4
    LD B, 0
    CALL tui_color
    LD HL, _mir2.str.7
    CALL tui_puts
    LD A, 0
    LD C, 24
    CALL tui_goto
    LD A, 0
    LD C, 6
    LD B, 0
    CALL tui_color
    LD HL, _mir2.str.8
    CALL tui_puts
    CALL tui_read_key
    CALL tui_show_cursor
    CALL tui_reset
    CALL tui_clear
    RET

; fun agon$tui_render$_tui_mos_putchar(ch: u8 = A)
agon_tui_render__tui_mos_putchar:
    RST.LIL $10
    RET

; fun agon$tui_render$_tui_esc()
agon_tui_render__tui_esc:
    LD A, $1B
        RST.LIL $10
    RET

; fun agon$tui_render$_tui_mos_puts(str: ptr = HL)
agon_tui_render__tui_mos_puts:
    .loop: LD A, (HL)
    OR A
    RET Z
        RST.LIL $10
        INC HL
        JR .loop
    RET

; fun agon$tui_render$_tui_vdu(byte: u8 = A)
agon_tui_render__tui_vdu:
    RST.LIL $10
    RET

; fun agon$tui_render$_tui_print_dec(val: u8 = A)
agon_tui_render__tui_print_dec:
    ; A = val (0-255)
        LD B, A
        ; Hundreds digit
        LD C, 0
        .hloop: CP 100
    JR C, .hdone
    SUB 100
    INC C
    JR .hloop
        .hdone:
        LD B, A
        LD A, C
    OR A
    JR Z, .skip_h
        ADD A, 48
    RST.LIL $10
        .skip_h:
        ; Tens digit
        LD A, B
    LD C, 0
        .tloop: CP 10
    JR C, .tdone
    SUB 10
    INC C
    JR .tloop
        .tdone:
        LD B, A
        LD A, C
    ADD A, 48
    RST.LIL $10
        ; Units digit
        LD A, B
    ADD A, 48
    RST.LIL $10
    RET

; fun agon$tui_render$tui_goto(x: u8 = B, y: u8 = C)
agon_tui_render_tui_goto:
    CALL agon_tui_render__tui_esc
    LD A, 91
    CALL agon_tui_render__tui_mos_putchar
    LD D, 1
    LD A, C
    ADD A, 1
    CALL agon_tui_render__tui_print_dec
    LD A, 59
    CALL agon_tui_render__tui_mos_putchar
    LD C, 1
    LD A, B
    ADD A, 1
    CALL agon_tui_render__tui_print_dec
    LD A, 72
    CALL agon_tui_render__tui_mos_putchar
    RET

; fun agon$tui_render$tui_color(fg: u8 = D, bg: u8 = E, bright: u8 = C)
agon_tui_render_tui_color:
    LD H, 30
    LD A, H
    ADD A, D
    LD D, 40
    LD A, D
    ADD A, E
    LD B, A
    LD D, 0
    LD A, C
    CP 0
    JP NZ, .agon_tui_render_tui_color_if_then1
    LD D, A
    JP .agon_tui_render_tui_color_if_join2
.agon_tui_render_tui_color_if_then1:
    LD C, 60
    ADD A, 60
    LD C, 60
    LD A, B
    ADD A, 60
    LD B, A
    LD D, A
    JP .agon_tui_render_tui_color_if_join2
.agon_tui_render_tui_color_if_join2:
    CALL agon_tui_render__tui_esc
    LD A, 91
    CALL agon_tui_render__tui_mos_putchar
    LD A, D
    CALL agon_tui_render__tui_print_dec
    LD A, 59
    CALL agon_tui_render__tui_mos_putchar
    LD A, B
    CALL agon_tui_render__tui_print_dec
    LD A, 109
    CALL agon_tui_render__tui_mos_putchar
    RET

; fun agon$tui_render$tui_reset()
agon_tui_render_tui_reset:
    CALL agon_tui_render__tui_esc
    LD A, 91
    CALL agon_tui_render__tui_mos_putchar
    LD A, 48
    CALL agon_tui_render__tui_mos_putchar
    LD A, 109
    CALL agon_tui_render__tui_mos_putchar
    RET

; fun agon$tui_render$tui_clear()
agon_tui_render_tui_clear:
    CALL agon_tui_render__tui_esc
    LD A, 91
    CALL agon_tui_render__tui_mos_putchar
    LD A, 50
    CALL agon_tui_render__tui_mos_putchar
    LD A, 74
    CALL agon_tui_render__tui_mos_putchar
    CALL agon_tui_render__tui_esc
    LD A, 91
    CALL agon_tui_render__tui_mos_putchar
    LD A, 72
    CALL agon_tui_render__tui_mos_putchar
    RET

; fun agon$tui_render$tui_putch(ch: u8 = A)
agon_tui_render_tui_putch:
    JP .agon_tui_render_tui_putch_if_join2
.agon_tui_render_tui_putch_if_join2:
    JP .agon_tui_render_tui_putch_if_join4
.agon_tui_render_tui_putch_if_join4:
    JP .agon_tui_render_tui_putch_if_join6
.agon_tui_render_tui_putch_if_join6:
    JP .agon_tui_render_tui_putch_if_join8
.agon_tui_render_tui_putch_if_join8:
    JP .agon_tui_render_tui_putch_if_join10
.agon_tui_render_tui_putch_if_join10:
    JP .agon_tui_render_tui_putch_if_join12
.agon_tui_render_tui_putch_if_join12:
    LD C, 6
    CP 6
    JP NZ, .agon_tui_render_tui_putch_if_then13
    JP .agon_tui_render_tui_putch_if_join14
.agon_tui_render_tui_putch_if_then13:
    CALL agon_tui_render__tui_mos_putchar
    JP .agon_tui_render_tui_putch_if_join14
.agon_tui_render_tui_putch_if_join14:
    RET

; fun agon$tui_render$tui_puts(str: ptr = HL)
agon_tui_render_tui_puts:
    CALL agon_tui_render__tui_mos_puts
    RET

; fun agon$tui_render$tui_read_key() -> u8 = A
agon_tui_render_tui_read_key:
    LD A, $00     ; MOS_GETKEY
        RST.LIL $08
    RET

; fun agon$tui_render$tui_read_line(buf: ptr = HL, maxlen: u8 = C) -> u8 = A
agon_tui_render_tui_read_line:
    ; HL = buf (from param 0), A = maxlen (from param 1)
        LD B, A        ; B = maxlen
        LD C, 1        ; C = 1 (clear buffer before use)
        LD A, $09      ; MOS_EDITLINE
        RST.LIL $08
        ; On return: A = length of string entered
    RET

; fun agon$tui_render$tui_width() -> u8 = A
agon_tui_render_tui_width:
    LD A, 80
    RET

; fun agon$tui_render$tui_height() -> u8 = A
agon_tui_render_tui_height:
    LD A, 30
    RET

; fun agon$tui_render$tui_set_mode(mode: u8 = B)
agon_tui_render_tui_set_mode:
    LD A, 22
    CALL agon_tui_render__tui_vdu
    LD A, B
    CALL agon_tui_render__tui_vdu
    RET

; fun agon$tui_render$tui_hide_cursor()
agon_tui_render_tui_hide_cursor:
    CALL agon_tui_render__tui_esc
    LD A, 91
    CALL agon_tui_render__tui_mos_putchar
    LD A, 63
    CALL agon_tui_render__tui_mos_putchar
    LD A, 50
    CALL agon_tui_render__tui_mos_putchar
    LD A, 53
    CALL agon_tui_render__tui_mos_putchar
    LD A, 108
    CALL agon_tui_render__tui_mos_putchar
    RET

; fun agon$tui_render$tui_show_cursor()
agon_tui_render_tui_show_cursor:
    CALL agon_tui_render__tui_esc
    LD A, 91
    CALL agon_tui_render__tui_mos_putchar
    LD A, 63
    CALL agon_tui_render__tui_mos_putchar
    LD A, 50
    CALL agon_tui_render__tui_mos_putchar
    LD A, 53
    CALL agon_tui_render__tui_mos_putchar
    LD A, 104
    CALL agon_tui_render__tui_mos_putchar
    RET

; fun agon$tui_render$tui_scroll_region(top: u8 = A, bottom: u8 = C)
agon_tui_render_tui_scroll_region:
    CALL agon_tui_render__tui_esc
    LD B, 91
    LD A, B
    CALL agon_tui_render__tui_mos_putchar
    LD D, 1
    ADD A, 1
    CALL agon_tui_render__tui_print_dec
    LD A, 59
    CALL agon_tui_render__tui_mos_putchar
    LD D, 1
    LD A, C
    ADD A, 1
    CALL agon_tui_render__tui_print_dec
    LD A, 114
    CALL agon_tui_render__tui_mos_putchar
    RET

; fun agon$tui_render$tui_reverse()
agon_tui_render_tui_reverse:
    CALL agon_tui_render__tui_esc
    LD A, 91
    CALL agon_tui_render__tui_mos_putchar
    LD A, 55
    CALL agon_tui_render__tui_mos_putchar
    LD A, 109
    CALL agon_tui_render__tui_mos_putchar
    RET

; fun agon$tui_render$draw_box(x: u8 = A, y: u8 = C, w: u8 = D, h: u8 = E)
agon_tui_render_draw_box:
    LD B, A
    LD A, B
    LD A, C
    CALL agon_tui_render_tui_goto
    LD B, 1
    LD A, B
    CALL agon_tui_render_tui_putch
    LD H, 0
    JP .agon_tui_render_draw_box_loop_head1
.agon_tui_render_draw_box_loop_head1:
    LD L, 2
    LD A, D
    SUB 2
    LD L, A
    LD A, H
    CP L
    JP NZ, .agon_tui_render_draw_box_loop_body2
    JP .agon_tui_render_draw_box_loop_exit3
.agon_tui_render_draw_box_loop_body2:
    LD B, 5
    LD A, B
    CALL agon_tui_render_tui_putch
    LD L, 1
    LD A, H
    ADD A, 1
    LD H, A
    JP .agon_tui_render_draw_box_loop_head1
.agon_tui_render_draw_box_loop_exit3:
    LD B, 2
    LD A, B
    CALL agon_tui_render_tui_putch
    LD H, 1
    LD C, E
    LD E, A
    LD L, C
    JP .agon_tui_render_draw_box_loop_head4
.agon_tui_render_draw_box_loop_head4:
    LD A, 1
    LD A, C
    SUB 1
    LD A, H
    CP A
    JP NZ, .agon_tui_render_draw_box_loop_body5
    JP .agon_tui_render_draw_box_loop_exit6
.agon_tui_render_draw_box_loop_body5:
    LD A, E
    LD A, L
    ADD A, H
    LD B, A
    LD A, B
    CALL agon_tui_render_tui_goto
    LD A, 6
    CALL agon_tui_render_tui_putch
    LD A, E
    ADD A, D
    LD B, 1
    SUB 1
    LD A, L
    ADD A, H
    LD B, A
    LD A, B
    CALL agon_tui_render_tui_goto
    LD A, 6
    CALL agon_tui_render_tui_putch
    LD A, 1
    LD A, H
    ADD A, 1
    LD H, A
    JP .agon_tui_render_draw_box_loop_head4
.agon_tui_render_draw_box_loop_exit6:
    LD A, L
    ADD A, C
    LD B, A
    LD C, 1
    LD A, B
    SUB 1
    LD B, A
    LD A, E
    LD A, B
    CALL agon_tui_render_tui_goto
    LD A, 3
    CALL agon_tui_render_tui_putch
    LD C, 0
    JP .agon_tui_render_draw_box_loop_head7
.agon_tui_render_draw_box_loop_head7:
    LD E, 2
    LD A, D
    SUB 2
    LD A, C
    CP A
    JP NZ, .agon_tui_render_draw_box_loop_body8
    JP .agon_tui_render_draw_box_loop_exit9
.agon_tui_render_draw_box_loop_body8:
    LD A, 5
    CALL agon_tui_render_tui_putch
    LD E, 1
    LD A, C
    ADD A, 1
    LD C, A
    JP .agon_tui_render_draw_box_loop_head7
.agon_tui_render_draw_box_loop_exit9:
    LD A, 4
    CALL agon_tui_render_tui_putch
    RET

; fun agon$tui_render$clear_rect(x: u8 = C, y: u8 = D, w: u8 = E, h: u8 = H)
agon_tui_render_clear_rect:
    LD L, 0
    LD C, H
    LD D, E
    LD E, C
    LD H, D
    JP .agon_tui_render_clear_rect_loop_head1
.agon_tui_render_clear_rect_loop_head1:
    LD A, L
    CP C
    ; TODO: terminator *mir2.TermCondRet
.agon_tui_render_clear_rect_loop_body2:
    LD A, E
    LD A, H
    ADD A, L
    LD B, A
    LD A, B
    CALL agon_tui_render_tui_goto
    LD B, 0
    JP .agon_tui_render_clear_rect_loop_head4
.agon_tui_render_clear_rect_loop_head4:
    LD A, B
    CP D
    JP NZ, .agon_tui_render_clear_rect_loop_body5
    JP .agon_tui_render_clear_rect_loop_exit6
.agon_tui_render_clear_rect_loop_body5:
    LD A, 32
    CALL agon_tui_render_tui_putch
    LD A, 1
    LD A, B
    ADD A, 1
    LD B, A
    JP .agon_tui_render_clear_rect_loop_head4
.agon_tui_render_clear_rect_loop_exit6:
    LD A, 1
    LD A, L
    ADD A, 1
    LD L, A
    JP .agon_tui_render_clear_rect_loop_head1

; fun agon$tui_render$puts_padded(str: ptr = HL, width: u8 = C)
agon_tui_render_puts_padded:
    LD B, 0
    JP .agon_tui_render_puts_padded_loop_head1
.agon_tui_render_puts_padded_loop_head1:
    LD A, B
    CP C
    ; TODO: terminator *mir2.TermCondRet
.agon_tui_render_puts_padded_loop_body2:
    LD D, (HL)
    LD E, 0
    LD A, D
    CP 0
    JP NZ, .agon_tui_render_puts_padded_if_then4
    JP .agon_tui_render_puts_padded_if_else6
.agon_tui_render_puts_padded_if_then4:
    LD D, (HL)
    LD A, D
    CALL agon_tui_render_tui_putch
    LD DE, 1
    ADD HL, DE
    JP .agon_tui_render_puts_padded_if_join5
.agon_tui_render_puts_padded_if_join5:
    LD D, 1
    LD A, B
    ADD A, 1
    LD B, A
    JP .agon_tui_render_puts_padded_loop_head1
.agon_tui_render_puts_padded_if_else6:
    LD A, 32
    CALL agon_tui_render_tui_putch
    JP .agon_tui_render_puts_padded_if_join5

; strings
_mir2.str.0:
    DB 32, 77, 105, 110, 90, 32, 84, 85, 73, 32, 68, 101, 109, 111, 32, 102, 111, 114, 32, 65, 103, 111, 110, 32, 76, 105, 103, 104, 116, 32, 50, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 0
_mir2.str.1:
    DB 32, 80, 97, 110, 101, 108, 32, 0
_mir2.str.2:
    DB 87, 104, 105, 116, 101, 32, 111, 110, 32, 98, 108, 117, 101, 0
_mir2.str.3:
    DB 89, 101, 108, 108, 111, 119, 32, 111, 110, 32, 98, 108, 117, 101, 0
_mir2.str.4:
    DB 71, 114, 101, 101, 110, 32, 111, 110, 32, 98, 108, 117, 101, 0
_mir2.str.5:
    DB 82, 101, 100, 32, 111, 110, 32, 98, 108, 117, 101, 0
_mir2.str.6:
    DB 101, 90, 56, 48, 32, 64, 32, 49, 56, 46, 52, 51, 50, 32, 77, 72, 122, 0
_mir2.str.7:
    DB 67, 111, 109, 112, 105, 108, 101, 100, 32, 119, 105, 116, 104, 32, 77, 105, 110, 90, 0
_mir2.str.8:
    DB 32, 80, 114, 101, 115, 115, 32, 97, 110, 121, 32, 107, 101, 121, 32, 116, 111, 32, 101, 120, 105, 116, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 0
