; eZ80 ADL mode assembly — generated by MinZ compiler
; Target: Agon Light 2 (eZ80 @ 18.432 MHz)

    .ASSUME ADL=1
    ORG $040000

; fun main()
main:
    CALL tui_clear
    LD A, 2
    LD C, 0
    LD B, 1
    CALL tui_color
    LD A, 5
    LD C, 3
    LD B, 40
    LD D, 7
    CALL draw_box
    LD A, 8
    LD C, 5
    CALL tui_goto
    LD A, 7
    LD C, 0
    LD B, 1
    CALL tui_color
    LD HL, _mir2.str.0
    CALL tui_puts
    LD A, 8
    LD C, 7
    CALL tui_goto
    LD A, 3
    LD C, 0
    LD B, 0
    CALL tui_color
    LD HL, _mir2.str.1
    CALL tui_puts
    LD A, 0
    LD C, 12
    CALL tui_goto
    CALL tui_reset
    LD HL, _mir2.str.2
    CALL tui_puts
    CALL tui_read_key
    RET

; fun agon$tui_render$_tui_mos_putchar(ch: u8 = A)
agon_tui_render__tui_mos_putchar:
    ; TODO: asm
    RET

; fun agon$tui_render$_tui_esc()
agon_tui_render__tui_esc:
    ; TODO: asm
    RET

; fun agon$tui_render$_tui_mos_puts(str: ptr = HL)
agon_tui_render__tui_mos_puts:
    ; TODO: asm
    RET

; fun agon$tui_render$_tui_print_dec(val: u8 = A)
agon_tui_render__tui_print_dec:
    ; TODO: asm
    RET

; fun agon$tui_render$tui_goto(x: u8 = B, y: u8 = C)
agon_tui_render_tui_goto:
    CALL agon_tui_render__tui_esc
    LD A, 91
    CALL agon_tui_render__tui_mos_putchar
    LD D, 1
    LD A, C
    ADD A, 1
    CALL agon_tui_render__tui_print_dec
    LD A, 59
    CALL agon_tui_render__tui_mos_putchar
    LD C, 1
    LD A, B
    ADD A, 1
    CALL agon_tui_render__tui_print_dec
    LD A, 72
    CALL agon_tui_render__tui_mos_putchar
    RET

; fun agon$tui_render$tui_color(fg: u8 = D, bg: u8 = E, bright: u8 = C)
agon_tui_render_tui_color:
    LD H, 30
    LD A, H
    ADD A, D
    LD D, 40
    LD A, D
    ADD A, E
    LD B, A
    LD D, 0
    LD A, C
    CP 0
    JP NZ, .agon_tui_render_tui_color_if_then1
    LD D, A
    JP .agon_tui_render_tui_color_if_join2
.agon_tui_render_tui_color_if_then1:
    LD C, 60
    ADD A, 60
    LD C, 60
    LD A, B
    ADD A, 60
    LD B, A
    LD D, A
    JP .agon_tui_render_tui_color_if_join2
.agon_tui_render_tui_color_if_join2:
    CALL agon_tui_render__tui_esc
    LD A, 91
    CALL agon_tui_render__tui_mos_putchar
    LD A, D
    CALL agon_tui_render__tui_print_dec
    LD A, 59
    CALL agon_tui_render__tui_mos_putchar
    LD A, B
    CALL agon_tui_render__tui_print_dec
    LD A, 109
    CALL agon_tui_render__tui_mos_putchar
    RET

; fun agon$tui_render$tui_reset()
agon_tui_render_tui_reset:
    CALL agon_tui_render__tui_esc
    LD A, 91
    CALL agon_tui_render__tui_mos_putchar
    LD A, 48
    CALL agon_tui_render__tui_mos_putchar
    LD A, 109
    CALL agon_tui_render__tui_mos_putchar
    RET

; fun agon$tui_render$tui_clear()
agon_tui_render_tui_clear:
    CALL agon_tui_render__tui_esc
    LD A, 91
    CALL agon_tui_render__tui_mos_putchar
    LD A, 50
    CALL agon_tui_render__tui_mos_putchar
    LD A, 74
    CALL agon_tui_render__tui_mos_putchar
    CALL agon_tui_render__tui_esc
    LD A, 91
    CALL agon_tui_render__tui_mos_putchar
    LD A, 72
    CALL agon_tui_render__tui_mos_putchar
    RET

; fun agon$tui_render$tui_putch(ch: u8 = A)
agon_tui_render_tui_putch:
    JP .agon_tui_render_tui_putch_if_join2
.agon_tui_render_tui_putch_if_join2:
    JP .agon_tui_render_tui_putch_if_join4
.agon_tui_render_tui_putch_if_join4:
    JP .agon_tui_render_tui_putch_if_join6
.agon_tui_render_tui_putch_if_join6:
    JP .agon_tui_render_tui_putch_if_join8
.agon_tui_render_tui_putch_if_join8:
    JP .agon_tui_render_tui_putch_if_join10
.agon_tui_render_tui_putch_if_join10:
    JP .agon_tui_render_tui_putch_if_join12
.agon_tui_render_tui_putch_if_join12:
    LD C, 6
    CP 6
    JP NZ, .agon_tui_render_tui_putch_if_then13
    JP .agon_tui_render_tui_putch_if_join14
.agon_tui_render_tui_putch_if_then13:
    CALL agon_tui_render__tui_mos_putchar
    JP .agon_tui_render_tui_putch_if_join14
.agon_tui_render_tui_putch_if_join14:
    RET

; fun agon$tui_render$tui_puts(str: ptr = HL)
agon_tui_render_tui_puts:
    CALL agon_tui_render__tui_mos_puts
    RET

; fun agon$tui_render$tui_read_key() -> u8 = A
agon_tui_render_tui_read_key:
    ; TODO: asm
    RET

; fun agon$tui_render$tui_read_line(buf: ptr = HL, maxlen: u8 = C) -> u8 = A
agon_tui_render_tui_read_line:
    ; TODO: asm
    RET

; fun agon$tui_render$tui_width() -> u8 = A
agon_tui_render_tui_width:
    ; TODO: asm
    RET

; fun agon$tui_render$tui_height() -> u8 = A
agon_tui_render_tui_height:
    ; TODO: asm
    RET

; fun agon$tui_render$draw_box(x: u8 = A, y: u8 = C, w: u8 = D, h: u8 = E)
agon_tui_render_draw_box:
    LD B, A
    LD A, B
    LD A, C
    CALL agon_tui_render_tui_goto
    LD B, 1
    LD A, B
    CALL agon_tui_render_tui_putch
    LD H, 0
    JP .agon_tui_render_draw_box_loop_head1
.agon_tui_render_draw_box_loop_head1:
    LD L, 2
    LD A, D
    SUB 2
    LD L, A
    LD A, H
    CP L
    JP NZ, .agon_tui_render_draw_box_loop_body2
    JP .agon_tui_render_draw_box_loop_exit3
.agon_tui_render_draw_box_loop_body2:
    LD B, 5
    LD A, B
    CALL agon_tui_render_tui_putch
    LD L, 1
    LD A, H
    ADD A, 1
    LD H, A
    JP .agon_tui_render_draw_box_loop_head1
.agon_tui_render_draw_box_loop_exit3:
    LD B, 2
    LD A, B
    CALL agon_tui_render_tui_putch
    LD H, 1
    LD C, E
    LD E, A
    LD L, C
    JP .agon_tui_render_draw_box_loop_head4
.agon_tui_render_draw_box_loop_head4:
    LD A, 1
    LD A, C
    SUB 1
    LD A, H
    CP A
    JP NZ, .agon_tui_render_draw_box_loop_body5
    JP .agon_tui_render_draw_box_loop_exit6
.agon_tui_render_draw_box_loop_body5:
    LD A, E
    LD A, L
    ADD A, H
    LD B, A
    LD A, B
    CALL agon_tui_render_tui_goto
    LD A, 6
    CALL agon_tui_render_tui_putch
    LD A, E
    ADD A, D
    LD B, 1
    SUB 1
    LD A, L
    ADD A, H
    LD B, A
    LD A, B
    CALL agon_tui_render_tui_goto
    LD A, 6
    CALL agon_tui_render_tui_putch
    LD A, 1
    LD A, H
    ADD A, 1
    LD H, A
    JP .agon_tui_render_draw_box_loop_head4
.agon_tui_render_draw_box_loop_exit6:
    LD A, L
    ADD A, C
    LD B, A
    LD C, 1
    LD A, B
    SUB 1
    LD B, A
    LD A, E
    LD A, B
    CALL agon_tui_render_tui_goto
    LD A, 3
    CALL agon_tui_render_tui_putch
    LD C, 0
    JP .agon_tui_render_draw_box_loop_head7
.agon_tui_render_draw_box_loop_head7:
    LD E, 2
    LD A, D
    SUB 2
    LD A, C
    CP A
    JP NZ, .agon_tui_render_draw_box_loop_body8
    JP .agon_tui_render_draw_box_loop_exit9
.agon_tui_render_draw_box_loop_body8:
    LD A, 5
    CALL agon_tui_render_tui_putch
    LD E, 1
    LD A, C
    ADD A, 1
    LD C, A
    JP .agon_tui_render_draw_box_loop_head7
.agon_tui_render_draw_box_loop_exit9:
    LD A, 4
    CALL agon_tui_render_tui_putch
    RET

; fun agon$tui_render$clear_rect(x: u8 = C, y: u8 = D, w: u8 = E, h: u8 = H)
agon_tui_render_clear_rect:
    LD L, 0
    LD C, H
    LD D, E
    LD E, C
    LD H, D
    JP .agon_tui_render_clear_rect_loop_head1
.agon_tui_render_clear_rect_loop_head1:
    LD A, L
    CP C
    ; TODO: terminator *mir2.TermCondRet
.agon_tui_render_clear_rect_loop_body2:
    LD A, E
    LD A, H
    ADD A, L
    LD B, A
    LD A, B
    CALL agon_tui_render_tui_goto
    LD B, 0
    JP .agon_tui_render_clear_rect_loop_head4
.agon_tui_render_clear_rect_loop_head4:
    LD A, B
    CP D
    JP NZ, .agon_tui_render_clear_rect_loop_body5
    JP .agon_tui_render_clear_rect_loop_exit6
.agon_tui_render_clear_rect_loop_body5:
    LD A, 32
    CALL agon_tui_render_tui_putch
    LD A, 1
    LD A, B
    ADD A, 1
    LD B, A
    JP .agon_tui_render_clear_rect_loop_head4
.agon_tui_render_clear_rect_loop_exit6:
    LD A, 1
    LD A, L
    ADD A, 1
    LD L, A
    JP .agon_tui_render_clear_rect_loop_head1

; fun agon$tui_render$puts_padded(str: ptr = HL, width: u8 = C)
agon_tui_render_puts_padded:
    LD B, 0
    JP .agon_tui_render_puts_padded_loop_head1
.agon_tui_render_puts_padded_loop_head1:
    LD A, B
    CP C
    ; TODO: terminator *mir2.TermCondRet
.agon_tui_render_puts_padded_loop_body2:
    LD D, (HL)
    LD E, 0
    LD A, D
    CP 0
    JP NZ, .agon_tui_render_puts_padded_if_then4
    JP .agon_tui_render_puts_padded_if_else6
.agon_tui_render_puts_padded_if_then4:
    LD D, (HL)
    LD A, D
    CALL agon_tui_render_tui_putch
    LD DE, 1
    ADD HL, DE
    JP .agon_tui_render_puts_padded_if_join5
.agon_tui_render_puts_padded_if_join5:
    LD D, 1
    LD A, B
    ADD A, 1
    LD B, A
    JP .agon_tui_render_puts_padded_loop_head1
.agon_tui_render_puts_padded_if_else6:
    LD A, 32
    CALL agon_tui_render_tui_putch
    JP .agon_tui_render_puts_padded_if_join5

; strings
_mir2.str.0:
    DB 72, 101, 108, 108, 111, 32, 102, 114, 111, 109, 32, 77, 105, 110, 90, 32, 111, 110, 32, 65, 103, 111, 110, 33, 0
_mir2.str.1:
    DB 101, 90, 56, 48, 32, 65, 68, 76, 32, 109, 111, 100, 101, 32, 64, 32, 49, 56, 46, 52, 51, 50, 32, 77, 72, 122, 0
_mir2.str.2:
    DB 80, 114, 101, 115, 115, 32, 97, 110, 121, 32, 107, 101, 121, 46, 46, 46, 0
