// Package mir2c translates MIR2 modules to C99 source text.
//
// C99 is used as a second correctness oracle alongside pkg/mir2qbe (QBE IL).
// Any divergence between the C result and the Z80 result localises the bug
// to the Z80 codegen.
//
// Key design decisions
//
//  1. Block params → mutable locals declared at function top.
//     Every register that is a block param is declared as a C local before
//     any label.  Branches assign to these locals then goto the target.
//     This avoids "goto crosses initialisation" warnings and is always correct
//     for SSA where each source register is written exactly once.
//
//  2. Parallel copy via tmp-and-assign.
//     Jump args are assigned through temporaries so aliased registers (e.g.
//     a loop that swaps a↔b) are handled correctly:
//         { T _t0 = rA; T _t1 = rB; p0 = _t0; p1 = _t1; }
//
//  3. Pointer registers → uintptr_t.
//     Registers used as memory addresses get C type uintptr_t (native ptr
//     width).  All other registers get the C type matching their MIR2 type.
//     Pointer detection reuses findPointerRegs from mir2qbe verbatim.
//
//  4. CmpSubCarry / CmpSubCarryNot: recover the original operands from the
//     defining OpSub instruction via findDef and emit a plain C comparison.
package mir2c

import (
	"fmt"
	"strings"

	"github.com/minz/minzc/pkg/mir2"
)

// Compile translates a MIR2 module to a C99 translation unit.
func Compile(m *mir2.Module) (string, error) {
	g := &gen{sb: &strings.Builder{}, mod: m}
	g.emitModule()
	return g.sb.String(), nil
}

// ── internal generator ────────────────────────────────────────────────────────

type gen struct {
	sb  *strings.Builder
	mod *mir2.Module

	// per-function
	ptrRegs  map[mir2.Reg]bool   // registers that are memory addresses
	slotVars map[mir2.Reg]string // OpPatchSlot: reg → "_slot<N>" name
	tmpCount int
}

// ── module ────────────────────────────────────────────────────────────────────

func (g *gen) emitModule() {
	g.line("/* generated by mir2c — do not edit */")
	g.line("#include <stdint.h>")
	g.line("#include <stdio.h>")
	g.line("#include <string.h>")
	g.line("")

	if len(g.mod.Globals) > 0 {
		g.line("/* ── globals ── */")
		for _, gl := range g.mod.Globals {
			g.emitGlobal(gl)
		}
		g.line("")
	}

	// Forward declarations so function order doesn't matter.
	g.line("/* ── forward declarations ── */")
	knownFuncs := make(map[string]bool)
	for _, f := range g.mod.Funcs {
		knownFuncs[f.Name] = true
		if f.Attrs.IsExtern {
			g.printf("extern %s;\n", g.funcSignature(f))
		} else {
			g.printf("%s;\n", g.funcSignature(f))
		}
	}

	// Emit extern declarations for called functions not in the module
	// (e.g. canvas_*, host functions provided by the runtime).
	calledExtern := make(map[string]bool)
	for _, f := range g.mod.Funcs {
		for _, b := range f.Blocks {
			for _, inst := range b.Insts {
				if inst.Op == mir2.OpCall && !knownFuncs[inst.Sym] &&
					!strings.HasPrefix(inst.Sym, "@") {
					calledExtern[inst.Sym] = true
				}
			}
		}
	}
	for name := range calledExtern {
		// Generic variadic declaration — the runtime provides the real signature.
		g.printf("extern int %s();\n", name)
	}
	g.line("")

	// Function bodies
	for _, f := range g.mod.Funcs {
		if !f.Attrs.IsExtern {
			g.emitFunc(f)
			g.line("")
		}
	}
}

func (g *gen) emitGlobal(gl mir2.Global) {
	align := ""
	if at, ok := gl.Ty.(*mir2.ArrayTy); ok && at.Align > 0 {
		align = fmt.Sprintf("_Alignas(%d) ", at.Align)
	}
	const_ := ""
	if gl.IsConst {
		const_ = "const "
	}
	byteLen := mir2ByteWidth(gl.Ty)
	if byteLen < 1 {
		byteLen = 1
	}

	if len(gl.Init) == 0 {
		// zero-initialised
		g.printf("%sstatic %suint8_t %s[%d];\n", align, const_, gl.Name, byteLen)
		return
	}

	parts := make([]string, len(gl.Init))
	for i, b := range gl.Init {
		parts[i] = fmt.Sprintf("0x%02x", b)
	}
	g.printf("%sstatic %suint8_t %s[%d] = { %s };\n",
		align, const_, gl.Name, len(gl.Init), strings.Join(parts, ", "))
}

// ── function ──────────────────────────────────────────────────────────────────

func (g *gen) emitFunc(f *mir2.Func) {
	g.ptrRegs = findPointerRegs(f)
	g.slotVars = make(map[mir2.Reg]string)
	g.tmpCount = 0

	g.printf("%s {\n", g.funcSignature(f))

	// 1. Declare all block-param registers as mutable locals.
	g.emitBlockParamDecls(f)

	// 2. Declare all non-param instruction results as locals.
	g.emitInstResultDecls(f)

	// 3. Declare alloca arrays.
	g.emitAllocaDecls(f)

	// 4. Emit blocks.
	for _, b := range f.Blocks {
		g.emitBlock(f, b)
	}

	g.line("}")
}

func (g *gen) funcSignature(f *mir2.Func) string {
	retC := "void"
	if len(f.Contract.Returns) > 0 && f.Contract.Returns[0].Ty != mir2.TyVoid {
		retC = cBaseTy(f.Contract.Returns[0].Ty)
	}
	params := make([]string, len(f.Contract.Params))
	for i, p := range f.Contract.Params {
		params[i] = fmt.Sprintf("%s r%d", g.cTy(p.Ty, p.Reg), p.Reg)
	}
	return fmt.Sprintf("%s %s(%s)", retC, f.Name, strings.Join(params, ", "))
}

// emitBlockParamDecls declares all block params as function-scope locals.
func (g *gen) emitBlockParamDecls(f *mir2.Func) {
	// Collect param reg set so we skip them in inst result pass.
	paramSet := make(map[mir2.Reg]bool)
	for _, p := range f.Contract.Params {
		paramSet[p.Reg] = true
	}

	any := false
	for _, b := range f.Blocks {
		for _, bp := range b.Params {
			if !paramSet[bp.Dst] {
				g.printf("\t%s r%d;\n", g.cTy(bp.Ty, bp.Dst), bp.Dst)
				paramSet[bp.Dst] = true
				any = true
			}
		}
	}
	if any {
		g.line("")
	}
}

// emitInstResultDecls declares all instruction result registers as locals.
func (g *gen) emitInstResultDecls(f *mir2.Func) {
	paramSet := make(map[mir2.Reg]bool)
	for _, p := range f.Contract.Params {
		paramSet[p.Reg] = true
	}
	for _, b := range f.Blocks {
		for _, bp := range b.Params {
			paramSet[bp.Dst] = true
		}
	}

	any := false
	for _, b := range f.Blocks {
		for _, inst := range b.Insts {
			if inst.Dst == mir2.NoReg || paramSet[inst.Dst] {
				continue
			}
			if inst.Op == mir2.OpAlloca {
				// Alloca dst register still needs a declaration (receives pointer).
				g.printf("\t%s r%d;\n", g.cTy(inst.Ty, inst.Dst), inst.Dst)
				paramSet[inst.Dst] = true
				any = true
				continue
			}
			g.printf("\t%s r%d;\n", g.cTy(inst.Ty, inst.Dst), inst.Dst)
			paramSet[inst.Dst] = true
			any = true
		}
	}
	if any {
		g.line("")
	}
}

// emitAllocaDecls declares stack arrays for OpAlloca instructions.
func (g *gen) emitAllocaDecls(f *mir2.Func) {
	any := false
	for _, b := range f.Blocks {
		for _, inst := range b.Insts {
			if inst.Op != mir2.OpAlloca {
				continue
			}
			sz := inst.Imm
			if sz < 1 {
				sz = 1
			}
			g.printf("\tuint8_t _alloca_r%d[%d];\n", inst.Dst, sz)
			any = true
		}
	}
	if any {
		g.line("")
	}
}

// ── block ─────────────────────────────────────────────────────────────────────

func (g *gen) emitBlock(f *mir2.Func, b *mir2.Block) {
	g.printf("b_%s:;\n", b.Label)
	for _, inst := range b.Insts {
		g.emitInst(f, inst)
	}
	g.emitTerm(f, b.Term)
}

// ── instructions ──────────────────────────────────────────────────────────────

func (g *gen) emitInst(f *mir2.Func, inst *mir2.Inst) {
	dst := inst.Dst
	a, b := inst.Src[0], inst.Src[1]

	// Helper: emit "r<dst> = (<cast>)(expr);\n"
	def := func(expr string) {
		cast := g.cTy(inst.Ty, dst)
		g.printf("\tr%d = (%s)(%s);\n", dst, cast, expr)
	}
	ra := func(r mir2.Reg) string { return fmt.Sprintf("r%d", r) }
	// Signed cast of a register for signed arithmetic.
	signed := func(r mir2.Reg, ty mir2.Ty) string {
		return fmt.Sprintf("(%s)r%d", g.cSignedTy(ty), r)
	}

	switch inst.Op {
	// Binary arithmetic
	case mir2.OpAdd:
		def(fmt.Sprintf("r%d + r%d", a, b))
	case mir2.OpSub:
		def(fmt.Sprintf("r%d - r%d", a, b))
	case mir2.OpMul:
		def(fmt.Sprintf("r%d * r%d", a, b))
	case mir2.OpDiv:
		def(fmt.Sprintf("r%d / r%d", a, b))
	case mir2.OpSDiv:
		def(fmt.Sprintf("%s / %s", signed(a, inst.Ty), signed(b, inst.Ty)))
	case mir2.OpMod:
		def(fmt.Sprintf("r%d %% r%d", a, b))

	// Bitwise
	case mir2.OpAnd:
		def(fmt.Sprintf("r%d & r%d", a, b))
	case mir2.OpOr:
		def(fmt.Sprintf("r%d | r%d", a, b))
	case mir2.OpXor:
		def(fmt.Sprintf("r%d ^ r%d", a, b))
	case mir2.OpShl:
		def(fmt.Sprintf("r%d << r%d", a, b))
	case mir2.OpShr:
		def(fmt.Sprintf("r%d >> r%d", a, b))
	case mir2.OpSar:
		def(fmt.Sprintf("%s >> r%d", signed(a, inst.SrcTy), b))

	// Unary
	case mir2.OpNeg:
		def(fmt.Sprintf("-%s", signed(a, inst.Ty)))
	case mir2.OpNot:
		def(fmt.Sprintf("~r%d", a))

	// Conversions
	case mir2.OpExt:
		def(ra(a)) // cast to wider unsigned type handles zero-extend
	case mir2.OpSext:
		def(fmt.Sprintf("(%s)r%d", g.cSignedTy(inst.SrcTy), a))
	case mir2.OpTrunc:
		def(ra(a)) // narrowing cast in def() handles truncation

	// Comparison
	case mir2.OpCmp:
		g.emitCmp(f, inst)
		return // emitCmp writes the full statement

	// Const / move
	case mir2.OpConst:
		g.printf("\tr%d = (%s)%d;\n", dst, g.cTy(inst.Ty, dst), inst.Imm)
	case mir2.OpMove:
		g.printf("\tr%d = r%d;\n", dst, a)

	// Memory
	case mir2.OpLoad:
		loadTy := g.cTy(inst.Ty, dst)
		g.printf("\tr%d = *(%s*)(uintptr_t)r%d;\n", dst, loadTy, a)
	case mir2.OpStore:
		ptr, val := inst.Src[0], inst.Src[1]
		storeTy := g.cTy(inst.Ty, val)
		g.printf("\t*(%s*)(uintptr_t)r%d = (%s)r%d;\n", storeTy, ptr, storeTy, val)

	case mir2.OpAddrOf:
		g.printf("\tr%d = (uintptr_t)(%s);\n", dst, inst.Sym)

	case mir2.OpAlloca:
		// Array was declared at function top; just assign pointer.
		g.printf("\tr%d = (uintptr_t)_alloca_r%d;\n", dst, dst)

	case mir2.OpField, mir2.OpPtrBump:
		g.printf("\tr%d = (uintptr_t)(r%d + %d);\n", dst, a, inst.Imm)

	case mir2.OpPtrAdd:
		g.printf("\tr%d = (uintptr_t)(r%d + r%d);\n", dst, a, b)

	// Calls
	case mir2.OpCall:
		g.emitCall(inst)
	case mir2.OpCallIndirect:
		g.emitCallIndirect(inst)

	// SMC — lowered to mutable variable
	case mir2.OpPatchSlot:
		name := fmt.Sprintf("_slot_r%d", dst)
		g.slotVars[dst] = name
		g.printf("\tstatic %s %s = %d;\n", g.cTy(inst.Ty, dst), name, inst.Imm)
		g.printf("\tr%d = %s;\n", dst, name)
	case mir2.OpLoadPatched:
		name := g.slotVars[a]
		if name == "" {
			name = fmt.Sprintf("_slot_r%d", a)
		}
		g.printf("\tr%d = %s;\n", dst, name)
	case mir2.OpPatch:
		name := g.slotVars[a]
		if name == "" {
			name = fmt.Sprintf("_slot_r%d", a)
		}
		g.printf("\t%s = r%d;\n", name, b)

	// Z80-specific — skip
	case mir2.OpPush, mir2.OpPop, mir2.OpAsm:
		g.printf("\t/* %v skipped (Z80-specific) */\n", inst.Op)

	default:
		g.printf("\t/* unhandled op %v */\n", inst.Op)
	}
}

func (g *gen) emitCmp(f *mir2.Func, inst *mir2.Inst) {
	dst := inst.Dst
	a, b := inst.Src[0], inst.Src[1]

	switch inst.Cond {
	case mir2.CmpSubCarry, mir2.CmpSubCarryNot:
		// CmpSubCarry(r=sub(orig_a, orig_b), orig_b) ≡ orig_a < orig_b unsigned.
		// Recover orig_a from the defining OpSub.
		origA := a
		if def := findDef(f, a); def != nil && def.Op == mir2.OpSub {
			origA = def.Src[0]
		}
		op := "<"
		if inst.Cond == mir2.CmpSubCarryNot {
			op = ">="
		}
		g.printf("\tr%d = (uint8_t)((r%d %s r%d) ? 1 : 0);\n", dst, origA, op, b)
		return
	}

	op, needSigned := cmpOp(inst.Cond)
	if needSigned {
		// Cast both sides to signed for signed comparisons.
		sTy := g.cSignedTy(inst.SrcTy)
		if sTy == "" {
			sTy = "int16_t"
		}
		g.printf("\tr%d = (uint8_t)(((%s)r%d %s (%s)r%d) ? 1 : 0);\n",
			dst, sTy, a, op, sTy, b)
	} else {
		g.printf("\tr%d = (uint8_t)((r%d %s r%d) ? 1 : 0);\n", dst, a, op, b)
	}
}

func (g *gen) emitCall(inst *mir2.Inst) {
	// Handle common intrinsics.
	switch inst.Sym {
	case "@mir.io.print.u8", "@mir.io.print.u16":
		if len(inst.Args) > 0 {
			g.printf("\tprintf(\"%%u\\n\", (unsigned)r%d);\n", inst.Args[0])
		}
		return
	case "@mir.io.print.str":
		if len(inst.Args) > 0 {
			g.printf("\tprintf(\"%%s\", (char*)(uintptr_t)r%d);\n", inst.Args[0])
		}
		return
	}
	if strings.HasPrefix(inst.Sym, "@mir.") || strings.HasPrefix(inst.Sym, "@") {
		g.printf("\t/* intrinsic %s skipped */\n", inst.Sym)
		return
	}

	argParts := make([]string, len(inst.Args))
	for i, arg := range inst.Args {
		argParts[i] = fmt.Sprintf("r%d", arg)
	}
	call := fmt.Sprintf("%s(%s)", inst.Sym, strings.Join(argParts, ", "))
	if inst.Dst != mir2.NoReg {
		g.printf("\tr%d = (%s)%s;\n", inst.Dst, g.cTy(inst.Ty, inst.Dst), call)
	} else {
		g.printf("\t%s;\n", call)
	}
}

func (g *gen) emitCallIndirect(inst *mir2.Inst) {
	fn := inst.Src[0]
	argParts := make([]string, len(inst.Args))
	for i, arg := range inst.Args {
		argParts[i] = fmt.Sprintf("r%d", arg)
	}
	retC := "void"
	if inst.Dst != mir2.NoReg {
		retC = g.cTy(inst.Ty, inst.Dst)
	}
	call := fmt.Sprintf("((%s(*)())r%d)(%s)", retC, fn, strings.Join(argParts, ", "))
	if inst.Dst != mir2.NoReg {
		g.printf("\tr%d = (%s)%s;\n", inst.Dst, retC, call)
	} else {
		g.printf("\t%s;\n", call)
	}
}

// ── terminators ───────────────────────────────────────────────────────────────

func (g *gen) emitTerm(f *mir2.Func, t mir2.Term) {
	switch t := t.(type) {
	case *mir2.TermJmp:
		g.emitParallelCopy(f, t.Target, t.Args)
		g.printf("\tgoto b_%s;\n", t.Target)

	case *mir2.TermBrIf:
		g.printf("\tif (r%d) {\n", t.Cond)
		g.emitParallelCopyIndented(f, t.Then, t.ThenArgs, "\t\t")
		g.printf("\t\tgoto b_%s;\n", t.Then)
		g.line("\t} else {")
		g.emitParallelCopyIndented(f, t.Else, t.ElseArgs, "\t\t")
		g.printf("\t\tgoto b_%s;\n", t.Else)
		g.line("\t}")

	case *mir2.TermBrIf2:
		lhs, rhs := fmt.Sprintf("r%d", t.Lhs), fmt.Sprintf("r%d", t.Rhs)
		// Determine unsigned type for lt/gt comparison (always unsigned per Z80 CP semantics).
		g.printf("\tif (%s == %s) {\n", lhs, rhs)
		g.emitParallelCopyIndented(f, t.Eq, t.EqArgs, "\t\t")
		g.printf("\t\tgoto b_%s;\n", t.Eq)
		g.printf("\t} else if ((uint16_t)%s < (uint16_t)%s) {\n", lhs, rhs)
		g.emitParallelCopyIndented(f, t.Lt, t.LtArgs, "\t\t")
		g.printf("\t\tgoto b_%s;\n", t.Lt)
		g.line("\t} else {")
		g.emitParallelCopyIndented(f, t.Gt, t.GtArgs, "\t\t")
		g.printf("\t\tgoto b_%s;\n", t.Gt)
		g.line("\t}")

	case *mir2.TermDJNZ:
		// Decrement counter; body block's Params[0] gets the decremented value.
		bodyBlock := blockByLabel(f, t.Body)
		ctrTy := "uint8_t"
		if bodyBlock != nil && len(bodyBlock.Params) > 0 {
			ctrTy = g.cTy(bodyBlock.Params[0].Ty, bodyBlock.Params[0].Dst)
		}
		tmp := g.freshTmp()
		g.printf("\t%s %s = (%s)(r%d - 1);\n", ctrTy, tmp, ctrTy, t.Counter)
		g.printf("\tif (%s != 0) {\n", tmp)
		// Assign decremented value to body block's first param, then body args.
		if bodyBlock != nil && len(bodyBlock.Params) > 0 {
			g.printf("\t\tr%d = %s;\n", bodyBlock.Params[0].Dst, tmp)
		}
		g.emitParallelCopyIndented(f, t.Body, t.BodyArgs, "\t\t")
		g.printf("\t\tgoto b_%s;\n", t.Body)
		g.line("\t} else {")
		g.emitParallelCopyIndented(f, t.Exit, t.ExitArgs, "\t\t")
		g.printf("\t\tgoto b_%s;\n", t.Exit)
		g.line("\t}")

	case *mir2.TermCondRet:
		// Cond == 0 → return Vals; Cond != 0 → jump to Then.
		g.printf("\tif (!r%d) {\n", t.Cond)
		if len(t.Vals) == 0 {
			g.line("\t\treturn;")
		} else {
			g.printf("\t\treturn r%d;\n", t.Vals[0])
		}
		g.line("\t}")
		g.emitParallelCopy(f, t.Then, t.ThenArgs)
		g.printf("\tgoto b_%s;\n", t.Then)

	case *mir2.TermRet:
		if len(t.Vals) == 0 {
			g.line("\treturn;")
		} else {
			g.printf("\treturn r%d;\n", t.Vals[0])
		}

	case *mir2.TermUnreachable:
		g.line("\t__builtin_unreachable();")

	case nil:
		g.line("\t/* missing terminator */")
	}
}

// emitParallelCopy emits assignments for block args → block params before a jump.
// Uses tmp-and-assign to correctly handle aliased registers.
func (g *gen) emitParallelCopy(f *mir2.Func, target string, args []mir2.Reg) {
	g.emitParallelCopyIndented(f, target, args, "\t")
}

func (g *gen) emitParallelCopyIndented(f *mir2.Func, target string, args []mir2.Reg, indent string) {
	tb := blockByLabel(f, target)
	if tb == nil || len(args) == 0 {
		return
	}

	// Determine which params to assign. For DJNZ body, Params[0] is handled
	// separately (decremented counter). emitParallelCopyIndented is called
	// with BodyArgs which covers Params[1..], so start offset 1 for DJNZ body.
	// We always match args positionally against tb.Params, letting the caller
	// pass the correct slice.
	n := len(args)
	if n > len(tb.Params) {
		n = len(tb.Params)
	}

	// Find offset: if args is a slice of BodyArgs (fewer than len(Params)),
	// the offset is len(Params) - len(args). But for non-DJNZ terminators
	// args always corresponds to Params[0..n-1].
	// Simple rule: offset = len(tb.Params) - n for DJNZ body (caller trims first),
	// but since TermDJNZ.BodyArgs skips param[0] we pass offset=1 implicitly.
	// Actually: TermDJNZ.BodyArgs maps to Params[1..], so:
	//   for non-DJNZ: args[i] → tb.Params[i]
	//   for DJNZ body: args[i] → tb.Params[i+1]  (caller handles Params[0])
	// We detect this by checking if len(args) < len(tb.Params) for DJNZ.
	// Simplest: always match args[i] → tb.Params[offset+i] where
	// offset = len(tb.Params) - len(args) when len(args) < len(tb.Params).
	offset := 0
	if len(args) < len(tb.Params) {
		offset = len(tb.Params) - len(args)
	}

	// Check if any src aliases a dst (parallel copy problem).
	needTmps := false
	for i := 0; i < n; i++ {
		param := tb.Params[offset+i].Dst
		src := args[i]
		if src == param {
			continue
		}
		// Check if param appears as a src later.
		for j := i + 1; j < n; j++ {
			if args[j] == param {
				needTmps = true
				break
			}
		}
		if needTmps {
			break
		}
	}

	if needTmps {
		// Save all sources to temporaries first.
		tmpNames := make([]string, n)
		for i := 0; i < n; i++ {
			ty := g.cTy(tb.Params[offset+i].Ty, tb.Params[offset+i].Dst)
			tmp := g.freshTmp()
			g.printf("%s%s %s = r%d;\n", indent, ty, tmp, args[i])
			tmpNames[i] = tmp
		}
		for i := 0; i < n; i++ {
			param := tb.Params[offset+i].Dst
			if args[i] != param {
				g.printf("%sr%d = %s;\n", indent, param, tmpNames[i])
			}
		}
	} else {
		// Simple: no aliasing, emit directly.
		for i := 0; i < n; i++ {
			param := tb.Params[offset+i].Dst
			src := args[i]
			if src != param {
				g.printf("%sr%d = r%d;\n", indent, param, src)
			}
		}
	}
}

// ── helpers ───────────────────────────────────────────────────────────────────

// cTy returns the C type for a MIR2 type, promoting to uintptr_t if the
// register is used as a memory address.
func (g *gen) cTy(ty mir2.Ty, r mir2.Reg) string {
	if g.ptrRegs[r] {
		return "uintptr_t"
	}
	return cBaseTy(ty)
}

// cBaseTy maps a MIR2 type to a C base type string (ignoring pointer promotion).
func cBaseTy(ty mir2.Ty) string {
	if ty == nil || ty == mir2.TyVoid {
		return "void"
	}
	// Unwrap ranged types.
	if r, ok := ty.(*mir2.RangedTy); ok {
		return cBaseTy(r.Base)
	}
	switch ty {
	case mir2.TyBool:
		return "uint8_t"
	case mir2.TyU8:
		return "uint8_t"
	case mir2.TyI8:
		return "int8_t"
	case mir2.TyU16:
		return "uint16_t"
	case mir2.TyI16:
		return "int16_t"
	case mir2.TyU24, mir2.TyU32:
		return "uint32_t"
	case mir2.TyI24, mir2.TyI32:
		return "int32_t"
	case mir2.TyPtr:
		return "uintptr_t"
	}
	// Fixed-point and other composite: fall through to width-based.
	w := ty.Width()
	if w <= 8 {
		return "uint8_t"
	}
	if w <= 16 {
		return "uint16_t"
	}
	return "uint32_t"
}

// cSignedTy returns the signed C counterpart for a type.
func (g *gen) cSignedTy(ty mir2.Ty) string {
	if ty == nil {
		return "int16_t"
	}
	if r, ok := ty.(*mir2.RangedTy); ok {
		return g.cSignedTy(r.Base)
	}
	switch ty {
	case mir2.TyU8, mir2.TyI8, mir2.TyBool:
		return "int8_t"
	case mir2.TyU16, mir2.TyI16:
		return "int16_t"
	case mir2.TyU24, mir2.TyU32, mir2.TyI24, mir2.TyI32:
		return "int32_t"
	}
	return "int16_t"
}

// cmpOp maps a CmpCond to a C operator and whether signed casts are needed.
func cmpOp(c mir2.CmpCond) (op string, signed bool) {
	switch c {
	case mir2.CmpEq:
		return "==", false
	case mir2.CmpNe:
		return "!=", false
	case mir2.CmpLt:
		return "<", true
	case mir2.CmpLe:
		return "<=", true
	case mir2.CmpGt:
		return ">", true
	case mir2.CmpGe:
		return ">=", true
	case mir2.CmpUlt:
		return "<", false
	case mir2.CmpUle:
		return "<=", false
	case mir2.CmpUgt:
		return ">", false
	case mir2.CmpUge:
		return ">=", false
	}
	return "==", false
}

func (g *gen) freshTmp() string {
	g.tmpCount++
	return fmt.Sprintf("_ct%d", g.tmpCount)
}

func (g *gen) printf(format string, args ...any) {
	fmt.Fprintf(g.sb, format, args...)
}

func (g *gen) line(s string) {
	g.sb.WriteString(s)
	g.sb.WriteByte('\n')
}

// ── findPointerRegs (copied from mir2qbe, pure MIR2 analysis) ────────────────

func findPointerRegs(f *mir2.Func) map[mir2.Reg]bool {
	ptrs := make(map[mir2.Reg]bool)
	for _, b := range f.Blocks {
		for _, inst := range b.Insts {
			switch inst.Op {
			case mir2.OpPtrAdd, mir2.OpField, mir2.OpPtrBump,
				mir2.OpAddrOf, mir2.OpAlloca:
				ptrs[inst.Dst] = true
				ptrs[inst.Src[0]] = true
			case mir2.OpLoad:
				ptrs[inst.Src[0]] = true
			case mir2.OpStore:
				ptrs[inst.Src[0]] = true
			}
			if inst.Ty == mir2.TyPtr && inst.Dst != mir2.NoReg {
				ptrs[inst.Dst] = true
			}
		}
	}
	for _, p := range f.Contract.Params {
		if p.Ty == mir2.TyPtr {
			ptrs[p.Reg] = true
		}
	}
	mark := func(r mir2.Reg) bool {
		if ptrs[r] {
			return false
		}
		ptrs[r] = true
		return true
	}
	changed := true
	for changed {
		changed = false
		for _, b := range f.Blocks {
			for _, inst := range b.Insts {
				if inst.Op == mir2.OpMove && inst.Dst != mir2.NoReg {
					if ptrs[inst.Src[0]] {
						changed = mark(inst.Dst) || changed
					}
					if ptrs[inst.Dst] {
						changed = mark(inst.Src[0]) || changed
					}
				}
			}
			propagateArgs := func(target string, args []mir2.Reg) {
				tb := blockByLabel(f, target)
				if tb == nil {
					return
				}
				for i, arg := range args {
					if i >= len(tb.Params) {
						break
					}
					param := tb.Params[i].Dst
					if ptrs[arg] {
						changed = mark(param) || changed
					}
					if ptrs[param] {
						changed = mark(arg) || changed
					}
				}
			}
			switch t := b.Term.(type) {
			case *mir2.TermJmp:
				propagateArgs(t.Target, t.Args)
			case *mir2.TermBrIf:
				propagateArgs(t.Then, t.ThenArgs)
				propagateArgs(t.Else, t.ElseArgs)
			case *mir2.TermBrIf2:
				propagateArgs(t.Eq, t.EqArgs)
				propagateArgs(t.Lt, t.LtArgs)
				propagateArgs(t.Gt, t.GtArgs)
			case *mir2.TermDJNZ:
				propagateArgs(t.Body, t.BodyArgs)
				propagateArgs(t.Exit, t.ExitArgs)
			}
		}
	}
	return ptrs
}

func blockByLabel(f *mir2.Func, label string) *mir2.Block {
	for _, b := range f.Blocks {
		if b.Label == label {
			return b
		}
	}
	return nil
}

// findDef returns the instruction in f that defines register r, or nil.
func findDef(f *mir2.Func, r mir2.Reg) *mir2.Inst {
	for _, b := range f.Blocks {
		for _, inst := range b.Insts {
			if inst.Dst == r {
				return inst
			}
		}
	}
	return nil
}

// mir2ByteWidth returns the byte width of a MIR2 type for global sizing.
func mir2ByteWidth(ty mir2.Ty) int {
	if ty == nil {
		return 1
	}
	w := ty.Width()
	if w == 0 {
		return 1
	}
	return (w + 7) / 8
}
