// Package ez80 implements the eZ80 ADL mode code generation backend.
//
// This is an independent backend that generates eZ80 assembly from IR.
// It does NOT share codegen code with the Z80 backend (pkg/codegen/z80.go).
// Both backends share the same IR and target-independent optimization passes.
//
// See docs/adr/0036-ez80-independent-backend.md for the design rationale.
package ez80

import (
	"bytes"
	"fmt"
	"io"

	"github.com/minz/minzc/pkg/codegen"
	"github.com/minz/minzc/pkg/ir"
)

// EZ80Backend implements the codegen.Backend interface for eZ80 ADL mode.
type EZ80Backend struct {
	options *codegen.BackendOptions
	target  codegen.TargetInfo
}

// NewEZ80Backend creates a new eZ80 backend.
func NewEZ80Backend(options *codegen.BackendOptions) codegen.Backend {
	return &EZ80Backend{
		options: options,
		target:  codegen.TargetEZ80ADL,
	}
}

func (b *EZ80Backend) Name() string            { return "ez80" }
func (b *EZ80Backend) GetFileExtension() string { return ".asm" }

func (b *EZ80Backend) SupportsFeature(feature string) bool {
	switch feature {
	case codegen.FeatureSelfModifyingCode:
		return false // not yet
	case codegen.FeatureInterrupts:
		return true
	case codegen.FeatureShadowRegisters:
		return true
	case codegen.Feature16BitPointers:
		return false
	case codegen.Feature24BitPointers:
		return true
	case codegen.FeatureHardwareMultiply:
		return true // MLT instruction
	case codegen.FeatureBlockInstructions:
		return true
	default:
		return false
	}
}

func (b *EZ80Backend) Generate(module *ir.Module) (string, error) {
	var buf bytes.Buffer
	gen := NewEZ80Generator(&buf, b.target)

	if err := gen.Generate(module); err != nil {
		return "", err
	}

	return buf.String(), nil
}

// Register the eZ80 backend
func init() {
	codegen.RegisterBackend("ez80", func(options *codegen.BackendOptions) codegen.Backend {
		return NewEZ80Backend(options)
	})
}

// ---------------------------------------------------------------------------
// EZ80Generator — eZ80 ADL assembly generator
// ---------------------------------------------------------------------------

type EZ80Generator struct {
	w      io.Writer
	target codegen.TargetInfo
	module *ir.Module

	labelCounter int
	stackOffset  int

	currentFunc    *ir.Function
	constantValues map[ir.Register]int64
}

func NewEZ80Generator(w io.Writer, target codegen.TargetInfo) *EZ80Generator {
	return &EZ80Generator{
		w:              w,
		target:         target,
		constantValues: make(map[ir.Register]int64),
	}
}

// Generate generates eZ80 ADL assembly for the entire module.
func (g *EZ80Generator) Generate(module *ir.Module) error {
	g.module = module

	g.emitHeader()

	// Generate main first (entry point at ORG), then others
	var mainFunc *ir.Function
	var otherFuncs []*ir.Function
	for _, fn := range module.Functions {
		if fn.IsExtern {
			continue
		}
		if fn.Name == "main" {
			mainFunc = fn
		} else {
			otherFuncs = append(otherFuncs, fn)
		}
	}

	if mainFunc != nil {
		if err := g.generateFunction(mainFunc); err != nil {
			return fmt.Errorf("main: %w", err)
		}
	}

	for _, fn := range otherFuncs {
		if err := g.generateFunction(fn); err != nil {
			return fmt.Errorf("%s: %w", fn.Name, err)
		}
	}

	g.emitDataSection()
	g.emitFooter()
	return nil
}

// ---------------------------------------------------------------------------
// Header / Footer / Data
// ---------------------------------------------------------------------------

func (g *EZ80Generator) emitHeader() {
	g.emit("; eZ80 ADL mode assembly — generated by MinZ compiler")
	g.emit("; Target: Agon Light 2 (eZ80 @ 18.432 MHz)")
	g.emit("")
	g.emit("    .ASSUME ADL=1")
	g.emit("    ORG $%06X", g.target.OrgAddr)
	g.emit("")
}

func (g *EZ80Generator) emitFooter() {
	g.emit("")
	g.emit("    END")
}

func (g *EZ80Generator) emitDataSection() {
	if g.module == nil {
		return
	}

	hasData := false

	for _, global := range g.module.Globals {
		if !hasData {
			g.emit("")
			g.emit("; --- Data Section ---")
			hasData = true
		}
		g.emit("%s:", global.Name)
		size := 0
		if global.Type != nil {
			size = global.Type.Size()
		}
		initVal := 0
		if v, ok := global.Init.(int); ok {
			initVal = v
		}
		switch {
		case size <= 1:
			g.emit("    DB %d", initVal)
		case size <= 2:
			g.emit("    DW %d", initVal)
		case size <= 3:
			g.emit("    DB %d, %d, %d", initVal&0xFF, (initVal>>8)&0xFF, (initVal>>16)&0xFF)
		default:
			g.emit("    DS %d, 0", size)
		}
	}

	for _, str := range g.module.Strings {
		if !hasData {
			g.emit("")
			g.emit("; --- Data Section ---")
			hasData = true
		}
		g.emit("%s:", str.Label)
		g.emit("    DB %d", len(str.Value))
		if len(str.Value) > 0 {
			g.emitNoNL("    DB ")
			for i, ch := range []byte(str.Value) {
				if i > 0 {
					g.emitNoNL(", ")
				}
				g.emitNoNL("%d", ch)
			}
			g.emit("")
		}
	}
}

// ---------------------------------------------------------------------------
// Function codegen
// ---------------------------------------------------------------------------

func (g *EZ80Generator) generateFunction(fn *ir.Function) error {
	g.currentFunc = fn
	g.constantValues = make(map[ir.Register]int64)
	g.stackOffset = 0

	g.emit("; --- %s ---", fn.Name)
	g.emit("%s:", fn.Name)

	g.generatePrologue(fn)

	for _, inst := range fn.Instructions {
		if err := g.generateInstruction(inst); err != nil {
			return fmt.Errorf("instruction %v: %w", inst.Op, err)
		}
	}

	g.emit("")
	return nil
}

func (g *EZ80Generator) generatePrologue(fn *ir.Function) {
	g.emit("    PUSH IX")
	g.emit("    LD IX, 0")
	g.emit("    ADD IX, SP")

	// Allocate locals: count unique Dest registers
	locals := g.countLocals(fn)
	if locals > 0 {
		frameSize := locals * g.target.StackSlot
		g.stackOffset = frameSize
		if frameSize <= 6 {
			for i := 0; i < frameSize; i++ {
				g.emit("    DEC SP")
			}
		} else {
			g.emit("    LD HL, -%d", frameSize)
			g.emit("    ADD HL, SP")
			g.emit("    LD SP, HL")
		}
	}

	g.loadParameters(fn)
}

func (g *EZ80Generator) generateEpilogue() {
	g.emit("    LD SP, IX")
	g.emit("    POP IX")
	g.emit("    RET")
}

func (g *EZ80Generator) countLocals(fn *ir.Function) int {
	seen := make(map[ir.Register]bool)
	for _, inst := range fn.Instructions {
		if inst.Dest != 0 {
			seen[inst.Dest] = true
		}
	}
	return len(seen)
}

func (g *EZ80Generator) loadParameters(fn *ir.Function) {
	// eZ80 ADL calling convention:
	//   Param 0: A (u8) or HL (u24/ptr)
	//   Param 1: DE (u24)
	//   Param 2: BC (u24)
	//   Param 3+: stack at IX+6, IX+9, IX+12, ... (3 bytes per slot)
	for i, param := range fn.Params {
		switch i {
		case 0:
			if param.Type != nil && param.Type.Size() == 1 {
				g.emit("    LD (IX+%d), A", g.localOffset(param.Reg))
			} else {
				g.storeFromHL(param.Reg)
			}
		case 1:
			g.storeFromDE(param.Reg)
		case 2:
			g.storeFromBC(param.Reg)
		default:
			stackOff := 6 + (i-3)*g.target.StackSlot
			g.emit("    LD HL, (IX+%d)", stackOff)
			g.storeFromHL(param.Reg)
		}
	}
}

// localOffset returns the IX+d offset for a virtual register's local slot.
// Locals grow downward: first local at IX-3, second at IX-6, etc. (3 bytes in ADL)
func (g *EZ80Generator) localOffset(reg ir.Register) int {
	return -int(reg+1) * g.target.StackSlot
}

// ---------------------------------------------------------------------------
// Instruction dispatch
// ---------------------------------------------------------------------------

func (g *EZ80Generator) generateInstruction(inst ir.Instruction) error {
	switch inst.Op {
	case ir.OpLoadImm:
		g.constantValues[inst.Dest] = inst.Imm
		if inst.Imm >= 0 && inst.Imm <= 255 {
			g.emit("    LD A, %d", inst.Imm)
			g.emit("    LD (IX+%d), A", g.localOffset(inst.Dest))
		} else {
			g.emit("    LD HL, %d", inst.Imm)
			g.storeFromHL(inst.Dest)
		}

	case ir.OpAdd:
		g.loadToHL(inst.Src1)
		g.loadToDE(inst.Src2)
		g.emit("    ADD HL, DE")
		g.storeFromHL(inst.Dest)

	case ir.OpSub:
		g.loadToHL(inst.Src1)
		g.loadToDE(inst.Src2)
		g.emit("    OR A")
		g.emit("    SBC HL, DE")
		g.storeFromHL(inst.Dest)

	case ir.OpMul:
		if g.isU8(inst.Src1) && g.isU8(inst.Src2) {
			g.loadToB(inst.Src1)
			g.loadToC(inst.Src2)
			g.emit("    MLT BC")
			g.emit("    LD L, C")
			g.emit("    LD H, B")
			g.storeFromHL(inst.Dest)
		} else {
			g.emit("    ; TODO: 24-bit multiply")
		}

	case ir.OpReturn:
		if inst.Src1 != 0 {
			if g.isU8(inst.Src1) {
				g.loadToA(inst.Src1)
			} else {
				g.loadToHL(inst.Src1)
			}
		}
		g.generateEpilogue()

	case ir.OpCall:
		g.generateCall(inst)

	case ir.OpLabel:
		g.emit("%s:", inst.Label)
		g.constantValues = make(map[ir.Register]int64)

	case ir.OpJump:
		g.emit("    JP %s", inst.Label)

	case ir.OpJumpIf:
		g.loadToA(inst.Src1)
		g.emit("    OR A")
		g.emit("    JP NZ, %s", inst.Label)

	case ir.OpLoadVar:
		g.loadToHL(inst.Src1)
		g.storeFromHL(inst.Dest)

	case ir.OpStoreVar:
		g.loadToHL(inst.Src1)
		g.storeFromHL(inst.Dest)

	case ir.OpNop:
		// nothing

	default:
		g.emit("    ; TODO: %v", inst.Op)
	}

	return nil
}

func (g *EZ80Generator) generateCall(inst ir.Instruction) {
	for i, arg := range inst.Args {
		switch i {
		case 0:
			if g.isU8(arg) {
				g.loadToA(arg)
			} else {
				g.loadToHL(arg)
			}
		case 1:
			g.loadToDE(arg)
		case 2:
			g.loadToBC(arg)
		default:
			g.loadToHL(arg)
			g.emit("    PUSH HL")
		}
	}

	name := inst.Label
	if name == "" {
		name = inst.FuncName
	}
	g.emit("    CALL %s", name)

	if len(inst.Args) > 3 {
		cleanup := (len(inst.Args) - 3) * g.target.StackSlot
		g.emit("    LD HL, %d", cleanup)
		g.emit("    ADD HL, SP")
		g.emit("    LD SP, HL")
	}

	if inst.Dest != 0 {
		g.storeFromHL(inst.Dest)
	}
}

// ---------------------------------------------------------------------------
// Load / Store helpers
// ---------------------------------------------------------------------------

func (g *EZ80Generator) loadToHL(reg ir.Register) {
	if val, ok := g.constantValues[reg]; ok {
		g.emit("    LD HL, %d", val)
		return
	}
	g.emit("    LD HL, (IX+%d)", g.localOffset(reg))
}

func (g *EZ80Generator) loadToDE(reg ir.Register) {
	if val, ok := g.constantValues[reg]; ok {
		g.emit("    LD DE, %d", val)
		return
	}
	g.emit("    LD DE, (IX+%d)", g.localOffset(reg))
}

func (g *EZ80Generator) loadToBC(reg ir.Register) {
	if val, ok := g.constantValues[reg]; ok {
		g.emit("    LD BC, %d", val)
		return
	}
	g.emit("    LD BC, (IX+%d)", g.localOffset(reg))
}

func (g *EZ80Generator) loadToA(reg ir.Register) {
	if val, ok := g.constantValues[reg]; ok {
		g.emit("    LD A, %d", val&0xFF)
		return
	}
	g.emit("    LD A, (IX+%d)", g.localOffset(reg))
}

func (g *EZ80Generator) loadToB(reg ir.Register) {
	if val, ok := g.constantValues[reg]; ok {
		g.emit("    LD B, %d", val&0xFF)
		return
	}
	g.emit("    LD B, (IX+%d)", g.localOffset(reg))
}

func (g *EZ80Generator) loadToC(reg ir.Register) {
	if val, ok := g.constantValues[reg]; ok {
		g.emit("    LD C, %d", val&0xFF)
		return
	}
	g.emit("    LD C, (IX+%d)", g.localOffset(reg))
}

func (g *EZ80Generator) storeFromHL(reg ir.Register) {
	g.emit("    LD (IX+%d), HL", g.localOffset(reg))
}

func (g *EZ80Generator) storeFromDE(reg ir.Register) {
	g.emit("    EX DE, HL")
	g.storeFromHL(reg)
	g.emit("    EX DE, HL")
}

func (g *EZ80Generator) storeFromBC(reg ir.Register) {
	off := g.localOffset(reg)
	g.emit("    LD (IX+%d), C", off)
	g.emit("    LD (IX+%d), B", off+1)
	if g.target.StackSlot == 3 {
		g.emit("    LD (IX+%d), 0", off+2)
	}
}

// ---------------------------------------------------------------------------
// Type helpers
// ---------------------------------------------------------------------------

func (g *EZ80Generator) isU8(reg ir.Register) bool {
	if val, ok := g.constantValues[reg]; ok {
		return val >= 0 && val <= 255
	}
	if g.currentFunc != nil {
		for _, param := range g.currentFunc.Params {
			if param.Reg == reg && param.Type != nil && param.Type.Size() == 1 {
				return true
			}
		}
	}
	return false
}

// ---------------------------------------------------------------------------
// Emit helpers
// ---------------------------------------------------------------------------

func (g *EZ80Generator) emit(format string, args ...interface{}) {
	if len(args) > 0 {
		fmt.Fprintf(g.w, format+"\n", args...)
	} else {
		fmt.Fprintln(g.w, format)
	}
}

func (g *EZ80Generator) emitNoNL(format string, args ...interface{}) {
	if len(args) > 0 {
		fmt.Fprintf(g.w, format, args...)
	} else {
		fmt.Fprint(g.w, format)
	}
}

func (g *EZ80Generator) uniqueLabel(prefix string) string {
	g.labelCounter++
	return fmt.Sprintf(".%s_%d", prefix, g.labelCounter)
}
