package ez80

import (
	"fmt"
	"strings"

	"github.com/minz/minzc/pkg/mir2"
)

// MIR2Codegen generates eZ80 ADL assembly from a MIR2 module with allocation results.
//
// Phase 1 implementation: wraps mir2.Z80Codegen output with eZ80 ADL directives.
// MZA in ADL mode handles 24-bit immediates/addresses automatically via emitWord().
// Future phases will add eZ80-specific instruction selection (MLT, LEA, PEA, TST).
func MIR2Codegen(m *mir2.Module, ar *mir2.AllocResult) string {
	// Generate Z80 assembly (reuse existing battle-tested codegen)
	z80asm := mir2.Z80Codegen(m, ar)

	var sb strings.Builder

	// eZ80 ADL header
	sb.WriteString("; eZ80 ADL mode assembly — generated by MinZ compiler (MIR2 pipeline)\n")
	sb.WriteString("; Target: Agon Light 2 (eZ80 @ 18.432 MHz)\n\n")
	sb.WriteString("    .ASSUME ADL=1\n")
	sb.WriteString(fmt.Sprintf("    ORG $%06X\n\n", 0x040000))

	// Append Z80 codegen output (MZA handles ADL encoding)
	sb.WriteString(z80asm)

	return sb.String()
}
