// Native eZ80 ADL codegen from MIR2.
//
// This is an independent codegen that does NOT wrap Z80Codegen. It generates
// eZ80-specific assembly directly from MIR2 with allocation results, exploiting:
//   - 24-bit register width (native LD rr, nn with 3-byte immediate)
//   - MLT for 8×8 multiply (6T vs ~80T software)
//   - LEA for index+displacement address computation
//   - TST for non-destructive AND
//   - Cheaper frame setup (LEA IX, SP+0 vs PUSH IX / LD IX,0 / ADD IX,SP)
//   - 3-byte stack slots
//
// See docs/adr/0036-ez80-independent-backend.md and
// docs/adr/0037-target-neutral-optimization-split.md.
package ez80

import (
	"fmt"
	"strings"

	"github.com/minz/minzc/pkg/mir2"
)

// MIR2Codegen generates eZ80 ADL assembly from a MIR2 module with allocation results.
func MIR2Codegen(m *mir2.Module, ar *mir2.AllocResult) string {
	var sb strings.Builder
	cg := &ez80cg{ar: ar, sb: &sb, mod: m}

	cg.emitf("; eZ80 ADL mode assembly — generated by MinZ compiler")
	cg.emitf("; Target: Agon Light 2 (eZ80 @ 18.432 MHz)")
	cg.emit("")
	cg.emit("    .ASSUME ADL=1")
	cg.emitf("    ORG $%06X", 0x040000)
	cg.emit("")

	// Emit main first so binary entry point is at ORG.
	funcs := m.Funcs
	if main := m.FuncByName("main"); main != nil && len(funcs) > 0 && funcs[0].Name != "main" {
		ordered := make([]*mir2.Func, 0, len(funcs))
		ordered = append(ordered, main)
		for _, f := range funcs {
			if f.Name != "main" {
				ordered = append(ordered, f)
			}
		}
		funcs = ordered
	}

	for _, f := range funcs {
		cg.genFunc(f)
		sb.WriteByte('\n')
	}

	// Globals
	if len(m.Globals) > 0 {
		cg.emit("; globals")
		for _, g := range m.Globals {
			w := mir2.ByteWidth(g.Ty)
			if len(g.Init) > w {
				w = len(g.Init)
			}
			if w == 0 {
				cg.emitf("%s:", sanitize(g.Name))
				continue
			}
			cg.emitf("%s:", sanitize(g.Name))
			cg.sb.WriteString("    DB ")
			for i := 0; i < w; i++ {
				if i > 0 {
					cg.sb.WriteString(", ")
				}
				b := byte(0)
				if i < len(g.Init) {
					b = g.Init[i]
				}
				fmt.Fprintf(cg.sb, "%d", b)
			}
			cg.sb.WriteByte('\n')
		}
	}

	// Strings
	if m.Strings.Len() > 0 {
		cg.emit("; strings")
		for i := 0; i < m.Strings.Len(); i++ {
			sym := sanitize(m.Strings.Symbol(i))
			s := m.Strings.At(i)
			kind := m.Strings.Kind(i)
			cg.emitf("%s:", sym)
			switch kind {
			case mir2.StrSString:
				fmt.Fprintf(cg.sb, "    DB %d", len(s))
				for _, c := range []byte(s) {
					fmt.Fprintf(cg.sb, ", %d", c)
				}
				cg.sb.WriteByte('\n')
			case mir2.StrLString:
				lo := len(s) & 0xFF
				hi := (len(s) >> 8) & 0xFF
				fmt.Fprintf(cg.sb, "    DB %d, %d", lo, hi)
				for _, c := range []byte(s) {
					fmt.Fprintf(cg.sb, ", %d", c)
				}
				cg.sb.WriteByte('\n')
			case mir2.StrCString:
				cg.sb.WriteString("    DB ")
				for j, c := range []byte(s) {
					if j > 0 {
						cg.sb.WriteString(", ")
					}
					fmt.Fprintf(cg.sb, "%d", c)
				}
				cg.sb.WriteString(", 0\n")
			}
		}
	}

	if cg.needsCallHL {
		cg.emit("\n; runtime: indirect call trampoline")
		cg.emit("__call_hl:")
		cg.emit("    JP (HL)")
	}

	return sb.String()
}

// ---------------------------------------------------------------------------
// ez80cg — native eZ80 ADL code generator
// ---------------------------------------------------------------------------

type ez80cg struct {
	ar          *mir2.AllocResult
	sb          *strings.Builder
	mod         *mir2.Module
	fn          *mir2.Func
	constVals   map[mir2.Reg]int64
	blockParams map[mir2.Reg]bool
	needsCallHL bool
}

func (g *ez80cg) emit(s string)                    { g.sb.WriteString(s); g.sb.WriteByte('\n') }
func (g *ez80cg) emitf(f string, args ...any)       { g.emit(fmt.Sprintf(f, args...)) }
func (g *ez80cg) loc(r mir2.Reg) string {
	if r == mir2.NoReg {
		return "?"
	}
	return g.ar.Loc(r).Name
}

// ---------------------------------------------------------------------------
// Function codegen
// ---------------------------------------------------------------------------

func (g *ez80cg) genFunc(f *mir2.Func) {
	g.fn = f
	g.constVals = make(map[mir2.Reg]int64)
	g.blockParams = make(map[mir2.Reg]bool)
	for _, b := range f.Blocks {
		for _, p := range b.Params {
			g.blockParams[p.Dst] = true
		}
	}

	label := sanitize(f.Name)
	g.emitf("; %s", funcSig(f, g.ar))
	g.emitf("%s:", label)

	for _, b := range f.Blocks {
		g.genBlock(f, b)
	}
}

func (g *ez80cg) genBlock(f *mir2.Func, b *mir2.Block) {
	if b.Label != "entry" {
		g.emitf(".%s_%s:", sanitize(f.Name), sanitize(b.Label))
	}

	for _, inst := range b.Insts {
		g.genInst(inst)
	}

	g.genTerm(f, b)
}

// ---------------------------------------------------------------------------
// Instruction codegen
// ---------------------------------------------------------------------------

func (g *ez80cg) genInst(inst *mir2.Inst) {
	dst := g.loc(inst.Dst)

	switch inst.Op {
	case mir2.OpConst:
		if !g.blockParams[inst.Dst] {
			g.constVals[inst.Dst] = inst.Imm
		}
		if dst == "F" {
			if inst.Imm != 0 {
				g.emit("    SCF")
			} else {
				g.emit("    AND A")
			}
			return
		}
		w := inst.Ty.Width()
		if w <= 8 {
			g.emitf("    LD %s, %d", dst, inst.Imm)
		} else {
			// 16-bit or 24-bit: native on eZ80 (no shadow pair needed)
			g.emitf("    LD %s, %d", dst, inst.Imm)
		}

	case mir2.OpMove:
		src := g.loc(inst.Src[0])
		if dst != src {
			g.emitMov(dst, src, inst.Ty.Width())
		}

	case mir2.OpAdd:
		g.genBinOp("ADD", inst)
	case mir2.OpSub:
		g.genBinOp("SUB", inst)
	case mir2.OpAnd:
		g.genBinOp("AND", inst)
	case mir2.OpOr:
		g.genBinOp("OR", inst)
	case mir2.OpXor:
		g.genBinOp("XOR", inst)

	case mir2.OpMul:
		g.genMul(inst)

	case mir2.OpNeg:
		src := g.loc(inst.Src[0])
		if src != "A" {
			g.emitf("    LD A, %s", src)
		}
		g.emit("    NEG")
		if dst != "A" {
			g.emitf("    LD %s, A", dst)
		}

	case mir2.OpNot:
		src := g.loc(inst.Src[0])
		if src != "A" {
			g.emitf("    LD A, %s", src)
		}
		g.emit("    CPL")
		if dst != "A" {
			g.emitf("    LD %s, A", dst)
		}

	case mir2.OpExt:
		// Zero-extend u8 -> u16/u24: LD H,0 / LD L,src
		src := g.loc(inst.Src[0])
		pair := dst
		if pair == "HL" || pair == "DE" || pair == "BC" {
			hi, lo := pairHiLo(pair)
			g.emitf("    LD %s, 0", hi)
			if src != lo {
				g.emitf("    LD %s, %s", lo, src)
			}
		} else {
			g.emitf("    LD %s, %s", dst, src) // fallback
		}

	case mir2.OpCmp:
		g.genCmp(inst)

	case mir2.OpCall:
		g.genCall(inst)

	case mir2.OpCallIndirect:
		// Ensure function pointer in HL
		ptr := g.loc(inst.Src[0])
		if ptr != "HL" {
			g.emitf("    LD HL, %s", ptr) // TODO: handle pair moves properly
		}
		g.emit("    CALL __call_hl")
		g.needsCallHL = true
		if inst.Dst != mir2.NoReg && dst != "A" && dst != "HL" {
			g.emitf("    LD %s, A", dst)
		}

	case mir2.OpLoad:
		ptr := g.loc(inst.Src[0])
		w := inst.Ty.Width()
		if w <= 8 {
			if ptr == "HL" {
				g.emitf("    LD %s, (HL)", dst)
			} else if isIXY(ptr) {
				g.emitf("    LD %s, (%s+%d)", dst, ptr, inst.Imm)
			} else {
				g.emitf("    LD A, (%s)", ptr)
				if dst != "A" {
					g.emitf("    LD %s, A", dst)
				}
			}
		} else {
			// 16/24-bit load: eZ80 has LD rr,(IX+d) natively!
			if isIXY(ptr) {
				g.emitf("    LD %s, (%s+%d)", dst, ptr, inst.Imm)
			} else if ptr == "HL" {
				// LD rr,(HL) not available — use byte-by-byte or via IX
				lo, hi := pairHiLo(dst)
				g.emitf("    LD %s, (HL)", lo)
				g.emit("    INC HL")
				g.emitf("    LD %s, (HL)", hi)
			} else {
				g.emitf("    ; TODO: 16-bit load from %s", ptr)
			}
		}

	case mir2.OpStore:
		ptr := g.loc(inst.Src[0])
		val := g.loc(inst.Src[1])
		w := inst.Ty.Width()
		if w <= 8 {
			if ptr == "HL" {
				if val == "A" || is8bit(val) {
					g.emitf("    LD (HL), %s", val)
				} else {
					g.emitf("    LD A, %s", val)
					g.emit("    LD (HL), A")
				}
			} else if isIXY(ptr) {
				g.emitf("    LD (%s+%d), %s", ptr, inst.Imm, val)
			} else {
				g.emitf("    ; TODO: store to %s", ptr)
			}
		} else {
			// 16/24-bit store: eZ80 has LD (IX+d),rr natively!
			if isIXY(ptr) {
				g.emitf("    LD (%s+%d), %s", ptr, inst.Imm, val)
			} else if ptr == "HL" {
				lo, hi := pairHiLo(val)
				g.emitf("    LD (HL), %s", lo)
				g.emit("    INC HL")
				g.emitf("    LD (HL), %s", hi)
			} else {
				g.emitf("    ; TODO: 16-bit store to %s", ptr)
			}
		}

	case mir2.OpAddrOf:
		g.emitf("    LD %s, %s", dst, sanitize(inst.Sym))

	case mir2.OpField:
		src := g.loc(inst.Src[0])
		off := int(inst.Imm)
		// eZ80 LEA: compute address in one instruction
		if isIXY(src) && isPair(dst) {
			g.emitf("    LEA %s, %s+%d", dst, src, off)
		} else if isPair(src) && isPair(dst) {
			if off == 0 {
				g.emitMov(dst, src, 24)
			} else {
				g.emitf("    LD %s, %d", "DE", off) // TODO: pick scratch
				g.emitf("    ADD %s, DE", src)
				if dst != src {
					g.emitMov(dst, src, 24)
				}
			}
		} else {
			g.emitf("    ; TODO: OpField %s + %d -> %s", src, off, dst)
		}

	case mir2.OpPtrAdd:
		base := g.loc(inst.Src[0])
		idx := g.loc(inst.Src[1])
		if base == dst {
			g.emitf("    ADD %s, %s", base, idx)
		} else {
			if dst != base {
				g.emitMov(dst, base, 24)
			}
			g.emitf("    ADD %s, %s", dst, idx)
		}

	case mir2.OpPtrBump:
		src := g.loc(inst.Src[0])
		stride := int(inst.Imm)
		if dst != src {
			g.emitMov(dst, src, 24)
		}
		if stride == 1 {
			g.emitf("    INC %s", dst)
		} else if stride == -1 {
			g.emitf("    DEC %s", dst)
		} else {
			g.emitf("    LD DE, %d", stride)
			g.emitf("    ADD %s, DE", dst)
		}

	case mir2.OpAlloca:
		// Stack allocation: DEC SP * N or LD HL,-N / ADD HL,SP / LD SP,HL
		size := int(inst.Imm)
		if size <= 6 {
			for i := 0; i < size; i++ {
				g.emit("    DEC SP")
			}
		} else {
			g.emitf("    LD HL, -%d", size)
			g.emit("    ADD HL, SP")
			g.emit("    LD SP, HL")
		}
		// Result = SP (stack pointer after allocation)
		if dst != "HL" {
			g.emitMov(dst, "HL", 24)
		}

	default:
		g.emitf("    ; TODO: %v", inst.Op)
	}
}

// ---------------------------------------------------------------------------
// Binary operations (8-bit ALU + 16/24-bit pair ops)
// ---------------------------------------------------------------------------

func (g *ez80cg) genBinOp(mnem string, inst *mir2.Inst) {
	dst := g.loc(inst.Dst)
	lhs := g.loc(inst.Src[0])
	rhs := g.loc(inst.Src[1])
	w := inst.Ty.Width()

	if w <= 8 {
		// 8-bit: op goes through A
		if lhs != "A" {
			g.emitf("    LD A, %s", lhs)
		}
		// Check for constant RHS
		if cv, ok := g.constVals[inst.Src[1]]; ok && mnem != "SUB" {
			g.emitf("    %s A, %d", mnem, cv)
		} else if mnem == "SUB" {
			if cv, ok := g.constVals[inst.Src[1]]; ok {
				g.emitf("    SUB %d", cv)
			} else {
				g.emitf("    SUB %s", rhs)
			}
		} else {
			g.emitf("    %s A, %s", mnem, rhs)
		}
		if dst != "A" {
			g.emitf("    LD %s, A", dst)
		}
	} else {
		// 16/24-bit pair operation
		switch mnem {
		case "ADD":
			if lhs != dst {
				g.emitMov(dst, lhs, w)
			}
			g.emitf("    ADD %s, %s", dst, rhs)
		case "SUB":
			if lhs != dst {
				g.emitMov(dst, lhs, w)
			}
			g.emit("    OR A") // clear carry
			g.emitf("    SBC %s, %s", dst, rhs)
		default:
			// AND/OR/XOR on pairs: byte-by-byte through A
			lo1, hi1 := pairHiLo(lhs)
			lo2, hi2 := pairHiLo(rhs)
			dlo, dhi := pairHiLo(dst)
			g.emitf("    LD A, %s", lo1)
			g.emitf("    %s A, %s", mnem, lo2)
			g.emitf("    LD %s, A", dlo)
			g.emitf("    LD A, %s", hi1)
			g.emitf("    %s A, %s", mnem, hi2)
			g.emitf("    LD %s, A", dhi)
		}
	}
}

// ---------------------------------------------------------------------------
// Multiply — MLT for u8, software for u16+
// ---------------------------------------------------------------------------

func (g *ez80cg) genMul(inst *mir2.Inst) {
	dst := g.loc(inst.Dst)
	lhs := g.loc(inst.Src[0])
	rhs := g.loc(inst.Src[1])
	w := inst.Ty.Width()

	if w <= 8 {
		// eZ80 MLT: B*C -> BC, D*E -> DE, H*L -> HL
		// Pick a pair. Prefer BC (most common for counter*value patterns).
		g.emitf("    LD B, %s", lhs)
		g.emitf("    LD C, %s", rhs)
		g.emit("    MLT BC")
		// Result in C (low byte) — for u8 result
		if dst == "A" {
			g.emit("    LD A, C")
		} else if dst != "C" {
			g.emitf("    LD %s, C", dst)
		}
	} else {
		// 16/24-bit multiply: call __mul16 runtime
		// TODO: implement __mul16 for eZ80
		g.emitf("    ; TODO: %d-bit multiply %s * %s -> %s", w, lhs, rhs, dst)
	}
}

// ---------------------------------------------------------------------------
// Compare
// ---------------------------------------------------------------------------

func (g *ez80cg) genCmp(inst *mir2.Inst) {
	lhs := g.loc(inst.Src[0])
	rhs := g.loc(inst.Src[1])

	if lhs != "A" {
		g.emitf("    LD A, %s", lhs)
	}
	if cv, ok := g.constVals[inst.Src[1]]; ok {
		g.emitf("    CP %d", cv)
	} else {
		g.emitf("    CP %s", rhs)
	}
	// Result is in flags — ClassFlag dst handled by TermBrIf
}

// ---------------------------------------------------------------------------
// Function call
// ---------------------------------------------------------------------------

func (g *ez80cg) genCall(inst *mir2.Inst) {
	callee := g.mod.FuncByName(inst.Sym)

	// Set up arguments per callee contract
	if callee != nil && len(callee.Contract.Params) > 0 {
		for i, p := range callee.Contract.Params {
			if i >= len(inst.Args) {
				break
			}
			argLoc := g.loc(inst.Args[i])
			target := classToPhys(p.Class)
			if target != "" && argLoc != target {
				g.emitMov(target, argLoc, p.Ty.Width())
			}
		}
	}

	if callee != nil && callee.Attrs.ExternAddr != 0 {
		addr := callee.Attrs.ExternAddr
		// RST for well-known addresses
		if addr == 0x08 || addr == 0x10 || addr == 0x18 {
			g.emitf("    RST.LIL $%02X", addr)
		} else {
			g.emitf("    CALL $%06X", addr)
		}
	} else {
		g.emitf("    CALL %s", sanitize(inst.Sym))
	}

	// Return value: nothing to do if already in correct location
	if inst.Dst != mir2.NoReg {
		dst := g.loc(inst.Dst)
		if callee != nil && len(callee.Contract.Returns) > 0 {
			retClass := callee.Contract.Returns[0].Class
			retLoc := classToPhys(retClass)
			if retLoc != "" && retLoc != dst {
				g.emitMov(dst, retLoc, callee.Contract.Returns[0].Ty.Width())
			}
		}
	}
}

// ---------------------------------------------------------------------------
// Terminators
// ---------------------------------------------------------------------------

func (g *ez80cg) genTerm(f *mir2.Func, b *mir2.Block) {
	switch t := b.Term.(type) {
	case *mir2.TermRet:
		// Move return values to contract positions (usually A or HL)
		if len(t.Vals) > 0 && len(f.Contract.Returns) > 0 {
			src := g.loc(t.Vals[0])
			retClass := f.Contract.Returns[0].Class
			retLoc := classToPhys(retClass)
			if retLoc != "" && src != retLoc {
				g.emitMov(retLoc, src, f.Contract.Returns[0].Ty.Width())
			}
		}
		g.emit("    RET")

	case *mir2.TermJmp:
		// Emit parallel copy for block args
		g.emitBlockArgCopies(f, t.Target, t.Args)
		g.emitf("    JP .%s_%s", sanitize(f.Name), sanitize(t.Target))

	case *mir2.TermBrIf:
		// Find the CmpCond from the defining OpCmp instruction
		cc := g.findCondCode(f, t.Cond)
		// Emit copies for the taken edge, then JP cc
		g.emitBlockArgCopies(f, t.Then, t.ThenArgs)
		g.emitf("    JP %s, .%s_%s", cc, sanitize(f.Name), sanitize(t.Then))
		// Fall through to else
		g.emitBlockArgCopies(f, t.Else, t.ElseArgs)
		g.emitf("    JP .%s_%s", sanitize(f.Name), sanitize(t.Else))

	case *mir2.TermUnreachable:
		g.emit("    DI")
		g.emit("    HALT")

	case *mir2.TermDJNZ:
		counter := g.loc(t.Counter)
		if counter != "B" {
			g.emitf("    LD B, %s", counter)
		}
		g.emitf("    DJNZ .%s_%s", sanitize(f.Name), sanitize(t.Body))
		g.emitBlockArgCopies(f, t.Exit, t.ExitArgs)
		g.emitf("    JP .%s_%s", sanitize(f.Name), sanitize(t.Exit))

	default:
		g.emitf("    ; TODO: terminator %T", b.Term)
	}
}

func (g *ez80cg) emitBlockArgCopies(f *mir2.Func, targetLabel string, args []mir2.Reg) {
	if len(args) == 0 {
		return
	}
	// Find target block
	var target *mir2.Block
	for _, b := range f.Blocks {
		if b.Label == targetLabel {
			target = b
			break
		}
	}
	if target == nil {
		return
	}
	for i, arg := range args {
		if i >= len(target.Params) {
			break
		}
		src := g.loc(arg)
		dst := g.loc(target.Params[i].Dst)
		if src != dst {
			g.emitMov(dst, src, target.Params[i].Ty.Width())
		}
	}
}

// ---------------------------------------------------------------------------
// Move helper
// ---------------------------------------------------------------------------

func (g *ez80cg) emitMov(dst, src string, widthBits int) {
	if dst == src {
		return
	}
	// Flag materialization
	if src == "F" {
		// Can't LD from F directly — use SBC A,A for carry flag
		g.emit("    SBC A, A") // A = 0xFF if carry, 0x00 if not
		if dst != "A" {
			g.emitf("    LD %s, A", dst)
		}
		return
	}
	// Pair-to-pair: try EX DE,HL first, else use LD
	if isPair(dst) && isPair(src) {
		if (dst == "HL" && src == "DE") || (dst == "DE" && src == "HL") {
			g.emit("    EX DE, HL")
			return
		}
		// eZ80: PUSH src / POP dst (3 bytes each in ADL)
		g.emitf("    PUSH %s", src)
		g.emitf("    POP %s", dst)
		return
	}
	// 8-bit or mixed: direct LD
	g.emitf("    LD %s, %s", dst, src)
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

func sanitize(s string) string {
	var b strings.Builder
	for _, c := range s {
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
			(c >= '0' && c <= '9') || c == '_' || c == '.' {
			b.WriteRune(c)
		} else {
			b.WriteByte('_')
		}
	}
	return b.String()
}

func isIXY(reg string) bool   { return reg == "IX" || reg == "IY" }
func isPair(reg string) bool  { return reg == "HL" || reg == "DE" || reg == "BC" || isIXY(reg) }
func is8bit(reg string) bool {
	switch reg {
	case "A", "B", "C", "D", "E", "H", "L", "IXH", "IXL", "IYH", "IYL":
		return true
	}
	return false
}

func pairHiLo(pair string) (hi, lo string) {
	switch pair {
	case "HL":
		return "H", "L"
	case "DE":
		return "D", "E"
	case "BC":
		return "B", "C"
	default:
		return pair, pair // fallback
	}
}

func cmpCondToCC(c mir2.CmpCond) string {
	switch c {
	case mir2.CmpEq:
		return "Z"
	case mir2.CmpNe:
		return "NZ"
	case mir2.CmpLt:
		return "C"
	case mir2.CmpGe:
		return "NC"
	case mir2.CmpGt:
		return "NZ" // simplified: GT after CP uses NZ (works for unsigned)
	case mir2.CmpLe:
		return "Z" // simplified
	default:
		return "NZ"
	}
}

// findCondCode locates the OpCmp that defined the flag register `condReg`
// and returns the appropriate Z80/eZ80 condition code string.
func (g *ez80cg) findCondCode(f *mir2.Func, condReg mir2.Reg) string {
	for _, b := range f.Blocks {
		for _, inst := range b.Insts {
			if inst.Dst == condReg && inst.Op == mir2.OpCmp {
				return cmpCondToCC(inst.Cond)
			}
		}
	}
	return "NZ" // fallback
}

func funcSig(f *mir2.Func, ar *mir2.AllocResult) string {
	var sb strings.Builder
	sb.WriteString("fun ")
	sb.WriteString(f.Name)
	sb.WriteByte('(')
	for i, p := range f.Contract.Params {
		if i > 0 {
			sb.WriteString(", ")
		}
		fmt.Fprintf(&sb, "%s: %s = %s", p.Name, p.Ty, ar.Loc(p.Reg).Name)
	}
	sb.WriteByte(')')
	if len(f.Contract.Returns) > 0 {
		fmt.Fprintf(&sb, " -> %s = %s", f.Contract.Returns[0].Ty,
			classToPhys(f.Contract.Returns[0].Class))
	}
	return sb.String()
}

// classToPhys maps a register class to its preferred eZ80 physical location name.
func classToPhys(cls mir2.RegClass) string {
	switch cls {
	case mir2.ClassAcc, mir2.ClassAccShadow:
		return "A"
	case mir2.ClassCounter:
		return "B"
	case mir2.ClassPointer:
		return "HL"
	case mir2.ClassIndex:
		return "DE"
	case mir2.ClassPair, mir2.ClassDWord:
		return "HL"
	case mir2.ClassIX:
		return "IX"
	case mir2.ClassIY:
		return "IY"
	case mir2.ClassFlag:
		return "F"
	default:
		return "A" // fallback for ClassGeneral etc.
	}
}
