// Package mir2go translates MIR2 modules to Go source text.
//
// This is essentially an AOT compiler for what MZV (pkg/mir2/vm.go) does
// at runtime. Every MIR2 opcode maps to a Go statement. The output is a
// standalone Go program that can be compiled with `go build`.
//
// Design:
//   - Registers → local variables (r0, r1, ...) of type int64
//   - Memory → []byte heap (like VM.heap)
//   - Block params → mutable locals, assigned at branch site
//   - Terminators → if/goto with labels
//   - Calls → direct Go function calls
//   - Strings → byte slices in the heap, initialized at startup
package mir2go

import (
	"fmt"
	"strings"

	"github.com/minz/minzc/pkg/mir2"
)

// goSym sanitizes a MIR2 symbol for Go identifiers.
func goSym(name string) string {
	s := strings.ReplaceAll(name, "@", "")
	s = strings.ReplaceAll(s, ".", "_")
	s = strings.ReplaceAll(s, "$", "_")
	s = strings.ReplaceAll(s, "-", "_")
	return s
}

// Compile translates a MIR2 module to a standalone Go program.
func Compile(m *mir2.Module) (string, error) {
	g := &gen{sb: &strings.Builder{}, mod: m}
	g.emitModule()
	return g.sb.String(), nil
}

type gen struct {
	sb       *strings.Builder
	mod      *mir2.Module
	slotVars map[mir2.Reg]string
}

func (g *gen) line(s string)                         { g.sb.WriteString(s); g.sb.WriteByte('\n') }
func (g *gen) printf(f string, a ...interface{}) { fmt.Fprintf(g.sb, f, a...) }

// ── module ──────────────────────────────────────────────────────────────────

func (g *gen) emitModule() {
	g.line("// Generated by mir2go — do not edit.")
	g.line("package main")
	g.line("")
	g.line("import \"fmt\"")
	g.line("import \"os\"")
	g.line("")

	// Heap (flat memory, like MIR2 VM)
	g.line("var heap []byte")
	g.line("")

	// Globals as heap offsets
	if len(g.mod.Globals) > 0 {
		g.line("// globals (heap offsets)")
		offset := 0
		for _, gl := range g.mod.Globals {
			w := mir2.ByteWidth(gl.Ty)
			if w < 1 {
				w = 1
			}
			g.printf("var gl_%s int64 = %d // %s, %d bytes\n", goSym(gl.Name), offset, gl.Ty, w)
			offset += w
		}
		g.printf("const heapGlobalsEnd = %d\n", offset)
		g.line("")
	}

	// String pool offsets
	if g.mod.Strings.Len() > 0 {
		g.line("// string pool (heap offsets)")
		for i := 0; i < g.mod.Strings.Len(); i++ {
			sym := goSym(g.mod.Strings.Symbol(i))
			g.printf("var %s int64\n", sym)
		}
		g.line("")
	}

	// Memory helpers
	g.emitHelpers()

	// Functions
	for _, f := range g.mod.Funcs {
		if !f.Attrs.IsExtern {
			g.emitFunc(f)
			g.line("")
		}
	}

	// Main entry point
	g.emitMain()
}

// ── helpers ─────────────────────────────────────────────────────────────────

func (g *gen) emitHelpers() {
	g.line("// memory access")
	g.line("func ld8(addr int64) int64 {")
	g.line("\tif addr >= 0 && int(addr) < len(heap) { return int64(heap[addr]) }")
	g.line("\treturn 0")
	g.line("}")
	g.line("func st8(addr, val int64) {")
	g.line("\tif addr >= 0 && int(addr) < len(heap) { heap[addr] = byte(val) }")
	g.line("}")
	g.line("func ld16(addr int64) int64 {")
	g.line("\treturn ld8(addr) | (ld8(addr+1) << 8)")
	g.line("}")
	g.line("func st16(addr, val int64) {")
	g.line("\tst8(addr, val&0xFF); st8(addr+1, (val>>8)&0xFF)")
	g.line("}")
	g.line("")

	g.line("// intrinsics")
	g.line("func mir_io_print_str(ptr int64) {")
	g.line("\tfor i := ptr; i < int64(len(heap)); i++ {")
	g.line("\t\tif heap[i] == 0 { break }")
	g.line("\t\tfmt.Printf(\"%c\", heap[i])")
	g.line("\t}")
	g.line("}")
	g.line("func mir_io_print_u8(v int64)  { fmt.Print(v) }")
	g.line("func mir_io_print_u16(v int64) { fmt.Print(v) }")
	g.line("func mir_io_print_nl()         { fmt.Println() }")
	g.line("func mir_io_print_char(v int64){ fmt.Printf(\"%c\", byte(v)) }")
	g.line("")
	g.line("var _ = os.Exit // suppress unused import")
	g.line("")
}

// ── main ────────────────────────────────────────────────────────────────────

func (g *gen) emitMain() {
	g.line("func main() {")
	g.line("\t// Init heap")
	g.line("\theap = make([]byte, 65536)")
	g.line("")

	// Init globals
	for _, gl := range g.mod.Globals {
		if len(gl.Init) > 0 {
			off := 0
			for _, gl2 := range g.mod.Globals {
				if gl2.Name == gl.Name {
					break
				}
				w := mir2.ByteWidth(gl2.Ty)
				if w < 1 {
					w = 1
				}
				off += w
			}
			for i, b := range gl.Init {
				if b != 0 {
					g.printf("\theap[%d] = %d\n", off+i, b)
				}
			}
		}
	}

	// Init strings
	if g.mod.Strings.Len() > 0 {
		g.line("")
		g.line("\t// string pool")
		g.printf("\tstrOff := int64(heapGlobalsEnd)\n")
		for i := 0; i < g.mod.Strings.Len(); i++ {
			s := g.mod.Strings.At(i)
			sym := goSym(g.mod.Strings.Symbol(i))
			g.printf("\t%s = strOff\n", sym)
			for _, b := range []byte(s) {
				g.printf("\theap[strOff] = %d; strOff++\n", b)
			}
			g.printf("\theap[strOff] = 0; strOff++ // NUL\n")
		}
	}

	g.line("")
	g.line("\t// run")
	g.line("\tfn_main()")
	g.line("}")
}

// ── function ────────────────────────────────────────────────────────────────

func (g *gen) emitFunc(f *mir2.Func) {
	g.slotVars = make(map[mir2.Reg]string)
	name := "fn_" + goSym(f.Name)

	params := f.Contract.Params
	results := f.Contract.Returns

	// Signature
	var paramList []string
	for i, p := range params {
		paramList = append(paramList, fmt.Sprintf("p%d int64 /*%s*/", i, p.Ty))
	}
	retType := ""
	if len(results) > 0 {
		retType = " int64"
	}
	g.printf("func %s(%s)%s {\n", name, strings.Join(paramList, ", "), retType)

	// Declare ALL registers (including param regs and arg regs)
	allRegs := make(map[mir2.Reg]bool)
	for _, p := range params {
		allRegs[p.Reg] = true
	}
	for _, b := range f.Blocks {
		for _, p := range b.Params {
			allRegs[p.Dst] = true
		}
		for _, inst := range b.Insts {
			if inst.Dst != mir2.NoReg {
				allRegs[inst.Dst] = true
			}
			for _, arg := range inst.Args {
				allRegs[arg] = true
			}
			if inst.Src[0] != mir2.NoReg {
				allRegs[inst.Src[0]] = true
			}
			if inst.Src[1] != mir2.NoReg {
				allRegs[inst.Src[1]] = true
			}
		}
	}
	delete(allRegs, mir2.NoReg)
	if len(allRegs) > 0 {
		var decls []string
		for r := range allRegs {
			decls = append(decls, fmt.Sprintf("r%d", r))
		}
		g.printf("\tvar %s int64\n", strings.Join(decls, ", "))
		// Suppress "declared and not used" for Go
		for r := range allRegs {
			g.printf("\t_ = r%d\n", r)
		}
	}

	// Bind params
	for i, p := range params {
		g.printf("\tr%d = p%d\n", p.Reg, i)
	}
	g.line("")

	// Emit blocks
	for i, b := range f.Blocks {
		if i > 0 {
			g.printf("%s:\n", goBlockLabel(b.Label))
		}
		for _, inst := range b.Insts {
			g.emitInst(inst)
		}
		g.emitTerm(f, b)
	}

	// Default return
	if len(results) > 0 {
		g.line("\treturn 0")
	}
	g.line("}")
}

func goBlockLabel(label string) string {
	s := strings.ReplaceAll(label, ".", "_")
	s = strings.ReplaceAll(s, "@", "")
	return "L_" + s
}

// ── instructions ────────────────────────────────────────────────────────────

func (g *gen) emitInst(inst *mir2.Inst) {
	dst := inst.Dst
	a, b := inst.Src[0], inst.Src[1]
	r := func(reg mir2.Reg) string { return fmt.Sprintf("r%d", reg) }

	mask := ""
	w := mir2.ByteWidth(inst.Ty)
	if w == 1 {
		mask = " & 0xFF"
	} else if w == 2 {
		mask = " & 0xFFFF"
	}

	def := func(expr string) {
		g.printf("\t%s = (%s)%s\n", r(dst), expr, mask)
	}

	switch inst.Op {
	case mir2.OpAdd:
		def(fmt.Sprintf("%s + %s", r(a), r(b)))
	case mir2.OpSub:
		def(fmt.Sprintf("%s - %s", r(a), r(b)))
	case mir2.OpMul:
		def(fmt.Sprintf("%s * %s", r(a), r(b)))
	case mir2.OpDiv:
		g.printf("\tif %s != 0 { %s = %s / %s } else { %s = 0 }\n", r(b), r(dst), r(a), r(b), r(dst))
	case mir2.OpMod:
		g.printf("\tif %s != 0 { %s = %s %% %s } else { %s = 0 }\n", r(b), r(dst), r(a), r(b), r(dst))

	case mir2.OpAnd:
		def(fmt.Sprintf("%s & %s", r(a), r(b)))
	case mir2.OpOr:
		def(fmt.Sprintf("%s | %s", r(a), r(b)))
	case mir2.OpXor:
		def(fmt.Sprintf("%s ^ %s", r(a), r(b)))
	case mir2.OpShl:
		def(fmt.Sprintf("%s << uint(%s)", r(a), r(b)))
	case mir2.OpShr:
		def(fmt.Sprintf("int64(uint64(%s) >> uint(%s))", r(a), r(b)))

	case mir2.OpNeg:
		def(fmt.Sprintf("-%s", r(a)))
	case mir2.OpNot:
		def(fmt.Sprintf("^%s", r(a)))

	case mir2.OpExt, mir2.OpTrunc, mir2.OpMove:
		def(r(a))
	case mir2.OpSext:
		if mir2.ByteWidth(inst.SrcTy) == 1 {
			g.printf("\t%s = int64(int8(%s))\n", r(dst), r(a))
		} else {
			g.printf("\t%s = int64(int16(%s))\n", r(dst), r(a))
		}

	case mir2.OpCmp:
		op := "=="
		switch inst.Cond {
		case mir2.CmpEq:
			op = "=="
		case mir2.CmpNe:
			op = "!="
		case mir2.CmpLt, mir2.CmpUlt, mir2.CmpSubCarry:
			op = "<"
		case mir2.CmpLe, mir2.CmpUle:
			op = "<="
		case mir2.CmpGt, mir2.CmpUgt, mir2.CmpSubCarryNot:
			op = ">"
		case mir2.CmpGe, mir2.CmpUge:
			op = ">="
		}
		g.printf("\tif %s %s %s { %s = 1 } else { %s = 0 }\n", r(a), op, r(b), r(dst), r(dst))

	case mir2.OpConst:
		g.printf("\t%s = %d\n", r(dst), inst.Imm)

	case mir2.OpLoad:
		if w <= 1 {
			g.printf("\t%s = ld8(%s)\n", r(dst), r(a))
		} else {
			g.printf("\t%s = ld16(%s)\n", r(dst), r(a))
		}
	case mir2.OpStore:
		ptr, val := inst.Src[0], inst.Src[1]
		if w <= 1 {
			g.printf("\tst8(%s, %s)\n", r(ptr), r(val))
		} else {
			g.printf("\tst16(%s, %s)\n", r(ptr), r(val))
		}

	case mir2.OpAddrOf:
		g.printf("\t%s = gl_%s\n", r(dst), goSym(inst.Sym))
	case mir2.OpField, mir2.OpPtrBump:
		g.printf("\t%s = %s + %d\n", r(dst), r(a), inst.Imm)
	case mir2.OpPtrAdd:
		g.printf("\t%s = %s + %s\n", r(dst), r(a), r(b))
	case mir2.OpAlloca:
		g.printf("\t%s = int64(len(heap)); heap = append(heap, make([]byte, %d)...)\n", r(dst), inst.Imm)

	case mir2.OpCall:
		g.emitCall(inst)

	case mir2.OpPatchSlot:
		name := fmt.Sprintf("slot_r%d", dst)
		g.slotVars[dst] = name
		g.printf("\t%s = %d; %s = int64(%s)\n", name, inst.Imm, r(dst), name)
	case mir2.OpLoadPatched:
		name := g.slotVars[a]
		if name == "" {
			name = fmt.Sprintf("slot_r%d", a)
		}
		g.printf("\t%s = int64(%s)\n", r(dst), name)
	case mir2.OpPatch:
		name := g.slotVars[a]
		if name == "" {
			name = fmt.Sprintf("slot_r%d", a)
		}
		g.printf("\t%s = int(%s)\n", name, r(b))

	default:
		g.printf("\t// TODO: %s r%d\n", inst.Op, dst)
	}
}

// ── calls ───────────────────────────────────────────────────────────────────

func (g *gen) emitCall(inst *mir2.Inst) {
	name := inst.Sym

	// Map intrinsics
	switch name {
	case "@mir.io.print.str":
		g.printf("\tmir_io_print_str(%s)\n", fmt.Sprintf("r%d", inst.Args[0]))
		return
	case "@mir.io.print.u8":
		g.printf("\tmir_io_print_u8(%s)\n", fmt.Sprintf("r%d", inst.Args[0]))
		return
	case "@mir.io.print.u16":
		g.printf("\tmir_io_print_u16(%s)\n", fmt.Sprintf("r%d", inst.Args[0]))
		return
	case "@mir.io.print.nl":
		g.line("\tmir_io_print_nl()")
		return
	case "@mir.io.print.char":
		g.printf("\tmir_io_print_char(%s)\n", fmt.Sprintf("r%d", inst.Args[0]))
		return
	}

	goName := "fn_" + goSym(name)
	var args []string
	for _, arg := range inst.Args {
		args = append(args, fmt.Sprintf("r%d", arg))
	}

	if inst.Dst != mir2.NoReg {
		g.printf("\tr%d = %s(%s)\n", inst.Dst, goName, strings.Join(args, ", "))
	} else {
		g.printf("\t%s(%s)\n", goName, strings.Join(args, ", "))
	}
}

// ── terminators ─────────────────────────────────────────────────────────────

func (g *gen) emitTerm(f *mir2.Func, b *mir2.Block) {
	switch t := b.Term.(type) {
	case *mir2.TermRet:
		if len(t.Vals) > 0 {
			g.printf("\treturn r%d\n", t.Vals[0])
		} else {
			g.line("\treturn")
		}

	case *mir2.TermJmp:
		target := f.BlockByLabel(t.Target)
		if target != nil {
			for i, p := range target.Params {
				if i < len(t.Args) {
					g.printf("\tr%d = r%d\n", p.Dst, t.Args[i])
				}
			}
		}
		g.printf("\tgoto %s\n", goBlockLabel(t.Target))

	case *mir2.TermBrIf:
		g.printf("\tif r%d != 0 {\n", t.Cond)
		thenBlock := f.BlockByLabel(t.Then)
		if thenBlock != nil {
			for i, p := range thenBlock.Params {
				if i < len(t.ThenArgs) {
					g.printf("\t\tr%d = r%d\n", p.Dst, t.ThenArgs[i])
				}
			}
		}
		g.printf("\t\tgoto %s\n", goBlockLabel(t.Then))
		g.line("\t}")
		elseBlock := f.BlockByLabel(t.Else)
		if elseBlock != nil {
			for i, p := range elseBlock.Params {
				if i < len(t.ElseArgs) {
					g.printf("\tr%d = r%d\n", p.Dst, t.ElseArgs[i])
				}
			}
		}
		g.printf("\tgoto %s\n", goBlockLabel(t.Else))
	}
}
