package analysis

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/minz/minzc/pkg/z80asm"
)

// LoadSymbolFile reads labels from a .sym file.
// Format: XXXX name [; comment]
// Lines starting with ; are comments.
func (a *Analysis) LoadSymbolFile(path string) error {
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	lineNum := 0
	for scanner.Scan() {
		lineNum++
		line := strings.TrimSpace(scanner.Text())

		// Skip empty lines and comments
		if line == "" || strings.HasPrefix(line, ";") {
			continue
		}

		// Remove inline comments
		if idx := strings.Index(line, ";"); idx >= 0 {
			line = strings.TrimSpace(line[:idx])
		}

		// Parse: XXXX name
		parts := strings.Fields(line)
		if len(parts) < 2 {
			return fmt.Errorf("line %d: expected 'XXXX name', got %q", lineNum, line)
		}

		addr, err := strconv.ParseUint(parts[0], 16, 16)
		if err != nil {
			return fmt.Errorf("line %d: invalid address %q: %w", lineNum, parts[0], err)
		}

		name := parts[1]
		a.SetLabel(uint16(addr), name, "user")
	}

	return scanner.Err()
}

// ExportSymbolFile writes all labels to a .sym file.
func (a *Analysis) ExportSymbolFile(path string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintf(f, "; Symbol file generated by mzd\n")
	fmt.Fprintf(f, "; Format: XXXX name\n\n")

	for _, lbl := range a.GetSortedLabels() {
		fmt.Fprintf(f, "%04X %s\n", lbl.Addr, lbl.Name)
	}

	return nil
}

// LoadPlatformSymbols loads platform-specific known symbols.
// Uses z80asm.GetTargetConfig() to find CommonSymbols.
func (a *Analysis) LoadPlatformSymbols(platform string) {
	target, err := z80asm.ParseTarget(platform)
	if err != nil {
		return
	}

	cfg := z80asm.GetTargetConfig(target)
	if cfg == nil {
		return
	}

	for name, addr := range cfg.Conventions.CommonSymbols {
		a.SetLabel(uint16(addr), name, "platform")
	}
}
