// mul_table.go — GPU-precomputed constant multiplication table.
//
// For each constant K=2..255, the table stores the shortest Z80 instruction
// sequence that computes A × K. Generated by exhaustive GPU brute-force
// search (z80-optimizer CUDA kernel).
//
// At compile time: mul(x, K) → emit precomputed sequence instead of
// CALL __mul8 (~80T loop). Typical savings: 4-8x speedup.
//
// Example: mul(x, 3) → LD B,A / ADD A,A / ADD A,B (12T vs 80T)
package vir

import (
	"encoding/json"
	"os"
	"sync"

	"github.com/minz/minzc/pkg/mir2"
)

// MulEntry is one precomputed constant multiply sequence.
type MulEntry struct {
	K       int      `json:"k"`
	Ops     []string `json:"ops"`
	Length  int      `json:"length"`
	TStates int      `json:"tstates"`
}

var (
	mulTable     map[int]*MulEntry // K → entry
	mulTableOnce sync.Once
)

// getMulTable loads and returns the multiply table.
func getMulTable() map[int]*MulEntry {
	mulTableOnce.Do(func() {
		mulTable = make(map[int]*MulEntry)
		// Try well-known paths
		for _, p := range []string{
			os.ExpandEnv("$HOME/dev/minz-vir/mul_table.json"),
			os.ExpandEnv("$HOME/dev/z80-optimizer/mul_table.json"),
			"mul_table.json",
		} {
			data, err := os.ReadFile(p)
			if err != nil {
				continue
			}
			var entries []MulEntry
			if err := json.Unmarshal(data, &entries); err != nil {
				continue
			}
			for i := range entries {
				mulTable[entries[i].K] = &entries[i]
			}
			break
		}
	})
	return mulTable
}

// tryConstMul checks if a MIR2 OpMul has a constant operand and returns
// an inline VIROp sequence from the precomputed table. Returns nil if
// no constant operand or no table entry.
func tryConstMul(inst *mir2.Inst, desc *MachineDesc, w int) []VIROp {
	table := getMulTable()
	if len(table) == 0 {
		return nil
	}

	// Check if Src[1] is a constant (most common: x * K)
	// We look for OpConst in the function's instructions that defines Src[1].
	// Since we're in translateInst (single instruction), we check inst.Imm
	// which is set for immediate multiply (from constant folding).
	k := int(inst.Imm)
	varSrc := int(inst.Src[0])

	// If Imm is 0, check if this is a reg×reg multiply (can't optimize)
	if k == 0 {
		return nil
	}

	entry, ok := table[k]
	if !ok {
		return nil
	}

	// Convert the table's instruction sequence to VIROps.
	// The table assumes: input in A, scratch in B, output in A.
	// We emit: move varSrc → A, then the sequence, result in dst.
	var ops []VIROp

	// Load the variable into a temp vreg that Z3 will assign to A
	srcVreg := varSrc
	dstVreg := int(inst.Dst)

	// Emit the precomputed sequence as an OpAsmBlock (opaque to Z3,
	// it just sees: input=srcVreg, output=dstVreg, clobbers=A,B,F)
	// Build asm template: join instructions with newlines
	asmTemplate := ""
	for i, op := range entry.Ops {
		if i > 0 {
			asmTemplate += "\n"
		}
		asmTemplate += "    " + op
	}

	clobbers := desc.LocSetByNames("A", "B", "F")
	ops = append(ops, VIROp{
		Op:          OpAsmBlock,
		Dst:         dstVreg,
		Src:         [2]int{srcVreg, -1},
		Width:       w,
		Clobbers:    clobbers,
		DstHint:     desc.LocSetByNames("A"), // result in A
		SrcHint:     [2]LocSet{desc.LocSetByNames("A")}, // input in A
		AsmTemplate: asmTemplate,
	})

	return ops
}
