// mul_table.go — GPU-precomputed constant multiplication table.
//
// For each constant K=2..255, the table stores the shortest Z80 instruction
// sequence that computes A × K. Generated by exhaustive GPU brute-force
// search (z80-optimizer CUDA kernel).
//
// At compile time: mul(x, K) → emit precomputed sequence instead of
// CALL __mul8 (~80T loop). Typical savings: 4-8x speedup.
//
// Example: mul(x, 3) → LD B,A / ADD A,A / ADD A,B (12T vs 80T)
package vir

import (
	"encoding/json"
	"os"
	"strings"
	"sync"

	"github.com/minz/minzc/pkg/mir2"
)

// MulEntry is one precomputed constant multiply sequence.
type MulEntry struct {
	K       int      `json:"k"`
	Ops     []string `json:"ops"`
	Length  int      `json:"length"`
	TStates int      `json:"tstates"`
}

var (
	mulTable     map[int]*MulEntry // K → entry
	mulTableOnce sync.Once
)

// getMulTable loads and returns the multiply table.
func getMulTable() map[int]*MulEntry {
	mulTableOnce.Do(func() {
		mulTable = make(map[int]*MulEntry)
		// Try well-known paths
		for _, p := range []string{
			os.ExpandEnv("$HOME/dev/minz-vir/mul_table.json"),
			os.ExpandEnv("$HOME/dev/z80-optimizer/mul_table.json"),
			"mul_table.json",
		} {
			data, err := os.ReadFile(p)
			if err != nil {
				continue
			}
			var entries []MulEntry
			if err := json.Unmarshal(data, &entries); err != nil {
				continue
			}
			for i := range entries {
				mulTable[entries[i].K] = &entries[i]
			}
			break
		}
	})
	return mulTable
}

// tryConstMul checks if a MIR2 OpMul has a constant operand and returns
// an inline VIROp sequence from the precomputed table. Returns nil if
// no constant operand or no table entry.
func tryConstMul(inst *mir2.Inst, desc *MachineDesc, w int) []VIROp {
	table := getMulTable()
	if len(table) == 0 {
		return nil
	}

	// Check if Src[1] is a constant (most common: x * K)
	k := int(inst.Imm)
	varSrc := int(inst.Src[0])

	// If Imm is 0, check if this is a reg×reg multiply (can't optimize)
	if k == 0 {
		return nil
	}

	// Safety: these sequences compute A×K mod 256 (8-bit truncated).
	// Only use when the MIR2 instruction is 8-bit width AND the result
	// type is u8. For u16 results (where overflow matters), fall back
	// to the full __mul8 or __mul16 runtime which returns in HL.
	if inst.Ty != nil && inst.Ty.Width() > 8 {
		return nil // needs 16-bit result — use runtime
	}

	entry, ok := table[k]
	if !ok {
		return nil
	}

	// Convert the table's instruction sequence to VIROps.
	// The table assumes: input in A, scratch in B, output in A.
	// We emit: move varSrc → A, then the sequence, result in dst.
	var ops []VIROp

	// Load the variable into a temp vreg that Z3 will assign to A
	srcVreg := varSrc
	dstVreg := int(inst.Dst)

	// Emit the precomputed sequence as an OpAsmBlock (opaque to Z3,
	// it just sees: input=srcVreg, output=dstVreg, clobbers=A,B,F)
	// Build asm template: join instructions with newlines
	asmTemplate := ""
	if dependsOnEntryCarry(entry.Ops) {
		asmTemplate += "    OR A\n"
	}
	for i, op := range entry.Ops {
		if i > 0 {
			asmTemplate += "\n"
		}
		asmTemplate += "    " + op
	}

	clobbers := desc.LocSetByNames("A", "B", "F")
	ops = append(ops, VIROp{
		Op:          OpAsmBlock,
		Dst:         dstVreg,
		Src:         [2]int{srcVreg, -1},
		Width:       w,
		Clobbers:    clobbers,
		DstHint:     desc.LocSetByNames("A"),            // result in A
		SrcHint:     [2]LocSet{desc.LocSetByNames("A")}, // input in A
		AsmTemplate: asmTemplate,
	})

	return ops
}

// Carry classification for the precomputed multiply sequences.
//
// The GPU search that produced these tables fixed CY=0 in its test vectors
// instead of sweeping it, so some sequences begin with a carry-consuming
// instruction and silently inherit the caller's flags. For a * 23 the table
// emits "LD B,A / RLA / ..." — which returns 161 with CY=0 on entry and 169
// with CY=1. Both are "optimal"; only one is correct.
//
// carryConsumers read CY. Reaching one before any definer means the result
// depends on the caller's flags and the block needs an OR A in front.
var carryConsumers = map[string]bool{
	"ADC": true, "SBC": true, "RLA": true, "RRA": true,
	"RL": true, "RR": true, "CCF": true, "DAA": true,
}

// carryDefiners write CY without reading it. Once one has executed, the rest
// of the sequence cannot observe the entry carry, so no guard is needed.
var carryDefiners = map[string]bool{
	"ADD": true, "SUB": true, "AND": true, "OR": true, "XOR": true,
	"CP": true, "NEG": true, "SCF": true,
	"RLCA": true, "RRCA": true, "RLC": true, "RRC": true,
	"SLA": true, "SRA": true, "SRL": true, "SLL": true,
}

// carryTransparent lists mnemonics known not to touch CY. Kept explicit so an
// unfamiliar instruction falls through to the conservative branch in
// dependsOnEntryCarry rather than being silently assumed harmless.
var carryTransparent = map[string]bool{
	"LD": true, "INC": true, "DEC": true, "EX": true, "EXX": true,
	"NOP": true, "CPL": true, "PUSH": true, "BIT": true,
	"SET": true, "RES": true, "HALT": true,
}

// dependsOnEntryCarry reports whether a table sequence observes the carry flag
// as it stood on entry. Transparent instructions are skipped; an unrecognised
// mnemonic is treated as a consumer, since a spurious OR A costs 4T while a
// missing one is a miscompile.
func dependsOnEntryCarry(ops []string) bool {
	for _, op := range ops {
		fields := strings.Fields(op)
		if len(fields) == 0 {
			continue
		}
		m := strings.ToUpper(strings.TrimSuffix(fields[0], ","))
		switch {
		case carryConsumers[m]:
			return true
		case carryDefiners[m]:
			return false
		case carryTransparent[m]:
			continue
		default:
			return true // unknown mnemonic — be safe
		}
	}
	return false
}
