// pipeline.go — VIR module-level codegen entry point.
//
// This is the --vir entry point: MIR2 → VIR → Z3 solver → PIR → ASM.
// Replaces the 5-layer LIR pipeline with a single unified solver pass.
package vir

import (
	"fmt"
	"os"
	"strings"

	"github.com/minz/minzc/pkg/mir2"
)

// FuncResult tracks per-function codegen outcome.
type FuncResult struct {
	Name  string
	OK    bool
	Error string
	ASM   string
}

// CodegenModule runs the VIR unified solver on all functions in a MIR2 module.
// Returns assembly text and per-function results.
func CodegenModule(m *mir2.Module, opts SolverOptions) (string, []FuncResult) {
	var sb strings.Builder
	var results []FuncResult

	sb.WriteString("; generated by VIR unified solver (Z3 joint isel+regalloc)\n\n")

	// Emit main first
	funcs := m.Funcs
	if main := m.FuncByName("main"); main != nil && len(funcs) > 0 && funcs[0].Name != "main" {
		ordered := make([]*mir2.Func, 0, len(funcs))
		ordered = append(ordered, main)
		for _, f := range funcs {
			if f.Name != "main" {
				ordered = append(ordered, f)
			}
		}
		funcs = ordered
	}

	for _, f := range funcs {
		asm, err := CodegenFunc(f, m, opts)
		r := FuncResult{Name: f.Name}
		if err != nil {
			r.Error = err.Error()
			if opts.Verbose {
				fmt.Fprintf(os.Stderr, "[vir] %s: %v\n", f.Name, err)
			}
		} else {
			r.OK = true
			r.ASM = asm
			sb.WriteString(asm)
			sb.WriteByte('\n')
		}
		results = append(results, r)
	}

	return sb.String(), results
}

// CodegenFunc runs the VIR solver on a single MIR2 function.
func CodegenFunc(f *mir2.Func, m *mir2.Module, opts SolverOptions) (string, error) {
	desc := Z80

	// Lower MIR2 → VIR
	vf, err := LowerFunc(f, desc, m)
	if err != nil {
		return "", fmt.Errorf("vir lower %s: %w", f.Name, err)
	}

	var sb strings.Builder

	// Function header
	sb.WriteString(fmt.Sprintf("; %s — VIR codegen\n", f.Name))
	sb.WriteString(f.Name + ":\n")

	// Process each block
	for bi, block := range vf.Blocks {
		if bi > 0 || block.Label != "" {
			if block.Label != "" && block.Label != f.Name {
				sb.WriteString(block.Label + ":\n")
			}
		}

		if len(block.Ops) == 0 {
			continue
		}

		// Run Z3 solver on this block
		pirOps, err := Solve(block.Ops, desc, opts)
		if err != nil {
			return "", fmt.Errorf("vir solve %s/%s: %w", f.Name, block.Label, err)
		}

		// Emit PIROps → ASM
		for _, p := range pirOps {
			line := p.Emit(desc)
			if line == "" {
				continue
			}
			// Handle multi-line templates (e.g., "LD L, A\n    LD H, 0")
			for _, subline := range strings.Split(line, "\n") {
				subline = strings.TrimSpace(subline)
				if subline == "" {
					continue
				}
				if strings.HasPrefix(subline, ";") {
					sb.WriteString("    " + subline + "\n")
				} else {
					sb.WriteString("    " + subline + "\n")
				}
			}
		}
	}

	// Append RET if not already present
	asmText := sb.String()
	trimmed := strings.TrimRight(asmText, " \n\t")
	if !strings.HasSuffix(trimmed, "RET") && !strings.HasSuffix(trimmed, "JP") {
		sb.WriteString("    RET\n")
	}

	return sb.String(), nil
}
