// pipeline.go — VIR module-level codegen entry point.
//
// This is the --vir entry point: MIR2 → VIR → Z3 solver → PIR → ASM.
// Replaces the 5-layer LIR pipeline with a single unified solver pass.
package vir

import (
	"fmt"
	"os"
	"strings"

	"github.com/minz/minzc/pkg/mir2"
)

// FuncResult tracks per-function codegen outcome.
type FuncResult struct {
	Name  string
	OK    bool
	Error string
	ASM   string
}

// CodegenModule runs the VIR unified solver on all functions in a MIR2 module.
// Returns assembly text and per-function results.
func CodegenModule(m *mir2.Module, opts SolverOptions) (string, []FuncResult) {
	var sb strings.Builder
	var results []FuncResult

	// Phase 0: Z3-PFCCO — find optimal calling conventions for all functions.
	// This is interprocedural: Z3 considers all call sites simultaneously.
	pfccoResults, pfccoErr := OptimizePFCCO(m, Z80, PFCCOOptions{
		Z3Path:  opts.Z3Path,
		Timeout: opts.Timeout,
	})
	if pfccoErr == nil && len(pfccoResults) > 0 {
		sb.WriteString("; generated by VIR unified solver (Z3-PFCCO + Z3 joint isel+regalloc)\n")
		sb.WriteString("; calling conventions optimized by Z3 SMT solver\n\n")
		// Store PFCCO results for use by CodegenFunc
		// (currently informational — full wiring TODO)
		for _, pr := range pfccoResults {
			if len(pr.ParamNames) > 0 {
				sb.WriteString(fmt.Sprintf("; %s: params=[%s] ret=%s (Z3-PFCCO)\n",
					pr.FuncName, strings.Join(pr.ParamNames, ","), pr.ReturnName))
			}
		}
		sb.WriteString("\n")
	} else {
		sb.WriteString("; generated by VIR unified solver (Z3 joint isel+regalloc)\n\n")
	}

	// Emit main first
	funcs := m.Funcs
	if main := m.FuncByName("main"); main != nil && len(funcs) > 0 && funcs[0].Name != "main" {
		ordered := make([]*mir2.Func, 0, len(funcs))
		ordered = append(ordered, main)
		for _, f := range funcs {
			if f.Name != "main" {
				ordered = append(ordered, f)
			}
		}
		funcs = ordered
	}

	for _, f := range funcs {
		asm, err := CodegenFunc(f, m, opts)
		r := FuncResult{Name: f.Name}
		if err != nil {
			r.Error = err.Error()
			if opts.Verbose {
				fmt.Fprintf(os.Stderr, "[vir] %s: %v\n", f.Name, err)
			}
		} else {
			r.OK = true
			r.ASM = asm
			sb.WriteString(asm)
			sb.WriteByte('\n')
		}
		results = append(results, r)
	}

	// Emit runtime routines referenced by generated code
	asmText := sb.String()
	if strings.Contains(asmText, "__mul8") || strings.Contains(asmText, "__mul16") ||
		strings.Contains(asmText, "__div8") || strings.Contains(asmText, "__div16") ||
		strings.Contains(asmText, "__mod8") || strings.Contains(asmText, "__mod16") {
		sb.WriteString(emitRuntimeRoutines(asmText))
	}

	// Emit VIR memory spill slots (DW 0 storage for _vir_memN labels)
	asmText = sb.String()
	for i := 0; i < 4; i++ {
		label := fmt.Sprintf("_vir_mem%d", i)
		if strings.Contains(asmText, label) {
			sb.WriteString(fmt.Sprintf("%s: DW 0\n", label))
		}
	}

	return sb.String(), results
}

// emitRuntimeRoutines appends Z80 runtime helper routines referenced by VIR code.
func emitRuntimeRoutines(asm string) string {
	var sb strings.Builder

	if strings.Contains(asm, "__mul8") {
		sb.WriteString(`; __mul8: A = A * B (8-bit multiply, ~80T)
__mul8:
    LD C, A
    XOR A
    LD D, 8
.__mul8_lp:
    SRL C
    JR NC, .__mul8_sk
    ADD A, B
.__mul8_sk:
    SLA B
    DEC D
    JR NZ, .__mul8_lp
    RET
`)
	}

	if strings.Contains(asm, "__mul16") {
		sb.WriteString(`; __mul16: HL = HL * DE (~200T)
__mul16:
    LD B, H
    LD C, L
    LD HL, 0
    LD A, 16
.__mul16_lp:
    SRL B
    RR C
    JR NC, .__mul16_sk
    ADD HL, DE
.__mul16_sk:
    SLA E
    RL D
    DEC A
    JR NZ, .__mul16_lp
    RET
`)
	}

	if strings.Contains(asm, "__div8") {
		// DIVU111 algorithm (Dark / X-Trade, 1997)
		// Input: A=dividend, B=divisor. Output: A=quotient, C=remainder.
		sb.WriteString(`; __div8: A = A / B (quotient), C = remainder
__div8:
    LD C, B
    LD B, A
    XOR A
    LD D, 8
.__div8_lp:
    SLA B
    RLA
    CP C
    JR C, .__div8_sk
    SUB C
    INC B
.__div8_sk:
    DEC D
    JR NZ, .__div8_lp
    LD A, B
    RET
`)
	}

	if strings.Contains(asm, "__mod8") {
		// Uses __div8 internally, returns remainder (A after div loop, before LD A,B)
		sb.WriteString(`; __mod8: A = A mod B
__mod8:
    LD C, B
    LD B, A
    XOR A
    LD D, 8
.__mod8_lp:
    SLA B
    RLA
    CP C
    JR C, .__mod8_sk
    SUB C
    INC B
.__mod8_sk:
    DEC D
    JR NZ, .__mod8_lp
    RET
`)
	}

	if strings.Contains(asm, "__div16") {
		// 16-bit unsigned division: HL / DE → HL=quotient, DE=remainder
		// Shift-and-subtract long division, 16 iterations.
		sb.WriteString(`; __div16: HL = HL / DE (quotient), DE = remainder
__div16:
    LD B, H
    LD C, L
    LD HL, 0
    LD A, 16
.__div16_lp:
    SLA C
    RL B
    ADC HL, HL
    SBC HL, DE
    JR NC, .__div16_sk
    ADD HL, DE
    JR .__div16_noinc
.__div16_sk:
    INC C
.__div16_noinc:
    DEC A
    JR NZ, .__div16_lp
    EX DE, HL
    LD H, B
    LD L, C
    RET
`)
	}

	if strings.Contains(asm, "__mod16") {
		// 16-bit unsigned modulo: HL % DE → HL=remainder
		sb.WriteString(`; __mod16: HL = HL mod DE (remainder)
__mod16:
    LD B, H
    LD C, L
    LD HL, 0
    LD A, 16
.__mod16_lp:
    SLA C
    RL B
    ADC HL, HL
    SBC HL, DE
    JR NC, .__mod16_sk
    ADD HL, DE
.__mod16_sk:
    DEC A
    JR NZ, .__mod16_lp
    RET
`)
	}

	return sb.String()
}

// CodegenFunc runs the VIR solver on a single MIR2 function.
// Uses whole-function Z3 encoding: all blocks flattened into one SMT query.
func CodegenFunc(f *mir2.Func, m *mir2.Module, opts SolverOptions) (string, error) {
	desc := Z80

	// Pre-lower MIR2 optimizations
	mir2.FuseAbsDiff(f) // SUB+CMP → SUB with carry reuse (4 insts vs 11)

	// Lower MIR2 → VIR
	vf, err := LowerFunc(f, desc, m)
	if err != nil {
		return "", fmt.Errorf("vir lower %s: %w", f.Name, err)
	}

	// Deep-copy VIR blocks to avoid stale SrcHint mutations
	vfCopy := deepCopyFunc(vf)

	// Try CFG-aware whole-function solver first
	cfgResult, cfgErr := codegenFuncCFG(f, vfCopy, desc, opts)
	if cfgErr == nil {
		return cfgResult, nil
	}

	// Always log CFG failure for debugging
	fmt.Fprintf(os.Stderr, "[vir] CFG solver failed for %s: %v, falling back to per-block\n", f.Name, cfgErr)

	// Fallback to per-block approach (with fresh copy)
	vfCopy2 := deepCopyFunc(vf)
	return codegenFuncPerBlock(f, vfCopy2, desc, opts)
}

// emitFuncHeader writes the ABI annotation comment for a function.
// Format: ; fun name(p1: type = REG, ...) -> type = REG ; clobbers: REG, ...
func emitFuncHeader(sb *strings.Builder, f *mir2.Func, opts SolverOptions) {
	sb.WriteString("; fun " + f.Name + "(")
	for i, p := range f.Contract.Params {
		if i > 0 {
			sb.WriteString(", ")
		}
		tyName := "u8"
		if p.Ty != nil {
			if p.Ty.Width() > 8 {
				tyName = "u16"
			}
		}
		regName := p.Class.String()
		// Use PBQP allocation if available
		if opts.FuncParamLocs != nil {
			if pl, ok := opts.FuncParamLocs[f.Name]; ok {
				if phys, ok2 := pl[int(p.Reg)]; ok2 && phys < len(Z80.Locs) {
					regName = Z80.Locs[phys].Name
				}
			}
		}
		sb.WriteString(fmt.Sprintf("%s: %s = %s", p.Name, tyName, regName))
	}
	sb.WriteString(")")
	if len(f.Contract.Returns) > 0 {
		r := f.Contract.Returns[0]
		retReg := "A"
		if r.Ty != nil && r.Ty.Width() > 8 {
			retReg = "HL"
		}
		tyName := "u8"
		if r.Ty != nil && r.Ty.Width() > 8 {
			tyName = "u16"
		}
		sb.WriteString(fmt.Sprintf(" -> %s = %s", tyName, retReg))
	}
	sb.WriteString(" ; clobbers: F\n")
}

// deepCopyFunc creates a deep copy of a VIR Func to avoid stale mutations.
func deepCopyFunc(vf *Func) *Func {
	cp := &Func{Name: vf.Name}
	for _, b := range vf.Blocks {
		ops := make([]VIROp, len(b.Ops))
		for i, op := range b.Ops {
			ops[i] = op
			// Reset hints to prevent stale mutations from previous runs
			ops[i].SrcHint = [2]LocSet{}
		}
		cp.Blocks = append(cp.Blocks, Block{Label: b.Label, Ops: ops})
	}
	return cp
}

// codegenFuncCFG uses the CFG-aware solver: per-block variables with edge constraints.
func codegenFuncCFG(f *mir2.Func, vf *Func, desc *MachineDesc, opts SolverOptions) (string, error) {
	// Param hints are passed via opts and applied inside SolveCFG
	// AFTER pre-solver passes (which may rewrite vreg references).
	blockPIR, err := SolveCFG(vf, f, desc, opts)
	if err != nil {
		return "", err
	}

	// Emit assembly
	var sb strings.Builder
	emitFuncHeader(&sb, f, opts)
	sb.WriteString(f.Name + ":\n")

	for bi, block := range vf.Blocks {
		label := block.Label
		if bi > 0 && label != "" {
			sb.WriteString("." + f.Name + "_" + label + ":\n")
		}

		pirOps := blockPIR[label]
		for _, p := range pirOps {
			line := p.Emit(desc)
			if !isSelfMove(line) {
				emitLine(&sb, line)
			}
		}

		if bi < len(f.Blocks) {
			emitTerminator(&sb, f.Blocks[bi], f.Name)
		}
	}

	return peepholeCleanup(sb.String()), nil
}

// codegenFuncWhole solves ALL blocks of a function in one Z3 query.
// Cross-block register state is handled automatically via per-instruction variables.
func codegenFuncWhole(f *mir2.Func, vf *Func, desc *MachineDesc, opts SolverOptions) (string, error) {
	// Flatten all blocks into one VIROp sequence, tracking block boundaries
	var allOps []VIROp
	type blockRange struct {
		label string
		start int
		end   int
	}
	var ranges []blockRange

	// Seed param locations from PBQP (if available)
	paramHints := make(map[int]int) // vreg → phys
	if opts.FuncParamLocs != nil {
		if pl, ok := opts.FuncParamLocs[f.Name]; ok {
			for v, p := range pl {
				paramHints[v] = p
			}
		}
	}
	for v, p := range opts.ParamLocs {
		if _, ok := paramHints[v]; !ok {
			paramHints[v] = p
		}
	}

	// Apply param SrcHints to first block's ops
	for bi, block := range vf.Blocks {
		start := len(allOps)

		if bi == 0 && len(paramHints) > 0 {
			for i := range block.Ops {
				for j, s := range block.Ops[i].Src {
					if s > 0 {
						if phys, ok := paramHints[s]; ok {
							block.Ops[i].SrcHint[j] = Singleton(phys)
						}
					}
				}
			}
		}

		allOps = append(allOps, block.Ops...)
		ranges = append(ranges, blockRange{block.Label, start, len(allOps)})
	}

	if len(allOps) == 0 {
		// Empty function
		var sb strings.Builder
		sb.WriteString(fmt.Sprintf("; %s — VIR codegen\n", f.Name))
		sb.WriteString(f.Name + ":\n    RET\n")
		return sb.String(), nil
	}

	// Solve entire function as one block
	pirOps, err := Solve(allOps, desc, opts)
	if err != nil {
		return "", err
	}

	// Simplest approach: emit ALL PIROps as one flat sequence,
	// with block labels and terminators injected based on block boundaries.
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("; %s — VIR codegen\n", f.Name))
	sb.WriteString(f.Name + ":\n")

	// Emit all PIROps (the solver handled cross-block register state)
	for _, p := range pirOps {
		line := p.Emit(desc)
		if !isSelfMove(line) {
			emitLine(&sb, line)
		}
	}

	// Now emit terminators for ALL blocks
	// The terminators provide control flow (JR/JP/RET) between blocks.
	// They reference block labels which we emit as well.
	for bi, br := range ranges {
		if bi > 0 && br.label != "" {
			// Insert label — but where? The flat PIR already has the instructions.
			// We need labels BEFORE the block's instructions.
			// This flat approach can't easily insert labels mid-stream.
			// Use a different strategy: just emit terminators at the end.
			_ = br
		}
		if bi < len(f.Blocks) {
			_ = f.Blocks[bi] // terminator
		}
	}

	// Actually: the flat approach without labels won't work for branching.
	// Fall back to per-block emission with the whole-function PIROps.
	// We know the original VIROp count per block, and PIROps include
	// inserted moves. Let's emit block-by-block using a PIROp cursor.
	sb.Reset()
	sb.WriteString(fmt.Sprintf("; %s — VIR codegen\n", f.Name))
	sb.WriteString(f.Name + ":\n")

	// Simple heuristic: the number of PIROps per block equals
	// original ops + (PIROps total - original ops total) distributed.
	// Since most moves are for the block that needs them, we can
	// just emit ALL PIROps first, then all labels+terminators.
	// But this doesn't work for branching.

	// Best approach: reconstruct block structure from the flat PIR.
	// Use the original op count as guide, emit extra PIROps with the
	// block they belong to.

	pirCursor := 0
	for bi, br := range ranges {
		if bi > 0 && br.label != "" {
			sb.WriteString("." + f.Name + "_" + br.label + ":\n")
		}

		blockOrigOps := br.end - br.start
		// Emit PIROps: each original op may have 0-2 move PIROps before it
		for k := 0; k < blockOrigOps && pirCursor < len(pirOps); {
			p := pirOps[pirCursor]
			line := p.Emit(desc)
			if !isSelfMove(line) {
				emitLine(&sb, line)
			}
			pirCursor++

			// Count: if this PIROp matches a non-move original op, advance k
			if p.Pat != nil && p.Pat.Op != OpMove {
				k++
			} else if p.Pat != nil && p.Pat.Op == OpMove {
				// Check if the original op at this position was also a move
				origOpIdx := br.start + k
				if origOpIdx < len(allOps) && allOps[origOpIdx].Op == OpMove {
					k++ // original move, advance
				}
				// else: inserted move, don't advance k
			}
		}

		if bi < len(f.Blocks) {
			emitTerminator(&sb, f.Blocks[bi], f.Name)
		}
	}

	// Emit any remaining PIROps (shouldn't happen normally)
	for pirCursor < len(pirOps) {
		line := pirOps[pirCursor].Emit(desc)
		if !isSelfMove(line) {
			emitLine(&sb, line)
		}
		pirCursor++
	}

	return peepholeCleanup(sb.String()), nil
}

// codegenFuncPerBlock is the original per-block solver (fallback).
func codegenFuncPerBlock(f *mir2.Func, vf *Func, desc *MachineDesc, opts SolverOptions) (string, error) {

	var sb strings.Builder

	// Function header with ABI annotation
	emitFuncHeader(&sb, f, opts)
	sb.WriteString(f.Name + ":\n")

	// Track vreg → physical register across blocks.
	// Seed with ParamLocs from PBQP allocation (if available).
	vregPhys := make(map[int]int)
	// Per-function param locs (priority)
	if opts.FuncParamLocs != nil {
		if pl, ok := opts.FuncParamLocs[f.Name]; ok {
			for vreg, phys := range pl {
				vregPhys[vreg] = phys
			}
		}
	}
	// Global param locs (fallback)
	for vreg, phys := range opts.ParamLocs {
		if _, ok := vregPhys[vreg]; !ok {
			vregPhys[vreg] = phys
		}
	}

	// Process each block — emit PIROps + terminator
	for bi, block := range vf.Blocks {
		// Block label (prefix with function name for uniqueness)
		label := block.Label
		if bi == 0 {
			// First block = function entry, label already emitted
		} else if label != "" {
			sb.WriteString("." + f.Name + "_" + label + ":\n")
		}

		// For non-entry blocks: apply known vreg locations as SrcHint
		// so the solver knows where cross-block vregs live.
		// Cross-block register awareness:
		if len(vregPhys) > 0 {
			if bi == 0 {
				// Entry block: hard SrcHint on ALL ops (params MUST match ABI)
				for i := range block.Ops {
					for j, s := range block.Ops[i].Src {
						if s > 0 {
							if phys, ok := vregPhys[s]; ok {
								block.Ops[i].SrcHint[j] = Singleton(phys)
							}
						}
					}
				}
			} else {
				// Non-entry blocks: inject pin moves at block start.
				// Each pin defines where a cross-block vreg lives.
				// The per-instruction solver can then insert moves as needed.
				var pins []VIROp
				pinMap := make(map[int]int) // original vreg → pin vreg
				nextPin := 8500

				// Collect cross-block vregs used in this block
				used := make(map[int]bool)
				for _, op := range block.Ops {
					for _, s := range op.Src {
						if s > 0 { used[s] = true }
					}
				}

				for vreg := range used {
					phys, ok := vregPhys[vreg]
					if !ok { continue }
					// Skip if vreg is defined in this block
					definedHere := false
					for _, op := range block.Ops {
						if op.Dst == vreg { definedHere = true; break }
					}
					if definedHere { continue }

					pinReg := nextPin
					nextPin++
					pinMap[vreg] = pinReg

					// Pin: "pinReg lives in phys register, loaded from vreg"
					w := 8
					for _, op := range block.Ops {
						for _, s := range op.Src {
							if s == vreg && op.Width > 0 { w = op.Width }
						}
					}
					// Pin: source vreg is in phys (hard SrcHint).
				// Destination is UNCONSTRAINED — solver picks optimal register.
				// Per-inst solver can then move from phys to wherever needed.
				pins = append(pins, VIROp{
						Op: OpMove, Dst: pinReg,
						Src: [2]int{vreg, -1}, Width: w,
						SrcHint: [2]LocSet{Singleton(phys)},
						// No DstHint — let solver freely place the pin
					})
				}

				// Rewrite block ops: replace cross-block vregs with pin vregs
				if len(pins) > 0 {
					for i := range block.Ops {
						for j, s := range block.Ops[i].Src {
							if pin, ok := pinMap[s]; ok {
								block.Ops[i].Src[j] = pin
							}
						}
					}
					block.Ops = append(pins, block.Ops...)
				}
			}
		}

		// Solve block ops
		if len(block.Ops) > 0 {
			pirOps, err := Solve(block.Ops, desc, opts)
			if err != nil {
				return "", fmt.Errorf("vir solve %s/%s: %w", f.Name, block.Label, err)
			}

			// Record vreg → physical register from solution.
			// DON'T overwrite PBQP param locations — those are the ABI truth.
			paramVRegs := make(map[int]bool)
			if opts.FuncParamLocs != nil {
				if pl, ok := opts.FuncParamLocs[f.Name]; ok {
					for v := range pl { paramVRegs[v] = true }
				}
			}
			for v := range opts.ParamLocs { paramVRegs[v] = true }

			for k, p := range pirOps {
				if k < len(block.Ops) {
					op := block.Ops[k]
					if op.Dst > 0 && p.DstPhys >= 0 && !paramVRegs[op.Dst] {
						vregPhys[op.Dst] = p.DstPhys
					}
					for j, s := range op.Src {
						if s > 0 && p.SrcPhys[j] >= 0 && !paramVRegs[s] {
							vregPhys[s] = p.SrcPhys[j]
						}
					}
				}
			}

			for _, p := range pirOps {
				line := p.Emit(desc)
				if isSelfMove(line) {
					continue
				}
				emitLine(&sb, line)
			}
		}

		// Emit terminator (control flow between blocks)
		if bi < len(f.Blocks) {
			mir2Block := f.Blocks[bi]
			emitTerminator(&sb, mir2Block, f.Name)
		}
	}

	// Apply peephole cleanup (PUSH/POP, fallthrough, LD A,0→XOR A, etc.)
	return peepholeCleanup(sb.String()), nil
}

// emitLine writes one or more assembly lines (handles multi-line templates).
func emitLine(sb *strings.Builder, line string) {
	if line == "" {
		return
	}
	for _, subline := range strings.Split(line, "\n") {
		subline = strings.TrimSpace(subline)
		if subline != "" {
			sb.WriteString("    " + subline + "\n")
		}
	}
}

// emitTerminator generates Z80 control flow instructions for a MIR2 block terminator.
func emitTerminator(sb *strings.Builder, b *mir2.Block, funcName string) {
	if b.Term == nil {
		return
	}
	prefix := "." + funcName + "_"

	switch t := b.Term.(type) {
	case *mir2.TermRet:
		sb.WriteString("    RET\n")

	case *mir2.TermJmp:
		sb.WriteString(fmt.Sprintf("    JP %s%s\n", prefix, t.Target))

	case *mir2.TermBrIf:
		// Find the CMP that defined the condition vreg to determine flag semantics
		cmpCond := findCmpCond(b, t.Cond)
		elseLabel := prefix + t.Else

		// Emit branch based on comparison kind:
		// CP sets Z (equal) and C (a < b unsigned)
		switch cmpCond {
		case mir2.CmpUgt: // a > b: skip to else if Z or C
			sb.WriteString(fmt.Sprintf("    JR Z, %s\n", elseLabel))
			sb.WriteString(fmt.Sprintf("    JR C, %s\n", elseLabel))
			// fall through = then (a > b)
		case mir2.CmpUlt: // a < b: skip to else if NC (a >= b)
			sb.WriteString(fmt.Sprintf("    JR NC, %s\n", elseLabel))
			// fall through = then (a < b, C set)
		case mir2.CmpUge: // a >= b: skip to else if C (a < b)
			sb.WriteString(fmt.Sprintf("    JR C, %s\n", elseLabel))
		case mir2.CmpUle: // a <= b: skip to else if not Z and NC
			sb.WriteString(fmt.Sprintf("    JR Z, %s%s\n", prefix, t.Then))
			sb.WriteString(fmt.Sprintf("    JR NC, %s\n", elseLabel))
		case mir2.CmpEq: // a == b
			sb.WriteString(fmt.Sprintf("    JR NZ, %s\n", elseLabel))
		case mir2.CmpNe: // a != b
			sb.WriteString(fmt.Sprintf("    JR Z, %s\n", elseLabel))
		case mir2.CmpSubCarry: // carry set by preceding SUB means a < b
			sb.WriteString(fmt.Sprintf("    JR NC, %s\n", elseLabel))
			// fall through = then (a < b, carry set)
		case mir2.CmpSubCarryNot: // no carry means a >= b
			sb.WriteString(fmt.Sprintf("    JR C, %s\n", elseLabel))
		default:
			// Generic: treat as NZ (bool condition)
			sb.WriteString(fmt.Sprintf("    JR NZ, %s%s\n", prefix, t.Then))
			if t.Else != "" {
				sb.WriteString(fmt.Sprintf("    JP %s\n", elseLabel))
			}
			return
		}
		// Fall-through to Then block (or explicit jump if blocks aren't adjacent)
		sb.WriteString(fmt.Sprintf("    JP %s%s\n", prefix, t.Then))

	case *mir2.TermBrIf2:
		// Two-way branch based on comparison result
		// Lhs vs Rhs already compared, flags set
		if t.Eq != "" && t.Lt == "" && t.Gt == "" {
			// Simple equality check
			sb.WriteString(fmt.Sprintf("    JR Z, %s%s\n", prefix, t.Eq))
		} else {
			// Full three-way
			if t.Eq != "" {
				sb.WriteString(fmt.Sprintf("    JR Z, %s%s\n", prefix, t.Eq))
			}
			if t.Lt != "" {
				sb.WriteString(fmt.Sprintf("    JR C, %s%s\n", prefix, t.Lt))
			}
			if t.Gt != "" {
				sb.WriteString(fmt.Sprintf("    JP %s%s\n", prefix, t.Gt))
			}
		}

	case *mir2.TermDJNZ:
		sb.WriteString(fmt.Sprintf("    DJNZ %s%s\n", prefix, t.Body))
		if t.Exit != "" {
			sb.WriteString(fmt.Sprintf("    JP %s%s\n", prefix, t.Exit))
		}

	case *mir2.TermCondRet:
		// If cond==0, return vals. Else jump to Then.
		cmpCond := findCmpCond(b, t.Cond)
		if t.Then != "" {
			switch cmpCond {
			case mir2.CmpSubCarry:
				// Carry set by preceding SUB means a < b → RET NC (return if a >= b)
				sb.WriteString(fmt.Sprintf("    JR C, %s%s\n", prefix, t.Then))
			case mir2.CmpSubCarryNot:
				sb.WriteString(fmt.Sprintf("    JR NC, %s%s\n", prefix, t.Then))
			default:
				// Generic: Z flag = equal/zero → jump when NZ
				sb.WriteString(fmt.Sprintf("    JR NZ, %s%s\n", prefix, t.Then))
			}
		}
		sb.WriteString("    RET\n")

	case *mir2.TermUnreachable:
		sb.WriteString("    ; unreachable\n")
	}
}

// findCmpCond looks up the CmpCond of the OpCmp instruction that defines
// the given condition vreg. Returns -1 if not found.
func findCmpCond(b *mir2.Block, condReg mir2.Reg) mir2.CmpCond {
	for i := len(b.Insts) - 1; i >= 0; i-- {
		inst := b.Insts[i]
		if inst.Op == mir2.OpCmp && inst.Dst == condReg {
			return inst.Cond
		}
	}
	return mir2.CmpCond(255) // not found
}

// ── Peephole ────────────────────────────────────────────────────────────────

// isSelfMove detects Z80 no-op moves that can be eliminated:
//   LD A, A    — register self-copy
//   PUSH HL / POP HL  — stack self-move (from coalescing artifacts)
//   ; trunc ... (alias) — zero-cost aliases (already no instruction)
func isSelfMove(line string) bool {
	line = strings.TrimSpace(line)
	if line == "" {
		return false
	}

	// LD r, r (self-copy): LD A, A / LD B, B / etc.
	if strings.HasPrefix(line, "LD ") {
		parts := strings.SplitN(line[3:], ", ", 2)
		if len(parts) == 2 && strings.TrimSpace(parts[0]) == strings.TrimSpace(parts[1]) {
			return true
		}
	}

	// PUSH r / POP r on consecutive lines (handled as multi-line template)
	if strings.HasPrefix(line, "PUSH ") {
		// Check if next part is POP with same register
		// Multi-line templates are split before reaching here, so check single lines
	}

	return false
}

// peepholeCleanup applies additional Z80 peephole optimizations.
// Inspired by SDCC's peephole rules (https://sdcc.sourceforge.net/).
func peepholeCleanup(asm string) string {
	lines := strings.Split(asm, "\n")
	var result []string
	inlineCounter := 0

	for i := 0; i < len(lines); i++ {
		line := strings.TrimSpace(lines[i])

		// PUSH rr / POP rr → remove both (self-move via stack)
		if i+1 < len(lines) && strings.HasPrefix(line, "PUSH ") {
			next := strings.TrimSpace(lines[i+1])
			reg := strings.TrimPrefix(line, "PUSH ")
			if next == "POP "+reg {
				i++ // skip both lines
				continue
			}
		}

		// JP label where label is the very next line → remove (fallthrough)
		if strings.HasPrefix(line, "JP ") {
			target := strings.TrimPrefix(line, "JP ")
			target = strings.TrimSpace(target)
			if i+1 < len(lines) {
				nextLine := strings.TrimSpace(lines[i+1])
				// Next line is "target:" label
				if nextLine == target+":" || nextLine == "."+target+":" {
					continue // skip redundant jump
				}
			}
		}

		// LD A, 0 → XOR A (1 byte shorter, faster)
		if line == "LD A, 0" {
			result = append(result, "    XOR A")
			continue
		}

		// CP 0 → OR A (sets Z flag same way, 1 byte shorter)
		if line == "CP 0" {
			result = append(result, "    OR A")
			continue
		}

		// ── Superoptimizer-derived rules (z80-optimizer/CUDA) ────────

		// CALL label / RET → JP label (tail call optimization, saves 1 byte + 17T)
		if i+1 < len(lines) && strings.HasPrefix(line, "CALL ") {
			next := strings.TrimSpace(lines[i+1])
			if next == "RET" {
				target := strings.TrimPrefix(line, "CALL ")
				result = append(result, "    JP "+target)
				i++ // skip RET
				continue
			}
		}

		// Inline runtime calls — replace CALL __div8/mod8/mul8 with inline body.
		// Each instance gets a unique label suffix. Dedup'd in post-pass.
		if strings.HasPrefix(line, "CALL __div8") || strings.HasPrefix(line, "JP __div8") {
			idx := inlineCounter
			inlineCounter++
			result = append(result,
				"    LD C, B",
				"    LD B, A",
				"    XOR A",
				"    LD D, 8",
				fmt.Sprintf(".vir_div8_%d:", idx),
				"    SLA B",
				"    RLA",
				"    CP C",
				fmt.Sprintf("    JR C, .vir_div8_sk_%d", idx),
				"    SUB C",
				"    INC B",
				fmt.Sprintf(".vir_div8_sk_%d:", idx),
				"    DEC D",
				fmt.Sprintf("    JR NZ, .vir_div8_%d", idx),
				"    LD A, B",  // A = quotient
			)
			// Skip subsequent LD A, r (return-move — result already in A)
			if i+1 < len(lines) {
				next := strings.TrimSpace(lines[i+1])
				if strings.HasPrefix(next, "LD A, ") && next != "LD A, B" {
					i++ // skip redundant return move
				}
			}
			continue
		}
		if strings.HasPrefix(line, "CALL __mod8") || strings.HasPrefix(line, "JP __mod8") {
			idx := inlineCounter
			inlineCounter++
			result = append(result,
				"    LD C, B",
				"    LD B, A",
				"    XOR A",
				"    LD D, 8",
				fmt.Sprintf(".vir_mod8_%d:", idx),
				"    SLA B",
				"    RLA",
				"    CP C",
				fmt.Sprintf("    JR C, .vir_mod8_sk_%d", idx),
				"    SUB C",
				"    INC B",
				fmt.Sprintf(".vir_mod8_sk_%d:", idx),
				"    DEC D",
				fmt.Sprintf("    JR NZ, .vir_mod8_%d", idx),
			)
			if i+1 < len(lines) {
				next := strings.TrimSpace(lines[i+1])
				if strings.HasPrefix(next, "LD A, ") { i++ }
			}
			continue
		}
		if strings.HasPrefix(line, "CALL __mul8") || strings.HasPrefix(line, "JP __mul8") {
			idx := inlineCounter
			inlineCounter++
			result = append(result,
				"    LD C, A",
				"    XOR A",
				"    LD D, 8",
				fmt.Sprintf(".vir_mul8_%d:", idx),
				"    SRL C",
				fmt.Sprintf("    JR NC, .vir_mul8_sk_%d", idx),
				"    ADD A, B",
				fmt.Sprintf(".vir_mul8_sk_%d:", idx),
				"    SLA B",
				"    DEC D",
				fmt.Sprintf("    JR NZ, .vir_mul8_%d", idx),
			)
			if i+1 < len(lines) {
				next := strings.TrimSpace(lines[i+1])
				if strings.HasPrefix(next, "LD A, ") { i++ }
			}
			continue
		}

		// Inline 16-bit runtime calls
		if strings.HasPrefix(line, "CALL __div16") || strings.HasPrefix(line, "JP __div16") {
			idx := inlineCounter
			inlineCounter++
			result = append(result,
				"    LD B, H",
				"    LD C, L",
				"    LD HL, 0",
				"    LD A, 16",
				fmt.Sprintf(".vir_div16_%d:", idx),
				"    SLA C",
				"    RL B",
				"    ADC HL, HL",
				"    SBC HL, DE",
				fmt.Sprintf("    JR NC, .vir_div16_sk_%d", idx),
				"    ADD HL, DE",
				fmt.Sprintf("    JR .vir_div16_ni_%d", idx),
				fmt.Sprintf(".vir_div16_sk_%d:", idx),
				"    INC C",
				fmt.Sprintf(".vir_div16_ni_%d:", idx),
				"    DEC A",
				fmt.Sprintf("    JR NZ, .vir_div16_%d", idx),
				"    EX DE, HL",   // DE = remainder
				"    LD H, B",     // HL = quotient
				"    LD L, C",
			)
			continue
		}
		if strings.HasPrefix(line, "CALL __mod16") || strings.HasPrefix(line, "JP __mod16") {
			idx := inlineCounter
			inlineCounter++
			result = append(result,
				"    LD B, H",
				"    LD C, L",
				"    LD HL, 0",
				"    LD A, 16",
				fmt.Sprintf(".vir_mod16_%d:", idx),
				"    SLA C",
				"    RL B",
				"    ADC HL, HL",
				"    SBC HL, DE",
				fmt.Sprintf("    JR NC, .vir_mod16_sk_%d", idx),
				"    ADD HL, DE",
				fmt.Sprintf(".vir_mod16_sk_%d:", idx),
				"    DEC A",
				fmt.Sprintf("    JR NZ, .vir_mod16_%d", idx),
			)
			continue
		}
		if strings.HasPrefix(line, "CALL __mul16") || strings.HasPrefix(line, "JP __mul16") {
			idx := inlineCounter
			inlineCounter++
			result = append(result,
				"    LD B, H",
				"    LD C, L",
				"    LD HL, 0",
				"    LD A, 16",
				fmt.Sprintf(".vir_mul16_%d:", idx),
				"    SRL B",
				"    RR C",
				fmt.Sprintf("    JR NC, .vir_mul16_sk_%d", idx),
				"    ADD HL, DE",
				fmt.Sprintf(".vir_mul16_sk_%d:", idx),
				"    SLA E",
				"    RL D",
				"    DEC A",
				fmt.Sprintf("    JR NZ, .vir_mul16_%d", idx),
			)
			continue
		}

		// LD r, r (self-move) — also catch at peephole level
		if strings.HasPrefix(line, "LD ") {
			parts := strings.SplitN(line[3:], ", ", 2)
			if len(parts) == 2 && strings.TrimSpace(parts[0]) == strings.TrimSpace(parts[1]) {
				continue // remove self-move
			}
		}

		// ADD A, 0 → remove (no effect, just sets flags)
		if line == "ADD A, 0" {
			continue
		}

		// SUB 0 → remove
		if line == "SUB 0" {
			continue
		}

		// LD A, r / LD r, A → remove second (redundant store-back)
		if i+1 < len(lines) && strings.HasPrefix(line, "LD A, ") {
			src := strings.TrimPrefix(line, "LD A, ")
			next := strings.TrimSpace(lines[i+1])
			if next == "LD "+src+", A" {
				result = append(result, lines[i]) // keep first LD
				i++                                // skip second
				continue
			}
		}

		// LD r, A / LD A, r → remove second (redundant reload)
		if i+1 < len(lines) && strings.HasPrefix(line, "LD ") && strings.HasSuffix(line, ", A") {
			reg := strings.TrimSuffix(strings.TrimPrefix(line, "LD "), ", A")
			reg = strings.TrimSpace(reg)
			next := strings.TrimSpace(lines[i+1])
			if next == "LD A, "+reg {
				result = append(result, lines[i]) // keep first LD
				i++                                // skip second
				continue
			}
		}

		// OR A / OR A → remove duplicate (idempotent)
		if i+1 < len(lines) && line == "OR A" {
			next := strings.TrimSpace(lines[i+1])
			if next == "OR A" {
				result = append(result, lines[i]) // keep one
				i++                                // skip duplicate
				continue
			}
		}

		// XOR A / LD A, 0 → keep only XOR A (both set A=0)
		if i+1 < len(lines) && line == "XOR A" {
			next := strings.TrimSpace(lines[i+1])
			if next == "LD A, 0" || next == "XOR A" {
				result = append(result, lines[i])
				i++
				continue
			}
		}

		// ── Codegen suboptimality fixes ──────────────────────────────

		// LD r, N / INC A / RET → INC A / RET (dead const, only when RET follows)
		if i+2 < len(lines) && strings.HasPrefix(line, "LD ") && !strings.HasPrefix(line, "LD A,") {
			next := strings.TrimSpace(lines[i+1])
			next2 := strings.TrimSpace(lines[i+2])
			if (next == "INC A" || next == "DEC A") && next2 == "RET" {
				parts := strings.SplitN(line[3:], ", ", 2)
				if len(parts) == 2 && strings.TrimSpace(parts[0]) != "A" {
					continue // skip dead const load
				}
			}
		}

		// LD r, N / LD A, r → LD A, N (const through intermediate, only for immediates)
		if i+1 < len(lines) && strings.HasPrefix(line, "LD ") && !strings.HasPrefix(line, "LD A,") {
			parts := strings.SplitN(line[3:], ", ", 2)
			if len(parts) == 2 {
				reg := strings.TrimSpace(parts[0])
				imm := strings.TrimSpace(parts[1])
				next := strings.TrimSpace(lines[i+1])
				// Only merge when imm is a numeric constant (not a register name)
				isImm := len(imm) > 0 && (imm[0] >= '0' && imm[0] <= '9')
				if next == "LD A, "+reg && isImm {
					result = append(result, "    LD A, "+imm)
					i++
					continue
				}
			}
		}

		// XOR A / SUB r → NEG (when input was in A, 0-x = negate)
		// Actually: XOR A sets A=0, then SUB r = 0-r = -r = NEG if r had the value
		// This is tricky — only valid if the SUB source had the original A value.
		// Skip for now — needs more context.

		// ── Grace-like CFG rules (on assembly level) ─────────────────

		// Conditional RET: JR/JP cc, .target / [labels...] / RET / .target: → RET cc_inverted
		// Also handles: JR/JP cc, .target / [labels...] / RET / [labels...] / .target:
		// This is a massive win — saves 2 instructions per conditional return.
		if (strings.HasPrefix(line, "JR ") || strings.HasPrefix(line, "JP ")) &&
			!strings.HasPrefix(line, "JR .") && !strings.HasPrefix(line, "JP .") &&
			!strings.HasPrefix(line, "JP (") {
			prefix := "JR "
			if strings.HasPrefix(line, "JP ") {
				prefix = "JP "
			}
			rest := strings.TrimPrefix(line, prefix)
			if commaIdx := strings.Index(rest, ", "); commaIdx > 0 {
				cc := strings.TrimSpace(rest[:commaIdx])
				target := strings.TrimSpace(rest[commaIdx+2:])
				// Scan forward: skip labels, find RET, then find target label
				retIdx := -1
				for j := i + 1; j < len(lines) && j <= i+4; j++ {
					t := strings.TrimSpace(lines[j])
					if t == "" || strings.HasSuffix(t, ":") || strings.HasPrefix(t, ";") {
						continue // skip labels, comments, empty
					}
					if t == "RET" {
						retIdx = j
						break
					}
					break // non-label, non-RET instruction → stop
				}
				if retIdx > 0 {
					// Now find target label after RET
					targetIdx := -1
					for j := retIdx + 1; j < len(lines) && j <= retIdx+3; j++ {
						t := strings.TrimSpace(lines[j])
						if t == "" || strings.HasPrefix(t, ";") {
							continue
						}
						if t == target+":" {
							targetIdx = j
							break
						}
						if strings.HasSuffix(t, ":") {
							continue // other labels, keep scanning
						}
						break // instruction → stop
					}
					if targetIdx > 0 {
						invCC := invertCC(cc)
						if invCC != "" {
							result = append(result, "    RET "+invCC)
							i = targetIdx - 1 // skip up to target label; label preserved on next iteration
							continue
						}
					}
				}
			}
		}

		// Duplicate CP elimination: CP r / JR cc, label / [labels...] / CP r → skip second CP
		// JR and labels don't modify flags, so the second CP is redundant on fall-through.
		if strings.HasPrefix(line, "CP ") {
			operand := strings.TrimPrefix(line, "CP ")
			// Look back: was the previous non-label, non-comment instruction a JR cc?
			// And before that, was there a CP with the same operand?
			prevCPIdx := -1
			allFlagsSafe := true
			for j := len(result) - 1; j >= 0 && j >= len(result)-4; j-- {
				prev := strings.TrimSpace(result[j])
				if prev == "" || strings.HasSuffix(prev, ":") || strings.HasPrefix(prev, ";") {
					continue // labels/comments don't touch flags
				}
				if strings.HasPrefix(prev, "JR ") {
					continue // JR reads but doesn't modify flags
				}
				if prev == "CP "+operand {
					prevCPIdx = j
					break
				}
				allFlagsSafe = false // some other instruction modifies flags
				break
			}
			if prevCPIdx >= 0 && allFlagsSafe {
				continue // skip redundant CP
			}
		}

		// Dead LD elimination: LD r, X / LD r, Y → remove first (same dest, first is dead)
		// Only for single registers, not memory or pairs
		if i+1 < len(lines) && strings.HasPrefix(line, "LD ") {
			parts := strings.SplitN(line[3:], ", ", 2)
			if len(parts) == 2 {
				dst := strings.TrimSpace(parts[0])
				nextLine := strings.TrimSpace(lines[i+1])
				if strings.HasPrefix(nextLine, "LD ") && !strings.HasPrefix(dst, "(") {
					nextParts := strings.SplitN(nextLine[3:], ", ", 2)
					if len(nextParts) == 2 {
						nextDst := strings.TrimSpace(nextParts[0])
						if dst == nextDst && len(dst) <= 3 && !strings.HasPrefix(dst, "(") {
							continue // skip first LD — dead store
						}
					}
				}
			}
		}

		// Reverse-copy elimination: LD X, Y / LD Y, X → keep only first
		if i+1 < len(lines) && strings.HasPrefix(line, "LD ") {
			parts := strings.SplitN(line[3:], ", ", 2)
			if len(parts) == 2 {
				a := strings.TrimSpace(parts[0])
				b := strings.TrimSpace(parts[1])
				nextLine := strings.TrimSpace(lines[i+1])
				if nextLine == "LD "+b+", "+a {
					result = append(result, lines[i]) // keep first
					i++                                // skip second
					continue
				}
			}
		}

		result = append(result, lines[i])
	}

	// Second pass: remove consecutive duplicate labels
	var pass2 []string
	for i, line := range result {
		// Skip empty lines between labels
		trimmed := strings.TrimSpace(line)
		if trimmed == "" && i+1 < len(result) && strings.HasSuffix(strings.TrimSpace(result[i+1]), ":") {
			continue
		}
		pass2 = append(pass2, line)
	}

	// Grace pass: multi-instruction CFG-aware optimizations
	pass3 := gracePass(pass2)

	return strings.Join(pass3, "\n")
}

// gracePass applies Grace-like CFG pattern rules on Z80 assembly.
// These are multi-instruction patterns that the simple peephole can't catch.
// invertCC returns the inverted Z80 condition code, or "" if unknown.
func invertCC(cc string) string {
	switch strings.ToUpper(cc) {
	case "Z":
		return "NZ"
	case "NZ":
		return "Z"
	case "C":
		return "NC"
	case "NC":
		return "C"
	case "PE":
		return "PO"
	case "PO":
		return "PE"
	case "M":
		return "P"
	case "P":
		return "M"
	default:
		return ""
	}
}

// fuseAbsDiffASM detects the abs_diff pattern in assembly and rewrites to SUB/RET NC/NEG/RET.
// Pattern: CP r / JR Z+JR C → block1(a-b, RET) / block2(b-a, RET)
// Replacement: SUB r / RET NC / NEG / RET (4 instructions)
func fuseAbsDiffASM(lines []string) []string {
	for i := 0; i < len(lines)-5; i++ {
		l := strings.TrimSpace(lines[i])
		// Look for: CP r (where r is a single register)
		if !strings.HasPrefix(l, "CP ") {
			continue
		}
		reg := strings.TrimPrefix(l, "CP ")
		reg = strings.TrimSpace(reg)
		if len(reg) == 0 || len(reg) > 3 || strings.Contains(reg, "(") {
			continue
		}

		// Next two lines must be: JR Z, .label / JR C, .label (same label)
		l1 := strings.TrimSpace(lines[i+1])
		l2 := strings.TrimSpace(lines[i+2])
		if !strings.HasPrefix(l1, "JR Z, ") || !strings.HasPrefix(l2, "JR C, ") {
			continue
		}
		joinLabel := strings.TrimPrefix(l1, "JR Z, ")
		joinLabel2 := strings.TrimPrefix(l2, "JR C, ")
		if joinLabel != joinLabel2 {
			continue
		}

		// Scan forward to find: block1 ending with SUB + RET, then joinLabel, block2 ending with SUB + RET
		// block1: [labels] [LD...] SUB r / RET
		// block2: joinLabel: [LD...] SUB r / RET
		block1End := -1
		for j := i + 3; j < len(lines) && j < i+12; j++ {
			t := strings.TrimSpace(lines[j])
			if t == "RET" {
				block1End = j
				break
			}
		}
		if block1End < 0 {
			continue
		}

		// Check block1 has SUB before RET
		block1Sub := strings.TrimSpace(lines[block1End-1])
		if !strings.HasPrefix(block1Sub, "SUB ") {
			continue
		}

		// Find join label after block1
		joinIdx := -1
		for j := block1End + 1; j < len(lines) && j <= block1End+3; j++ {
			t := strings.TrimSpace(lines[j])
			if t == joinLabel+":" {
				joinIdx = j
				break
			}
			if t == "" || strings.HasSuffix(t, ":") {
				continue
			}
			break
		}
		if joinIdx < 0 {
			continue
		}

		// Find block2's SUB + RET
		block2End := -1
		for j := joinIdx + 1; j < len(lines) && j < joinIdx+8; j++ {
			t := strings.TrimSpace(lines[j])
			if t == "RET" {
				block2End = j
				break
			}
		}
		if block2End < 0 {
			continue
		}

		block2Sub := strings.TrimSpace(lines[block2End-1])
		if !strings.HasPrefix(block2Sub, "SUB ") {
			continue
		}

		// Pattern matched! Replace everything from CP to block2 RET with:
		// SUB reg / RET NC / NEG / RET
		var newLines []string
		newLines = append(newLines, lines[:i]...)
		indent := "    "
		newLines = append(newLines, indent+"SUB "+reg)
		newLines = append(newLines, indent+"RET NC")
		newLines = append(newLines, indent+"NEG")
		newLines = append(newLines, indent+"RET")
		newLines = append(newLines, lines[block2End+1:]...)
		return fuseAbsDiffASM(newLines) // recurse for multiple patterns
	}
	return lines
}

func gracePass(lines []string) []string {
	// First: fuse abs_diff patterns
	lines = fuseAbsDiffASM(lines)

	// JP threading: JP .label where .label only contains JP .target → JP .target
	// Build label→first-instruction map
	labelTarget := make(map[string]string) // label → JP target (if label block is just JP)
	for i := 0; i < len(lines)-1; i++ {
		t := strings.TrimSpace(lines[i])
		if strings.HasSuffix(t, ":") && strings.HasPrefix(t, ".") {
			label := strings.TrimSuffix(t, ":")
			// Find next non-label, non-empty line
			for j := i + 1; j < len(lines) && j <= i+3; j++ {
				next := strings.TrimSpace(lines[j])
				if next == "" || strings.HasSuffix(next, ":") || strings.HasPrefix(next, ";") {
					continue
				}
				if strings.HasPrefix(next, "JP ") && !strings.HasPrefix(next, "JP (") {
					target := strings.TrimPrefix(next, "JP ")
					target = strings.TrimSpace(target)
					labelTarget[label] = target
				}
				break
			}
		}
	}
	// Rewrite JP/JR targets through chains
	if len(labelTarget) > 0 {
		for i, line := range lines {
			t := strings.TrimSpace(line)
			for _, prefix := range []string{"JP ", "JR Z, ", "JR NZ, ", "JR C, ", "JR NC, ", "JR "} {
				if strings.HasPrefix(t, prefix) {
					target := strings.TrimSpace(strings.TrimPrefix(t, prefix))
					if newTarget, ok := labelTarget[target]; ok {
						lines[i] = "    " + prefix + newTarget
					}
					break
				}
			}
		}
	}

	var result []string

	for i := 0; i < len(lines); i++ {
		line := strings.TrimSpace(lines[i])

		// ── Dead instruction before RET ─────────────────────────────
		// Any instruction that writes to a register right before RET is dead
		// if it doesn't write to A (return value) or affect flags for conditional return.
		// Example: DEC HL / RET → RET (HL not used after return)
		if i+1 < len(lines) {
			next := strings.TrimSpace(lines[i+1])
			if next == "RET" {
				// DEC rr / RET → RET (pair decrements are dead before unconditional return)
				if line == "DEC HL" || line == "DEC DE" || line == "DEC BC" {
					continue // skip dead decrement
				}
				// EX DE, HL / RET → RET (register swap is dead before return)
				if line == "EX DE, HL" {
					continue
				}
				// LD r, N / RET where r != A → skip (dead const load before return)
				if strings.HasPrefix(line, "LD ") && !strings.HasPrefix(line, "LD A") {
					parts := strings.SplitN(line[3:], ", ", 2)
					if len(parts) == 2 {
						reg := strings.TrimSpace(parts[0])
						if reg != "A" && reg != "(HL)" && !strings.HasPrefix(reg, "(") {
							continue // dead load before RET
						}
					}
				}
			}
		}

		// ── EX DE,HL / LD A,(HL) → LD A,(DE) ────────────────────────
		// When EX is only used to access memory through HL, use direct (DE) access
		if i+1 < len(lines) && line == "EX DE, HL" {
			next := strings.TrimSpace(lines[i+1])
			if next == "LD A, (HL)" {
				result = append(result, "    LD A, (DE)")
				i++ // skip LD A, (HL)
				// Check if next is EX DE, HL (restore) — skip it too
				if i+1 < len(lines) && strings.TrimSpace(lines[i+1]) == "EX DE, HL" {
					i++
				}
				continue
			}
		}

		// ── LD BC, 0 / ADD HL, BC → nothing (add 0 = nop) ──────────
		if i+1 < len(lines) && (line == "LD BC, 0" || line == "LD DE, 0") {
			next := strings.TrimSpace(lines[i+1])
			pair := "BC"
			if strings.HasPrefix(line, "LD DE") { pair = "DE" }
			if next == "ADD HL, "+pair {
				i++ // skip both
				continue
			}
		}

		// ── Redundant EX DE, HL pairs ────────────────────────────────
		// EX DE, HL / EX DE, HL → remove both (self-canceling)
		if i+1 < len(lines) && line == "EX DE, HL" {
			next := strings.TrimSpace(lines[i+1])
			if next == "EX DE, HL" {
				i++ // skip both
				continue
			}
		}

		// ── Empty label blocks ───────────────────────────────────────
		// .label: / .next_label: → merge (empty block)
		if strings.HasSuffix(line, ":") && i+1 < len(lines) {
			next := strings.TrimSpace(lines[i+1])
			if strings.HasSuffix(next, ":") && !strings.HasPrefix(line, ";") {
				// Keep both labels — they may be branch targets
			}
		}

		result = append(result, lines[i])
	}

	return result
}
