// pipeline.go — VIR module-level codegen entry point.
//
// This is the --vir entry point: MIR2 → VIR → Z3 solver → PIR → ASM.
// Replaces the 5-layer LIR pipeline with a single unified solver pass.
package vir

import (
	"fmt"
	"os"
	"strings"

	"github.com/minz/minzc/pkg/mir2"
)

// FuncResult tracks per-function codegen outcome.
type FuncResult struct {
	Name  string
	OK    bool
	Error string
	ASM   string
}

// CodegenModule runs the VIR unified solver on all functions in a MIR2 module.
// Returns assembly text and per-function results.
func CodegenModule(m *mir2.Module, opts SolverOptions) (string, []FuncResult) {
	var sb strings.Builder
	var results []FuncResult

	// Phase 0: Z3-PFCCO — find optimal calling conventions for all functions.
	// This is interprocedural: Z3 considers all call sites simultaneously.
	pfccoResults, pfccoErr := OptimizePFCCO(m, Z80, PFCCOOptions{
		Z3Path:  opts.Z3Path,
		Timeout: opts.Timeout,
	})
	if pfccoErr == nil && len(pfccoResults) > 0 {
		sb.WriteString("; generated by VIR unified solver (Z3-PFCCO + Z3 joint isel+regalloc)\n")
		sb.WriteString("; calling conventions optimized by Z3 SMT solver\n\n")
		// Store PFCCO results for use by CodegenFunc
		// (currently informational — full wiring TODO)
		for _, pr := range pfccoResults {
			if len(pr.ParamNames) > 0 {
				sb.WriteString(fmt.Sprintf("; %s: params=[%s] ret=%s (Z3-PFCCO)\n",
					pr.FuncName, strings.Join(pr.ParamNames, ","), pr.ReturnName))
			}
		}
		sb.WriteString("\n")
	} else {
		sb.WriteString("; generated by VIR unified solver (Z3 joint isel+regalloc)\n\n")
	}

	// Emit main first
	funcs := m.Funcs
	if main := m.FuncByName("main"); main != nil && len(funcs) > 0 && funcs[0].Name != "main" {
		ordered := make([]*mir2.Func, 0, len(funcs))
		ordered = append(ordered, main)
		for _, f := range funcs {
			if f.Name != "main" {
				ordered = append(ordered, f)
			}
		}
		funcs = ordered
	}

	for _, f := range funcs {
		asm, err := CodegenFunc(f, m, opts)
		r := FuncResult{Name: f.Name}
		if err != nil {
			r.Error = err.Error()
			if opts.Verbose {
				fmt.Fprintf(os.Stderr, "[vir] %s: %v\n", f.Name, err)
			}
		} else {
			r.OK = true
			r.ASM = asm
			sb.WriteString(asm)
			sb.WriteByte('\n')
		}
		results = append(results, r)
	}

	return sb.String(), results
}

// CodegenFunc runs the VIR solver on a single MIR2 function.
func CodegenFunc(f *mir2.Func, m *mir2.Module, opts SolverOptions) (string, error) {
	desc := Z80

	// Lower MIR2 → VIR
	vf, err := LowerFunc(f, desc, m)
	if err != nil {
		return "", fmt.Errorf("vir lower %s: %w", f.Name, err)
	}

	var sb strings.Builder

	// Function header
	sb.WriteString(fmt.Sprintf("; %s — VIR codegen\n", f.Name))
	sb.WriteString(f.Name + ":\n")

	// Track vreg → physical register across blocks.
	// Seed with ParamLocs from PBQP allocation (if available).
	vregPhys := make(map[int]int)
	// Per-function param locs (priority)
	if opts.FuncParamLocs != nil {
		if pl, ok := opts.FuncParamLocs[f.Name]; ok {
			for vreg, phys := range pl {
				vregPhys[vreg] = phys
			}
		}
	}
	// Global param locs (fallback)
	for vreg, phys := range opts.ParamLocs {
		if _, ok := vregPhys[vreg]; !ok {
			vregPhys[vreg] = phys
		}
	}

	// Process each block — emit PIROps + terminator
	for bi, block := range vf.Blocks {
		// Block label (prefix with function name for uniqueness)
		label := block.Label
		if bi == 0 {
			// First block = function entry, label already emitted
		} else if label != "" {
			sb.WriteString("." + f.Name + "_" + label + ":\n")
		}

		// For non-entry blocks: apply known vreg locations as SrcHint
		// so the solver knows where cross-block vregs live.
		// Apply cross-block register hints:
		// - Entry block (bi==0): ALL ops get SrcHint (params MUST match ABI)
		// - Non-entry: ONLY return-move ops (DstHint + OpMove)
		//   Computation ops use soft hints to avoid ALU tied conflicts.
		if len(vregPhys) > 0 {
			for i := range block.Ops {
				isReturnMove := block.Ops[i].Op == OpMove && !block.Ops[i].DstHint.IsEmpty()
				if bi == 0 || isReturnMove {
					for j, s := range block.Ops[i].Src {
						if s > 0 {
							if phys, ok := vregPhys[s]; ok {
								block.Ops[i].SrcHint[j] = Singleton(phys)
							}
						}
					}
				}
			}
		}

		// Solve block ops
		if len(block.Ops) > 0 {
			pirOps, err := Solve(block.Ops, desc, opts)
			if err != nil {
				return "", fmt.Errorf("vir solve %s/%s: %w", f.Name, block.Label, err)
			}

			// Record vreg → physical register from solution
			for k, p := range pirOps {
				if k < len(block.Ops) {
					op := block.Ops[k]
					if op.Dst > 0 && p.DstPhys >= 0 {
						vregPhys[op.Dst] = p.DstPhys
					}
					for j, s := range op.Src {
						if s > 0 && p.SrcPhys[j] >= 0 {
							vregPhys[s] = p.SrcPhys[j]
						}
					}
				}
			}

			for _, p := range pirOps {
				line := p.Emit(desc)
				if isSelfMove(line) {
					continue
				}
				emitLine(&sb, line)
			}
		}

		// Emit terminator (control flow between blocks)
		if bi < len(f.Blocks) {
			mir2Block := f.Blocks[bi]
			emitTerminator(&sb, mir2Block, f.Name)
		}
	}

	// Apply peephole cleanup (PUSH/POP, fallthrough, LD A,0→XOR A, etc.)
	return peepholeCleanup(sb.String()), nil
}

// emitLine writes one or more assembly lines (handles multi-line templates).
func emitLine(sb *strings.Builder, line string) {
	if line == "" {
		return
	}
	for _, subline := range strings.Split(line, "\n") {
		subline = strings.TrimSpace(subline)
		if subline != "" {
			sb.WriteString("    " + subline + "\n")
		}
	}
}

// emitTerminator generates Z80 control flow instructions for a MIR2 block terminator.
func emitTerminator(sb *strings.Builder, b *mir2.Block, funcName string) {
	if b.Term == nil {
		return
	}
	prefix := "." + funcName + "_"

	switch t := b.Term.(type) {
	case *mir2.TermRet:
		sb.WriteString("    RET\n")

	case *mir2.TermJmp:
		sb.WriteString(fmt.Sprintf("    JP %s%s\n", prefix, t.Target))

	case *mir2.TermBrIf:
		// Find the CMP that defined the condition vreg to determine flag semantics
		cmpCond := findCmpCond(b, t.Cond)
		elseLabel := prefix + t.Else

		// Emit branch based on comparison kind:
		// CP sets Z (equal) and C (a < b unsigned)
		switch cmpCond {
		case mir2.CmpUgt: // a > b: skip to else if Z or C
			sb.WriteString(fmt.Sprintf("    JR Z, %s\n", elseLabel))
			sb.WriteString(fmt.Sprintf("    JR C, %s\n", elseLabel))
			// fall through = then (a > b)
		case mir2.CmpUlt: // a < b: skip to else if NC (a >= b)
			sb.WriteString(fmt.Sprintf("    JR NC, %s\n", elseLabel))
			// fall through = then (a < b, C set)
		case mir2.CmpUge: // a >= b: skip to else if C (a < b)
			sb.WriteString(fmt.Sprintf("    JR C, %s\n", elseLabel))
		case mir2.CmpUle: // a <= b: skip to else if not Z and NC
			sb.WriteString(fmt.Sprintf("    JR Z, %s%s\n", prefix, t.Then))
			sb.WriteString(fmt.Sprintf("    JR NC, %s\n", elseLabel))
		case mir2.CmpEq: // a == b
			sb.WriteString(fmt.Sprintf("    JR NZ, %s\n", elseLabel))
		case mir2.CmpNe: // a != b
			sb.WriteString(fmt.Sprintf("    JR Z, %s\n", elseLabel))
		default:
			// Generic: treat as NZ (bool condition)
			sb.WriteString(fmt.Sprintf("    JR NZ, %s%s\n", prefix, t.Then))
			if t.Else != "" {
				sb.WriteString(fmt.Sprintf("    JP %s\n", elseLabel))
			}
			return
		}
		// Fall-through to Then block (or explicit jump if blocks aren't adjacent)
		sb.WriteString(fmt.Sprintf("    JP %s%s\n", prefix, t.Then))

	case *mir2.TermBrIf2:
		// Two-way branch based on comparison result
		// Lhs vs Rhs already compared, flags set
		if t.Eq != "" && t.Lt == "" && t.Gt == "" {
			// Simple equality check
			sb.WriteString(fmt.Sprintf("    JR Z, %s%s\n", prefix, t.Eq))
		} else {
			// Full three-way
			if t.Eq != "" {
				sb.WriteString(fmt.Sprintf("    JR Z, %s%s\n", prefix, t.Eq))
			}
			if t.Lt != "" {
				sb.WriteString(fmt.Sprintf("    JR C, %s%s\n", prefix, t.Lt))
			}
			if t.Gt != "" {
				sb.WriteString(fmt.Sprintf("    JP %s%s\n", prefix, t.Gt))
			}
		}

	case *mir2.TermDJNZ:
		sb.WriteString(fmt.Sprintf("    DJNZ %s%s\n", prefix, t.Body))
		if t.Exit != "" {
			sb.WriteString(fmt.Sprintf("    JP %s%s\n", prefix, t.Exit))
		}

	case *mir2.TermCondRet:
		// If cond==0, return vals. Else jump to Then.
		// Flags set by preceding CMP: Z flag = equal/zero
		if t.Then != "" {
			sb.WriteString(fmt.Sprintf("    JR NZ, %s%s\n", prefix, t.Then))
		}
		sb.WriteString("    RET\n") // return when cond==0 (Z flag set)

	case *mir2.TermUnreachable:
		sb.WriteString("    ; unreachable\n")
	}
}

// findCmpCond looks up the CmpCond of the OpCmp instruction that defines
// the given condition vreg. Returns -1 if not found.
func findCmpCond(b *mir2.Block, condReg mir2.Reg) mir2.CmpCond {
	for i := len(b.Insts) - 1; i >= 0; i-- {
		inst := b.Insts[i]
		if inst.Op == mir2.OpCmp && inst.Dst == condReg {
			return inst.Cond
		}
	}
	return mir2.CmpCond(255) // not found
}

// ── Peephole ────────────────────────────────────────────────────────────────

// isSelfMove detects Z80 no-op moves that can be eliminated:
//   LD A, A    — register self-copy
//   PUSH HL / POP HL  — stack self-move (from coalescing artifacts)
//   ; trunc ... (alias) — zero-cost aliases (already no instruction)
func isSelfMove(line string) bool {
	line = strings.TrimSpace(line)
	if line == "" {
		return false
	}

	// LD r, r (self-copy): LD A, A / LD B, B / etc.
	if strings.HasPrefix(line, "LD ") {
		parts := strings.SplitN(line[3:], ", ", 2)
		if len(parts) == 2 && strings.TrimSpace(parts[0]) == strings.TrimSpace(parts[1]) {
			return true
		}
	}

	// PUSH r / POP r on consecutive lines (handled as multi-line template)
	if strings.HasPrefix(line, "PUSH ") {
		// Check if next part is POP with same register
		// Multi-line templates are split before reaching here, so check single lines
	}

	return false
}

// peepholeCleanup applies additional Z80 peephole optimizations.
// Inspired by SDCC's peephole rules (https://sdcc.sourceforge.net/).
func peepholeCleanup(asm string) string {
	lines := strings.Split(asm, "\n")
	var result []string

	for i := 0; i < len(lines); i++ {
		line := strings.TrimSpace(lines[i])

		// PUSH rr / POP rr → remove both (self-move via stack)
		if i+1 < len(lines) && strings.HasPrefix(line, "PUSH ") {
			next := strings.TrimSpace(lines[i+1])
			reg := strings.TrimPrefix(line, "PUSH ")
			if next == "POP "+reg {
				i++ // skip both lines
				continue
			}
		}

		// JP label where label is the very next line → remove (fallthrough)
		if strings.HasPrefix(line, "JP ") {
			target := strings.TrimPrefix(line, "JP ")
			target = strings.TrimSpace(target)
			if i+1 < len(lines) {
				nextLine := strings.TrimSpace(lines[i+1])
				// Next line is "target:" label
				if nextLine == target+":" || nextLine == "."+target+":" {
					continue // skip redundant jump
				}
			}
		}

		// LD A, 0 → XOR A (1 byte shorter, faster)
		if line == "LD A, 0" {
			result = append(result, "    XOR A")
			continue
		}

		// CP 0 → OR A (sets Z flag same way, 1 byte shorter)
		if line == "CP 0" {
			result = append(result, "    OR A")
			continue
		}

		result = append(result, lines[i])
	}

	return strings.Join(result, "\n")
}
