// Package mir2gpu translates MIR2 modules to GPU compute shaders.
//
// Architecture: universal body (C-like expressions) + thin backend wraps.
//
//   MIR2 → emitBody() → universal C-like statements
//                              │
//                ┌─────────────┼─────────────┬──────────────┐
//                ▼             ▼             ▼              ▼
//          cuda.Wrap()   cl.Wrap()    vk.Wrap()      mtl.Wrap()
//          (10 lines)   (10 lines)  (15 lines)     (12 lines)
//
// The universal body handles: vreg declarations, MIR2 ops → expressions,
// block labels, terminators, goto/if/return. Identical across all backends.
//
// Backend wraps handle: kernel qualifier, thread ID, address space,
// parameter syntax, atomics, type names.
package mir2gpu

import (
	"fmt"
	"strings"

	"github.com/minz/minzc/pkg/mir2"
)

// Backend selects the GPU target language.
type Backend int

const (
	CUDA Backend = iota
	OpenCL
	Vulkan
	Metal
)

func (b Backend) String() string {
	return [...]string{"cuda", "opencl", "vulkan", "metal"}[b]
}

func (b Backend) Ext() string {
	return [...]string{".cu", ".cl", ".comp", ".metal"}[b]
}

// backendSpec defines the thin wrapper differences between GPU targets.
type backendSpec struct {
	Header     string // file header (includes, pragmas)
	KernelDecl func(name string) string // kernel function declaration opening
	ThreadID   string // expression for thread index
	ParamDecl  func() string // kernel parameter list
	ResultWrite func(reg string) string // write result to output buffer
	Footer     string // closing braces etc.
	UintType   string // unsigned int type name
	Uint8Type  string // unsigned 8-bit type
}

var specs = map[Backend]backendSpec{
	CUDA: {
		Header: "// Generated by MinZ mir2gpu — CUDA\n#include <stdint.h>\n",
		KernelDecl: func(name string) string {
			return fmt.Sprintf("__global__ void %s(uint32_t* __restrict__ results, uint32_t n)", name)
		},
		ThreadID:   "uint32_t tid = blockIdx.x * blockDim.x + threadIdx.x;\n    if (tid >= n) return;",
		ParamDecl:  func() string { return "" },
		ResultWrite: func(reg string) string { return fmt.Sprintf("results[tid] = %s;", reg) },
		UintType:   "uint32_t",
		Uint8Type:  "uint8_t",
	},
	OpenCL: {
		Header: "// Generated by MinZ mir2gpu — OpenCL\n",
		KernelDecl: func(name string) string {
			return fmt.Sprintf("__kernel void %s(__global uint* results, uint n)", name)
		},
		ThreadID:   "uint tid = get_global_id(0);\n    if (tid >= n) return;",
		ParamDecl:  func() string { return "" },
		ResultWrite: func(reg string) string { return fmt.Sprintf("results[tid] = %s;", reg) },
		UintType:   "uint",
		Uint8Type:  "uchar",
	},
	Vulkan: {
		Header: "// Generated by MinZ mir2gpu — Vulkan GLSL\n#version 450\nlayout(local_size_x = 256) in;\nlayout(std430, binding = 0) buffer ResultBuf { uint results[]; };\nlayout(push_constant) uniform Params { uint n; };\n",
		KernelDecl: func(name string) string {
			return "void main()"
		},
		ThreadID:   "uint tid = gl_GlobalInvocationID.x;\n    if (tid >= n) return;",
		ParamDecl:  func() string { return "" },
		ResultWrite: func(reg string) string { return fmt.Sprintf("results[tid] = %s;", reg) },
		UintType:   "uint",
		Uint8Type:  "uint", // GLSL has no uint8
	},
	Metal: {
		Header: "// Generated by MinZ mir2gpu — Metal\n#include <metal_stdlib>\nusing namespace metal;\n",
		KernelDecl: func(name string) string {
			return fmt.Sprintf("kernel void %s(\n    device uint* results [[buffer(0)]],\n    constant uint& n [[buffer(1)]],\n    uint tid [[thread_position_in_grid]])", name)
		},
		ThreadID:   "if (tid >= n) return;",
		ParamDecl:  func() string { return "" },
		ResultWrite: func(reg string) string { return fmt.Sprintf("results[tid] = %s;", reg) },
		UintType:   "uint",
		Uint8Type:  "uint8_t",
	},
}

// CompileOptions controls GPU code generation.
type CompileOptions struct {
	Backend   Backend
	EntryFunc string // entry function (default: first)
}

// Compile translates a MIR2 module to GPU compute shader source code.
func Compile(m *mir2.Module, opts CompileOptions) (string, error) {
	spec, ok := specs[opts.Backend]
	if !ok {
		return "", fmt.Errorf("unknown backend: %d", opts.Backend)
	}

	var sb strings.Builder

	// Header
	sb.WriteString(spec.Header)
	sb.WriteString("\n")

	// Emit each function as a kernel
	for _, f := range m.Funcs {
		name := gpuSym(f.Name)

		// Kernel declaration
		sb.WriteString(spec.KernelDecl(name))
		sb.WriteString(" {\n")

		// Thread ID
		sb.WriteString("    " + spec.ThreadID + "\n")

		// Universal body
		emitUniversalBody(&sb, f, spec)

		sb.WriteString("}\n\n")
	}

	return sb.String(), nil
}

// ── Universal body (shared across ALL backends) ──────────────────────────────

func emitUniversalBody(sb *strings.Builder, f *mir2.Func, spec backendSpec) {
	// Declare vregs
	vregs := make(map[mir2.Reg]bool)
	for _, b := range f.Blocks {
		for _, inst := range b.Insts {
			if inst.Dst != mir2.NoReg {
				vregs[inst.Dst] = true
			}
		}
		for _, p := range b.Params {
			vregs[p.Dst] = true
		}
	}

	// Map first param to tid
	for i, cp := range f.Contract.Params {
		if i == 0 {
			sb.WriteString(fmt.Sprintf("    %s r%d = tid;\n", spec.UintType, cp.Reg))
		} else {
			sb.WriteString(fmt.Sprintf("    %s r%d = 0;\n", spec.UintType, cp.Reg))
		}
		delete(vregs, cp.Reg)
	}
	for vreg := range vregs {
		sb.WriteString(fmt.Sprintf("    %s r%d = 0;\n", spec.UintType, vreg))
	}
	sb.WriteString("\n")

	// Emit blocks
	for bi, b := range f.Blocks {
		if bi > 0 && b.Label != "" {
			sb.WriteString(fmt.Sprintf("  %s:\n", gpuSym(b.Label)))
		}
		for _, inst := range b.Insts {
			emitUniversalInst(sb, inst, spec)
		}
		emitUniversalTerm(sb, f, b, spec)
	}
}

func emitUniversalInst(sb *strings.Builder, inst *mir2.Inst, spec backendSpec) {
	dst := fmt.Sprintf("r%d", inst.Dst)
	switch inst.Op {
	case mir2.OpConst:
		sb.WriteString(fmt.Sprintf("    %s = %d;\n", dst, inst.Imm))
	case mir2.OpMove:
		sb.WriteString(fmt.Sprintf("    %s = r%d;\n", dst, inst.Src[0]))
	case mir2.OpAdd:
		sb.WriteString(fmt.Sprintf("    %s = (r%d + r%d) & 0xFF;\n", dst, inst.Src[0], inst.Src[1]))
	case mir2.OpSub:
		sb.WriteString(fmt.Sprintf("    %s = (r%d - r%d) & 0xFF;\n", dst, inst.Src[0], inst.Src[1]))
	case mir2.OpMul:
		sb.WriteString(fmt.Sprintf("    %s = (r%d * r%d) & 0xFF;\n", dst, inst.Src[0], inst.Src[1]))
	case mir2.OpAnd:
		sb.WriteString(fmt.Sprintf("    %s = r%d & r%d;\n", dst, inst.Src[0], inst.Src[1]))
	case mir2.OpOr:
		sb.WriteString(fmt.Sprintf("    %s = r%d | r%d;\n", dst, inst.Src[0], inst.Src[1]))
	case mir2.OpXor:
		sb.WriteString(fmt.Sprintf("    %s = r%d ^ r%d;\n", dst, inst.Src[0], inst.Src[1]))
	case mir2.OpShl:
		sb.WriteString(fmt.Sprintf("    %s = (r%d << r%d) & 0xFF;\n", dst, inst.Src[0], inst.Src[1]))
	case mir2.OpShr:
		sb.WriteString(fmt.Sprintf("    %s = r%d >> r%d;\n", dst, inst.Src[0], inst.Src[1]))
	case mir2.OpNeg:
		sb.WriteString(fmt.Sprintf("    %s = (-%s(r%d)) & 0xFF;\n", dst, "int", inst.Src[0]))
	case mir2.OpNot:
		sb.WriteString(fmt.Sprintf("    %s = ~r%d;\n", dst, inst.Src[0]))
	case mir2.OpCmp:
		sb.WriteString(fmt.Sprintf("    %s = (r%d %s r%d) ? 1 : 0;\n", dst, inst.Src[0], cmpOp(inst.Cond), inst.Src[1]))
	case mir2.OpLoad:
		sb.WriteString(fmt.Sprintf("    // load r%d from [r%d]\n", inst.Dst, inst.Src[0]))
	case mir2.OpStore:
		sb.WriteString(fmt.Sprintf("    // store r%d to [r%d]\n", inst.Src[1], inst.Src[0]))
	case mir2.OpCall:
		sym := gpuSym(inst.Sym)
		if inst.Dst != mir2.NoReg {
			sb.WriteString(fmt.Sprintf("    %s = %s(", dst, sym))
		} else {
			sb.WriteString(fmt.Sprintf("    %s(", sym))
		}
		for i, arg := range inst.Args {
			if i > 0 { sb.WriteString(", ") }
			sb.WriteString(fmt.Sprintf("r%d", arg))
		}
		sb.WriteString(");\n")
	case mir2.OpDiv:
		sb.WriteString(fmt.Sprintf("    %s = r%d / r%d;\n", dst, inst.Src[0], inst.Src[1]))
	case mir2.OpMod:
		sb.WriteString(fmt.Sprintf("    %s = r%d %% r%d;\n", dst, inst.Src[0], inst.Src[1]))
	default:
		sb.WriteString(fmt.Sprintf("    // TODO: op %d\n", inst.Op))
	}
}

func emitUniversalTerm(sb *strings.Builder, f *mir2.Func, b *mir2.Block, spec backendSpec) {
	if b.Term == nil {
		return
	}
	switch t := b.Term.(type) {
	case *mir2.TermRet:
		if len(t.Vals) > 0 {
			sb.WriteString(fmt.Sprintf("    %s\n", spec.ResultWrite(fmt.Sprintf("r%d", t.Vals[0]))))
		}
		sb.WriteString("    return;\n")
	case *mir2.TermJmp:
		target := f.BlockByLabel(t.Target)
		if target != nil {
			for i, arg := range t.Args {
				if i < len(target.Params) {
					sb.WriteString(fmt.Sprintf("    r%d = r%d;\n", target.Params[i].Dst, arg))
				}
			}
		}
		sb.WriteString(fmt.Sprintf("    goto %s;\n", gpuSym(t.Target)))
	case *mir2.TermBrIf:
		thenBlock := f.BlockByLabel(t.Then)
		if thenBlock != nil {
			for i, arg := range t.ThenArgs {
				if i < len(thenBlock.Params) {
					sb.WriteString(fmt.Sprintf("    if (r%d) r%d = r%d;\n", t.Cond, thenBlock.Params[i].Dst, arg))
				}
			}
		}
		elseBlock := f.BlockByLabel(t.Else)
		if elseBlock != nil {
			for i, arg := range t.ElseArgs {
				if i < len(elseBlock.Params) {
					sb.WriteString(fmt.Sprintf("    if (!r%d) r%d = r%d;\n", t.Cond, elseBlock.Params[i].Dst, arg))
				}
			}
		}
		sb.WriteString(fmt.Sprintf("    if (r%d) goto %s; else goto %s;\n",
			t.Cond, gpuSym(t.Then), gpuSym(t.Else)))
	case *mir2.TermCondRet:
		if len(t.Vals) > 0 {
			sb.WriteString(fmt.Sprintf("    if (!r%d) { %s return; }\n",
				t.Cond, spec.ResultWrite(fmt.Sprintf("r%d", t.Vals[0]))))
		}
		sb.WriteString(fmt.Sprintf("    goto %s;\n", gpuSym(t.Then)))
	default:
		sb.WriteString("    // TODO: terminator\n")
	}
}

// ── Utilities ────────────────────────────────────────────────────────────────

func gpuSym(name string) string {
	s := strings.ReplaceAll(name, "@", "")
	s = strings.ReplaceAll(s, ".", "_")
	s = strings.ReplaceAll(s, "$", "_")
	s = strings.ReplaceAll(s, "-", "_")
	switch s {
	case "double", "float", "int", "char", "short", "long", "void",
		"return", "if", "else", "for", "while", "do", "switch", "case",
		"break", "continue", "goto", "default", "struct", "union", "enum",
		"main", "half", "kernel":
		return "fn_" + s
	}
	return s
}

func gpuType(width int) string {
	switch {
	case width <= 8:
		return "uint8_t"
	case width <= 16:
		return "uint16_t"
	case width <= 32:
		return "uint32_t"
	default:
		return "uint64_t"
	}
}

func cmpOp(cond mir2.CmpCond) string {
	switch cond {
	case mir2.CmpEq:
		return "=="
	case mir2.CmpNe:
		return "!="
	case mir2.CmpLt, mir2.CmpUlt:
		return "<"
	case mir2.CmpLe, mir2.CmpUle:
		return "<="
	case mir2.CmpGt, mir2.CmpUgt:
		return ">"
	case mir2.CmpGe, mir2.CmpUge:
		return ">="
	default:
		return "=="
	}
}
