// Package mir2gpu translates MIR2 modules to GPU compute shaders.
//
// Targets: CUDA (.cu), OpenCL (.cl), Vulkan/SPIR-V (.comp), Metal (.metal)
//
// Design:
//   - Each MIR2 function → one GPU kernel function
//   - Bounded-range iterators → thread-per-element dispatch
//   - Registers → local variables (trivial allocation on GPU)
//   - Memory → device buffer
//   - Block params → local variables, assigned at branch site
//   - Terminators → if/goto
//   - u8 range → 256 threads, u16 → 65536 threads
//
// Architecture:
//   MIR2 ops map directly to C-like GPU expressions:
//     OpAdd → a + b
//     OpSub → a - b
//     OpMul → a * b
//     OpShl → a << b
//     OpCmp → a < b (etc.)
//     OpLoad → buf[addr]
//     OpStore → buf[addr] = val
//
// The GPU has hundreds of registers — no allocation problem.
// No Z3, no PBQP, no heuristic. Just emit expressions.
package mir2gpu

import (
	"fmt"
	"strings"

	"github.com/minz/minzc/pkg/mir2"
)

// Backend selects the GPU target language.
type Backend int

const (
	CUDA Backend = iota
	OpenCL
	Vulkan // GLSL compute shader → compiled to SPIR-V via glslc
	Metal
)

func (b Backend) String() string {
	switch b {
	case CUDA:
		return "cuda"
	case OpenCL:
		return "opencl"
	case Vulkan:
		return "vulkan"
	case Metal:
		return "metal"
	}
	return "unknown"
}

// CompileOptions controls GPU code generation.
type CompileOptions struct {
	Backend    Backend
	ThreadDim  int    // override thread count (0 = auto from types)
	EntryFunc  string // entry function name (default: first function)
	BufferSize int    // device buffer size in bytes (default: 4096)
}

// Compile translates a MIR2 module to GPU compute shader source code.
func Compile(m *mir2.Module, opts CompileOptions) (string, error) {
	g := &gpuGen{
		sb:   &strings.Builder{},
		mod:  m,
		opts: opts,
	}
	return g.emit()
}

type gpuGen struct {
	sb   *strings.Builder
	mod  *mir2.Module
	opts CompileOptions
}

func (g *gpuGen) emit() (string, error) {
	switch g.opts.Backend {
	case CUDA:
		return g.emitCUDA()
	case OpenCL:
		return g.emitOpenCL()
	case Vulkan:
		return g.emitVulkan()
	case Metal:
		return g.emitMetal()
	default:
		return "", fmt.Errorf("unknown GPU backend: %d", g.opts.Backend)
	}
}

// ── CUDA backend ─────────────────────────────────────────────────────────────

func (g *gpuGen) emitCUDA() (string, error) {
	g.sb.WriteString("// Generated by MinZ mir2gpu — CUDA compute kernel\n")
	g.sb.WriteString("#include <stdint.h>\n\n")

	for _, f := range g.mod.Funcs {
		g.emitCUDAKernel(f)
	}

	return g.sb.String(), nil
}

func (g *gpuGen) emitCUDAKernel(f *mir2.Func) {
	name := gpuSym(f.Name)
	g.sb.WriteString(fmt.Sprintf("__global__ void %s(", name))
	g.emitParams(f, "cuda")
	g.sb.WriteString(") {\n")
	g.sb.WriteString("    uint32_t tid = blockIdx.x * blockDim.x + threadIdx.x;\n")
	g.emitBody(f)
	g.sb.WriteString("}\n\n")
}

// ── OpenCL backend ───────────────────────────────────────────────────────────

func (g *gpuGen) emitOpenCL() (string, error) {
	g.sb.WriteString("// Generated by MinZ mir2gpu — OpenCL compute kernel\n\n")

	for _, f := range g.mod.Funcs {
		g.emitOpenCLKernel(f)
	}

	return g.sb.String(), nil
}

func (g *gpuGen) emitOpenCLKernel(f *mir2.Func) {
	name := gpuSym(f.Name)
	g.sb.WriteString(fmt.Sprintf("__kernel void %s(", name))
	g.emitParams(f, "opencl")
	g.sb.WriteString(") {\n")
	g.sb.WriteString("    uint tid = get_global_id(0);\n")
	g.emitBody(f)
	g.sb.WriteString("}\n\n")
}

// ── Vulkan backend (GLSL compute) ────────────────────────────────────────────

func (g *gpuGen) emitVulkan() (string, error) {
	g.sb.WriteString("// Generated by MinZ mir2gpu — Vulkan GLSL compute shader\n")
	g.sb.WriteString("#version 450\n\n")
	g.sb.WriteString("layout(local_size_x = 256) in;\n\n")

	// SSBO bindings for parameters
	g.sb.WriteString("layout(std430, binding = 0) buffer InputBuf  { uint data_in[];  };\n")
	g.sb.WriteString("layout(std430, binding = 1) buffer OutputBuf { uint data_out[]; };\n\n")

	for _, f := range g.mod.Funcs {
		g.emitVulkanMain(f)
		break // Vulkan has single main()
	}

	return g.sb.String(), nil
}

func (g *gpuGen) emitVulkanMain(f *mir2.Func) {
	g.sb.WriteString("void main() {\n")
	g.sb.WriteString("    uint tid = gl_GlobalInvocationID.x;\n")
	g.emitBody(f)
	g.sb.WriteString("}\n")
}

// ── Metal backend ────────────────────────────────────────────────────────────

func (g *gpuGen) emitMetal() (string, error) {
	g.sb.WriteString("// Generated by MinZ mir2gpu — Metal compute kernel\n")
	g.sb.WriteString("#include <metal_stdlib>\n")
	g.sb.WriteString("using namespace metal;\n\n")

	for _, f := range g.mod.Funcs {
		g.emitMetalKernel(f)
	}

	return g.sb.String(), nil
}

func (g *gpuGen) emitMetalKernel(f *mir2.Func) {
	name := gpuSym(f.Name)
	g.sb.WriteString(fmt.Sprintf("kernel void %s(", name))
	g.emitParams(f, "metal")
	g.sb.WriteString(fmt.Sprintf("    uint tid [[thread_position_in_grid]]) {\n"))
	g.emitBody(f)
	g.sb.WriteString("}\n\n")
}

// ── Shared code generation ───────────────────────────────────────────────────

func (g *gpuGen) emitParams(f *mir2.Func, backend string) {
	switch backend {
	case "cuda":
		g.sb.WriteString("uint8_t* __restrict__ buf, uint32_t* __restrict__ result, uint32_t n")
	case "opencl":
		g.sb.WriteString("__global uchar* buf, __global uint* result, uint n")
	case "metal":
		g.sb.WriteString("\n    device uint8_t* buf [[buffer(0)]],\n    device uint32_t* result [[buffer(1)]],\n    constant uint& n [[buffer(2)]],\n")
	}
}

func (g *gpuGen) emitBody(f *mir2.Func) {
	// Declare local variables for all vregs
	vregs := make(map[mir2.Reg]bool)
	for _, b := range f.Blocks {
		for _, inst := range b.Insts {
			if inst.Dst != mir2.NoReg {
				vregs[inst.Dst] = true
			}
		}
		for _, p := range b.Params {
			vregs[p.Dst] = true
		}
	}
	for vreg := range vregs {
		ty := g.typeForReg(f, vreg)
		g.sb.WriteString(fmt.Sprintf("    %s r%d = 0;\n", ty, vreg))
	}
	g.sb.WriteString("\n")

	// Emit blocks
	for bi, b := range f.Blocks {
		if bi > 0 && b.Label != "" {
			g.sb.WriteString(fmt.Sprintf("  %s:\n", gpuSym(b.Label)))
		}

		// Block params (PHI)
		// (assigned at branch site, not here)

		// Instructions
		for _, inst := range b.Insts {
			g.emitInst(inst)
		}

		// Terminator
		g.emitTerm(f, b)
	}
}

func (g *gpuGen) emitInst(inst *mir2.Inst) {
	dst := fmt.Sprintf("r%d", inst.Dst)

	switch inst.Op {
	case mir2.OpConst:
		g.sb.WriteString(fmt.Sprintf("    %s = %d;\n", dst, inst.Imm))

	case mir2.OpMove:
		g.sb.WriteString(fmt.Sprintf("    %s = r%d;\n", dst, inst.Src[0]))

	case mir2.OpAdd:
		g.sb.WriteString(fmt.Sprintf("    %s = r%d + r%d;\n", dst, inst.Src[0], inst.Src[1]))

	case mir2.OpSub:
		g.sb.WriteString(fmt.Sprintf("    %s = r%d - r%d;\n", dst, inst.Src[0], inst.Src[1]))

	case mir2.OpMul:
		g.sb.WriteString(fmt.Sprintf("    %s = r%d * r%d;\n", dst, inst.Src[0], inst.Src[1]))

	case mir2.OpAnd:
		g.sb.WriteString(fmt.Sprintf("    %s = r%d & r%d;\n", dst, inst.Src[0], inst.Src[1]))

	case mir2.OpOr:
		g.sb.WriteString(fmt.Sprintf("    %s = r%d | r%d;\n", dst, inst.Src[0], inst.Src[1]))

	case mir2.OpXor:
		g.sb.WriteString(fmt.Sprintf("    %s = r%d ^ r%d;\n", dst, inst.Src[0], inst.Src[1]))

	case mir2.OpShl:
		g.sb.WriteString(fmt.Sprintf("    %s = r%d << r%d;\n", dst, inst.Src[0], inst.Src[1]))

	case mir2.OpShr:
		g.sb.WriteString(fmt.Sprintf("    %s = r%d >> r%d;\n", dst, inst.Src[0], inst.Src[1]))

	case mir2.OpNeg:
		g.sb.WriteString(fmt.Sprintf("    %s = -r%d;\n", dst, inst.Src[0]))

	case mir2.OpNot:
		g.sb.WriteString(fmt.Sprintf("    %s = ~r%d;\n", dst, inst.Src[0]))

	case mir2.OpCmp:
		op := cmpOp(inst.Cond)
		g.sb.WriteString(fmt.Sprintf("    %s = (r%d %s r%d) ? 1 : 0;\n", dst, inst.Src[0], op, inst.Src[1]))

	case mir2.OpLoad:
		g.sb.WriteString(fmt.Sprintf("    %s = buf[r%d];\n", dst, inst.Src[0]))

	case mir2.OpStore:
		g.sb.WriteString(fmt.Sprintf("    buf[r%d] = r%d;\n", inst.Src[0], inst.Src[1]))

	case mir2.OpCall:
		// Function call → inline or device function call
		sym := gpuSym(inst.Sym)
		if inst.Dst != mir2.NoReg {
			g.sb.WriteString(fmt.Sprintf("    %s = %s(", dst, sym))
		} else {
			g.sb.WriteString(fmt.Sprintf("    %s(", sym))
		}
		for i, arg := range inst.Args {
			if i > 0 {
				g.sb.WriteString(", ")
			}
			g.sb.WriteString(fmt.Sprintf("r%d", arg))
		}
		g.sb.WriteString(");\n")

	default:
		g.sb.WriteString(fmt.Sprintf("    // TODO: op %d\n", inst.Op))
	}
}

func (g *gpuGen) emitTerm(f *mir2.Func, b *mir2.Block) {
	if b.Term == nil {
		return
	}

	switch t := b.Term.(type) {
	case *mir2.TermRet:
		if len(t.Vals) > 0 {
			g.sb.WriteString(fmt.Sprintf("    result[tid] = r%d;\n", t.Vals[0]))
		}
		g.sb.WriteString("    return;\n")

	case *mir2.TermJmp:
		// Assign block args
		target := f.BlockByLabel(t.Target)
		if target != nil {
			for i, arg := range t.Args {
				if i < len(target.Params) {
					g.sb.WriteString(fmt.Sprintf("    r%d = r%d;\n", target.Params[i].Dst, arg))
				}
			}
		}
		g.sb.WriteString(fmt.Sprintf("    goto %s;\n", gpuSym(t.Target)))

	case *mir2.TermBrIf:
		g.sb.WriteString(fmt.Sprintf("    if (r%d) goto %s; else goto %s;\n",
			t.Cond, gpuSym(t.Then), gpuSym(t.Else)))

	case *mir2.TermCondRet:
		if len(t.Vals) > 0 {
			g.sb.WriteString(fmt.Sprintf("    if (!r%d) { result[tid] = r%d; return; }\n",
				t.Cond, t.Vals[0]))
		}
		g.sb.WriteString(fmt.Sprintf("    goto %s;\n", gpuSym(t.Then)))

	default:
		g.sb.WriteString("    // TODO: terminator\n")
	}
}

func (g *gpuGen) typeForReg(f *mir2.Func, reg mir2.Reg) string {
	// Check contract params for type info
	for _, cp := range f.Contract.Params {
		if cp.Reg == reg && cp.Ty != nil {
			return gpuType(cp.Ty.Width())
		}
	}
	// Default: 32-bit int (safe for GPU)
	return "int32_t"
}

func gpuType(width int) string {
	switch {
	case width <= 8:
		return "uint8_t"
	case width <= 16:
		return "uint16_t"
	case width <= 32:
		return "uint32_t"
	default:
		return "uint64_t"
	}
}

func gpuSym(name string) string {
	s := strings.ReplaceAll(name, "@", "")
	s = strings.ReplaceAll(s, ".", "_")
	s = strings.ReplaceAll(s, "$", "_")
	s = strings.ReplaceAll(s, "-", "_")
	// Prefix C/C++ reserved words
	switch s {
	case "double", "float", "int", "char", "short", "long", "void",
		"return", "if", "else", "for", "while", "do", "switch", "case",
		"break", "continue", "goto", "default", "struct", "union", "enum":
		return "fn_" + s
	}
	return s
}

func cmpOp(cond mir2.CmpCond) string {
	switch cond {
	case mir2.CmpEq:
		return "=="
	case mir2.CmpNe:
		return "!="
	case mir2.CmpLt, mir2.CmpUlt:
		return "<"
	case mir2.CmpLe, mir2.CmpUle:
		return "<="
	case mir2.CmpGt, mir2.CmpUgt:
		return ">"
	case mir2.CmpGe, mir2.CmpUge:
		return ">="
	default:
		return "=="
	}
}
