// standalone_cuda.go — Generate a complete, compilable CUDA program from MIR2.
//
// Usage:
//   code := mir2gpu.StandaloneCUDA(m, "double", 256)
//   // → complete .cu file with kernel + main() + dispatch
//   // → nvcc -o test test.cu && ./test
package mir2gpu

import (
	"fmt"
	"strings"

	"github.com/minz/minzc/pkg/mir2"
)

// StandaloneCUDA generates a complete CUDA program that:
// 1. Defines the kernel from the MIR2 function
// 2. Launches it with N threads (one per input value)
// 3. Prints results
func StandaloneCUDA(m *mir2.Module, funcName string, numThreads int) (string, error) {
	f := m.FuncByName(funcName)
	if f == nil {
		return "", fmt.Errorf("function %s not found", funcName)
	}

	var sb strings.Builder

	// Header
	sb.WriteString("// Generated by MinZ mir2gpu — standalone CUDA test\n")
	sb.WriteString("#include <stdio.h>\n")
	sb.WriteString("#include <stdint.h>\n\n")

	// Device function (not kernel — callable from kernel)
	sb.WriteString(fmt.Sprintf("__device__ uint32_t %s(", gpuSym(funcName)))
	for i, cp := range f.Contract.Params {
		if i > 0 {
			sb.WriteString(", ")
		}
		ty := gpuType(8) // default u8
		if cp.Ty != nil {
			ty = gpuType(cp.Ty.Width())
		}
		sb.WriteString(fmt.Sprintf("%s p%d", ty, i))
	}
	sb.WriteString(") {\n")

	// Declare vregs
	vregs := make(map[mir2.Reg]bool)
	for _, b := range f.Blocks {
		for _, inst := range b.Insts {
			if inst.Dst != mir2.NoReg {
				vregs[inst.Dst] = true
			}
		}
		for _, p := range b.Params {
			vregs[p.Dst] = true
		}
	}
	// Map function params to vregs
	for i, cp := range f.Contract.Params {
		sb.WriteString(fmt.Sprintf("    uint32_t r%d = p%d;\n", cp.Reg, i))
		delete(vregs, cp.Reg) // already declared
	}
	for vreg := range vregs {
		sb.WriteString(fmt.Sprintf("    uint32_t r%d = 0;\n", vreg))
	}
	sb.WriteString("\n")

	// Emit blocks
	for bi, b := range f.Blocks {
		if bi > 0 && b.Label != "" {
			sb.WriteString(fmt.Sprintf("  %s:\n", gpuSym(b.Label)))
		}
		for _, inst := range b.Insts {
			emitCUDAInst(&sb, inst)
		}
		emitCUDATerm(&sb, f, b)
	}

	sb.WriteString("    return 0; // fallthrough\n")
	sb.WriteString("}\n\n")

	// Kernel: each thread calls the function with tid as first argument
	sb.WriteString(fmt.Sprintf("__global__ void kernel_%s(uint32_t* results, uint32_t n) {\n", gpuSym(funcName)))
	sb.WriteString("    uint32_t tid = blockIdx.x * blockDim.x + threadIdx.x;\n")
	sb.WriteString("    if (tid >= n) return;\n")

	// Call the device function with tid as first param, 0 for rest
	sb.WriteString(fmt.Sprintf("    results[tid] = %s(tid", gpuSym(funcName)))
	for i := 1; i < len(f.Contract.Params); i++ {
		sb.WriteString(", 0")
	}
	sb.WriteString(");\n")
	sb.WriteString("}\n\n")

	// Main: allocate, launch, print
	sb.WriteString("int main() {\n")
	sb.WriteString(fmt.Sprintf("    const int N = %d;\n", numThreads))
	sb.WriteString("    uint32_t *d_results, *h_results;\n")
	sb.WriteString("    h_results = (uint32_t*)malloc(N * sizeof(uint32_t));\n")
	sb.WriteString("    cudaMalloc(&d_results, N * sizeof(uint32_t));\n\n")
	sb.WriteString(fmt.Sprintf("    kernel_%s<<<(N+255)/256, 256>>>(d_results, N);\n", gpuSym(funcName)))
	sb.WriteString("    cudaMemcpy(h_results, d_results, N * sizeof(uint32_t), cudaMemcpyDeviceToHost);\n\n")
	sb.WriteString("    // Print first 16 results\n")
	sb.WriteString("    for (int i = 0; i < 16 && i < N; i++) {\n")
	sb.WriteString(fmt.Sprintf("        printf(\"%s(%%d) = %%d\\n\", i, h_results[i]);\n", funcName))
	sb.WriteString("    }\n\n")
	sb.WriteString("    // Verify: count correct results\n")
	sb.WriteString("    int correct = 0;\n")
	sb.WriteString("    for (int i = 0; i < N; i++) {\n")
	sb.WriteString(fmt.Sprintf("        if (h_results[i] == (uint32_t)(%s)) correct++;\n", verifyExpr(funcName)))
	sb.WriteString("    }\n")
	sb.WriteString(fmt.Sprintf("    printf(\"Correct: %%d/%%d\\n\", correct, N);\n"))
	sb.WriteString("\n    cudaFree(d_results);\n")
	sb.WriteString("    free(h_results);\n")
	sb.WriteString("    return 0;\n")
	sb.WriteString("}\n")

	return sb.String(), nil
}

func emitCUDAInst(sb *strings.Builder, inst *mir2.Inst) {
	dst := fmt.Sprintf("r%d", inst.Dst)
	switch inst.Op {
	case mir2.OpConst:
		sb.WriteString(fmt.Sprintf("    %s = %d;\n", dst, inst.Imm))
	case mir2.OpMove:
		sb.WriteString(fmt.Sprintf("    %s = r%d;\n", dst, inst.Src[0]))
	case mir2.OpAdd:
		sb.WriteString(fmt.Sprintf("    %s = (r%d + r%d) & 0xFF;\n", dst, inst.Src[0], inst.Src[1]))
	case mir2.OpSub:
		sb.WriteString(fmt.Sprintf("    %s = (r%d - r%d) & 0xFF;\n", dst, inst.Src[0], inst.Src[1]))
	case mir2.OpMul:
		sb.WriteString(fmt.Sprintf("    %s = (r%d * r%d) & 0xFF;\n", dst, inst.Src[0], inst.Src[1]))
	case mir2.OpAnd:
		sb.WriteString(fmt.Sprintf("    %s = r%d & r%d;\n", dst, inst.Src[0], inst.Src[1]))
	case mir2.OpOr:
		sb.WriteString(fmt.Sprintf("    %s = r%d | r%d;\n", dst, inst.Src[0], inst.Src[1]))
	case mir2.OpXor:
		sb.WriteString(fmt.Sprintf("    %s = r%d ^ r%d;\n", dst, inst.Src[0], inst.Src[1]))
	case mir2.OpShl:
		sb.WriteString(fmt.Sprintf("    %s = (r%d << r%d) & 0xFF;\n", dst, inst.Src[0], inst.Src[1]))
	case mir2.OpShr:
		sb.WriteString(fmt.Sprintf("    %s = r%d >> r%d;\n", dst, inst.Src[0], inst.Src[1]))
	case mir2.OpNeg:
		sb.WriteString(fmt.Sprintf("    %s = (-r%d) & 0xFF;\n", dst, inst.Src[0]))
	case mir2.OpCmp:
		op := cmpOp(inst.Cond)
		sb.WriteString(fmt.Sprintf("    %s = (r%d %s r%d) ? 1 : 0;\n", dst, inst.Src[0], op, inst.Src[1]))
	default:
		sb.WriteString(fmt.Sprintf("    // TODO: op %d\n", inst.Op))
	}
}

func emitCUDATerm(sb *strings.Builder, f *mir2.Func, b *mir2.Block) {
	if b.Term == nil {
		return
	}
	switch t := b.Term.(type) {
	case *mir2.TermRet:
		if len(t.Vals) > 0 {
			sb.WriteString(fmt.Sprintf("    return r%d;\n", t.Vals[0]))
		} else {
			sb.WriteString("    return 0;\n")
		}
	case *mir2.TermJmp:
		target := f.BlockByLabel(t.Target)
		if target != nil {
			for i, arg := range t.Args {
				if i < len(target.Params) {
					sb.WriteString(fmt.Sprintf("    r%d = r%d;\n", target.Params[i].Dst, arg))
				}
			}
		}
		sb.WriteString(fmt.Sprintf("    goto %s;\n", gpuSym(t.Target)))
	case *mir2.TermBrIf:
		// Assign then-args
		thenBlock := f.BlockByLabel(t.Then)
		if thenBlock != nil {
			for i, arg := range t.ThenArgs {
				if i < len(thenBlock.Params) {
					sb.WriteString(fmt.Sprintf("    if (r%d) r%d = r%d;\n", t.Cond, thenBlock.Params[i].Dst, arg))
				}
			}
		}
		elseBlock := f.BlockByLabel(t.Else)
		if elseBlock != nil {
			for i, arg := range t.ElseArgs {
				if i < len(elseBlock.Params) {
					sb.WriteString(fmt.Sprintf("    if (!r%d) r%d = r%d;\n", t.Cond, elseBlock.Params[i].Dst, arg))
				}
			}
		}
		sb.WriteString(fmt.Sprintf("    if (r%d) goto %s; else goto %s;\n",
			t.Cond, gpuSym(t.Then), gpuSym(t.Else)))
	case *mir2.TermCondRet:
		if len(t.Vals) > 0 {
			sb.WriteString(fmt.Sprintf("    if (!r%d) return r%d;\n", t.Cond, t.Vals[0]))
		}
		sb.WriteString(fmt.Sprintf("    goto %s;\n", gpuSym(t.Then)))
	}
}

func verifyExpr(funcName string) string {
	switch funcName {
	case "double":
		return "(i * 2) & 0xFF" // u8 wraps
	case "triple":
		return "(i * 3) & 0xFF"
	case "add":
		return "(i + 0) & 0xFF"
	default:
		return "i & 0xFF"
	}
}
