// standalone_opencl.go — Generate a complete OpenCL host+kernel program from MIR2.
package mir2gpu

import (
	"fmt"
	"strings"

	"github.com/minz/minzc/pkg/mir2"
)

// StandaloneOpenCL generates a complete OpenCL C host program + embedded kernel.
func StandaloneOpenCL(m *mir2.Module, funcName string, numThreads int) (string, error) {
	f := m.FuncByName(funcName)
	if f == nil {
		return "", fmt.Errorf("function %s not found", funcName)
	}

	var sb strings.Builder

	// Host program with embedded kernel source
	sb.WriteString("// Generated by MinZ mir2gpu — standalone OpenCL test\n")
	sb.WriteString("#include <stdio.h>\n")
	sb.WriteString("#include <stdlib.h>\n")
	sb.WriteString("#include <stdint.h>\n")
	sb.WriteString("#include <CL/cl.h>\n\n")

	// Kernel source as string literal
	sb.WriteString("const char* kernel_src = \"\\\n")

	// Build kernel body
	name := gpuSym(funcName)
	sb.WriteString(fmt.Sprintf("__kernel void %s(__global uint* results, uint n) {\\n\\\n", name))
	sb.WriteString("    uint tid = get_global_id(0);\\n\\\n")
	sb.WriteString("    if (tid >= n) return;\\n\\\n")

	// Declare vregs
	vregs := make(map[mir2.Reg]bool)
	for _, b := range f.Blocks {
		for _, inst := range b.Insts {
			if inst.Dst != mir2.NoReg {
				vregs[inst.Dst] = true
			}
		}
	}
	// Param → vreg
	for _, cp := range f.Contract.Params {
		sb.WriteString(fmt.Sprintf("    uint r%d = tid;\\n\\\n", cp.Reg)) // first param = tid
		delete(vregs, cp.Reg)
	}
	for vreg := range vregs {
		sb.WriteString(fmt.Sprintf("    uint r%d = 0;\\n\\\n", vreg))
	}

	// Instructions
	for _, b := range f.Blocks {
		for _, inst := range b.Insts {
			line := openclInst(inst)
			if line != "" {
				sb.WriteString(fmt.Sprintf("    %s\\n\\\n", line))
			}
		}
		// Terminator: write result
		if b.Term != nil {
			if t, ok := b.Term.(*mir2.TermRet); ok && len(t.Vals) > 0 {
				sb.WriteString(fmt.Sprintf("    results[tid] = r%d;\\n\\\n", t.Vals[0]))
			}
		}
	}

	sb.WriteString("    return;\\n\\\n")
	sb.WriteString("}\";\n\n")

	// Host code
	sb.WriteString("int main() {\n")
	sb.WriteString(fmt.Sprintf("    const int N = %d;\n", numThreads))
	sb.WriteString(`
    cl_platform_id platform;
    cl_device_id device;
    clGetPlatformIDs(1, &platform, NULL);
    clGetDeviceIDs(platform, CL_DEVICE_TYPE_GPU, 1, &device, NULL);

    cl_context ctx = clCreateContext(NULL, 1, &device, NULL, NULL, NULL);
    cl_command_queue queue = clCreateCommandQueue(ctx, device, 0, NULL);

    cl_program prog = clCreateProgramWithSource(ctx, 1, &kernel_src, NULL, NULL);
    cl_int err = clBuildProgram(prog, 1, &device, NULL, NULL, NULL);
    if (err != CL_SUCCESS) {
        char log[4096];
        clGetProgramBuildInfo(prog, device, CL_PROGRAM_BUILD_LOG, sizeof(log), log, NULL);
        printf("Build error: %s\n", log);
        return 1;
    }
`)
	sb.WriteString(fmt.Sprintf("    cl_kernel kernel = clCreateKernel(prog, \"%s\", NULL);\n", name))
	sb.WriteString(`
    cl_mem d_results = clCreateBuffer(ctx, CL_MEM_WRITE_ONLY, N * sizeof(uint32_t), NULL, NULL);
    uint32_t n = N;

    clSetKernelArg(kernel, 0, sizeof(cl_mem), &d_results);
    clSetKernelArg(kernel, 1, sizeof(uint32_t), &n);

    size_t global_size = N;
    clEnqueueNDRangeKernel(queue, kernel, 1, NULL, &global_size, NULL, 0, NULL, NULL);

    uint32_t* h_results = (uint32_t*)malloc(N * sizeof(uint32_t));
    clEnqueueReadBuffer(queue, d_results, CL_TRUE, 0, N * sizeof(uint32_t), h_results, 0, NULL, NULL);

    for (int i = 0; i < 16 && i < N; i++)
`)
	sb.WriteString(fmt.Sprintf("        printf(\"%s(%%d) = %%d\\n\", i, h_results[i]);\n", funcName))
	sb.WriteString(fmt.Sprintf(`
    int correct = 0;
    for (int i = 0; i < N; i++)
        if (h_results[i] == (uint32_t)(%s)) correct++;
    printf("Correct: %%d/%%d\n", correct, N);

    clReleaseMemObject(d_results);
    clReleaseKernel(kernel);
    clReleaseProgram(prog);
    clReleaseCommandQueue(queue);
    clReleaseContext(ctx);
    free(h_results);
    return 0;
}
`, verifyExpr(funcName)))

	return sb.String(), nil
}

func openclInst(inst *mir2.Inst) string {
	dst := fmt.Sprintf("r%d", inst.Dst)
	switch inst.Op {
	case mir2.OpConst:
		return fmt.Sprintf("%s = %d;", dst, inst.Imm)
	case mir2.OpAdd:
		return fmt.Sprintf("%s = (r%d + r%d) & 0xFF;", dst, inst.Src[0], inst.Src[1])
	case mir2.OpSub:
		return fmt.Sprintf("%s = (r%d - r%d) & 0xFF;", dst, inst.Src[0], inst.Src[1])
	case mir2.OpMul:
		return fmt.Sprintf("%s = (r%d * r%d) & 0xFF;", dst, inst.Src[0], inst.Src[1])
	case mir2.OpAnd:
		return fmt.Sprintf("%s = r%d & r%d;", dst, inst.Src[0], inst.Src[1])
	case mir2.OpOr:
		return fmt.Sprintf("%s = r%d | r%d;", dst, inst.Src[0], inst.Src[1])
	case mir2.OpXor:
		return fmt.Sprintf("%s = r%d ^ r%d;", dst, inst.Src[0], inst.Src[1])
	case mir2.OpShl:
		return fmt.Sprintf("%s = (r%d << r%d) & 0xFF;", dst, inst.Src[0], inst.Src[1])
	case mir2.OpShr:
		return fmt.Sprintf("%s = r%d >> r%d;", dst, inst.Src[0], inst.Src[1])
	case mir2.OpNeg:
		return fmt.Sprintf("%s = (-r%d) & 0xFF;", dst, inst.Src[0])
	case mir2.OpMove:
		return fmt.Sprintf("%s = r%d;", dst, inst.Src[0])
	default:
		return fmt.Sprintf("// TODO: op %d", inst.Op)
	}
}
