// standalone_metal.go — Generate Metal shader + Swift host for M2 Mac testing.
package mir2gpu

import (
	"fmt"
	"strings"

	"github.com/minz/minzc/pkg/mir2"
)

// StandaloneMetal generates:
// 1. .metal shader file (compute kernel)
// 2. Swift host program (Metal dispatch + verify)
func StandaloneMetal(m *mir2.Module, funcName string, numThreads int) (metalSrc, swiftHost string, err error) {
	f := m.FuncByName(funcName)
	if f == nil {
		return "", "", fmt.Errorf("function %s not found", funcName)
	}

	// Generate .metal shader
	metalCode, err := Compile(m, CompileOptions{Backend: Metal})
	if err != nil {
		return "", "", err
	}

	// Generate Swift host
	name := gpuSym(funcName)
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf(`// Generated by MinZ mir2gpu — Metal host (Swift)
// Compile: xcrun metal -c %s.metal -o %s.air && xcrun metallib %s.air -o %s.metallib
// Run: swiftc -framework Metal -framework Foundation host.swift -o test && ./test

import Metal
import Foundation

let N = %d
guard let device = MTLCreateSystemDefaultDevice() else {
    print("No Metal device"); exit(1)
}

// Load shader
let library: MTLLibrary
do {
    let metalSrc = """
`, name, name, name, name, numThreads))

	// Embed Metal source as Swift string
	for _, line := range strings.Split(metalCode, "\n") {
		sb.WriteString(fmt.Sprintf("    %s\n", line))
	}

	sb.WriteString(fmt.Sprintf(`    """
    library = try device.makeLibrary(source: metalSrc, options: nil)
} catch {
    print("Shader compile error: \\(error)"); exit(1)
}

guard let function = library.makeFunction(name: "%s") else {
    print("Function not found"); exit(1)
}
let pipeline = try! device.makeComputePipelineState(function: function)
let queue = device.makeCommandQueue()!

// Buffers
let resultBuf = device.makeBuffer(length: N * MemoryLayout<UInt32>.size, options: .storageModeShared)!
var n: UInt32 = UInt32(N)
let nBuf = device.makeBuffer(bytes: &n, length: MemoryLayout<UInt32>.size, options: .storageModeShared)!

// Dispatch
let cmdBuf = queue.makeCommandBuffer()!
let encoder = cmdBuf.makeComputeCommandEncoder()!
encoder.setComputePipelineState(pipeline)
encoder.setBuffer(resultBuf, offset: 0, index: 0)
encoder.setBuffer(nBuf, offset: 0, index: 1)
encoder.dispatchThreads(MTLSize(width: N, height: 1, depth: 1),
                        threadsPerThreadgroup: MTLSize(width: min(N, 256), height: 1, depth: 1))
encoder.endEncoding()
cmdBuf.commit()
cmdBuf.waitUntilCompleted()

// Read results
let results = resultBuf.contents().bindMemory(to: UInt32.self, capacity: N)
for i in 0..<min(16, N) {
    print("%s(\(i)) = \(results[i])")
}
var correct = 0
for i in 0..<N {
    if results[i] == UInt32((i * 2) & 0xFF) { correct += 1 }
}
print("Correct: \(correct)/\(N)")
`, name, funcName))

	return metalCode, sb.String(), nil
}
