version: "2"
run:
  timeout: 5m
linters:
  default: none
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
output:
  formats:
    json:
      path: stdout
