// Code generated by "stringer -output stringer.go -linecomment -type=tokCh,Kind,Linkage,StorageDuration"; DO NOT EDIT.

package cparse

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ADDASSIGN-57345]
	_ = x[ALIGNAS-57346]
	_ = x[ALIGNOF-57347]
	_ = x[ANDAND-57348]
	_ = x[ANDASSIGN-57349]
	_ = x[ARROW-57350]
	_ = x[ASM-57351]
	_ = x[ATOMIC-57352]
	_ = x[ATTRIBUTE-57353]
	_ = x[AUTO-57354]
	_ = x[AUTOTYPE-57355]
	_ = x[BOOL-57356]
	_ = x[BREAK-57357]
	_ = x[CASE-57358]
	_ = x[CHAR-57359]
	_ = x[CHARCONST-57360]
	_ = x[COMPLEX-57361]
	_ = x[CONST-57362]
	_ = x[CONTINUE-57363]
	_ = x[DDD-57364]
	_ = x[DEC-57365]
	_ = x[DECIMAL128-57366]
	_ = x[DECIMAL32-57367]
	_ = x[DECIMAL64-57368]
	_ = x[DECLSPEC-57369]
	_ = x[DEFAULT-57370]
	_ = x[DIVASSIGN-57371]
	_ = x[DO-57372]
	_ = x[DOUBLE-57373]
	_ = x[ELSE-57374]
	_ = x[ENUM-57375]
	_ = x[EQ-57376]
	_ = x[EXTERN-57377]
	_ = x[FLOAT-57378]
	_ = x[FLOAT128-57379]
	_ = x[FLOAT128X-57380]
	_ = x[FLOAT16-57381]
	_ = x[FLOAT32-57382]
	_ = x[FLOAT32X-57383]
	_ = x[FLOAT64-57384]
	_ = x[FLOAT64X-57385]
	_ = x[FLOATCONST-57386]
	_ = x[FOR-57387]
	_ = x[GENERIC-57388]
	_ = x[GEQ-57389]
	_ = x[GOTO-57390]
	_ = x[HEADER_NAME-57391]
	_ = x[IDENTIFIER-57392]
	_ = x[IF-57393]
	_ = x[IMAG-57394]
	_ = x[IMAGINARY-57395]
	_ = x[INC-57396]
	_ = x[INLINE-57397]
	_ = x[INT-57398]
	_ = x[INT128-57399]
	_ = x[INTCONST-57400]
	_ = x[LABEL-57401]
	_ = x[LEQ-57402]
	_ = x[LONG-57403]
	_ = x[LONGCHARCONST-57404]
	_ = x[LONGSTRINGLITERAL-57405]
	_ = x[LSH-57406]
	_ = x[LSHASSIGN-57407]
	_ = x[MODASSIGN-57408]
	_ = x[MULASSIGN-57409]
	_ = x[NEQ-57410]
	_ = x[NONNULL-57411]
	_ = x[NORETURN-57412]
	_ = x[ORASSIGN-57413]
	_ = x[OROR-57414]
	_ = x[PPNUMBER-57415]
	_ = x[PPPASTE-57416]
	_ = x[REAL-57417]
	_ = x[REGISTER-57418]
	_ = x[RESTRICT-57419]
	_ = x[RETURN-57420]
	_ = x[RSH-57421]
	_ = x[RSHASSIGN-57422]
	_ = x[SHORT-57423]
	_ = x[SIGNED-57424]
	_ = x[SIZEOF-57425]
	_ = x[STATIC-57426]
	_ = x[STATICASSERT-57427]
	_ = x[STRINGLITERAL-57428]
	_ = x[STRUCT-57429]
	_ = x[SUBASSIGN-57430]
	_ = x[SWITCH-57431]
	_ = x[THREADLOCAL-57432]
	_ = x[TYPEDEF-57433]
	_ = x[TYPENAME-57434]
	_ = x[TYPEOF-57435]
	_ = x[UINT128-57436]
	_ = x[UNION-57437]
	_ = x[UNSIGNED-57438]
	_ = x[VOID-57439]
	_ = x[VOLATILE-57440]
	_ = x[WHILE-57441]
	_ = x[XORASSIGN-57442]
	_ = x[OBJC_INTERFACE-57443]
	_ = x[OBJC_IMPLEMENTATION-57444]
	_ = x[OBJC_PROTOCOL-57445]
	_ = x[OBJC_END-57446]
	_ = x[OBJC_PROPERTY-57447]
	_ = x[OBJC_SYNTHESIZE-57448]
	_ = x[OBJC_DYNAMIC-57449]
	_ = x[OBJC_SELECTOR-57450]
	_ = x[OBJC_ENCODE-57451]
	_ = x[OBJC_CLASS-57452]
	_ = x[OBJC_OPTIONAL-57453]
	_ = x[OBJC_REQUIRED-57454]
	_ = x[OBJC_IMPORT-57455]
	_ = x[OBJC_YES-57456]
	_ = x[OBJC_NO-57457]
	_ = x[OBJC_NIL-57458]
	_ = x[OBJC_SELF-57459]
	_ = x[OBJC_SUPER-57460]
}

// _tokCh_names maps tokCh values to human-readable strings.
// Extended with ObjC tokens (MinZ fork).
var _tokCh_names = map[tokCh]string{
	ADDASSIGN: "'+='" , ALIGNAS: "'_Alignas'", ALIGNOF: "'_Alignof'",
	ANDAND: "'&&'", ANDASSIGN: "'&='", ARROW: "'->'", ASM: "'__asm__'",
	ATOMIC: "'_Atomic'", ATTRIBUTE: "'__attribute__'", AUTO: "'auto'",
	AUTOTYPE: "'__auto_type'", BOOL: "'_Bool'", BREAK: "'break'",
	CASE: "'case'", CHAR: "'char'", CHARCONST: "character constant",
	COMPLEX: "'_Complex'", CONST: "'const'", CONTINUE: "'continue'",
	DDD: "'...'", DEC: "'--'", DECIMAL128: "'_Decimal128'",
	DECIMAL32: "'_Decimal32'", DECIMAL64: "'_Decimal64'",
	DECLSPEC: "'__declspec'", DEFAULT: "'default'", DIVASSIGN: "'/='",
	DO: "'do'", DOUBLE: "'double'", ELSE: "'else'", ENUM: "'enum'",
	EQ: "'=='", EXTERN: "'extern'", FLOAT: "'float'",
	FLOAT128: "'_Float128'", FLOAT128X: "'_Float128x'",
	FLOAT16: "'_Float16'", FLOAT32: "'_Float32'", FLOAT32X: "'_Float32x'",
	FLOAT64: "'_Float64'", FLOAT64X: "'_Float64x'",
	FLOATCONST: "floating point constant", FOR: "'for'",
	GENERIC: "'_Generic'", GEQ: "'>='", GOTO: "'goto'",
	HEADER_NAME: "<header-name>", IDENTIFIER: "identifier", IF: "'if'",
	IMAG: "'__imag__'", IMAGINARY: "'_Imaginary'", INC: "'++'",
	INLINE: "'inline'", INT: "'int'", INT128: "'__int128'",
	INTCONST: "integer constant", LABEL: "'__label__'", LEQ: "'<='",
	LONG: "'long'", LONGCHARCONST: "long character constant",
	LONGSTRINGLITERAL: "long string literal", LSH: "'<<'",
	LSHASSIGN: "'<<='", MODASSIGN: "'%='", MULASSIGN: "'*='",
	NEQ: "'!='", NONNULL: "'_Nonnull'", NORETURN: "'_Noreturn'",
	ORASSIGN: "'|='", OROR: "'||'", PPNUMBER: "preprocessing number",
	PPPASTE: "'##'", REAL: "'__real__'", REGISTER: "'register'",
	RESTRICT: "'restrict'", RETURN: "'return'", RSH: "'>>'",
	RSHASSIGN: "'>>='", SHORT: "'short'", SIGNED: "'signed'",
	SIZEOF: "'sizeof'", STATIC: "'static'", STATICASSERT: "_Static_assert",
	STRINGLITERAL: "string literal", STRUCT: "'struct'",
	SUBASSIGN: "'-='", SWITCH: "'switch'", THREADLOCAL: "'_Thread_local'",
	TYPEDEF: "'typedef'", TYPENAME: "type name", TYPEOF: "'typeof'",
	UINT128: "'__uint128_t'", UNION: "'union'", UNSIGNED: "'unsigned'",
	VOID: "'void'", VOLATILE: "'volatile'", WHILE: "'while'",
	XORASSIGN: "'^='",
	// ObjC (MinZ fork)
	OBJC_INTERFACE: "@interface", OBJC_IMPLEMENTATION: "@implementation",
	OBJC_PROTOCOL: "@protocol", OBJC_END: "@end",
	OBJC_PROPERTY: "@property", OBJC_SYNTHESIZE: "@synthesize",
	OBJC_DYNAMIC: "@dynamic", OBJC_SELECTOR: "@selector",
	OBJC_ENCODE: "@encode", OBJC_CLASS: "@class",
	OBJC_OPTIONAL: "@optional", OBJC_REQUIRED: "@required",
	OBJC_IMPORT: "#import",
	OBJC_YES: "YES", OBJC_NO: "NO", OBJC_NIL: "nil",
	OBJC_SELF: "self", OBJC_SUPER: "super",
}

func (i tokCh) String() string {
	if s, ok := _tokCh_names[i]; ok {
		return s
	}
	return "tokCh(" + strconv.FormatInt(int64(i), 10) + ")"
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvalidKind-0]
	_ = x[Array-1]
	_ = x[Bool-2]
	_ = x[Char-3]
	_ = x[ComplexChar-4]
	_ = x[ComplexDouble-5]
	_ = x[ComplexFloat-6]
	_ = x[ComplexFloat16-7]
	_ = x[ComplexInt-8]
	_ = x[ComplexLong-9]
	_ = x[ComplexLongDouble-10]
	_ = x[ComplexLongLong-11]
	_ = x[ComplexShort-12]
	_ = x[ComplexUInt-13]
	_ = x[ComplexUShort-14]
	_ = x[Decimal128-15]
	_ = x[Decimal32-16]
	_ = x[Decimal64-17]
	_ = x[Double-18]
	_ = x[Enum-19]
	_ = x[Float-20]
	_ = x[Float128-21]
	_ = x[Float128x-22]
	_ = x[Float16-23]
	_ = x[Float32-24]
	_ = x[Float32x-25]
	_ = x[Float64-26]
	_ = x[Float64x-27]
	_ = x[Function-28]
	_ = x[Int-29]
	_ = x[Int128-30]
	_ = x[Long-31]
	_ = x[LongDouble-32]
	_ = x[LongLong-33]
	_ = x[Ptr-34]
	_ = x[SChar-35]
	_ = x[Short-36]
	_ = x[Struct-37]
	_ = x[UChar-38]
	_ = x[UInt-39]
	_ = x[UInt128-40]
	_ = x[ULong-41]
	_ = x[ULongLong-42]
	_ = x[UShort-43]
	_ = x[Union-44]
	_ = x[Void-45]
	_ = x[maxKind-46]
}

const _Kind_name = "InvalidKindarray_Boolchar_Complex char_Complex double_Complex float_Complex _Float16_Complex int_Complex long_Complex long double_Complex long long_Complex short_Complex unsigned_Complex unsigned short_Decimal128_Decimal32_Decimal64doubleenumfloat_Float128_Float128x_Float16_Float32_Float32x_Float64_Float64xfunctionint__int128longlong doublelong longpointersigned charshortstructunsigned charunsignedunsigned __int128unsigned longunsigned long longunsigned shortunionvoidmaxKind"

var _Kind_index = [...]uint16{0, 11, 16, 21, 25, 38, 53, 67, 84, 96, 109, 129, 147, 161, 178, 201, 212, 222, 232, 238, 242, 247, 256, 266, 274, 282, 291, 299, 308, 316, 319, 327, 331, 342, 351, 358, 369, 374, 380, 393, 401, 418, 431, 449, 463, 468, 472, 479}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[External-0]
	_ = x[Internal-1]
	_ = x[None-2]
}

const _Linkage_name = "ExternalInternalNone"

var _Linkage_index = [...]uint8{0, 8, 16, 20}

func (i Linkage) String() string {
	if i < 0 || i >= Linkage(len(_Linkage_index)-1) {
		return "Linkage(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Linkage_name[_Linkage_index[i]:_Linkage_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Static-0]
	_ = x[Automatic-1]
	_ = x[Allocated-2]
}

const _StorageDuration_name = "StaticAutomaticAllocated"

var _StorageDuration_index = [...]uint8{0, 6, 15, 24}

func (i StorageDuration) String() string {
	if i < 0 || i >= StorageDuration(len(_StorageDuration_index)-1) {
		return "StorageDuration(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StorageDuration_name[_StorageDuration_index[i]:_StorageDuration_index[i+1]]
}
