// Generated by MinZ mir2gpu — Metal
#include <metal_stdlib>
using namespace metal;

kernel void fn_double(
    device uint* results [[buffer(0)]],
    constant uint& n [[buffer(1)]],
    uint tid [[thread_position_in_grid]]) {
    if (tid >= n) return;
    uint r1 = tid;
    uint r2 = 0;

    r2 = (r1 + r1) & 0xFF;
    results[tid] = r2;
    return;
}

