// Generated by MinZ mir2gpu — Metal host (Swift)
// Compile: xcrun metal -c fn_double.metal -o fn_double.air && xcrun metallib fn_double.air -o fn_double.metallib
// Run: swiftc -framework Metal -framework Foundation host.swift -o test && ./test

import Metal
import Foundation

let N = 256
guard let device = MTLCreateSystemDefaultDevice() else {
    print("No Metal device"); exit(1)
}

// Load shader
let library: MTLLibrary
do {
    let metalSrc = """
    // Generated by MinZ mir2gpu — Metal
    #include <metal_stdlib>
    using namespace metal;
    
    kernel void fn_double(
        device uint* results [[buffer(0)]],
        constant uint& n [[buffer(1)]],
        uint tid [[thread_position_in_grid]]) {
        if (tid >= n) return;
        uint r1 = tid;
        uint r2 = 0;
    
        r2 = (r1 + r1) & 0xFF;
        results[tid] = r2;
        return;
    }
    
    
    """
    library = try device.makeLibrary(source: metalSrc, options: nil)
} catch {
    print("Shader compile error: \\(error)"); exit(1)
}

guard let function = library.makeFunction(name: "fn_double") else {
    print("Function not found"); exit(1)
}
let pipeline = try! device.makeComputePipelineState(function: function)
let queue = device.makeCommandQueue()!

// Buffers
let resultBuf = device.makeBuffer(length: N * MemoryLayout<UInt32>.size, options: .storageModeShared)!
var n: UInt32 = UInt32(N)
let nBuf = device.makeBuffer(bytes: &n, length: MemoryLayout<UInt32>.size, options: .storageModeShared)!

// Dispatch
let cmdBuf = queue.makeCommandBuffer()!
let encoder = cmdBuf.makeComputeCommandEncoder()!
encoder.setComputePipelineState(pipeline)
encoder.setBuffer(resultBuf, offset: 0, index: 0)
encoder.setBuffer(nBuf, offset: 0, index: 1)
encoder.dispatchThreads(MTLSize(width: N, height: 1, depth: 1),
                        threadsPerThreadgroup: MTLSize(width: min(N, 256), height: 1, depth: 1))
encoder.endEncoding()
cmdBuf.commit()
cmdBuf.waitUntilCompleted()

// Read results
let results = resultBuf.contents().bindMemory(to: UInt32.self, capacity: N)
for i in 0..<min(16, N) {
    print("double(\(i)) = \(results[i])")
}
var correct = 0
for i in 0..<N {
    if results[i] == UInt32((i * 2) & 0xFF) { correct += 1 }
}
print("Correct: \(correct)/\(N)")
